### ISSUE TITLE
Trusting yourself should fail

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-core#1020]
This might need a feature flag.

**Comment by vogel** [comment]
As I understand it:

1.) if config.LEDGER_PROTOCOL_VERSION <= 2 (current) version, everything should work as currently
2.) if config.LEDGER_PROTOCOL_VERSION > 2:
2.) 1.) for new trust lines, we should deny creation when source account = asset.issuer and return CHANGE_TRUST_MALFORMED or new error code CHANGE_TRUST_INVALID_SELF (or with better name)
2.) 2.) for existing self-trusting trust lines we should allow only DELETE operation

Am I correct?

**Comment by vogel** [comment]
After reading the code:
2.) trusting yourselfs never creates/stores trustlines - so 2.1) and 2.2) are not needed, only error code is returned

**Comment by jedmccaleb** [comment]
fixed
