### ISSUE TITLE
UTF-8 support

### ISSUE THREAD

**Issue by DmRomantsov** [stellar/stellar-core#1023]
Hello!
We are developing the open government auctions system on “Stellar” platform. We forked Stellar and run our own network. We’ve added Lot creation transactions, auction participation, bids etc. There is encoding problem. We tried this solution:  https://github.com/stellar/js-stellar-base/issues/60 But during the debug process we’ve find out that Stellar-core can’t process the data sent by js-xdr library in base64 (UTF-8) format. We’ve looked at the C++ source code but haven’t found the way to fix that.

Error example: 
{\"exception\"=>\"Non-zero padding bytes encountered\"}"

Some help and/or advice on this issue will be much appreciated.
All source are available here: http://www.eauction.idf.solutions/

**Comment by DmRomantsov** [comment]
We rewrote some JS code and solved this issue. The problem was in count of characters encoded in tx. C++ code allocate memory depending of count variable in tx.

**Comment by jedmccaleb** [comment]
Thanks. Sorry I didn't get to look at it in time but glad you figured it out. @bartek do we still need to pull in the PR?

**Comment by nullstyle** [comment]
We've just merged that PR into js-xdr and will be doing a release shortly

**Comment by bartekn** [comment]
@DmRomantsov this has been released as `stellar-base@0.5.6` ([npm](https://www.npmjs.com/package/stellar-base) [bower](https://github.com/stellar/bower-js-stellar-base)) and `stellar-sdk@0.4.3` ([npm](https://www.npmjs.com/package/stellar-sdk) [bower](https://github.com/stellar/bower-js-stellar-sdk)). Please note that if you're using Horizon you need to upgrade to [v0.5.1](https://github.com/stellar/horizon/releases/tag/v0.5.1).
