### ISSUE TITLE
applying checkpoint very slow

### ISSUE THREAD

**Issue by codeck** [stellar/stellar-core#1040]
i'm running a stellar-core (head in prod branch) in linode 1G node and it's still

```
GBUPU [History INFO ] Catching up: applying checkpoint 1831/73978 (2%)
```

after half a day and will take months to sync.

the code seems slow in https://github.com/stellar/stellar-core/blob/5b39fd8/src/ledger/LedgerManagerImpl.cpp#L767-L780 .

**Comment by sacarlson** [comment]
I have also noted very slow or infinite times to sync when I run stellar-core commit 657d67b... with config setting CATCHUP_COMPLETE=true on testnet. Work around for me has been config setting of  CATCHUP_COMPLETE=false.   This is seen when running from a full reset with blank database to start.  Config file attached. 
[stellar-core_testnet_no_secrets.cfg.txt](https://github.com/stellar/stellar-core/files/307150/stellar-core_testnet_no_secrets.cfg.txt)

**Comment by codeck** [comment]
It's observed the time for applying checkpoint is proportional to the applied checkpoints. HistoryManagerImpl::getPublishQueueStates() in BucketManagerImpl::forgetUnreferencedBuckets() slows down the whole process.

**Comment by jedmccaleb** [comment]
should be fixed now
