### ISSUE TITLE
support cascaded history archive

### ISSUE THREAD

**Issue by codeck** [stellar/stellar-core#1045]
history archive is stored/fetched in checkpoint level (i.e. 64 ledger) in current codebase.
it's about 80k checkpoints now. and the load of either client/server side when downloading for full catching up is high.
considering checkpoints are stored in 256-branched tree directories:

```
ledger/aa/bb/cc/ledger-aabbccdd.xdr.gz
...
transactions/...
history/...
...
```

the history subsystem should archive checkpoints as belows

```
ledger/aa/bb/cc/ledger-aa-bb-cc.tar
ledger/aa/bb/ledger-aa-bb.tar
ledger/aa/ledger-aa.tar
```

once the branche is fully filled. and try to fetch them first.
this feature will accelerate the downloading phase of full catching up.

**Comment by jedmccaleb** [comment]
Possibly vNext if the other fixes to catchup don't make the process reasonable

**Comment by MonsieurNicolas** [comment]
Closing this in favor of #1707
