### ISSUE TITLE
Expiring asset possible?

### ISSUE THREAD

**Issue by davistan** [stellar/stellar-core#1057]
Hi, based on coupon or reward points systems, is there a way / workaround that we can make an asset having an expiry date (TTL)?

Thanks.

**Comment by jedmccaleb** [comment]
I think you would want to handle this largely outside of the protocol. You could let anyone getting your asset know that this would happen. Then just freeze the asset at the correct time. https://www.stellar.org/developers/guides/concepts/assets.html#controlling-asset-holders

**Comment by davistan** [comment]
Ok, noted on this. Thanks for the reply.
