### ISSUE TITLE
two nodes can't restart after stop in publishing

### ISSUE THREAD

**Issue by codeck** [stellar/stellar-core#1072]
I run two nodes feeding history archive. and both can't restart after stopped.
They are running on lowest VPS with 1G mem. (many memory allocate failures in log).
It's painful to republishing all unless #1045 implemented. 
so is it any alternative method to resume?
the attached log in from one node and the other is alike.
[stellar-core.log.1.gz](https://github.com/stellar/stellar-core/files/520949/stellar-core.log.1.gz)

**Comment by codeck** [comment]
fyi. the code is based on master with #1047 .

**Comment by vogel** [comment]
It was issue with history permissions. Already solved.
