### ISSUE TITLE
Improve "-c quorum" output to better show problems

### ISSUE THREAD

**Issue by vogel** [stellar/stellar-core#1098]
For given quorums set:

node1 = [node1, node2, node3, failing1]
node2 = [node1, node2, node3, failing1, failing2, failing3]
node3 = [node1, node2, node3, failing1]
failingX = [does not matter]

When failing2, failing3 are not working and failing1 stops working, then no node have a valid quorum (as node2 loses quorum and then node1 and node3). In such a case executing "-c quorum" on node1-3 does not give enough information to diagnose the problem.

Improve output of "-c quorum" so this kind of problems is better visible.

**Comment by MonsieurNicolas** [comment]
I am not sure I understand the situation as I don't know what kind of failure you're talking about.

in the case of nodes down, you should have something like:
* on node1 it should say `fail_at: 0` (already failed) and `missing: failing1`, `disagree: node2, node3`
* on node2 it should say `fail_at: 0` (already failed) and `missing: failing1... failing3` and `disagree: node1 node3`
* on node3 similar than node1

a node missing, means it's down and a node disagreeing means it's up but consensus cannot be reached somehow.
