### ISSUE TITLE
Make tests use randomized NodeIDs and AccountIDs

### ISSUE THREAD

**Issue by vogel** [stellar/stellar-core#1099]
As shown in Force SCP, the result of tests sometimes depends on generated NodeID (for some values of NodeIDs in Force SCP a third node is chosen as round leader over and over again which timeouts the tests).

It is possible that similar issues would be found in other tests if ID for nodes (and possibly accounts) were not hardcoded but chosen at random.

**Comment by jedmccaleb** [comment]
Hmm maybe it is worse to have the tests not be deterministic and reproducible. Maybe we should test the configurations where nodeID maters with fixed configurations?

**Comment by vogel** [comment]
I think it may be hard to say where nodeID matters and which values of nodeID should we check to find bogus behaviors.

We could use some random seed for random nodeIDs and accountIDs and store it in tests logs, so we could replicate test run when we get failed assertions.

**Comment by MonsieurNicolas** [comment]
I like this idea
 > We could use some random seed for random nodeIDs and accountIDs and store it in tests logs, so we could replicate test run when we get failed assertions.

For this to work we'd need to ensure that all random sources are taken care of from tests, in particular tests should only use pseudo-random data based on that single seed.
This means that we have to scrub code for things like:
 * multiple initialization of random generators (only the top level `main` should initialize it, right now it's initialized at least per application)
 * not using other sources - for example tests that use `SecretKey::random()` are "too random", and instead should be changed to use `SecretKey::fromSeed(seed)` where `seed` is generated using std random number generators.
