### ISSUE TITLE
When bogus offer is present in path payment and deleted, it is also added to offer trail for that payment

### ISSUE THREAD

**Issue by vogel** [stellar/stellar-core#1109]
See PR #1108 for details (only last commit - 6036ce0938969328b7a623bac9265364ee692b6a).

**Comment by MonsieurNicolas** [comment]
I think @nullstyle ran into this recently (didn't know about the behavior). the offers show up as "claimed" (with a value of 0).

We wanted to expose in the offer trail the fact that offers got deleted somehow as this information is accessible from the ledger header without having to run a validator node (so can be validated cheaply by just watching headers + txsets and results).
Alternative would be to leave it only to full validators to compute this information (meta).

**Comment by vogel** [comment]
Yes, I've noticed that as well. I was sure that I've closed this bug as invalid, but probably I've just changed tests to not indicate that this is a bug.
