### ISSUE TITLE
Verify downloaded `xdr.gz` is really a GZIP file.

### ISSUE THREAD

**Issue by mvaneijk** [stellar/stellar-core#1114]
Sometimes unzipping fails because the history download process of the core stores whatever it gets back from the history store server as `xdr.gz`. This includes HTTP 4xx and 5xx error messages when the downloading script is not set to fail when response is not HTTP 200.

The fix can be extended by signaling the HTTP response code back to the core download process. Retries don't make much sense when they are initiated by HTTP 400, 401, 403 response codes.

**Comment by vogel** [comment]
PR #1130 should handle that. We cannot check HTTP response, because history get and history put methods are implemented externally - in stellar-core we only know if operation succeeded or not (by exit code or command).

**Comment by vogel** [comment]
Fixed by #1130
