### ISSUE TITLE
time lock on the protocol upgrade

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-core#1123]
Right now the network will upgrade as soon as a quorum of nodes are running the new version. It would be smoother if there was also a date before which validators running the new version won't vote to switch to the new version of the protocol. This will give people some time to switch over.

I suggest we add another configuration value that controls when nodes will start voting for the new version. 

PREFERRED_UPGRADE_DATE=<time stamp>

This controls when they start voting for the new version. Of course they can accept the new version earlier if a quorum out there upgrades earlier.

**Comment by vogel** [comment]
Implemented PREFERRED_UPGRADE_DATETIME with format: YYYY-MM-DDTHH:mm:ssZ

Example:

PREFERRED_UPGRADE_DATETIME=2017-02-02T00:00:00Z

**Comment by vogel** [comment]
Fixed in #1131
