### ISSUE TITLE
problems with complete catchup on testnet

### ISSUE THREAD

**Issue by vogel** [stellar/stellar-core#1129]
From sacarlson:

2017-01-18T11:04:11.764 GAIKS [History INFO ] Catching up: downloading transactions files 784/784 (100%)
2017-01-18T11:04:12.405 GAIKS [Herder INFO ] Quorum information for 6311133 : {"agree":3,"disagree":0,"fail_at":2,"hash":"273af2","missing":0,"phase":"EXTERNALIZE"}

2017-01-18T11:04:12.413 GAIKS [Ledger INFO ] Got consensus: [seq=6311135, prev=f0494e, tx_count=0, sv: [  txH: 6e989d, ct: 1484712250, upgrades: [ ] ]]
2017-01-18T11:04:13.692 GAIKS [History INFO ] Catchup COMPLETE verifying history
2017-01-18T11:04:13.692 GAIKS [History INFO ] Catching up: verifying checkpoint 1/784 (0%)
**2017-01-18T11:04:13.692 GAIKS [History ERROR] Bad hash-chain: [seq=6260955, hash=27e674] wants prev hash 1586fe but actual prev hash is cf29b1 [HistoryWork.cpp:381]**
2017-01-18T11:04:13.692 GAIKS [History ERROR] Catchup material failed verification, propagating failure [HistoryWork.cpp:499]
2017-01-18T11:04:13.692 GAIKS [Work WARN ] Scheduling retry #1/5 in 1 sec, for catchup-complete-00604c9d
2017-01-18T11:04:14.692 GAIKS [Work WARN ] Scheduling retry #1/5 in 36 sec, for get-history-archive-state
2017-01-18T11:04:16.407 GAIKS [Herder INFO ] Quorum information for 6311134 : {"agree":3,"disagree":0,"fail_at":2,"hash":"273af2","missing":0,"phase":"EXTERNALIZE"}

**Comment by sacarlson** [comment]
That was from build of stellar-core "v0.5.1-113-gcff752b

{   "info" : {      "UNSAFE_QUORUM" : "UNSAFE QUORUM ALLOWED",      "build" : "v0.5.1-113-gcff752b",      "ledger" : {         "age" : 190943,         "closeTime" : 1484519471,         "hash" : "cf29b137d98624243689c3b8ab1ca5fecf94935120ce96ea96a47ffa321070a5",         "num" : 6260955      },      "network" : "Test SDF Network ; September 2015",      "numPeers" : 6,      "protocol_version" : 3,      "quorum" : {         "6310659" : {            "agree" : 3,            "disagree" : 0,            "fail_at" : 2,            "hash" : "273af2",            "missing" : 0,            "phase" : "EXTERNALIZE"         }      },      "state" : "Catching up",      "status" : [ "Catching up: Awaiting checkpoint (ETA: 25 seconds)" ]   } }

**Comment by vogel** [comment]
The problem also occurs on CATCHUP_RECENT with big enough value. And on next-db-and-proto-2 branch.

Investigating.

**Comment by vogel** [comment]
Needs to be checked and fixed before 0.6

**Comment by jedmccaleb** [comment]
He is running the wrong version. He is running protocol version 2. This won't be able to sync with a network that is on version 3

**Comment by vogel** [comment]
I have the same error on proper version. There is something wrong with ledger 6260954 on testnet.
Move from protocol 2 to protocol 3 was on ledger 6246503.

Laboratory shows that there was no transaction for 6260954: https://www.stellar.org/laboratory/#explorer?resource=transactions&endpoint=for_ledger&values=eyJsZWRnZXIiOiI2MjYwOTU0In0%3D&network=test

But in transactions files got from history there is a transaction:

 ledgerSeq = 6260954,
  txSet = {
    previousLedgerHash = c0d07621e18c39c44e50fbf9dbd352edca099ecaf7a76dad0ff8522cc151d94c,
    txs = [
      { tx = {
          sourceAccount = GA7QCCAVJHBYBHUFI3IGPQPBUCEBLBPAGKOR54BGUM2Q2POWT27G45P3,
          fee = 100,
          seqNum = 18018483023380482,
          timeBounds = NULL,
          memo = {
            type = MEMO_NONE
          },
          operations = [
            { sourceAccount = NULL,
              body = {
                type = MANAGE_DATA,
                manageDataOp = {
                  dataName = "OFR: GDCXKIDYH7DN6YY4Y6A27XBLAVPEQB4PG5B7ROZVXU7XRBUC5MSTSSUJ",
                  dataValue = 3730303030
                }
              } }
          ],
          ext = {
            v = 0
          }
        },
        signatures = [
          { hint = d69ebe6e,
            signature = 36880e4dae0fb94e4f9595b31cb7b0934ab0d08eb6a53057511e7a25b965d2b9bbc42fe91b0dea57a7a1d9b4f84b82b0a036c68eb2567e5e6590c49b3e0e6f05 }
        ] }
    ]
  },
  ext = {
    v = 0
  } }

Horizon does not show such 'manage_data' operation for this account: https://www.stellar.org/laboratory/#explorer?resource=operations&endpoint=for_account&values=eyJhY2NvdW50X2lkIjoiR0E3UUNDQVZKSEJZQkhVRkkzSUdQUVBCVUNFQkxCUEFHS09SNTRCR1VNMlEyUE9XVDI3RzQ1UDMifQ%3D%3D&network=test

But in account view: https://www.stellar.org/laboratory/#explorer?resource=accounts&endpoint=single&values=eyJhY2NvdW50X2lkIjoiR0E3UUNDQVZKSEJZQkhVRkkzSUdQUVBCVUNFQkxCUEFHS09SNTRCR1VNMlEyUE9XVDI3RzQ1UDMifQ%3D%3D&network=test

there is similar account data entry (but not the same).

Still investigating the issue

**Comment by vogel** [comment]
Reasons of this issue are now clear.

When I've created my first PR with BanManager, the new table in database required change of database schema version from '3' to '4' (and it was done in master branch). So every node that has code published after that merge has database with version '4' (as in all new docker images).

After some time it was decided that all new updates to database and protocol version for stellar-core 6.0 (named vNext in github issues) should go to next-db-and-proto branch, that will upgrade database schema to version '4' and ledger protocol version to '3'. Unfortunately, I've forgotten that there is a change in 'master' branch that already updated database schema to version '4'. Next-db-and-proto branch should use version '5' of database schema.

When testnet was upgraded to next-db-and-proto branch to changes were made to database and no `lastmodified` field was added to `accountdata` table. After that the first operation of `MANAGE_DATA` failed. After the database change, `MANAGE_DATA` operations store into database number of ledger that it was performed. As no such field exists now on testnet datbases, exception was thrown and transaction was finished with txINTERNAL_ERROR.

When someone installs new version from next-db-and-proto on a clean database then the field is created. Then, when doing CATCHUP_COMPLETE (or CATCHUP_RECENT that is big enough to contains ledger 6260954 with the latest `MANAGE_DATA` operation on testnet), then the same operation succeeds with txSUCCESS. This difference then propagetes itself in form of txSetResultHash and bucketListHash and then in form of ledger hashes. So entire blockchain becomes invalid and catchup is impossible.

Proposed solution:
* upgrade database schema version to 5
* leave `BanManager::dropAll(*this);` in version 4 of database schema
* move remaining 2 changes to databsae schema 5
    mSession << "ALTER TABLE accountdata ADD lastmodified INT NOT NULL DEFAULT 0;";
    mSession << "CREATE INDEX scpquorumsbyseq ON scpquorums(lastledgerseq)";
* update database schemas on testenet to version 5 and check the changes
* each user will get a proper upgrade then

For tesnet:
* either add a special condition to throw an exception on 6260954 ledger operations on testnet
** pro: all testnet users history remains as it is
** con: ugly special condition in code
** con: will have to be removed when testnet is reset again
* or reset testnet with new genesis ledger
** pro: no ugly special condition in code
** con: all users lose their transactions

To prevent such bugs in future:
* add code that checks after database upgrade (even if skipped because already in current version) if it was performed correctly (eg: check list of all tables/columns and indexes)

**Comment by vogel** [comment]
Fixed by restarting testnet. Issue was caused by upgrade process being not completed properly.

**Comment by bartekn** [comment]
I'm getting similar error:
```
Bad hash-chain: [seq=9318048, hash=ac507d] wants prev hash 483657 but actual prev hash is 33fefb
```
Network: public
Stellar-core version:  0.5.1-341-3c4e3568

**Comment by bartekn** [comment]
Confirmed 728f8de539c75606ab8833fe32cefa7255460d34 fixes the issue. Thanks @vogel!

**Comment by playersai** [comment]
2018-06-08T18:18:34.341 GCU2W [History ERROR] Catchup material failed verification - hash mismatch, propagating failure [VerifyLedgerChainWork.cpp:257]
2018-06-08T18:18:34.341 GCU2W [Ledger ERROR] Error catching up: Connection timed out [LedgerManagerImpl.cpp:682]
2018-06-08T18:18:34.341 GCU2W [Ledger ERROR] Catchup will restart at next close. [LedgerManagerImpl.cpp:683] 
what is meaning？

**Comment by MonsieurNicolas** [comment]
Does your validator get stuck like this or it eventually retried and succeeded? I think I've seen this only when getting bad (corrupt) data from archives somehow or the local state is corrupt. Post exact repro steps (and which version you're using etc see - https://github.com/stellar/stellar-core/blob/master/.github/ISSUE_TEMPLATE.md ) and logs to help understand.
