### ISSUE TITLE
Allow X as a signer of an account

### ISSUE THREAD

**Issue by vogel** [stellar/stellar-core#1134]
David proposed making a CryptoKeyType  called KEY_TYPE_X this will be created when a hash(x) tx is successful. The idea is that when a hash(x) tx happens it will have the side effect of replacing the SIGNER_KEY_TYPE_HASH_X with a SIGNER_KEY_TYPE_X  on the account. this way it will be obvious what the preimage was without having to go find the tx that included the preimage.

It should not be allowed to add KEY_TYPE_X directly, it can only appear as a result of successful KEY_TYPE_HASH_X signing.

**Comment by MonsieurNicolas** [comment]
I don't see why we'd need protocol support for this. It seems useful only if `X` can be used to unlock a bunch of other transactions. regardless, this is something that should be discussed in the protocol repo.
