### ISSUE TITLE
[hardening] Create option for testing network failures

### ISSUE THREAD

**Issue by vogel** [stellar/stellar-core#1136]
Such an option could be used to run test instance of stellar-core that simulated bad network conditions.
It could, for example:
- randomly disconnects peers
- randomly changing messages received from peers
- randomly deleting/changing files downloaded by GetRemoteFile work

Option could be named ARTIFICALLY_BAD_NETWORK=true

Using that could help us find inefficiencies in catchup implementation.

**Comment by MonsieurNicolas** [comment]
closing: this can be achieved by using network simulators, probably not something that should be baked into stellar-core itself.
