### ISSUE TITLE
Subprocesses could still be running when catchup restarts

### ISSUE THREAD

**Issue by vogel** [stellar/stellar-core#1140]
Our work code cancels parent work when at least one of subworks returns with FAILED_RAISE result. It means that other subworks of parent work could be still running. In case of catchup it is possible that GetRemoteFile jobs are still running (usually wget/curl commands) when catchup fails. And when catchup fails, tmp directory gets removed recursively.

It can happen that one of tmp subdir is removed just after a wget/curl finishes its works and writes file to that subdir. This can cause rmdir to fail and to throw exception, crashing whole stellar-core.

This issue was found when invalid history entry was entered into one of livenet servers, which caused a lot more downloads (and catchup operations) to fail than usual, making this rare error not so rare.

**Comment by jedmccaleb** [comment]
I think we just want to catch this exception so stellar-core doesn't crash. Otherwise the code can stay the same
