### ISSUE TITLE
Sending asset without trustline within a single account possible

### ISSUE THREAD

**Issue by bartekn** [stellar/stellar-core#1142]
It's possible to send a payment from account `A` to `A` even if `A` doesn't have a trust line to asset being sent. What's more it's possible to set asset issuer to account that does not exist.

Issuer and `CODE` trustline exists but asset with `COD` code does not: https://horizon-testnet.stellar.org/operations/27741975448915969
Issuer does not exist: https://horizon-testnet.stellar.org/operations/27742280391593985

**Comment by vogel** [comment]
Merged
