### ISSUE TITLE
regtest mode for private network?

### ISSUE THREAD

**Issue by chainhead** [stellar/stellar-core#1152]
How can I run Stellar core for a private network - similar to running Bitcoin in `regtest` mode? Link - [regtest mode](https://bitcoin.org/en/developer-examples#regtest-mode)

**Comment by jedmccaleb** [comment]
sure. just change the NETWORK_PASSPHRASE in the .cfg
https://github.com/stellar/stellar-core/blob/master/docs/stellar-core_example.cfg 
only nodes with the same NETWORK_PASSPHRASE name can interact with the given network

**Comment by chainhead** [comment]
ok. How do I get the Java SDK to connect to such a network? The [javadoc](https://stellar.github.io/java-stellar-sdk/org/stellar/sdk/Network.html) for `Network` mentions a `use(Network network)` method; can you show me an example to instantiate the `Network` class?

**Comment by bartekn** [comment]
@chainhead for standard networks just use:
```java
Network.useTestNetwork();
// or
Network.usePublicNetwork();
```
If you want to create your own network then you need to:
```java
Network network = new Network("your network passphrase");
Network.use(network);
```

**Comment by chainhead** [comment]
Thank you, @bartekn !

**Comment by thenakulchawla** [comment]
I think `regtest` would make more sense with this standalone cfg : https://github.com/stellar/stellar-core/blob/master/docs/stellar-core_standalone.cfg 

Although we can connect more nodes in `regtest` mode, but usually I would run one node to test my software for bugs.
