### ISSUE TITLE
Disjoint quora slices and global ledger status.

### ISSUE THREAD

**Issue by chainhead** [stellar/stellar-core#1157]
**Theoretically**, if all the nodes in the quorum _participate only in disjoint slices_, then there wouldn't ever be a single global state of the ledger. Does Stellar help identify such scenarios in the network (main or private)?

**Comment by chainhead** [comment]
Can someone please respond to this?

@jedmccaleb  perhaps ... ?

**Comment by MonsieurNicolas** [comment]
Good question.

We've limited the way quorums are configured in stellar-core to avoid this situation as much as possible by using `(threshold, list of nodes)` as a way to generate the quorum slices that a validator cares about (the paper allows for arbitrary sets). So in practice people will have some overlap between their quorum slices.

Going back to your question, I am not aware of code/tools that has been written to help identify if a network as a whole is configured like that - but if you (or people you know) has some cycles, feel free to give it a try.

I think the closest we have right now, baked into the main binary, is the information that you can get by running one of:
 * `stellar-core -c info` (abbreviated form)
 * `stellar-core -c quorum` (verbose)

The field `quorum` looks like this:
```
"4529028" : {
   "agree" : 3,
   "disagree" : null,
   "fail_at" : 2,
   "fail_with" : [ "sdf1", "sdf2" ],
   "hash" : "273af2",
   "missing" : null,
   "phase" : "EXTERNALIZE",
   "value" : {
      "t" : 2,
      "v" : [ "sdf1", "sdf2", "sdf3" ]
   }
},
```
`fail_at` is the distance (in number of nodes) to the closest v-blocking set, `fail_with` (visible only with the `quorum` command) is an example of a set that would cause the local validator to fail.

This information is aimed at the validator administrator that in theory is attempting to configure its node to avoid creating a disjoint network.

**Comment by chainhead** [comment]
Thanks for the response.

**Comment by MonsieurNicolas** [comment]
Oh - one thing I forgot to mention (almost forgot in the context of your question - @zbyszkol reminded me of that). you can take a look at
`checkquorum` that will use some messages from history to check for quorum intersection. The limitation of this implementation is that it only uses messages stored in the history archive, so it biases heavily towards the validator that uploaded into the archive: only messages used for that validator to reach consensus are guaranteed to be uploaded, others are best effort (so if other parts of the network lag behind their messages may not be included).
