### ISSUE TITLE
Documentation proposal: Sync stellar-core machine with NTP server

### ISSUE THREAD

**Issue by mvaneijk** [stellar/stellar-core#1171]
As I was experiencing the `Local time is not synchronized with NTP time.` error I had to synchronize my machine with the time server.
It would be nice if you added a description in the documentation, I did the following:

# Install NTP time synchronization (Amazon EC2 Ubuntu 14.04 Linux instance)

At the core machine:
- ~download latest ntp daemon @ http://www.ntp.org/downloads.html~
- ~follow build instructions (./configure, make, sudo make install)~
- ~reboot~
- sudo create a file '/etc/ntp.conf'
- paste following code in there:
```
server 0.pool.ntp.org
server 1.pool.ntp.org
server 2.pool.ntp.org
server 3.pool.ntp.org
```
- sudo apt-get install ntp
- /etc/init.d/ntp restart

Now the ntp daemon will search for a preferred time server. To check the status run
- `ntpq -p` , output should be like:

```
remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
*46.4.28.205     131.188.3.222    2 u    3   64    1    5.920    1.274   0.000
 193.175.73.151  .INIT.          16 u    -   64    0    0.000    0.000   0.000
 81.7.14.209     .INIT.          16 u    -   64    0    0.000    0.000   0.000
 213.209.109.45  10.129.40.211    2 u    3   64    1   13.492    1.378   0.000

Then find the id of the preferred server and synchronize time with it, run:
- `ntpdate -u 131.188.3.222` for the example above.

**Comment by MonsieurNicolas** [comment]
closing: this type of information in readily available on the internet and I suspect that it's heavily dependent on too many things (distro, architecture, etc)
