### ISSUE TITLE
Disallow connecting too old nodes to network

### ISSUE THREAD

**Issue by vogel** [stellar/stellar-core#1172]
Currently there are many old nodes connected to pubnet.
For example:

      {
         "id" : "jianing",
         "ip" : "61.187.198.156",
         "olver" : 5,
         "port" : 11625,
         "ver" : "v0.5.0-7-g19f2905"
      },

This node is using stellar-core that does not know how to properly handle ledger version 3 (version from May 2016).

This node should not be allowed to connect as it won't understand some transactions and will return invalid results which may cause additional network traffic.

Proposed solution:
* when peer send Hello with ledgerVersion smaller that current ledger version, drop it
* when current ledger version is upgraded, drop all peer that sent Hello with ledgerVersion smaller that it

**Comment by jedmccaleb** [comment]
Hmm maybe as long as the dropped side has some indication of why it was dropped.

**Comment by vogel** [comment]
After discussion with Jed we are dropping it. Let implement #1173 with usage of StatusManager at the side of the older node - it will be better for diagnostics.
