### ISSUE TITLE
Check what happens if network votes for ledger update and current instance is too old

### ISSUE THREAD

**Issue by vogel** [stellar/stellar-core#1173]
If network votes for ledger update but current node is too old it should disconnect as there is nothing it can do to read that network.

Check how it works currently.

**Comment by vogel** [comment]
Update after discussion with Jed and Lukas: old node should display information about being too old in /info endpoint (see StatusManager class) and try its best to keep up with the network (no disconnection, no stopping instance).

**Comment by MonsieurNicolas** [comment]
it will just get out of sync. https://github.com/stellar/stellar-core/issues/1506 will make it fail with a better message (without corrupting its state)
