### ISSUE TITLE
Sleep OverlayManager until next connection attempt

### ISSUE THREAD

**Issue by graydon** [stellar/stellar-core#118]
OverlayManagerImpl knows when to run its next connection attempt, but it does not currently use this information to limit its sleep/wake cycle. Instead it schedules a tick every 2 seconds (`OverlayManagerImpl::tick()`). There's no need for this, it might as well sleep until the next connect attempt should be made.

**Comment by MonsieurNicolas** [comment]
not worth doing at this point given that we're attempting to promote peers all the time
