### ISSUE TITLE
All payment operations should be done through one method

### ISSUE THREAD

**Issue by vogel** [stellar/stellar-core#1188]
Payment in code is done in 4 steps:

remove balance from A
store A in database
add balance to B
store B in database

This pattern is replicated in code several times. It needs a function/method of its own.

**Comment by allanliu** [comment]
I'd be interested in taking a look at this if no one else has already taken it..

**Comment by vogel** [comment]
Hi. Thank you for your interest in this task. Could you please hold for a few days? Doing any changes in this area of code is not advised before #1210 is merged (it changes a lot about payments, so your whole work would have to be redone after that).

I hope this merge will happen soon, so you can start working on it.

**Comment by allanliu** [comment]
Gotcha.  Thanks!

**Comment by allanliu** [comment]
Hi. Checking in on this.  Seeing that #1210 is now closed with each the PR now broken down into smaller PRs, does this now depend on the newly created PRs?

**Comment by vogel** [comment]
Lets see first what @MonsieurNicolas thinks of this idea.

**Comment by MonsieurNicolas** [comment]
It's hard to tell without actually looking into this in detail. I don't know where this pattern is repeated several times that would benefit from this change.

From what I know most of the time we are not actually doing this in pair like this, there is a bunch of logic in between.

**Comment by allanliu** [comment]
ah.  Well, I guess I'll just look for another issue to get my feet wet with :smile:

**Comment by MonsieurNicolas** [comment]
closing: I suspect that this kind of refactoring will not happen in isolation
