### ISSUE TITLE
Check test quality using mutation testing

### ISSUE THREAD

**Issue by mvaneijk** [stellar/stellar-core#1195]
I read about this concept, this can be handy to check the quality of the existing tests.  
https://en.wikipedia.org/wiki/Mutation_testing

**Comment by MonsieurNicolas** [comment]
Interesting.

From a practical standpoint I don't know if we could make it work against our code base - I suspect for that to work we'd need to mutate at a relatively low level (like a small module).

Any idea on how to move beyond the concept?
