### ISSUE TITLE
can't get a fresh node work with complete_catchup and 'put' history archive 

### ISSUE THREAD

**Issue by codeck** [stellar/stellar-core#1197]
current publish queue is about 100k and HistoryManagerImpl::getPublishQueueStates() will hang up for minutes every time after stellar-core gets synced, then the node lost sync and catchup again. it loops always.

**Comment by codeck** [comment]
actually it's also blocked by bucket gc. as https://github.com/stellar/stellar-core/commit/7a325688f7fe0a78148375257b57cc1c216ee6d0  tried to avoid in catchup phase.

**Comment by vogel** [comment]
Fixed by caching unreferenced buckets.
