### ISSUE TITLE
"Recovery has been disabled for this account"

### ISSUE THREAD

**Issue by JamieFarrelly** [stellar/stellar-core#1209]
To be honest I'm not sure if this is the best repo for this, and maybe there's already a bug for it but I genuinely can't find it. I'm a dev myself and was about to start looking in to contributing to Stellar, but then I tried to log in to my old account. I've an account from years ago and can't get access even though I've got my recovery key. 

I get a "Recovery has been disabled for this account" message when I enter my username and recovery key (the old site, not the new version with your secret etc).

I've found this link while searching (https://stellarorg.zendesk.com/hc/en-us/articles/204218285-Wallet-v1-recovery-code-bug-up-to-August-3rd-2014) which says that it's a bug that has been fixed, but without your password because of this bug you've lost access to your account - is this for real?

I don't see how anyone could have confidence in Stellar if a bug can liteally rob you from your lumens.

**Comment by JamieFarrelly** [comment]
The bug says "If your recovery code is not working, and you activated it prior to August 3 2014..." in that link. My account was created that exact day (weird, eh?)  so technically this bug shouldn't affect me? The email with my recovery key says that if someone has your username and recovery key they can get access to your account - but this isn't true now.

**Comment by jedmccaleb** [comment]
safest thing is to always store your own secret key. but please mail hello@stellar.org

**Comment by maxstoller** [comment]
Hi @JamieFarrelly, I'm running into the same problem. Were you able to recover your account? Thanks!

**Comment by JamieFarrelly** [comment]
@maxstoller The stellar team helped me out, this was before Stellar really gained traction though so you might be waiting a while now.

**Comment by maxstoller** [comment]
Thanks @JamieFarrelly
