### ISSUE TITLE
Tx with empty signature accepted

### ISSUE THREAD

**Issue by bartekn** [stellar/stellar-core#1225]
Stellar-core (testnet) accepted a tx with empty signature (`DecoratedSignature.Signature`):
```
AAAAAMIK9djC7k75ziKOLJcvMAIBG7tnBuoeI34x+Pi6zqcZAAAAZAAZphYAAAABAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAynnCTTyw53VVRLOWX6XKTva63IM1LslPNW01YB0hz/8AAAAAAAAAAlQL5AAAAAAAAAAAAh0hz/8AAABA8qkkeKaKfsbgInyIkzXJhqJE5/Ufxri2LdxmyKkgkT6I3sPmvrs5cPWQSzEQyhV750IW2ds97xTHqTpOfuZCAnhSuFUAAAAA
```
in the ledger: 1680922.

**Comment by vogel** [comment]
It seems like this empty signature is an empty X

This account had an hash-of-x signer added where hash-of-x was XDR3BRCCTD6BYFE27P2MRGLPXESCPLSB4RSJXE2MUSKZSG3YKK4FKDDZ, which is e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855, which is sha256(empty-string).

This signer had weight of 3 so with the second signature it was 6, and transaction was accepted. So with current implementation the behavior is correct

We can choose to leave it as it is and fix horizon or to ban empty signatures and value of sha256(empty-string) as signer with SET_OPTIONS_BAD_SIGNER error from setOptions operation.

**Comment by vogel** [comment]
Current behavior is proper. We will leave it as it is.
