### ISSUE TITLE
Allow out-of-order ledgers

### ISSUE THREAD

**Issue by vogel** [stellar/stellar-core#1229]
Currently when receiving out of order ledger stellar-core gets out of sync (if it was synced) and requires catchup, if it was during catchup, then catchup will fail and will have to be restarted.

It is also possible that after receiving out of order ledger a proper one will be received, for example:

client gets ledger N
client gets ledger N+2
client gets ledger N+1
client gets ledger N+3

I think we could support such scenarios and do not require catchup (or fail catchup) in that case. I think stellar-core could wait for up to 60 seconds for missing ledgers, and only then get out of sync.

**Comment by jedmccaleb** [comment]
Do you see it getting out of order ledgers in practice?

**Comment by vogel** [comment]
No, I have not seen that behavior, but you've mentioned it during our last call.

**Comment by vogel** [comment]
Just realized it is already implemented in PendingEnvelopes.
