### ISSUE TITLE
Build on alpine linux fails

### ISSUE THREAD

**Issue by Globegitter** [stellar/stellar-core#1237]
I am trying to compile stellar core for alpine linux but failing. I am using the image `globegitter/stellar-core-build:alpine-3.6` (Dockerfile: https://gist.github.com/Globegitter/d75a39f7f7c0f6305ce52f3196c46cdc) to build the image and getting the following error:

```
util/format.cc: In function 'int {anonymous}::safe_strerror(int, char*&, std::size_t)':
util/format.cc:142:29: error: invalid conversion from 'int' to 'char*' [-fpermissive]
   char *message = strerror_r(error_code, buffer, buffer_size);
                   ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option '-Wno-unknown-warning-option'
cc1plus: warning: unrecognized command line option '-Wno-unused-local-typedef'
cc1plus: warning: unrecognized command line option '-Wno-unused-command-line-argument'
make[3]: Leaving directory '/builds/core/lib'
make[3]: *** [Makefile:1587: util/format.o] Error 1
make[2]: *** [Makefile:1647: all-recursive] Error 1
make[2]: Leaving directory '/builds/core/lib'
make[1]: *** [Makefile:461: all-recursive] Error 1
make[1]: Leaving directory '/builds/core'
make: *** [Makefile:392: all] Error 2
```

I am not the c expert, so while the error in itself makes some sense to me why this is happening on alpine but not on ubuntu. Could that be an issue with the build dependencies installed? Or with alpine itself?

**Comment by vogel** [comment]
Looking here: https://wiki.alpinelinux.org/wiki/Running_glibc_programs
I think that you could try to install glibc with dev libraries and then compile stellar-core.

**Comment by MonsieurNicolas** [comment]
I think I found the issue. I'll get a PR out shortly

**Comment by MonsieurNicolas** [comment]
commit 5e54c91f751ce59590d106a3e7a661d5ad4a7f1b should have taken care of this problem, reopen if it's not the case. I do not have a machine running Alpine Linux.

**Comment by otokarev** [comment]
The issue still can be reproduced with [Dockerfile](https://gist.github.com/otokarev/c3455ac8c0c07d88848578930e4ecff7)

```
In file included from ../lib/asio/include/asio/impl/src.hpp:23:0,
                 from asio/src/asio.cpp:61:
../lib/asio/include/asio/impl/error_code.ipp: In member function 'virtual std::__cxx11::string asio::detail::system_category::message(int) const':
../lib/asio/include/asio/impl/error_code.ipp:110:22: error: could not convert 'strerror_r(value, ((char*)(& buf)), sizeof (buf))' from 'int' to 'std::__cxx11::string {aka std::__cxx11::basic_string<char>}'
     return strerror_r(value, buf, sizeof(buf));
            ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
At global scope:

```
