### ISSUE TITLE
Database connection sslmode

### ISSUE THREAD

**Issue by Globegitter** [stellar/stellar-core#1254]
I haven't seen anything on configuring ssl connection / no ssl connection to the postgres database. hoult that possible?

Should `DATABASE="postgresql://dbname=stellar user=postgres host=/postgresql-unix-sockets sslmode=enable"` for example work?

**Comment by jedmccaleb** [comment]
I believe that should work. Did you try it?

**Comment by vogel** [comment]
This is not correct syntax for sslmode.

You can use for example: DATABASE="postgresql://dbname=stellar user=postgres host=host sslmode=verify-full" 

And it work as expected.
