### ISSUE TITLE
error: static assertion failed: Require 64bit time_t

### ISSUE THREAD

**Issue by druilaap** [stellar/stellar-core#1257]
I'm trying to compile the prod branch of Stellar-core on Linux Raspbian Jessie. GCC version 4.9 and clang 3.5.  I get the following error. Full logs attached: [stellarcorecompilelog.txt](https://github.com/stellar/stellar-core/files/1153204/stellarcorecompilelog.txt) 

In file included from ./database/Database.h:11:0,
                 from ./bucket/BucketApplicator.h:8,
                 from bucket/Bucket.cpp:10:
./util/Timer.h:63:5: error: static assertion failed: Require 64bit time_t
     static_assert(sizeof(uint64_t) == sizeof(std::time_t),
     ^

Is there a way to work around this? This is a 32 bit linux system, so there is no 64 bit time_t.... But I did not see 64 bit as a requirement for building.

**Comment by vogel** [comment]
Hi. Thank you for your report.

Unfortunately, it is not possible to build stellar-core with 32 bit system.
I've added a node to INSTALL.md about that: https://github.com/stellar/stellar-core/pull/1285
