### ISSUE TITLE
check what happens if old stellar-core tries to catchup-minimal to current history

### ISSUE THREAD

**Issue by vogel** [stellar/stellar-core#1258]
Preferred behavior: it reports that it is too old to support that history and closes itself.
Guessed behavior: it tries to catchup and succeeds, because most transactions have the same behavior now and in old version. It finally fails when transaction with different behavior happens.

**Comment by MonsieurNicolas** [comment]
I think that what we probably want is to fast fail if we encounter a ledger header that is from a version more recent than what we're running, this is a problem that could also be encountered at consensus time (network outvotes local node that is running an old build).

Right now the code doesn't even check for that before applying and fails after making (bad) changes to the database.

**Comment by MonsieurNicolas** [comment]
we now fast fail as per linked issue
