### ISSUE TITLE
Disable history repository if catching up from it caused hash mismatches

### ISSUE THREAD

**Issue by vogel** [stellar/stellar-core#1263]
If catching up to one history repository caused hash mismatches then it should not be considered in next replies, because if it gets chosen again, it will fail again. This is probably already implemented and just needs checking.

**Comment by marta-lokhova** [comment]
Right now we do not have a way to "blame" a bad archive, so I think that should be implemented as well. 

As part of this, I think we need a few things:
* Refactor catchup code to allow specifying an archive (right now an archive is selected randomly at download)
* Mark and exclude "bad" archives during catchup. This requires some way of remembering which archives are bad, and figuring out the best way to notify an operator
* (fail fast: possibly for the next iteration) Move download->verify ledger header works from "download all then verify all" to "download one, verify one" mechanism
