### ISSUE TITLE
make check error

### ISSUE THREAD

**Issue by kimcyw** [stellar/stellar-core#1271]
I runed make check (under Mac Os)
I had error " ssertion failed: ((reinterpret_cast<intptr_t>(start) & 3)), function xdr_generic_get, file ./xdrpp/marshal.h, line 145."

How can I solve it?

**Comment by MonsieurNicolas** [comment]
Is it just `make check` or building in general that doesn't work for you?
If so, which version of Mac OS are you running?

btw, we just updated the instructions for Mac OS. See https://github.com/stellar/stellar-core/blob/master/INSTALL.md#os-x
