### ISSUE TITLE
review log levels for different logs

### ISSUE THREAD

**Issue by vogel** [stellar/stellar-core#1276]
After #1272 gets merged we need to review our log level.
I would like very much to get traces from logs when tx fails to apply during catchup, but also I don't care about traces from connection errors in Overlay module. Both of these use ERROR log level.

We should either change the less important ones from ERROR to WARNING and change in-memory push level to ERROR

or

we could change the more imporant ones to FATAL and leave in-memory push level as it is.

I prefer first solution.

**Comment by MonsieurNicolas** [comment]
PR #1272 was rolled back ; #1326 is now tracking this type of problem
