### ISSUE TITLE
Better system for preferred peers

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-core#1278]
Should be able to enter in an IP and a public key for preferred peers in the .cfg

Should prioritize connecting to the preferred peers. 

Also investigate how the peer list is being handled right now. It seems like the old peers can clog up a server and prevent it from joining the network for a long time.

**Comment by MonsieurNicolas** [comment]
First part was done in #1287 

Second part needs to be looked at
> It seems like the old peers can clog up a server and prevent it from joining the network for a long time."
