### ISSUE TITLE
Improve the built-in inflation mechanism

### ISSUE THREAD

**Issue by phasnox** [stellar/stellar-core#1284]
The current built-in inflation mechanism could potentially benefit only the wealthy. Any player with more than 0.05% of the lumens in circulation would always get what's in the inflation pool.

This could potentially escalate into centralization. Where one, or a group of few are in control of the XLM that is created and distributed weekly.

I was wondering if this is something you have discuss previously, and if you have any idea on how to mitigate this risk.

**Comment by vogel** [comment]
Hi.

Could you add this issue to stellar-protocol repository: https://github.com/stellar/stellar-protocol?
