### ISSUE TITLE
After removing every writable history from config stellar-core still tries to publish

### ISSUE THREAD

**Issue by vogel** [stellar/stellar-core#1289]
If stellar-core has anything in its publishqueue table it treis to publish even when all writable history are removed from configuration and stellar-core is restarted.

**Comment by MonsieurNicolas** [comment]
and what do we see here? I would imagine it just succeeds very quickly at publishing?

**Comment by vogel** [comment]
Yes, this is what happens.

**Comment by MonsieurNicolas** [comment]
so maybe we don't care about this then?

**Comment by vogel** [comment]
Fair point. We can just let this clear up the table.
