### ISSUE TITLE
Possible issue when removing unrecoverable bucket file

### ISSUE THREAD

**Issue by vogel** [stellar/stellar-core#1290]
Try following scenerio:
- catchup to a network
- stop node after ledger that was not a checkpoint ledger and had at least one transaction
- remove all local bucket files
- restart stellar-core

It should try to "repair missing buckets" but it could fail, as these buckets are not available to download from the network.

**Comment by vogel** [comment]
This could be fixed by introducing some reset option that resets state of current node to given checkpoint - without removing whole history.

Alghoritm could be very simple:
- delete all accounts, accountdata, offers, trustlines and other data that is stored in buckets
- delete ledger headers and similar per-ledger data that are later than given checkpoint
- download buckets for given checkpoint and apply them all
- store proper data (lastledger, history) in state table

**Comment by MonsieurNicolas** [comment]
I think @graydon basically implemented this already (not merged yet)

**Comment by graydon** [comment]
Yes, I have a workspace with basically this functionality in it, though I'm not _certain_ it builds us back to a state that can rejoin the network -- I only made it work to the point of testing the set of ledger objects in the DB, not a full restart. Still probably the right starting point. I'll post in a bit.

**Comment by graydon** [comment]
I've posted the bit here in PR #2087 along with 2 other minor changes.
