### ISSUE TITLE
Processes executed by stellar-core do not inherit the environment from stellar-core on all platforms

### ISSUE THREAD

**Issue by vogel** [stellar/stellar-core#1291]
For example if stellar-core is executed with AWS env vars like:

AWS_ACCESS_KEY_ID=xxx
AWS_SECRET_ACCESS_KEY=xxx
AWS_DEFAULT_REGION=us-east-2 aws

these should be passed to sub processes.

**Comment by s-a-y** [comment]
+1
Causing me trouble with gcloud too

**Comment by MonsieurNicolas** [comment]
Looking at the code it looks like we're just resetting the environment to nothing in the POSIX case (Windows inherits the environment).

Is it that people are typically using security groups to do auth for their archive integration?

**Comment by s-a-y** [comment]
For AWS you can probably get around this by using file with credentials,
but gcloud utility to publish archives to google cloud storage requires few environment variables to be set, and I couldn't make it work
