### ISSUE TITLE
Stellar core sometimes dies with "Assertion `snap' failed."

### ISSUE THREAD

**Issue by s-a-y** [stellar/stellar-core#1296]
Log message:
stellar-core: bucket/FutureBucket.cpp:267: void stellar::FutureBucket::startMerge(stellar::Application&): Assertion `snap' failed.

**Comment by MonsieurNicolas** [comment]
Thanks for the report.
Do you have any context on what core was doing at the time? Was it during normal operation, catch up, etc?

**Comment by s-a-y** [comment]
During normal operation.
I think it happened to me few times when I had big queue for publishing archives, then I cleared the queue and haven't seen that again.
I got long queue by specifying `put` command, which wasn't working

**Comment by vogel** [comment]
I think I can now reliably reproduce that.
