### ISSUE TITLE
I am able to submit an offer even if available balance for the selling asset code is zero

### ISSUE THREAD

**Issue by swetakedia** [stellar/stellar-core#1303]
I am able to submit an offer even if available balance for the selling asset code is zero

Selling asset code: EUR
Selling asset code issuer : GD6S4DBCI3GWUHZQAUSBX4LXMAR5ZNQC4R4P3VKOXXH5MYOKZZYAO6XP
Buying asset code : USD
Buying asset issuer : GDWDQVN367GJ3N4GEG2W4NJ3GPYA5OKTI4VHIRARDIRLJCXVMY75SDSP

Offer id : 4661

This offer is even getting fulfilled if I create a counter offer using another account.

I am creating offer using ManageOffer operation.

My observation, the offer is getting fulfilled and the account is getting credited the asset it is trying to buy, but the amount is not getting debited from balance available for the selling asset code.

Two more such accounts : GB66XIZRXNNL4NGSCBTCZWO3ANQKNX6TKEKRFSP27G5J7HHHOWAQURUW and GAHUPKUHI3WW3RZSQ4JJ7VIU3JAE73VXPOKRHHAY375UJNPJYGZZWWCM

**Comment by swetakedia** [comment]
I need to check few more things before confirming the issue hence closing.

**Comment by jedmccaleb** [comment]
I would be surprised if this is what is really going on. Can you paste the tx that you think this happened in?

**Comment by swetakedia** [comment]
You can check the settled offers in following trades endpoint:

https://horizon-testnet.stellar.org/order_book/trades?selling_asset_type=credit_alphanum4&selling_asset_code=AED&selling_asset_issuer=GD6S4DBCI3GWUHZQAUSBX4LXMAR5ZNQC4R4P3VKOXXH5MYOKZZYAO6XP&buying_asset_type=credit_alphanum4&buying_asset_code=INR&buying_asset_issuer=GDWDQVN367GJ3N4GEG2W4NJ3GPYA5OKTI4VHIRARDIRLJCXVMY75SDSP

When I submitted the offer first from - GB66XIZRXNNL4NGSCBTCZWO3ANQKNX6TKEKRFSP27G5J7HHHOWAQURUW for selling asset AED and buying asset INR. The available balance in AED for this account was 5000.

2nd offer 

From GAHUPKUHI3WW3RZSQ4JJ7VIU3JAE73VXPOKRHHAY375UJNPJYGZZWWCM for selling asset INR and buying AED. The available INR balance was 5000.

The moment I submitted the 2nd offer, both the offer got fulfilled but the available balance both AED and INR is same (5000).

**Comment by vogel** [comment]
Is the account an issuer of assets it is trying to sell?

**Comment by swetakedia** [comment]
No,

Following are the distribution a/c -

GB66XIZRXNNL4NGSCBTCZWO3ANQKNX6TKEKRFSP27G5J7HHHOWAQURUW and GAHUPKUHI3WW3RZSQ4JJ7VIU3JAE73VXPOKRHHAY375UJNPJYGZZWWCM

Their issuing a/c are - GALEHBJH7QWWAYPSVE5EKUFQ3YXWNBSUR2LZ7R3HUEV246BFQVWNIA3L and GCDMS3BID4KR7W2PJRMS6XB62UYYTLCNV62BD6SXCZ37EJT7MI6HPLDZ respectively.

**Comment by MonsieurNicolas** [comment]
I looked into this and you're not using the right issuers from what I can tell...

GAHUPKUHI3WW3RZSQ4JJ7VIU3JAE73VXPOKRHHAY375UJNPJYGZZWWCM was setup to trade
* INR/GCDMS3BID4KR7W2PJRMS6XB62UYYTLCNV62BD6SXCZ37EJT7MI6HPLDZ
* AED/GB66XIZRXNNL4NGSCBTCZWO3ANQKNX6TKEKRFSP27G5J7HHHOWAQURUW

GB66XIZRXNNL4NGSCBTCZWO3ANQKNX6TKEKRFSP27G5J7HHHOWAQURUW  was setup to trade
 * AED/GALEHBJH7QWWAYPSVE5EKUFQ3YXWNBSUR2LZ7R3HUEV246BFQVWNIA3L
 * INR/GAHUPKUHI3WW3RZSQ4JJ7VIU3JAE73VXPOKRHHAY375UJNPJYGZZWWCM

But the offers that you created were not matching the assets you prepared to trade...
check out what [GAHUP](https://www.stellar.org/laboratory/#xdr-viewer?input=AAAAAA9HqodG7W3HMocSn9UU2kBP7rd7lROcGN%2F7RLXpwbObAAAAZAA7%2FLoAAAAFAAAAAAAAAAAAAAABAAAAAQAAAAAPR6qHRu1txzKHEp%2FVFNpAT%2B63e5UTnBjf%2B0S16cGzmwAAAAMAAAABSU5SAAAAAAAPR6qHRu1txzKHEp%2FVFNpAT%2B63e5UTnBjf%2B0S16cGzmwAAAAFBRUQAAAAAAH3rozG7Wr400hBmLNnbA2Cm39NRFRLJ%2Bvm6n5zndYEKAAAAAAcnDgAAAAABAAAAAgAAAAAAAAAAAAAAAAAAAAHpwbObAAAAQJ6E56R7DaHtygAvbfBY%2Bei9FQRioU7l%2FzjCH0tLq6mKMtFwGFspjCXgFBPmH%2Fz9ZGkaO55spPeDyZnGbKVVyA0%3D&type=TransactionEnvelope&network=test) is doing:
it's selling 12 INR/GAHUP for AED/GB66X at a price of 0.5...

So when you tried to create an offer with GAHUP it crossed with the offer from GB66X... as you were expecting, except that you missed the fact that GAHUP is the issuer of the INR that GB66X is buying and GB66X is the issuer for the AED that GAHUP is buying.

The balances are updated correctly after that: GAHUP received 6 AED/GB66X and GB66X received 12 INR/GAHUP

**Comment by MonsieurNicolas** [comment]
please re-open this issue if you are seeing something different
