### ISSUE TITLE
No config file stellar-core.cfg found

### ISSUE THREAD

**Issue by zengdick** [stellar/stellar-core#1320]
start stellar-core No config file stellar-core.cfg found

**Comment by MonsieurNicolas** [comment]
@zengdick can you provide more detail on your environment. Are you running directly or from within a container?

Did you try with an absolute path to your config file?

**Comment by zengdick** [comment]
@MonsieurNicolas 
    I use vs2017 debug mode x64 to start running stellar-core code
int main (int argc, char * const * argv)
{
    using namespace stellar;

    Logging :: init ();
    if (sodium_init ()! = 0)
    {
        LOG (FATAL) << "Could not initialize crypto";
        return 1;
    }

    std :: string cfgFile ("stellar-core.cfg");
    std :: string command;
    el :: Level logLevel = el :: Level :: Info;
    std :: vector <char *> rest;

    optional <bool> forceSCP = nullptr;
    bool base64 = false;
    bool catchupComplete = false;
    bool inferQuorum = false;
    bool checkQuorum = false;
    bool graphQuorum = false;
    bool newDB = false;
    bool getOfflineInfo = false;
    std :: string loadXdrBucket = "";
    std :: vector <std :: string> newHistories;
    std :: vector <std :: string> metrics;

    int opt;
    while ((opt = getopt_long_only (argc, argv, "c:", stellar_core_options,
                                   nullptr))! = -1)
    {
        switch (opt)
        {
        case OPT_BASE64:
            base64 = true;
            break
        case OPT_CATCHUP_COMPLETE:
            catchupComplete = true;
            break
        case 'c':
        case OPT_CMD:
            command = optarg;
            rest.insert (rest.begin (), argv + optind, argv + argc);
            optind = argc;
            break
        case OPT_CONF:
            cfgFile = std :: string (optarg);
            break
        case OPT_CONVERTID:
            StrKeyUtils :: logKey (std :: cout, std :: string (optarg));
            return 0;
        case OPT_DUMPXDR:
            dumpxdr (std :: string (optarg));
            return 0;
        case OPT_PRINTTXN:
            printtxn (std :: string (optarg), base64);
            return 0;
        case OPT_SIGNTXN:
            signtxn (std :: string (optarg), base64);
            return 0;
        case OPT_SEC2PUB:
            priv2pub ();
            return 0;
        case OPT_NETID:
            signtxn_network_id = optarg;
            return 0;
        case OPT_LOADXDR:
            loadXdrBucket = std :: string (optarg);
            break
        case OPT_FORCESCP:
            forceSCP = make_optional <bool> (optarg == nullptr ||
                                           string (optarg) == "true");
            break
        case OPT_FUZZ:
            fuzz (std :: string (optarg), logLevel, metrics);
            return 0;
        case OPT_GENFUZZ:
            genfuzz (std :: string (optarg));
            return 0;
        case OPT_GENSEED:
        {
            SecretKey key = SecretKey :: random ();
            std :: cout << "Secret seed:" << key.getStrKeySeed (). value
                      << std :: endl;
            std :: cout << "Public:" << key.getStrKeyPublic () << std :: endl;
            return 0;
        }
        case OPT_INFERQUORUM:
            inferQuorum = true;
            break
        case OPT_CHECKQUORUM:
            checkQuorum = true;
            break
        case OPT_GRAPHQUORUM:
            graphQuorum = true;
            break
        case OPT_OFFLINEINFO:
            getOfflineInfo = true;
            break
        case OPT_LOGLEVEL:
            logLevel = Logging :: getLLfromString (std :: string (optarg));
            break
        case OPT_METRIC:
            metrics.push_back (std :: string (optarg));
            break
        case OPT_NEWDB:
            newDB = true;
            break
        case OPT_NEWHIST:
            newHistories.push_back (std :: string (optarg));
            break
        case OPT_TEST:
        {
            rest.push_back (* argv);
            rest.insert (++ rest.begin (), argv + optind, argv + argc);
            return test (static_cast <int> (rest.size ()), & rest [0], logLevel,
                        metrics
        }
        case OPT_VERSION:
            std :: cout << STELLAR_CORE_VERSION << std :: endl;
            return 0;
        case OPT_HELP:
        default:
            usage (0);
            return 0;
        }
    }

    Config cfg;
    try
    {
        // yes you really have to do this 3 times
        Logging :: setLogLevel (logLevel, nullptr);
        if (cfgFile == "-" || fs :: exists (cfgFile))
        {
            cfg.load (cfgFile);
        }
        else
        {
            std :: string s;
            s = "No config file";
            s + = cfgFile + "found";
            throw std :: invalid_argument (s);
        }
        Logging :: setFmt (KeyUtils :: toShortString (cfg.NODE_SEED.getPublicKey ()));
        Logging :: setLogLevel (logLevel, nullptr);

        if (command.size ())
        {
            sendCommand (command, rest, cfg.HTTP_PORT);
            return 0;
        }

**Comment by zengdick** [comment]
@MonsieurNicolas  
   Tried to use the absolute path, this still can not read the stellar-core.cfg file error

**Comment by MonsieurNicolas** [comment]
Which command line are you trying?

Maybe you should start by reading the [admin guide](https://github.com/stellar/stellar-core/blob/master/docs/software/admin.md)

On my dev box (Windows), I can do this:
```
C:\src\stellar-core\Builds\VisualStudio\x64\Debug> .\stellar-core.exe --conf ..\..\..\..\docs\stellar-core_testnet.cfg --ll info
2017-09-25T20:55:55.079 GCGDC [default INFO] Starting stellar-core unknown-msvc
2017-09-25T20:55:55.081 GCGDC [default INFO] Config from ..\..\..\..\docs\stellar-core_testnet.cfg
2017-09-25T20:55:55.084 GCGDC [Database INFO] Connecting to: sqlite3://stellar.db
2017-09-25T20:55:55.091 GCGDC [SCP INFO] LocalNode::LocalNode@GCGDC qSet: 273af2
2017-09-25T20:55:55.092 GCGDC [default INFO] Listening on 127.0.0.1:11626 for HTTP requests
2017-09-25T20:55:55.092 GCGDC [History INFO] Archive 'h1' has 'get' command only, will not be written
2017-09-25T20:55:55.092 GCGDC [History INFO] Archive 'h2' has 'get' command only, will not be written
2017-09-25T20:55:55.108 GCGDC [History INFO] Archive 'h3' has 'get' command only, will not be written
2017-09-25T20:55:55.124 GCGDC [History WARNING] No writable archives configured, history will not be written.
2017-09-25T20:55:55.139 GCGDC [default INFO] Loading last known ledger
```

or this using absolute path:
```
C:\src\stellar-core\Builds\VisualStudio\x64\Debug> .\stellar-core.exe --conf c:\src\stellar-core\docs\stellar-core_testnet.cfg --ll info
2017-09-25T20:56:19.089 GB6EI [default INFO] Starting stellar-core unknown-msvc
2017-09-25T20:56:19.091 GB6EI [default INFO] Config from c:\src\stellar-core\docs\stellar-core_testnet.cfg
2017-09-25T20:56:19.095 GB6EI [Database INFO] Connecting to: sqlite3://stellar.db
2017-09-25T20:56:19.101 GB6EI [SCP INFO] LocalNode::LocalNode@GB6EI qSet: 273af2
2017-09-25T20:56:19.101 GB6EI [default INFO] Listening on 127.0.0.1:11626 for HTTP requests
2017-09-25T20:56:19.101 GB6EI [History INFO] Archive 'h1' has 'get' command only, will not be written
2017-09-25T20:56:19.117 GB6EI [History INFO] Archive 'h2' has 'get' command only, will not be written
2017-09-25T20:56:19.117 GB6EI [History INFO] Archive 'h3' has 'get' command only, will not be written
2017-09-25T20:56:19.132 GB6EI [History WARNING] No writable archives configured, history will not be written.
2017-09-25T20:56:19.148 GB6EI [default INFO] Loading last known ledger
```
