### ISSUE TITLE
newdb doesn't clean bucket files

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1323]
As per #1282 it looks like `newdb` only cleans the SQL state but not the bucket state which may cause all sorts of problems if some of the bucket files are corrupted

**Comment by vogel** [comment]
In #1282 ckmakcesar mentions history archives (which are initialized by `--newhist`, I don't know of any way to clean that up from stellar-core).

Removing buckets dir is implemented in BucketManager::dropAll which should be called on `--newdb`. Let me check that.

**Comment by vogel** [comment]
Confirmed, bucket files are cleared on `--newdb`.
