### ISSUE TITLE
Long ledger close times

### ISSUE THREAD

**Issue by bartekn** [stellar/stellar-core#1333]
![screen shot 2017-09-28 at 16 21 31](https://user-images.githubusercontent.com/464938/31352610-a2da105c-ad2f-11e7-9588-ededa1ca0c50.png)
This started happening in the end of September. Looks persistent, every 10-30 ledgers: https://dashboard.stellar.org/

**Comment by MonsieurNicolas** [comment]
how is time tracked here? Is it looking up the `closeTime` field stored in the ledger headers or something else?

**Comment by bartekn** [comment]
> Is it looking up the `closeTime` field stored in the ledger headers or something else?

Yes, `closed_at` field in horizon ledger object (which is fetched from core db).

**Comment by bartekn** [comment]
It's not happening anymore. I think it's OK to close it.

**Comment by MonsieurNicolas** [comment]
it's definitively still happening

**Comment by bartekn** [comment]
OK, I haven't seen this pattern for a long time.
