### ISSUE TITLE
look at how FAILURE_SAFETY is calculated by default

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-core#1371]
It doesn't seem like this should be failing:

Can I get some help with this error from stellar-core:
```2017-11-03T19:49:39.759 <startup> [default ERROR] Not enough nodes / thresholds too strict in your Quorum set to ensure your desired level of FAILURE_SAFETY. Reduce FAILURE_SAFETY or fix quorum set [Config.cpp:711]
2017-11-03T19:49:39.759 <startup> [default INFO]  Current QUORUM_SET breaks with 3 failures
2017-11-03T19:49:39.759 <startup> [default FATAL] Got an exception: FAILURE_SAFETY incompatible with QUORUM_SET [main.cpp:643]
```

Here is the relevant part of my stellar-core.cfg:
```
[QUORUM_SET]
THRESHOLD_PERCENT=70
VALIDATORS=[
"$sdf_watcher1",
"$eno",
"$tempo.eu.com",
"$sdf_watcher2",
"$sdf_watcher3",
"$satoshipay"
]

[QUORUM_SET.1] 
THRESHOLD_PERCENT=51
VALIDATORS=[
"$cryptomover",
"$icicibank",
"$crservers",
"$umbrel",
"$zulucrypto"
]
```

**Comment by MonsieurNicolas** [comment]
it's tricky to guess intent (what we're trying to do).

Relevant code to look at is https://github.com/stellar/stellar-core/blob/aa7dc551b118b7856458f4306e612843d62c1cd3/src/main/Config.cpp#L691-L736

what we do by default:
* ensure that the safety margin is at least as good as a flat quorum (the failure we hit here)
   https://github.com/stellar/stellar-core/blob/aa7dc551b118b7856458f4306e612843d62c1cd3/src/main/Config.cpp#L702
    * operator needs to basically confirm the smaller number by setting `FAILURE_SAFETY` to the actual number of failures they're willing to tolerate. In this case the computed value is 3 (what happens when `FAILURE_SAFETY` is not set or set to -1) as there are 6+5=11 nodes, which in a flat configuration yields a capacity for 3 failures (using the n=3f+1 rule)
* check that the threshold creates the condition for having quorum intersection. https://github.com/stellar/stellar-core/blob/aa7dc551b118b7856458f4306e612843d62c1cd3/src/main/Config.cpp#L723-L726
   * the check that we have here is very simplistic and also uses the 3f+1 rule.
   * we cannot actually compute this with just the quorum configuration of the local node as it's a property of the network - so it's a conservative number/best guess type of situation

I don't know if there is something we can do to make this easier for people.

I could see changing the error message to actually explain to people that they have to set `FAILURE_SAFETY` to a different value (and that they understand what it means), and/or help generate a configuration file based on historical data.

**Comment by MonsieurNicolas** [comment]
Thinking about this more, I think that we can use as a default value for `FAILURE_SAFETY` the same thing that is computed for threshold:
````C++
unsigned int topSize = (unsigned int)(QUORUM_SET.validators.size() + 
QUORUM_SET.innerSets.size()); 
```
