### ISSUE TITLE
Not synced after taking one validation node offline

### ISSUE THREAD

**Issue by nengine** [stellar/stellar-core#1374]
# Issue type
  documentation

# Version found
v0.6.3-112-g20b5e3a

# Your environment and setup
Ubuntu 14.04
Postgres 9.6.5

# Issue description
I have started three validator nodes, which are all successfully synced at the beginning and I was able to make friedlybot requests and few payment transactions.  Then I took node #3 offline and network was still operational with node #1, #2 synced and was able to make few more payment transactions.   

## Actual result
When I brought node #3 online again with --forcescp flag, node #3 was not synced anymore and status is showing "Catching up: downloading ledger files 17/121 (14%)" and does not progress further, while the network was still operational and synced with just two nodes (node #1 and #2).  

## Expected result
node #3 status should also be "synced!". Any help is greatly appreciated.

## Supporting files

Only node #1 is setup to create history archive and node #2 and #3 read from it.  

node #1 config
```
NODE_IS_VALIDATOR=true
UNSAFE_QUORUM=true
[QUORUM_SET]
THRESHOLD_PERCENT=51
VALIDATORS=[
"$self", 
"$node2", 
"$node3"
]

[HISTORY.local]
get="cp /tmp/stellar-core/history/vs/{0} {1}"
put="cp {0} /tmp/stellar-core/history/vs/{1}"
mkdir="mkdir -p /tmp/stellar-core/history/vs/{0}"
```

node #2 config
```
NODE_IS_VALIDATOR=true
UNSAFE_QUORUM=true
[QUORUM_SET]
THRESHOLD_PERCENT=51
VALIDATORS=[
"$self", 
"$node1", 
"$node3"
]

[HISTORY.h1]
get="curl -sf http://xyz.org/stellar-core/history/vs/{0} -o {1}"
```

node #3 config
```
NODE_IS_VALIDATOR=true
UNSAFE_QUORUM=true
[QUORUM_SET]
THRESHOLD_PERCENT=51
VALIDATORS=[
"$self", 
"$node1", 
"$node2"
]

[HISTORY.h1]
get="curl -sf http://xyz.org/stellar-core/history/vs/{0} -o {1}"
```

**Comment by MonsieurNicolas** [comment]
Thanks for the detailed report.

Any chance that you can try this with 0.6.4rc ( https://github.com/stellar/stellar-core/tree/v0.6.4 ) ? It looks like you tried it on an arbitrary version of master that's missing a lot of catchup improvements.

Note that you should not have to use forcescp when rejoining the network for getting #3 to rejoin. I would expect to have #1 and #2 continue to work after taking down #3 - and #3 should catchup (using history) when it's restarted.

If you are running into this again, ideally you could also paste some logs (run #3 with option `--ll debug`) so that we can see what that node was doing.

**Comment by vogel** [comment]
That could be related with #802. Could you check if that node is really doing nothing after `Catching up: downloading ledger files 17/121 (14%)` or did it just stopped printing logs to stdout?

You could do that by either looking at it log file or doing HTTP request with /info on you stellar-core (default on port 11626).

**Comment by nengine** [comment]
I started a new network with version 0.6.4 and redoing the steps reported above seems to be working now **ONLY** **when I use --forcescp flag**.  I also changed the history section of config so that all three nodes write history archives and peers can read each others archive as shown below.  

If I don't use --forcescp flag to restart the node #3 then "Catching up: downloading ledger files 2/2 (100%)" is showing and it would not change the status to "Synced!".  Here is a link to log gist https://gist.github.com/nengine/ef48a50c32d601156846709f4150fee4 . 

Should I always to use --forcescp to restart validator node?  Thanks for your help.


node #1
```
[HISTORY.local]
get="cp /tmp/stellar-core/history/vs/{0} {1}"
put="cp {0} /tmp/stellar-core/history/vs/{1}"
mkdir="mkdir -p /tmp/stellar-core/history/vs/{0}"

[HISTORY.h2]
get="curl -sf http://stellar-02.xyz.info/stellar-core/history/vs/{0} -o {1}"

[HISTORY.h3]
get="curl -sf http://stellar-03.xyz.info/stellar-core/history/vs/{0} -o {1}"

```

node #2
```
[HISTORY.local]
get="cp /tmp/stellar-core/history/vs/{0} {1}"
put="cp {0} /tmp/stellar-core/history/vs/{1}"
mkdir="mkdir -p /tmp/stellar-core/history/vs/{0}"

[HISTORY.h1]
get="curl -sf http://stellar-01.xyz.info/stellar-core/history/vs/{0} -o {1}"

[HISTORY.h3]
get="curl -sf http://stellar-03.xyz.info/stellar-core/history/vs/{0} -o {1}"

```

node #3
```
[HISTORY.local]
get="cp /tmp/stellar-core/history/vs/{0} {1}"
put="cp {0} /tmp/stellar-core/history/vs/{1}"
mkdir="mkdir -p /tmp/stellar-core/history/vs/{0}"

[HISTORY.h1]
get="curl -sf http://stellar-01.xyz.info/stellar-core/history/vs/{0} -o {1}"

[HISTORY.h3]
get="curl -sf http://stellar-03.xyz.info/stellar-core/history/vs/{0} -o {1}"

```

**Comment by vogel** [comment]
Hi.

Thanks for the update. Could you check if your history archives are behaving correctly? Is there such a file as: http://stellar-01.xyz.info:3000/stellar-core/history/vs/ledger/00/00/06/ledger-000006bf.xdr.gz? Could you check content of /tmp/stellar-core/history/vs/ directories and their permissions? Maybe HTTP server does not have access to them.

Also, could you change your log level to INFO? Using DEBUG adds to much noise and is not really useful when debugging catchup problems.

--forcescp should only be used to start network, not single nodes (e.g. use that when many nodes failed and no quorum is available).

**Comment by nengine** [comment]
Hi, I got "Forbidden: You don't have permission to access ..." error and that must be an issue. I also see that 0600 permission was granted to the *.xdr.gz files and since stellar-core process is creating those files, is there a config flag to set minimum 0644 permission so that everyone can read?  

Thanks a lot.

**Comment by nengine** [comment]
Excellent!  Now all three nodes are syncing without --forcescp command after restarting.  

Many thanks.


cp-and-set-permission.sh
```sh
#!/bin/bash
cp $1 $2
chmod 644 $2

**Comment by vogel** [comment]
That is great! I've created follow-up issue for this one: #1377

**Comment by nengine** [comment]
Hello @vogel , I have three nodes running for nearly two weeks without any issue, but today after shutting down and restarting node-2, it is not syncing anymore!  I restarted without using --forcescp first, but since it didn't sync, I use --forcescp second time.  Still would not sync so I restarted without --forcescp third.  Not so sure it may have corrupted the database.  Could you please let me know what is the recommended way to restart a node so that it would sync properly?  Thanks a lot.

```
{
   "info" : {
      "UNSAFE_QUORUM" : "UNSAFE QUORUM ALLOWED",
      "build" : "v0.6.4",
      "ledger" : {
         "age" : 1511527609,
         "closeTime" : 0,
         "hash" : "0000000000000000000000000000000000000000000000000000000000000000",
         "num" : 136650
      },
      "network" : "Test XYZ Stellar Network ; October 2017",
      "numPeers" : 0,
      "protocol_version" : 8,
      "state" : "Joining SCP"
   }
}
```
```
2017-11-24T12:41:27.871 GCSJO [Work WARNING] Scheduling retry #8/32 in 161 sec, for get-and-unzip-remote-file bucket/04/af/a3/bucket-04afa38340d7807a377be3fbe15909d4e41a30eda71934746ed7ac0b1e43b65d.xdr.gz
2017-11-24T12:41:31.771 GCSJO [Process WARNING] process 8466 exited 22: curl -sf http://scp-03.xyz.info/stellar-core/history/vs/bucket/03/82/10/bucket-03821013fc4f132191276f9ebcabc35ce0d770c9eababe5bdb7dfa89ec261650.xdr.gz -o buckets/tmp/repair-buckets-b525f67f11945e20/bucket-03821013fc4f132191276f9ebcabc35ce0d770c9eababe5bdb7dfa89ec261650.xdr.gz.tmp
2017-11-24T12:41:31.771 GCSJO [Work WARNING] Reached retry limit 0 for get-remote-file bucket/03/82/10/bucket-03821013fc4f132191276f9ebcabc35ce0d770c9eababe5bdb7dfa89ec261650.xdr.gz
2017-11-24T12:41:31.772 GCSJO [Work WARNING] Scheduling retry #8/32 in 182 sec, for get-and-unzip-remote-file bucket/03/82/10/bucket-03821013fc4f132191276f9ebcabc35ce0d770c9eababe5bdb7dfa89ec261650.xdr.gz
2017-11-24T12:41:35.779 GCSJO [Process WARNING] process 8468 exited 22: curl -sf http://scp-03.xyz.info/stellar-core/history/vs/bucket/46/57/47/bucket-465747c22bc3f650dfa7e6f20e3622f974b2c59cd2e8d213875bfdba1d1495d8.xdr.gz -o buckets/tmp/repair-buckets-b525f67f11945e20/bucket-465747c22bc3f650dfa7e6f20e3622f974b2c59cd2e8d213875bfdba1d1495d8.xdr.gz.tmp
2017-11-24T12:41:35.780 GCSJO [Work WARNING] Reached retry limit 0 for get-remote-file bucket/46/57/47/bucket-465747c22bc3f650dfa7e6f20e3622f974b2c59cd2e8d213875bfdba1d1495d8.xdr.gz
2017-11-24T12:41:35.780 GCSJO [Work WARNING] Scheduling retry #8/32 in 72 sec, for get-and-unzip-remote-file bucket/46/57/47/bucket-465747c22bc3f650dfa7e6f20e3622f974b2c59cd2e8d213875bfdba1d1495d8.xdr.gz
```

**Comment by nengine** [comment]
I think I found the issue.  Archive files are stored in /tmp/stellar-core/history/ path and it seems like system is automatically purging those files, since it is in the /tmp/ folder.

**Comment by vogel** [comment]
Thanks for the update! I hope it will work well for you with new archive path.
