### ISSUE TITLE
Investigate using afl (fuzzer) to derive transaction tests

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1376]
Right now we only use fuzzer builds to test overlay and hand craft transactions for testing the transaction subsystem.
As we are adding invariants, we should investigate what it would take to use afl to generate interesting transactions and/or transaction sets.
Some hurdles that need to be overcome:
* get passed signature verification - we can disable encryption (AFL builds are special anyways)
* catching unexpected results - invariants should help but that might not be enough?
* deal with the number of possible accounts - automatically map accounts based on the first byte of the public key (for example), with some number of pre-populated accounts in interesting configurations (with trustlines, without, etc).

**Comment by MonsieurNicolas** [comment]
As of https://github.com/stellar/stellar-core/pull/2823 this is mostly implemented.

Areas of improvement (probably in order of priority):
 - [ ] the "setup" code that creates a few accounts and order book seems wrong.
  * The setup is unsafe. Account creation is done directly (should be done with operations) and the rest is setup by applying a transaction but is not checked for success so it's possible that the setup code leaves the ledger in a bad state or a state that is not the one we expect.
  * Balances seem wrong. The numbers are way too big, and require the fuzzer to work on many bits. Numbers should be selected so that "interesting things" can happen with a few bits, maybe 5 or 6 bits is enough (so balances setup with less than 64 stroops, right now they're setup with 100k*10e7=10e9 stroops).
  * Trustlines and orders seem "uninteresting". Setup is fully symetrical. No variations on issuer/trustline flags.
  * Missing other ledger entries like `BalanceEntry`
  - [ ] Handling of certain types like `LedgerKey` should be specialized
  * right now it's pretty much impossible for the fuzzer to generate operations that will operate on `LedgerKey` (like sponsorship), because the space is just too big.
    * a possible alternative could be to map a `LedgerKey` into 1(?) byte, and use that number as an index in the list of all `LedgerKey`s known when the operation gets executed. This can be done in a few ways:
      * The simplest way could be to just incorporate sponsorship into the setup (so have some accounts, trustlines, etc sponsored in the original Ledger state).
      * a more advanced way might be to split up the code that maps "compact binary form" and "in memory xdr". Where the first pass would do most of what it does today, and the second pass, done between operation application, would be to update some fields in a deterministic way.
  - [ ] The data generated to seed the fuzzer via the `gen-fuzz` is very low quality
  *  right now we just generate operations randomly with `autocheck`, and generating 1000 blobs only yields about 30 unique traces that the fuzzer can use (output of `fuzz-cmin`)
     *  better would be to generate transactions with all combinations of operations possible, ie for sets with 1 operation, we should generate 19 (as of now) sets of 1 operation (where each set generated in one round contains a different operation type). That way the fuzzer has a good starting point where "flipping bits" should already yield interesting scenarios. For example, with about 7k blobs we can generate all possible combinations of sets with between 1 and 3 operations.
     * best would be to generate those seed operations with the help of a "grammar" of sorts to have a more systematic way of generating interesting sets of operations that don't overlap.
  - [ ] It should be possible to fuzz the setup as well.
  * in theory, allowing to inject more operations leaves part of "setup" to be discovered by the fuzzer, but this is probably not practical
  * a better approach might be to expand the blob used to fuzz with some (limited) control over the setup. Could be for example a few bytes that control which ledger entries are created in the ledger.

**Comment by rokopt** [comment]
I've split out #2949 , #2950 , and #2951 to cover the aspects of this issue that have not already been implemented in PRs such as #2904 and #2933 , so I think we can probably close this one.
