### ISSUE TITLE
Implement in memory bucket manager

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1386]
Right now, running tests requires a bucket folder to be setup and bucket files are created/deleted which is time consuming.

BucketManager should be refactored to allow for a pluggable Bucket implementation, so that we can by default keep today's behavior, but in most tests use something much simpler like a map of bytes.

Tests that use the archive subsystem should probably keep using the on-disk version

**Comment by rchatsiri** [comment]
I read document from link here[1] describes Bucket stores on database(Postgresql). I have question about this issue. 

* Do you mean system want to change stores cryptographic hash on database to in memory method (Like share memory, memory mapping and etc.)? 
* Not clear on Pluggable Bucket word for implementing. Stellar-Core should plugs all bucket when system start first by administrators select bucket for using. Does Stellar-core should independent plugging for each bucket folder?

[1] https://github.com/stellar/stellar-core/tree/master/src/bucket

**Comment by MonsieurNicolas** [comment]
buckets are not in the database (per the readme in the folder you linked), they are flat files

**Comment by rchatsiri** [comment]
Should stellar-core move information on flat files to memory because slow create/deleted by time? Because application accesses flat file use longtime.

**Comment by MonsieurNicolas** [comment]
Actually you are right - when I wrote this I thought it was necessary to do this, but I realized later that running tests against `/tmp` means they are already "in memory". I am therefore closing this issue for now
