### ISSUE TITLE
Remove invariants.h from VS project files

### ISSUE THREAD

**Issue by PJvGrol** [stellar/stellar-core#1394]
The file invariants.h was removed as of commit 1343f14, but is still included in the vcxproj files (and as such shows up in Visual Studio);  
* https://github.com/stellar/stellar-core/blob/master/Builds/VisualStudio/stellar-core.vcxproj line 572
* https://github.com/stellar/stellar-core/blob/master/Builds/VisualStudio/stellar-core.vcxproj.filters line 1229 & 1230

**Comment by MonsieurNicolas** [comment]
fixed by as part of #1390

**Comment by MonsieurNicolas** [comment]
thanks for the report btw !
