### ISSUE TITLE
Add a livenet example config to the installed docs (or change the man page)

### ISSUE THREAD

**Issue by tomerweller** [stellar/stellar-core#1408]
From the stellar-core man page: 
`See /usr/local/share/doc/*.cfg for some example stellar-core configuration files`

This directory includes a test config, a standalone config and general config but no livenet config.
We do have one in the docs repository though: https://github.com/stellar/docs/blob/master/other/stellar-core-validator-example.cfg

Alternatively, the man page can refer to the github docs for examples.

**Comment by MonsieurNicolas** [comment]
we removed the man pages, so not a problem anymore
