### ISSUE TITLE
Implement operation level invariants

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1416]
As operations perform various changes to the ledger, we should be able to perform invariant checks on the ledger.
Here is a list on checks we should be performing:

 * Ledger Header fields/global
      - [ ] Lumens invariant `total = fee_pool + sum(balances)`
   * All operations except inflation
       - [ ] conservation of lumens `delta<total> = 0`, `delta<fee_pool> = 0`, `sum(delta<balances>) = 0`
   * Inflation
       - [ ] `Delta<total> = Sum(Delta<balances>)+delta<fee_pool> = inflation amount`
* Ledger Entries
     - [ ] last_modified matches current ledger header
   * Accounts
       - [ ] reserve met
       - [ ] fields are valid (positive balance, flags are valid)
    * TrustLine
       - [ ] fields are valid (balance within range, flags are valid)
    * Offer
       - [ ] fields are valid (price, flags)

Invariants are either "soft" (can be disabled) or "hard" (cannot be disabled).

When an invariant fails, we should:
* log the failure to the log file
* increment a counter (for reporting/alerting)
* surface the failure to the administrator (info endpoint)
   * in particular, this should be reported properly after performing a `catchup` (command line or real-time)

Hard invariants also cause the instance to stop or perform mitigations (such as dropping the faulty transaction).

**Comment by jonjove** [comment]
Resolved by #1392
