### ISSUE TITLE
Think about adding interactive shell for stellar-core

### ISSUE THREAD

**Issue by vogel** [stellar/stellar-core#1419]
With the new --catchup-xx command line options, and proposition of --reset-at (#1290) and also request from @bartekn for a dry-run mode for transactions, maybe we could use an interactive mode for stellar-core.

How it would look like? I think it could use commands like this:

```
stellar-core --interactive
# get last checkpoint from history
sc> get-last-checkpoint             
14000000
# do a command-line catchup-at
sc> catchup-at 13999000             
Catching up....
Catchhed up to 13999000             
# try a transaction
sc> try-tx  AAAAN25TKgg71CM3wj2/WDe....   
Success
# apply transaction
sc> apply-tx AAAAN25TKgg71CM3wj2    
Success
# reset to consistent-with-network-state
sc> reset-at 13999000     
sc> show ACCOUNTID
# some data about account
{ balance = 20000000 }
# now it follows network as usual          
sc> run                             
...
[Ctrl+C]
# back in interactive mode
sc>                                 
```

It could be implemented as its own process or as a gateway to another running stellar-core using HTTP requests.

This is rough idea for discussion.

**Comment by MonsieurNicolas** [comment]
since that issue, we've moved to something closer to sub-commands (similar to git), and adding more sub-commands in the future.
