### ISSUE TITLE
Quote SQL identifiers to so we are explicit about casing

### ISSUE THREAD

**Issue by nullstyle** [stellar/stellar-core#142]
According to SQL-92, identifiers that are not quoted are case-insensitive.  Postgresql supports this by lower-casing all unquoted identifiers transparently.  Sqlite does not have this problem.

Unfortunately some SQL toolkits (for example, both ActiveRecord and Sequel) will always quote identifiers for the SQL they produce.  To integrate with the hayashi DB, a developer will have to manually convert to the lower-cased form, which could be confusing (well, it certainly was for me).

IMO, we should either:

1.  Continue to use mixed casing in our SQL, but quote all identifiers such that casing is as expected
2.  Do not rely upon casing, i.e. lowercase everything and use underscores for word separation.

**Comment by nullstyle** [comment]
Looks like latobarita accidentally closed this issue.

**Comment by MonsieurNicolas** [comment]
no it is done - all lowercase now

**Comment by nullstyle** [comment]
my bad :)
