### ISSUE TITLE
Bogus NOTICE "relation pubsub already exists" in logs

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1421]
It looks like we have quite a few bogus entries in logs reading:
```
NOTICE:  relation "pubsub" already exists, skipping
```

A cursory look at the code seems to point to the `ExternalQueue` constructor that calls the `CREATE TABLE` statement.
PostgreSQL is probably ignoring the `IF NOT EXISTS` part and sputters those messages.

Fix is to probably follow the same pattern than elsewhere: add a proper `DropAll` static function that gets called when doing `newdb` instead of trying to create that table all the time.

```
string ExternalQueue::kSQLCreateStatement =
    "CREATE TABLE IF NOT EXISTS pubsub ("
    "resid       CHARACTER(32) PRIMARY KEY,"
    "lastread    INTEGER"
    "); ";

ExternalQueue::ExternalQueue(Application& app) : mApp(app)
{
    mApp.getDatabase().getSession() << kSQLCreateStatement;
}
```

**Comment by vogel** [comment]
Is that the same as #172?

**Comment by MonsieurNicolas** [comment]
related, but not the same: what this issue is tracking is that we're actually calling this not just at startup but every time this class is created

**Comment by evanlimanto** [comment]
Trying to look into this — isn't what you're asking already present here?
https://github.com/stellar/stellar-core/blob/06c5bac64f9865a707b79038141db52ad1db4f33/src/database/Database.cpp#L297

**Comment by MonsieurNicolas** [comment]
weird, yes: it looks like we're creating it in both places. Maybe deleting it from the constructor is enough.

**Comment by evanlimanto** [comment]
i think this issue can be closed now?

**Comment by MonsieurNicolas** [comment]
Yes. Auto resolve didn’t work
