### ISSUE TITLE
Output all logging information to stderr instead of stdout, it will allow for piping output

### ISSUE THREAD

**Issue by vogel** [stellar/stellar-core#1427]
Please also check for all documentation that says logging goes to stdout (and all external tools that assume that).

**Comment by MonsieurNicolas** [comment]
I imagine that this should be done when running subcommands that are supposed to be executed from the command line, like `offline-info` or `report-last-history-checkpoint`.
Also those should be changed to not use `LOG` for their result (so that it's possible to grab the result from shell).

**Comment by MonsieurNicolas** [comment]
fixed
