### ISSUE TITLE
Not connected to the node when i run stellar-core

### ISSUE THREAD

**Issue by waibb** [stellar/stellar-core#1437]
# Before creating an issue
 * check the [documentation](https://www.stellar.org/developers/)
 * ask for help [from the community](https://www.stellar.org/community/)

# Issue type
 help

# Version found
  * stellar-core

# Your environment and setup
  ubuntu14.04

# Issue description
Not connected to the node when i run stellar-core

 2017-12-05T23:11:41.727 GBA2J [Overlay INFO] New connected peer 54.161.82.181:11625
2017-12-05T23:11:42.381 GBA2J [Overlay ERROR] readHeaderHandler error: End of file :54.161.82.181:11625 [TCPPeer.cpp:308]
2017-12-05T23:11:42.381 GBA2J [Overlay INFO] Dropping peer GAAAA@54.161.82.181:11625
2017-12-05T23:11:45.863 GBA2J [Herder INFO] Lost track of consensus
2017-12-05T23:11:45.863 GBA2J [Herder INFO] Out of sync context: {
   "queue" : null,
   "you" : "self"
}

**Comment by MonsieurNicolas** [comment]
configuration?

**Comment by waibb** [comment]
Thank you for the reply.
yes,but I did not change the configuration.
How should I solve this problem?
My configuration:
[QUORUM_SET]
THRESHOLD_PERCENT=66
VALIDATORS=[
    "GDQWITFJLZ5HT6JCOXYEVV5VFD6FTLAKJAUDKHAV3HKYGVJWA2DPYSQV  A_from_above",
    "GANLKVE4WOTE75MJS6FQ73CL65TSPYYMFZKC4VDEZ45LGQRCATGAIGIA  B_from_above",
    "GDV46EIEF57TDL4W27UFDAUVPDDCKJNVBYB3WIV2WYUYUG753FCFU6EJ  C_from_above"
]

[QUORUM_SET.1]
THRESHOLD_PERCENT=67
VALIDATORS=[
    "$self", # 'D' from above is this node
    "GDXJAZZJ3H5MJGR6PDQX3JHRREAVYNCVM7FJYGLZJKEHQV2ZXEUO5SX2 E_from_above",
    "GB6GK3WWTZYY2JXWM6C5LRKLQ2X7INQ7IYTSECCG3SMZFYOZNEZR4SO5 F_from_above"
]

[QUORUM_SET.2]
THRESHOLD_PERCENT=100
VALIDATORS=[
    "GCTAIXWDDBM3HBDHGSAOLY223QZHPS2EDROF7YUBB3GNYXLOCPV5PXUK G_from_above",
    "GCJ6UBAOXNQFN3HGLCVQBWGEZO6IABSMNE2OCQC4FJAZXJA5AIE7WSPW H_from_above"
]

[QUORUM_SET.2.1]
THRESHOLD_PERCENT=50
VALIDATORS=[
    "GC4X65TQJVI3OWAS4DTA2EN2VNZ5ZRJD646H5WKEJHO5ZHURDRAX2OTH I_from_above",
    "GAXSWUO4RBELRQT5WMDLIKTRIKC722GGXX2GIGEYQZDQDLOTINQ4DX6F J_from_above",
    "GAWOEMG7DQDWHCFDTPJEBYWRKUUZTX2M2HLMNABM42G7C7IAPU54GL6X K_from_above",
    "GDZAJNUUDJFKTZX3YWZSOAS4S4NGCJ5RQAY7JPYBG5CUFL3JZ5C3ECOH L_from_above"
]

**Comment by vogel** [comment]
How long do you wait?

**Comment by MonsieurNicolas** [comment]
yeah this is not a real configuration: you should start by reading the admin guide
https://github.com/stellar/stellar-core/blob/master/docs/software/admin.md
that points to a few configuration choices depending on what you're trying to do
