### ISSUE TITLE
Proposed index improvements in service of horizon's transaction submission subsystem

### ISSUE THREAD

**Issue by nullstyle** [stellar/stellar-core#1452]
## Query workload

This issue is primarily focused on improving transaction submission latency at horizon.   Horizon's transaction submission system involves two components:  a background loop that maintains the submission system and responds to new data from stellar-core and an http handler that inserts new envelopes to the submission system.  Lets look at each in turn.

Every tick of the background loop updates horizon's cached ledger state.  This update generates a query against stellar core:

```sql
SELECT COALESCE(MAX(ledgerseq), 0) FROM ledgerheaders
```

After updating the ledger state, the background loop checks every _pending_ transaction for a result in the stellar-core database.  These checks generate queries of the shape:

```sql
  SELECT * FROM txhistory WHERE txid = ?
```

The http handler for this subsystem of horizon uses one additional query to lookup a batch of account sequence numbers:

```sql
  SELECT seqnum as sequence, accountid as address FROM accounts WHERE accountid IN (?)
```

## Effects of ingestion on transaction submission

Horizon tries to use its history database to answer any questions arising from user requests in an effort to avoid load on the connected stellar-core.  Prior to looking up a transaction in the `txhistory` table, horizon first checks its own `history_transactions` table.  While not strictly related to transaction submission, the ingester loads rows from `txfeehistory` by transaction hash: an unindexed query.  By adding this query we should improve the scalability of horizon's ingestion system.

## Proposed Indexes

- `CREATE INDEX txhistory_by_hash ON txhistory USING btree (txid);`
- `CREATE INDEX txfeehistory_by_hash ON txfeehistory USING btree (txid);`

**Comment by alex-nishikawa** [comment]
I looked at the schema and saw that txid and accountid are strings (CHARS(56)).  Shouldn't those be 
uuid?  uuids are stored as 16 bytes and comparisons are done numerically which would speed up your proposed indexes.

...Probably way too late in the game to change those though.

**Comment by MonsieurNicolas** [comment]
the new ingestion approach makes this irrelevant
