### ISSUE TITLE
Improve upgrade experience

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1453]
As of v9.0.0 we're pretty strict when it comes to validating upgrades but there are a few trade-offs:
current logic is fairly simple as a node looks at the value of `PREFERRED_UPGRADE_DATETIME` and if the current network time is before that time it will consider values invalid.

A few problems with the current solution:
* if the node gets upgraded to a new stellar-core binary, and the operator forgets to update `PREFERRED_UPGRADE_DATETIME`, the node will vote right away for the protocol upgrade which may cause issues
* if the network is reconfigured, the node will lose sync and vote for old values after rejoining the network, which is not the intention

A potential way to solve this is to add a new field in the ledger header to track the "version number" of the network wide settings `(protocol_version, fee, reserve, ...)`.

The configuration then would also contain the "version number" that the node is configured for, making it possible to adjust the behavior depending on what the current version number is (for example, only validate and vote if the version number matches, consider a version mismatch always invalid).

There might be a way to instead recycle the `ledgerVersion` field (currently 32 bit), turning it into a combination of a strictly monotonic field (16 bits for example) and use the other bits to track what ledgerVersion tracks today (ie: protocol version). 
16 bits seems plenty for network wide settings upgrade: doing such a change every week leaves room for over 1000 years of upgrades.

**Comment by MonsieurNicolas** [comment]
Turns out there is a much better way of doing this.

Replace the current mechanism with the following:

Add a configuration that controls the type of behavior for upgrades (boolean `validateUpgrades`).

* for non-validators/validators that don't care about those (`validateUpgrades` = false)
    * for upgrades not related to protocol version they will just re-nominate the value from nodes in their quorum_set (if validating) - we may want to limit this further in the future to a subset of those nodes but that doesn't seem necessary at this point
    * for protocol upgrade agree (and re-nominate if validating) to it if the binary supports that version (and it's a higher version) - otherwise, consider the value as invalid
* for nodes that want to participate in upgrade validation (`validateUpgrades` = true)
    * add a mechanism that moves the upgrade policy from the config file into a writable persistent store
    * when the upgrade makes it into a ledger, the upgrade policy gets archived so that the node won't try to perform the same upgrade twice
   * re-nominating only occurs if the validator has a matching upgrade in its policy queue (upgrade considered valid during SCP confirmation phase)
   * for protocol protocol version upgrades, if it's not supported, consider the value invalid

**Comment by nengine** [comment]
Hi @MonsieurNicolas,  I have build v0.6.4 and to upgrade to 0.9.x, should I just compile and replace the binary files and change network settings? Thank you.

**Comment by MonsieurNicolas** [comment]
yeah just remove the network settings from your config file and you should be good to go

**Comment by nengine** [comment]
Thanks a lot. I was able to upgrade it.

**Comment by ckmakcesar** [comment]
Hi @MonsieurNicolas, I am running a private network of 3 nodes, and not sure on some ideas..

Currently, I can only access one node, and have already upgraded it from build v0.6.4->v9.0.1. As a result, the protocol also upgraded from v8->v9. 

Will there  be any problem running this network with nodes of different build/protocol versions? 
Thank you.

**Comment by MonsieurNicolas** [comment]
Nodes running old versions of the protocol are left behind or become unstable. If the protocol version changed it means you had a quorum so only a minority of nodes are in this situation and should be able to catchup when upgraded. I’d recommend asking those types of questions on stack exchange in the future as they are not bugs

**Comment by ckmakcesar** [comment]
Thanks MonsieurNicolas!
