### ISSUE TITLE
v9.x.x under linux appears to have an issue with local history (.json) handling

### ISSUE THREAD

**Issue by smdwireless** [stellar/stellar-core#1461]
I imported the stellar-core/history/vs/.well-known/stellar-history.json path from v0.6.4 before starting the upgraded v9.0.0 up for the first time.

As soon as catch-up was complete, the stellar-core process died. Logs don't show an exit, they just stop at the last ledger entry to be processed.

When I remove stellar-history.json, core continues past 'catching up' all the way to 'synched!'. Everything seems to be working except the logs show this error:

```
GDOQL [Process WARNING] process XXXX exited 1: cp  /home/<blah blah>/stellar-core/history/vs/.well-known/stellar-history.json buckets/tmp/history-cdeedccdeedc/local-stellar-history.json
GDOQL [Work WARNING] Reached retry limit 5 for get-remote-file .well-known/stellar-history.json
GDOQL [Work WARNING] Scheduling retry #5/5 in 23 sec, for get-history-archive-state 
```

This repeats constantly through the logs. I believe there is some issue with the way in which v9.0.0 handles the local history archive.

My cfg has the following entries which were inherited from v0.6.4:

```
[HISTORY.local]
get="cp /home/<blah blah>/stellar-core/history/vs/{0} {1}"
put="cp {0} /home/<blah blah>/stellar-core/history/vs/{1}"
mkdir="mkdir -p /home/<blah blah>/stellar-core/history/vs/{0}"

[HISTORY.sdf1]
get="curl -sf http://history.stellar.org/prd/core-live/core_live_001/{0} -o {1}"

[HISTORY.sdf2]
get="curl -sf http://history.stellar.org/prd/core-live/core_live_002/{0} -o {1}"

[HISTORY.sdf3]
get="curl -sf http://history.stellar.org/prd/core-live/core_live_003/{0} -o {1}"
....

Running stellar-core build  "v9.0.0-2-gc04cc5a" natively compiled under Debian Jessie (x86-64) with kernel 4.6.4-1~bpo8+1 (2016-08-11).

Any ideas?

**Comment by MonsieurNicolas** [comment]
Thanks for the report!
Crash aside. Are you running in containers?
Also do you happen to have the content of that json file?
If so, can you post its content here and check if you have the bucket files referenced from its content in this local archive?

I suspect that somehow that file got corrupted or the process was interrupted leaving some other inconsistent state for the archive

**Comment by smdwireless** [comment]
@MonsieurNicolas no, not in a container (ie docker container version), compiled and running natively in the debian VM.

The original json file is shown below and I have attached the debug logs which also show the second issue of not core not publishing as discussed with @vogel 
[stellar.validator.2017.12.14-13:28:12.log](https://github.com/stellar/stellar-core/files/1559392/stellar.validator.2017.12.14-13.28.12.log)


`{
    "version": 1,
    "server": "v0.6.4-11-gf6311ac",
    "currentLedger": 15051071,
    "currentBuckets": [
        {
            "curr": "7dd172c673066c773078e78e167deb0921921f6fbcc3ec16c0de810294ddea02",
            "next": {
                "state": 0
            },
            "snap": "4155f6d4c95279810cb6a4e1ffda8ebf54cee4eb60b1eb1c93372858de2440a4"
        },
        {
            "curr": "7b66b6afb27ec8d69e06c9e7f18b2c135a5dbb2b26cf9ce20ee7c28b6afc1e40",
            "next": {
                "state": 1,
                "output": "4155f6d4c95279810cb6a4e1ffda8ebf54cee4eb60b1eb1c93372858de2440a4"
            },
            "snap": "0257d328d3b714553e7dcceac8684405d33e11190b3acde149fb145c3804a24c"
        },
        {
            "curr": "912dc9cb49d03c4cc7780d3d1abf3dfde156db18854bb4eb8eb5db38f150752e",
            "next": {
                "state": 1,
                "output": "dc92bf405f6288ab8ec76877902431c83f7486e731e06a82db0fb02dea0356ac"
            },
            "snap": "595d9086599f42ebc598556bf35d33fbea19fe35345c1cc4eaa9dc815431e93b"
        },
        {
            "curr": "ce0b903580c5810bac7d5446b4036cb6f9f08b91e2aff8bd72f40a25b5d2e7ba",
            "next": {
                "state": 1,
                "output": "90e6440c46adc7d3958a9c81e2e179bd25cca77b9e628d8f3132a64b5b71f0e7"
            },
            "snap": "a5b71b34870d1e2b55404b2e8c0a8202e8571cfd6e2aa491a05fd3da0603e0ea"
        },
        {
            "curr": "bb8068875cdd5a113f5aed5f6a64996046654f3c401344e0e1f298955862dcc3",
            "next": {
                "state": 1,
                "output": "2dd48782c450b555c921139e6dd1c1b7c125e269faf4592d33d2a582e9cc6d74"
            },
            "snap": "f6277f4c4e46b8cdfe5082d3ab3796eaa4d2a208381708a707f29b5462d019e5"
        },
        {
            "curr": "be2bf49d3d8cd94977853297d9d795fd1f0737dee8c78cb9d4ec09b63eedaa25",
            "next": {
                "state": 1,
                "output": "9d88df10df656a6bf0b9dfe5dd26507c5caf23e9fbb3d5f89068825eaf31cb09"
            },
            "snap": "907d50e9692e5175bf4124781c7ee958c4fb5c167f55e620b34958faba79de50"
        },
        {
            "curr": "84a952c50a486c55292fc27f13ecc3c1cf3231b1337fde6efafd05f0e133bf2f",
            "next": {
                "state": 1,
                "output": "e25d1514672fe10df41a069c88030952624581c2a390cace1a5473b978635657"
            },
            "snap": "715636d69b3f3bc1774be67ea540053c2e52bd0600d954c54912f9a6cd38a3b1"
        },
        {
            "curr": "7406bac8661ac875ff3428f928876541cf420c240c9db38f30675ad1de5f910e",
            "next": {
                "state": 1,
                "output": "15207279311065f92ebfe967c6c9406c213c3fdd64bde51db25923093908c652"
            },
            "snap": "6bca6e358a38de38c2dc67e3e4921c1488c9af85491e336d3f26745cdb430e18"
        },
        {
            "curr": "5a66c35e2cba3a63317ff0f713d555b3aa7fe41118828c14950a11eb1a3ce79c",
            "next": {
                "state": 1,
                "output": "74ca5bbff2008e2d9ab16761d8c21d1915443f7ebae8a675d6efff927e12cac9"
            },
            "snap": "0734b375ab14b7ea55e09fc6d14f9e1fa4356b82010111c04b32682c71cd9abf"
        },
        {
            "curr": "b6b6ff00d319159d58a41831a44fac28b44983726fd19f27c55eacd1ed10fa11",
            "next": {
                "state": 1,
                "output": "489c0e0f06c441f91fe18df58c863d1502b4d736e7b3313410b452abec43d6ed"
            },
            "snap": "f93165f9ecea6c3109377fe4dbc2dc731d04938a9e553f563bb692cf75add56d"
        },
        {
            "curr": "312b46fa788ff105e5a33665a4ba71f9b269770361137c746e576e8fac755bca",
            "next": {
                "state": 1,
                "output": "ce3f9f031abae012a7431845338e56bb99edf392f936108e836bf022add86944"
            },
            "snap": "0000000000000000000000000000000000000000000000000000000000000000"
        }
    ]
}`

The original buckets were included before but have since been removed. No new stellar-history.json is being saved or generated at this stage.

**Comment by smdwireless** [comment]
So after copying the stellar-history.json file from buckets/tmp/history-xyz123.../ to the history/vs/.well-known/ path there was another crash right after the first publish.

Then I flushed the db and restarted core which took the usual amount of time to complete the catch up but then it seems to work after that.

No more history errors, no more crashes and we are publishing.

Here is the content of the json file:

`{
    "version": 1,
    "server": "v9.0.0-2-gc04cc5a",
    "currentLedger": 15081471,
    "currentBuckets": [
        {
            "curr": "b9224e7b2523a1ba1f71f8106d2ff9586b1ded070bd77bd0a0a8ec903b803a49",
            "next": {
                "state": 0
            },
            "snap": "852c07c61f2c3efbf277be59169f07a84b635f4f2a37119dde295d3fa5a65871"
        },
        {
            "curr": "b4648869edb04294b6ccd740d0c4aabdb16138899db45773a91ef1a7b0678aaa",
            "next": {
                "state": 1,
                "output": "852c07c61f2c3efbf277be59169f07a84b635f4f2a37119dde295d3fa5a65871"
            },
            "snap": "0d3e611983cc33fcf491ef03db5005098fc2a42900d473d7aebcf03c19130cca"
        },
        {
            "curr": "cb07cb7f9a4de48670368c6b3bea7d5fe771a1bf96b52a5863f02e505fc107c6",
            "next": {
                "state": 1,
                "output": "b94ea5f17ce1c2e71afac057962afd102136b36df1fd92d1d5524c8b847199e9"
            },
            "snap": "d989a86c3120efd1a2ee19cf03e6cc240367e9e2405ad2dbd4a78fd859cd80e2"
        },
        {
            "curr": "4cdc7f44a810d8f0349609a0b0e387a9bbbcfb7455b1dd4e54c3f83de5b35027",
            "next": {
                "state": 1,
                "output": "f740ce524472da84ce4ba9f9105cbb036c5cd896675716cbde9b28c105451a37"
            },
            "snap": "c138f19377817fdbe05971291c48306f03f4d564de616f79474d6abec2293d4c"
        },
        {
            "curr": "a74ea157306e95221094737bdd8390b54f5fbe3a89bd53cbf9609aa6d1626b1c",
            "next": {
                "state": 1,
                "output": "75575c878ab10c852cf186e852b6cb98a0f5b913d763e3252c552f012eca478e"
            },
            "snap": "2ac11762e1eef3a367d4a6ab0a37b75ba98329124c28be6c4d858e0a2a7e09f2"
        },
        {
            "curr": "038567f3a8f3e22beb9d02051f675d5dec0d40fefe4389ec0f0110ad1a6bc4da",
            "next": {
                "state": 1,
                "output": "a8bdaba9b2fb111ee91c25fa4196f6be634c44c600281539e2200f4713cdbfb8"
            },
            "snap": "dbe9b59d907ff5b3318dd85928eb17aa365559405d369c4aa5ad9f50eb2f1131"
        },
        {
            "curr": "99e13d9477bcdcba94594bf8aad755df7d932857624ed97e77d6dfb340e10b43",
            "next": {
                "state": 1,
                "output": "dc2633ee64f51340d4a920eaa6b18f2b3442ae71a1a0cef71bee700220e2a471"
            },
            "snap": "482f630744d8e1c9c3e35a0a3976997a1138db88195bb733a27882cecbcf8117"
        },
        {
            "curr": "baf4a2c07abde1667ff52c00cdf0d9874e1beca897aee55f4cc905503872690e",
            "next": {
                "state": 1,
                "output": "62f12304b8280bf1af75bab97da23689f73e3ca22c89e41eb3b526ee96346b7b"
            },
            "snap": "9b4db5d04244163f94f049bbaf4cac33d10d9aef2b9e4aa5790b4a33e842b759"
        },
        {
            "curr": "74ca5bbff2008e2d9ab16761d8c21d1915443f7ebae8a675d6efff927e12cac9",
            "next": {
                "state": 1,
                "output": "1581afe04cf1f455cc2e8ca63af73238207ba1a8240acf77232b3266717768a7"
            },
            "snap": "5a66c35e2cba3a63317ff0f713d555b3aa7fe41118828c14950a11eb1a3ce79c"
        },
        {
            "curr": "489c0e0f06c441f91fe18df58c863d1502b4d736e7b3313410b452abec43d6ed",
            "next": {
                "state": 1,
                "output": "583c3155646dde50a965348b74c7af8b0989c4b7b1dffde44a630102a523a873"
            },
            "snap": "f93165f9ecea6c3109377fe4dbc2dc731d04938a9e553f563bb692cf75add56d"
        },
        {
            "curr": "312b46fa788ff105e5a33665a4ba71f9b269770361137c746e576e8fac755bca",
            "next": {
                "state": 1,
                "output": "ce3f9f031abae012a7431845338e56bb99edf392f936108e836bf022add86944"
            },
            "snap": "0000000000000000000000000000000000000000000000000000000000000000"
        }
    ]
}`

and attached is the first log file before the flushing of the db 
[stellar.validator.2017.12.15-11:16:24.log](https://github.com/stellar/stellar-core/files/1562734/stellar.validator.2017.12.15-11.16.24.log)

and then the compressed detailed log file from after when it all started to work correctly.
[stellar.validator.2017.12.15-113114.log.gz](https://github.com/stellar/stellar-core/files/1562737/stellar.validator.2017.12.15-113114.log.gz)

**Comment by vogel** [comment]
Thank for your report. In stellar.validator.2017.12.15-11:16:24.log you can see:

```2017-12-15T11:16:34.574 GDOQL [History INFO] Publishing 1315 queued checkpoints [14996031-15080127]: Retrying in 0 sec: prepare-snapshot
2017-12-15T11:16:36.408 GDOQL [History INFO] Publishing 1315 queued checkpoints [14996031-15080127]: Succeded: prepare-snapshot
2017-12-15T11:16:41.092 GDOQL [History INFO] Publishing 1312 queued checkpoints [14996223-15080127]: Retrying in 0 sec: prepare-snapshot
2017-12-15T11:17:17.086 GDOQL [History INFO] Publishing 1292 queued checkpoints [14997503-15080127]: Retrying in 0 sec: prepare-snapshot
```

It means that publishing is progressing - number of queued checkpoints get smaller and number of first one in queue is increasing.
