### ISSUE TITLE
Error when running ./autogen.sh

### ISSUE THREAD

**Issue by pkrasam** [stellar/stellar-core#1465]
stellar@stellar:~/stellar-core$ ./autogen.sh
Entering 'lib/libmedida'
Entering 'lib/libsodium'
**libtool is required, but wasn't found on this system**
Stopping at 'lib/libsodium'; script returned non-zero status.

**Comment by pkrasam** [comment]
I have installed Ubuntu Server 16.04 LTS on Azure
**These steps work**
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test
- apt-get update
- sudo apt-get install git build-essential pkg-config autoconf automake libtool bison flex libpq-dev clang++-3.5 gcc-4.9 g++-4.9 cpp-4.9

Erroring out on step 5
**Basic Installation**
1. git clone https://github.com/stellar/stellar-core.git
2. cd stellar-core
3. git submodule init
4. git submodule update
5. Type ./autogen.sh.

**Comment by MonsieurNicolas** [comment]
Are you saying that you followed instructions from INSTALL.md , adapting the steps from https://github.com/stellar/stellar-core/blob/master/INSTALL.md#ubuntu-1404
 but that didn't work? libtool is explicitly called out in the list of packages that needs to be installed for Ubuntu

**Comment by MonsieurNicolas** [comment]
let me know if I am missing something here

**Comment by pantheon25** [comment]
I'm having similar issue but with the Windows installation. Right when I run ./autogen.sh I get an error: 

![libtools](https://user-images.githubusercontent.com/11989083/35439598-46c8d0a2-0250-11e8-8d16-d6833ab93ee6.jpg)

I installed libtools and added to path but still nothing changed

**Comment by MonsieurNicolas** [comment]
@pantheon25 , your case might be different. Are you running Ubuntu in the Linux subsystem for Windows or cygwin? We do not have instructions for cygwin.
If under ubuntu, you should not need to mess with your path as apt-get installs it in the standard location.

**Comment by pantheon25** [comment]
@MonsieurNicolas i'm running it on Windows 7 64-bit. I was following the instructions [here](https://github.com/stellar/stellar-core/blob/testnet/INSTALL.md#basic-installation) and got the error once executing the line "./autogen.sh"

I tried the other instructions [here](https://github.com/stellar/stellar-core/blob/master/INSTALL-Windows.md#basic-installation) but once building the solution I get these errors (the rest below the image are related to the libsodium project:

![2](https://user-images.githubusercontent.com/11989083/35466100-cc38096e-02b5-11e8-8145-f0bcbef78828.jpg)

I installed everything and added it all to PATH, I don't know where I went wrong. Any help is fully appreciated

**Comment by MonsieurNicolas** [comment]
Windows setup is a whole different beast - you can try to follow the instructions in the error message (retarget the solution); You will need to follow all instructions from https://github.com/stellar/stellar-core/blob/testnet/INSTALL-Windows.md
