### ISSUE TITLE
Add option to pause/unpause stellar-core

### ISSUE THREAD

**Issue by vogel** [stellar/stellar-core#1468]
To be able to get a new instance of stellar-core from existing one one need to dump content of database and content of filesystem (buckets) at the same time.

To allow for best filesystem/db sync (non-checkpoint buckets), it would be best to add commands to pause and unpause stellar-core.

It is assumed that unpause would cause timeout on closing next ledger and a small catchup, but that is acceptable.

**Comment by MonsieurNicolas** [comment]
I think that once we have merged the remaining overlay PR - we should just exit core and restart it as other peers are going to kill connections to that peer anyways (timeout)

**Comment by vogel** [comment]
Good point. Closing.
