### ISSUE TITLE
Fail to build stellar-core in MacOS high Sierra

### ISSUE THREAD

**Issue by swwaden** [stellar/stellar-core#1473]
In file included from herder/Upgrades.cpp:9:
../lib/cereal/include/cereal/archives/json.hpp:831:8: error: no matching member function for call to 'loadValue'
    ar.loadValue( t );
    ~~~^~~~~~~~~

3 warnings and 1 error generated.
make[2]: *** [herder/Upgrades.o] Error 1
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1

**Comment by MonsieurNicolas** [comment]
this was fixed in 9.1.0
