### ISSUE TITLE
Stellar-History JSON file does not seem to exist

### ISSUE THREAD

**Issue by khelle** [stellar/stellar-core#1484]
# Issue type
I am not able to sync the stellar-core due to the stellar-history.json related errors.

# Version found
Stellar Core v9.0.1-6

# Your environment and setup
Ubuntu 16.04 64-bits
Custom build, livenet
Only custom path to the config file is being put in stellar-core parameters

# Issue description
When syncing the stellar core I got to the point of block 15576127, then stellar-history.json errors started to appear and node seems to be stuck.

## Actual result
Stuck stellar core in sync phase at block 15576127.

## Expected results
Synced up stellar core, without errors in the log.

## Logs
```
2018-01-11T12:50:09.770 GBA2J [Process WARNING] process 29494 exited 1: cp /home/xlm/.stellar-core/history/vs/.well-known/stellar-history.json buckets/tmp/history-838108c96ea2f2a5/local-stellar-history.json
2018-01-11T12:50:09.770 GBA2J [Work WARNING] Scheduling retry #2/5 in 2 sec, for get-remote-file .well-known/stellar-history.json
cp: cannot stat '/home/xlm/.stellar-core/history/vs/.well-known/stellar-history.json': No such file or directory
```
Additionaly although `/home/xlm/.stellar-core` directory exists, the `/home/xlm/.stellar-core/history` does not at all. The directory has been configured in config file as follows:

```
[HISTORY.local]
get="cp /home/xlm/.stellar-core/history/vs/{0} {1}"
put="cp {0} /home/xlm/.stellar-core/history/vs/{1}"
mkdir="mkdir -p /home/xlm/.stellar-core/history/vs/{0}"
```

**Comment by MonsieurNicolas** [comment]
it doesn't look like you configured your instance properly: you need to initialize archives before using them.

Please read https://github.com/stellar/stellar-core/blob/master/docs/software/admin.md

if you did, include exact repro steps that led to this problem and reopen this issue
