### ISSUE TITLE
Delayed operations mechanism. New operations to improve security

### ISSUE THREAD

**Issue by bnogalm** [stellar/stellar-core#1492]
I propose to add two new settings to setoptions and a new operation

SetOptions will be able to set a delay time together with a emergency public address account.
That delay time will apply to every new transaction submitted to the network. It will set the minimal amount of time, ignoring lower time limits set in the operation.
Once this delay time set, every transaction submitted will take effect after the delayed time.
The emergency public address account will be used with the new operation.

EmergencyMerge. It will merge the account with the previously set emergency public address. A transaction with only this operation will ignore the default delay time.

This way, users could have time to check that transactions are not submitted by a compromised secret key. If that is detected user could move everything to a cold storage wallet.

I explain motivations here : https://galactictalk.org/d/629-delayed-operations-mechanism-idea

**Comment by MonsieurNicolas** [comment]
thanks.
discussions of protocol changes should go in https://github.com/stellar/stellar-protocol/issues
