### ISSUE TITLE
Replay failed: disagreed on hash - How is the correct way to restore?

### ISSUE THREAD

**Issue by matheusb-comp** [stellar/stellar-core#1503]
During catch-up after a few hours of downtime, the stellar-core stdout log file presented the following error:
`[History ERROR] Replay failed: replay of [seq=6753672, hash=6cd13c] at LCL [seq=6753672, hash=16e63a] disagreed on hash [ApplyLedgerChainWork.cpp:269]`

What is the proper way to delete the ledgers that are not accepted and perform the catch-up again?
The HTTP commands "dropcursor", "setcursor" and "maintenance" seem to be the way to do it (https://www.stellar.org/developers/stellar-core/software/commands.html).

This other document explains how to use these commands to fix the "ledger gap detected" error for the Horizon endpoint. (https://github.com/stellar/go/blob/master/services/horizon/internal/docs/reference/admin.md#correcting-gaps-in-historical-data)

But for the hash disagreement during the replay, which cursor ID should I use?
Is there a list of IDs used by stellar-core and the horizon endpoint?

Thank you,

**Comment by vogel** [comment]
Currently there is no other way to restore. You need to go with --newdb and do a new catchup. This means that at previous catchup your node did something different that other nodes and you need to go to previous ledger. There is currently no way of doing that other that starting catchup from scratch.

**Comment by sgehrman** [comment]
I'm getting this on v10 testnet.  I can't seem to sync.

**Comment by MonsieurNicolas** [comment]
We're going to reset testnet: we've made breaking changes in the protocol without updating the protocol version (as it was only deployed to testnet) which may lead to this if you're trying to replay more ledgers than the past couple weeks.

Workaround is to reduce the value of `CATCHUP_RECENT`
