### ISSUE TITLE
add a way to populate cursors when setting up a node

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1508]
# Description of the problem

As we're about to implement #923 a race condition gets created when setting up an environment with a consumer such as Horizon:
if it takes a while to start up Horizon after core is started, for example because it takes a long time for core to catchup to the current ledger (in catchup_complete mode), there is a chance that the automatic maintenance gets executed even though Horizon didn't run yet.

The problem here is that the cursor that Horizon uses is not yet registered with core as Horizon does that when it first runs, causing some data to be deleted before Horizon gets a chance to ingest it.

# Approach
The solution is to add a mechanism for core to have the known cursors for a given environment added from the get go.

A couple ways this can be done (to be discussed before moving on to implementation):
* add new options to `newdb`, core can then be invoked like this
```
stellar-core --newdb --cursors HORIZON,FOO
```
This version couples the functionality to `newdb` which may or may not be desirable. It also bloats the command line even more.

* add a new option to `setcursor` for setting a cursor only if it doesn't exist, and add the following to core's config file
```
COMMANDS=[
"setcursor?id=HORIZON&cursor=1&createonly=true" , 
"setcursor?id=FOO&cursor=1&createonly=true"
]
```
This version is very simple to implement but allows cursors to be created at any time.

@nullstyle if you think about use cases, which version works for you best? My preference is the second one, but I'd like to hear your opinion.

**Comment by vogel** [comment]
What about INITIAL_CURSORS configuration options?
It would look like this:
```
INITIAL_CURSORS=["horizon", "foo"]
```

I think it should only be executed at `newdb` with cursor value defaulted to 1 (as there is no way to provide it in config file). This will fix the race between core and horizon.

And for all other cursors, those can be just created using HTTP endpoints.

**Comment by MonsieurNicolas** [comment]
Ah yes, INITIAL_CURSOR can implement either behaviors.

What I don't like about tying things up with `newdb` is that we're basically saying that if a new cursor gets added, the configuration is done outside of the config files, which is a time bomb for the validator operator : next time they are going to build a new node/rebuild, they will have to remember to run the same commands that they ran before.
If instead we make it that the configuration file ensures that cursors get registered, it will work all the time.

**Comment by nullstyle** [comment]
I like the `INITIAL_CURSORS` approach in the config file.

**Comment by vogel** [comment]
Do we have a consensus then?

**Comment by MonsieurNicolas** [comment]
if we make it work all the time and not just when doing `newdb`, yes.
If this is the case, we should just call it `KNOWN_CURSORS` as `INITIAL_CURSOR` implies an initial state of some sort.

**Comment by nullstyle** [comment]
IMO making it work on every launch is much preferred to only `newdb`.  I agree, `KNOWN_CURSORS` seems better than `INITIAL_CURSORS` as a name.

**Comment by MonsieurNicolas** [comment]
cool, let's go with this then
