### ISSUE TITLE
audit database calls for `effected_rows`

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1509]
it looks like the code doesn't always check if the call made changes that it was supposed to.
An example of these is `AccountFrame::storeDelete`.
We need to:
* look if we should add those checks
* add them with the appropriate protocol version check if required

**Comment by MonsieurNicolas** [comment]
this will probably be done in the datalayer branch that we're about to create

**Comment by graydon** [comment]
These are all being checked in the various Bulk*Operation classes.
