### ISSUE TITLE
Latency in network for watcher group

### ISSUE THREAD

**Issue by istrau2** [stellar/stellar-core#1522]
# Issue type
  bug

# Version found
  v9.1.0

# Your environment and setup
  * Linux
  * Docker Container
  * No special parameters

# Issue description
 We had a setup where we had 2 beefy watchers and 3 light validators. The 2 beefy watchers had a quorum that consisted of the 3 beefy validators. The objective was to have the watchers handle client requests (from our application), where as the validators focused on participating in consensus.

## Actual result
The watchers fell behind the validators. Sometimes just be a couple of seconds. However, sometimes they could fall behind for 30 or even 60 seconds.

## Expected result
The expectation was that this would behave like a replicated db (with similar latency).

## Supporting files
relevant validator config:
```
NODE_IS_VALIDATOR=true

CATCHUP_RECENT=86400

[QUORUM_SET]
THRESHOLD_PERCENT=66
VALIDATORS=[
"$self",
"$eno",
"$sdf_1",
"$sdf_3",
"$ibm_ca",
"$fairx_west",
"$tempo_1",
"$satoshipay_3",
"$umbrel"
]
```

relevant watcher config:
```
NODE_IS_VALIDATOR=false

UNSAFE_QUORUM=true

CATCHUP_COMPLETE=true

[QUORUM_SET]
THRESHOLD_PERCENT=75
VALIDATORS=[
'$self',
"$sp_1",
"$sp_2",
"$sp_3"
]
```

**Comment by MonsieurNicolas** [comment]
Sorry it took me a while to come back to this, I thought I had an explanation but I don't think it applies in this case.

If the watchers are not directly connected to those nodes, you may see something like this as the validator messages will have to be routed via other nodes on the network that may not like your validators :)

Are those watchers and validators preferred peers to each other?

**Comment by graydon** [comment]
Closing as stale. We have fairly extensive testing and monitoring on lag levels on the network and don't see this sort of thing recently, please reopen if you see it again.
