### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by YohanBaillot** [stellar/stellar-core#1526]
Interested in developing a Unity plugin using your C# library for the released platforms but more importantly for mobile platforms for AR/VR application blockchain support (virtual money, proof of ownership, database replication, ....). Is there any reason your C++ code would not target to Android or IOS?

**Comment by MonsieurNicolas** [comment]
Hello, not sure I understand what you are asking. This seems to be client code related, and not related to stellar-core. If you think it is, please use the template for submitting issues.
