### ISSUE TITLE
RequireMemoFlag: the transactions to the account must have memo

### ISSUE THREAD

**Issue by bitcodernull** [stellar/stellar-core#1546]
# Before creating an issue
 * check the [documentation](https://www.stellar.org/developers/)
 * ask for help [from the community](https://www.stellar.org/community/)

# Issue type
  feature request

# Version found
  

# Your environment and setup
 

# Issue description
  i have not found the stellar support the flag , or i missed it ?
   the flag is the same as  the ripple flag lsfRequireDestTag
   this is very useful for exchanges

**Comment by MonsieurNicolas** [comment]
yeah this is not supported right now (and it's not in the docs); see https://github.com/stellar/stellar-protocol/issues/71 for the active discussion
