### ISSUE TITLE
loadgenerator doesn't flood transactions

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1555]
It looks like the code used when generating transactions during load testing only adds them to the pending set managed in herder.
Compared to the code in `peer.cpp` or in `CommandHandler::tx`, where if a transaction is pending, it gets flooded.
As a consequence, flooding is not included in this load test, which is a problem.

**Comment by marta-lokhova** [comment]
Addressed this in the load generator PR #1582 (https://github.com/stellar/stellar-core/pull/1582/commits/ea0600aa942129ead3842c56fc57a8839b10f008)
