### ISSUE TITLE
pending transactions in herder is not managed properly

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1556]
When an account submits too many transactions, it looks like we only drop the oldest batch of transactions for that account:
when this happens, we keep the old batches around, with a higher sequence number, and because of that disallow resubmit of the transactions that got dropped (with a bad sequence number error).
This will probably manifest itself as a window where accounts are just in a broken state (until `triggerNextLedger` is called that ends up deleting all those invalid transactions).

We should refactor the code that deals with this (currently split between `struct TxMap` and `mPendingTransactions`) such that we track accounts across generations properly (we should not need to "recalculate" anything if we do it right too).

**Comment by MonsieurNicolas** [comment]
should take a look at this as part of #1854

**Comment by vogel** [comment]
I think it could be make simpler by allowing each transaction to submit transactions only for 4 ledgers (20 seconds) without applying them. After that, all transactions for that account are removed from TransactionQueue and banned for next 10 ledgers.

Currently only first batch (from first ledger close) of transaction in removed, but then all of the other ones are not valid anyways.

**Comment by MonsieurNicolas** [comment]
I thought you had a patch for this? @vogel

**Comment by vogel** [comment]
Only WIP, not finished yet.
