### ISSUE TITLE
how to hide transations on blockchain explore

### ISSUE THREAD

**Issue by bitcodernull** [stellar/stellar-core#1563]
# Before creating an issue
 * check the [documentation](https://www.stellar.org/developers/)
 * ask for help [from the community](https://www.stellar.org/community/)

# Issue type
  want help

# Version found
 

# Your environment and setup
 

# Issue description
 I found some addresses can hide transations on blockchain explore
how to set it?
for example:
https://stellarchain.io/address/GBIO3O2WFFF3QD6JMWRK2SXVOYG7JY347MVTAMWJOSI3XILT44MSR4NK

thanks

**Comment by MonsieurNicolas** [comment]
Sorry stellar-core does not manage this kind of data or properties
