### ISSUE TITLE
Test "Stress test on 2 nodes 3 accounts 10 random transactions 10tx/sec" takes more than 2 hours to finish

### ISSUE THREAD

**Issue by vogel** [stellar/stellar-core#1568]
I was executing long tests over night and `Stress test on 2 nodes 3 accounts 10 random transactions 10tx/sec` has not finished for 2 hours on current master.

**Comment by marta-lokhova** [comment]
Will be resolved when #1582 is merged, since the above test is updated to use the new load generator.

**Comment by marta-lokhova** [comment]
Fix is in master -- "Stress test on 2 nodes 3 accounts 10 random transactions 10tx/sec" finishes and properly outputs results. I think this issue can be closed now.

**Comment by vogel** [comment]
Thanks!
