### ISSUE TITLE
Trustline allocate to new users/members for asset

### ISSUE THREAD

**Issue by WallBB** [stellar/stellar-core#1574]
#### This is not an issue but a help wanted question regarding my asset of Stellar Platform and I thought it is better to ask the core team for help. I am stuck in this dillema and holding alpha of my project as this is the only thing left in my timelines. I have a solution which I described below but I am looking for a better solution. 

# Before creating an issue
 * Already read the documentation and stellar labs regarding this issue.
 * Already discussed a lot on stellar dev slack and galactic talk but still not able to find a viable solution

# Issue type
  help wanted - A better way to allocate trustline to new users/members for stellar assets. Example : Pedity (https://pedity.com) (this is my project)

# Issue description
 This is regarding my new project which rewards users based on content created by them. Please can read more about it in whitepaper(https://pedity.com/Pedity_Whitepaper.pdf) or galactic talk (https://galactictalk.org/d/1012-introducing-pedity-asset).
Okay so problem that I am facing is currently that any user who will join Pedity has to create a trustline and for that the user needs to have some XLM in their account. I can fund 100-1000 users with my own budget and easily create their accounts with minimum balance while registration. Problem will come when Pedity will have more users, I have seen example in other blockchains where they use a faucet to fund their users. Certainly for trustline, a faucet (that transfer money in pennies) or something like that is not viable as it will need to transfer 2XLM per user (~1$) and with time XLM will get much higher value which is a situation I am still thinking how to tackle.

# Where I am stuck
 If in future Pedity attracts a lot of users like steem,golos or LBRY etc, XLM can easily be awarded from projects budget but once Trustline is added and the users are ready for accepting PEDI tokens, I start asking back XLM from inactive users to project budget so that they can be awarded to new users and trustline can be added for them. Only issue is how to ask inactive users who are not active and certainly taking their private key is not something I believe (Some projects do this but I don't think it is a good thing). 

I am looking forward to Stellar core teams response and I can launch alpha of my project quickly. I have a solution which I described above but I am looking for a better solution. :)

**Comment by MonsieurNicolas** [comment]
Hello, thanks for submitting your question. Github is not the place for this type of question though, you should try https://stellar.stackexchange.com/

cheers
