### ISSUE TITLE
Cannot set base reserve or fee to 0 using stellar-core command line

### ISSUE THREAD

**Issue by zulucrypto** [stellar/stellar-core#1594]
To reproduce:

```
# stellar-core --c "upgrades?mode=set&upgradetime=2000-01-01T00:00:00Z&basereserve=0"
Content-Length: 71
Content-Type: application/json

2018-03-10T01:20:46.952 GBZER [default INFO] could not parse basereserve: '0'
Failed to parse 'basereserve' argument
```

I was trying this on a private network since this stack exchange question got me curious: https://stellar.stackexchange.com/questions/649/is-it-possible-to-create-a-private-stellar-network-without-transactions-fees

**Comment by MonsieurNicolas** [comment]
Yes this is by design 0 is not a valid value ; mostly a guardrail as people can still put 1.

**Comment by munawarb** [comment]
It would be nice to be able to set fees to 0 on a private network. I've set my `basefee` and `basereserve` values to 1 but this doesn't eliminate the fees entirely because it's some constant multiplied by `basefee` and `basereserve`.

**Comment by benxage** [comment]
@MonsieurNicolas can you point me to where these values parameter checks are so that I may modify it for a private network?
