### ISSUE TITLE
The legal implications of allowing arbitrary data storage on blockchains

### ISSUE THREAD

**Issue by bryanph** [stellar/stellar-core#1611]
I was wondering if anyone has read the following paper: ["A Quantitative Analysis of the Impact of
Arbitrary Blockchain Content onBitcoin"](https://fc18.ifca.ai/preproceedings/6.pdf).

Now as far as I know, Stellar allows for arbitrary data storage, is this correct? If so, wouldn't this pose a major risk to the future of Stellar? What if someone was able to upload pedo-pornographic content on the blockchain and hide this fact for a few months. Then courts could easily rule the use of the blockchain illegal.

Also, this might not be the right place to post this but I think this is of interest to the developers as well. If not, could you point me in the right direction please? Thanks.

**Comment by MonsieurNicolas** [comment]
yes this is not the right place. You may want to try https://stellar.stackexchange.com/ or https://www.reddit.com/r/Stellar/
