### ISSUE TITLE
Feature request, add limit to AllowTrust operation

### ISSUE THREAD

**Issue by bonen** [stellar/stellar-core#1615]
# Issue type
Feature request

# Issue description
The current protocol allows an asset holder to set a trustline limit. However it would be very valuable if also the Anchors can set a limit when they approve an acount (AllowTrust).
The Anchors we are working with (financial institutions) need to enforce a limit per asset holder they whitelisted (approved) for KYC reasons (different tier levels matching different limits).

**Comment by vogel** [comment]
This probably belongs to https://github.com/stellar/stellar-protocol/issues

**Comment by bonen** [comment]
yes I think so I will recreate the issue there and close it here
