### ISSUE TITLE
afl build broken

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1621]
Looks like https://github.com/stellar/stellar-core/pull/1617 broke the AFL build.

Unclear if this is because of unsupported options or what.
Building https://github.com/stellar/docker-stellar-core/blob/master/Dockerfile.fuzz
yields:
```
afl-clang-fast++ -DHAVE_CONFIG_H -I. -I..  -DSQLITE_OMIT_LOAD_EXTENSION=1 -isystem ".." -I"../src" -I"../src" -isystem /stellar-core/lib/libsodium/src/libsodium/include -isystem ../lib/libsodium/src/libsodium/include -isystem ../lib/libsodium/src/libsodium/include/sodium -isystem /stellar-core/lib/xdrpp -isystem /stellar-core/lib/xdrpp -isystem ../lib/libmedida/src -isystem ../lib/soci/src/core -isystem ../lib/soci/src/backends/sqlite3 -isystem ../lib/soci/src/backends/postgresql  -DASIO_SEPARATE_COMPILATION=1 -DASIO_STANDALONE -isystem ../lib/asio/asio/include -isystem "../lib" -isystem "../lib/autocheck/include" -isystem "../lib/cereal/include" -isystem "../lib/util" -isystem "../lib/soci/src/core" -DUSE_POSTGRES=1 -I/usr/include/postgresql    -g -O2 -std=c++11  -pthread -Wall -Wno-unused-command-line-argument -Qunused-arguments -Wno-unused-local-typedef -Wno-unknown-warning-option -Werror=unused-result -MT soci/src/backends/sqlite3/standard-into-type.o -MD -MP -MF $depbase.Tpo -c -o soci/src/backends/sqlite3/standard-into-type.o soci/src/backends/sqlite3/standard-into-type.cpp &&\
mv -f $depbase.Tpo $depbase.Po
In file included from soci/src/backends/sqlite3/standard-into-type.cpp:9:
../lib/soci/src/backends/sqlite3/soci-sqlite3.h:45:10: fatal error: 'sqlite3.h' file not found
#include <sqlite3.h>
         ^
1 error generated.
Makefile:1701: recipe for target 'soci/src/backends/sqlite3/standard-into-type.o' failed
```

could be that the detection of sqlite3 somehow doesn't work anymore?

**Comment by mfontanini** [comment]
Could this be related to the way the CFLAGS for sqlite are set? See how [they look now](https://github.com/stellar/stellar-core/blob/master/configure.ac#L134)? Looks like the `-I` was outside of the quotes before my patch and maybe now that there's a whitespace in between it somehow breaks something? See how the rest of the CFLAGS are set in that file, they all use `-I`/`-isystem` [inside the quotes](https://github.com/stellar/stellar-core/commit/5b50c40f42468078d9f3bd49e9de629e6197830f#diff-67e997bcfdac55191033d57a16d1408a).

That seems to be the only difference between sqlite and the rest of the library's flags being set, not sure if that would case this though.

**Comment by MonsieurNicolas** [comment]
yes that seems plausible

**Comment by mfontanini** [comment]
Just tried this, seems like that's actually the case, I'll create a PR now.

**Comment by mfontanini** [comment]
Btw, this is not just in the afl build. I imagine travis has libsqlite3-dev installed by default, otherwise this would have failed in there as well when building the PR. It may be worth uninstalling the package explicitly so that the builds are completely clean and don't accidentally use a system wide installed dependency.
