### ISSUE TITLE
Which tag is version 9.2.0? and is it stable?

### ISSUE THREAD

**Issue by fxcoudert** [stellar/stellar-core#1626]
It seems version 9.2.0 was retagged:
- on March 16 we (Homebrew) shipped the new version 9.2.0, which corresponded to commit https://github.com/stellar/stellar-core/commit/a8b6a9dcb6550ce652dc9f81bc92a28be7c9baf8 (https://github.com/Homebrew/homebrew-core/pull/25343)
- today, it seems that your 9.2.0 tag now corresponds to commit https://github.com/stellar/stellar-core/commit/7561c1d53366ec79b908de533726269e08474f77

Moreover, version 9.2.0 is marked currently as “Pre-release”.

Before we update the version we ship in Homebrew, we would need confirmation that the retag was not malicious or accidental, and that 9.2.0 is a stable version (not a “pre-release”). Failing that, we will downgrade the version shipped in Homebrew to the latest release, i.e. 9.1.0.

Thanks!

**Comment by MonsieurNicolas** [comment]
Thanks I updated the 9.2.0 tag to be marked as the latest release (forgot to do this after the first wave of validator upgrades).

I didn't realize there was automation that picks up tags.

Yes, the old 9.2.0 tag was a release candidate (a side effect of our release process), 9.2.0 was the first release where we moved to the rc tagging model but we missed a place in our process and ended up pushing this tag as a lightweight tag.

While it should not happen in the future, you should use the `releases` endpoint provided by github as you won't pick up other tags that we may create.

You can get the list of stable releases like this:
`curl https://api.github.com/repos/stellar/stellar-core/releases | jq '.[] | select (.prerelease == false) | {tag:.tag_name, created:.created_at, published: .published_at, prerelease:.prerelease, notes:.body }'`
