### ISSUE TITLE
Log percentage completed in `Bucket-apply` stage

### ISSUE THREAD

**Issue by bartekn** [stellar/stellar-core#1633]
# Issue type
feature request

# Issue description
I don't know what's the underlying data structure so not sure if it's even possible but at the `Bucket-apply` stage can we display progress in percents? Current log entries like:
```
Bucket-apply: committed 151551 entries
```
do not help much in estimating percentage completed.

**Comment by MonsieurNicolas** [comment]
sounds good. Ideally progress should be given of the overall bucket list being applied as we apply up to 19 buckets.

Best solution would be to use something like `bytes already processed` / `sum of bytes of buckets to apply`: it looks like `ApplyBucketsWork` is called after unzipping and verifying all buckets.

**Comment by bartekn** [comment]
🙏 Trying to catchup with pubnet in docker container for 30 minutes, changed `CATCHUP_RECENT` to `500` and still waiting. Not sure if it's my docker config or something but would be great to see how far am I from this stage to complete. Also, seeing these quite often:
```
2018-09-20T17:50:16.873 GB6Y3 [History INFO] Catching up (discontiguous; will fail and restart): Running: apply-buckets
2018-09-20T17:50:16.887 GB6Y3 [History INFO] Catching up: Running: apply-buckets
```
v10.0.0
