### ISSUE TITLE
In-depth stress testing & DDOS simulation

### ISSUE THREAD

**Issue by tomquisel** [stellar/stellar-core#1640]
# Issue type
testing request

# Issue description

I think it's valuable as Stellar matures to perform in-depth stress testing. It should be done in a real network environment with multiple nodes in different geographic locations, and should explore various adversarial client behaviors, node behaviors, network conditions, and machine conditions. The ideal output would be a document (potentially even publishable) describing tests done, failure modes, and propose ways to mitigate failures or improve performance in those cases. Charts showing the relationship between performance and load in different scenarios would be valuable.

Some ideas to test (default to network of 6 nodes in 3 locations):

* Chart of ops/sec achieved vs. network packet loss (simulated packet loss)
* Chart of ops/sec as # of nodes & # of geo locations increases
* Chart of ops/sec vs. # of open connections when a few adversarial clients open TCP connections and don't close them. Go above 65k open connections per machine, that can be a breaking point.
* Chart of ops/sec as # of accounts, offers, trustlines, or other objects gets huge
* Chart of ops/sec as the number of nodes sending adversarial bogus messages increases
* Chart of ops/sec for different EC2 machine choices for nodes for real-world scalability. Also quantify effect of 1 or 2 slow nodes.
* Also plot ledger close time or other important metrics in all of the above cases
* Document any errors that happen or throughput drops when network receives more ops than can be processed
* Document what happens when network is partitioned under load for several minutes and then rejoined

And I'm sure there are tons of other ideas out there too for adversarial conditions to test the network in. I just want to get the conversation started. Many of those tests may have already been performed as well, in which case the goal would be to compile those results together and then build on them.

**Comment by git734** [comment]
As future user such tests publication is mandatory.
I would add safety-resilience stress tests where thousands of unfair nodes try to overload Stellar.
