### ISSUE TITLE
Add sellerid index to offers table

### ISSUE THREAD

**Issue by tomquisel** [stellar/stellar-core#1644]
It looks like Horizon implements an [Offers for Account Endpoint](https://www.stellar.org/developers/horizon/reference/endpoints/offers-for-account.html) that uses stellar-core's `offers` table. However, the table has no index on `sellerid`. 

Perhaps the best fix would be to add an index on `sellerid, sellingassettype, sellingassetcode, sellingissuer`. This would speed up the existing endpoint, and also make the `offers` check proposed in stellar/go#389 fast.

**Comment by MonsieurNicolas** [comment]
This goes against the overall direction that we're taking to decouple Horizon from core wrt performance:
* as more scenarios are being incorporated into Horizon, the strategy of just adding more indexes to core's db won't scale
* this specific use case seems broken as Horizon is web facing, the pattern of hitting core's db directly for aggregation queries creates a large amplification attack vector for DoS attacks against core

**Comment by MonsieurNicolas** [comment]
we're not doing this
