### ISSUE TITLE
Sync->JoiningSCP || (Private) Network Suddenly Stops 

### ISSUE THREAD

**Issue by ckmakcesar** [stellar/stellar-core#1656]
Context: 4 nodes, private network, undergoing 400TPS stress test (1 operation/tx, just pay 1 unit of same asset). 

Core config: only recent catchup, every node was full validator

Other config: <Horizon> rate-limit=1,000,000 ; <CORE> upgrades?maxtxsize=10,000

--- 

Syndrome: 

Testing with 400TPS, no problem for more than 8 hours. 

Suddenly, all 4 Cores' `"state"` had `"Sync"` changed to `"Joining SCP"`. (i.e. Network is stopped). 

The logs on all nodes showed "Out of sync" together, and `"forcescp"` then restart did not get the nodes back into work. 

(I suspect it might be due to CATCHUP_RECENT? It dies out right after trying to trim records...)

---

p.s. over 2000 lines for this out-of-sync info... 

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/GlJqC.png

**Comment by MonsieurNicolas** [comment]
Could be that the default values for maintenance don't fit with your scenario (defaults are targeting public network).

You can try to set it up to run more often but with a smaller value. If you're doing 400 tx/s, maybe something like run every 5 minutes worth of data:
```
AUTOMATIC_MAINTENANCE_PERIOD=300
AUTOMATIC_MAINTENANCE_COUNT=100
```

Let me know how that goes.

**Comment by ckmakcesar** [comment]
Thanks @MonsieurNicolas ! I'll close it for the moment, and reopen it in case it haunts back.
