### ISSUE TITLE
Using horizon v0.12.3 and stellar-core 9.2.0, manage data op fails

### ISSUE THREAD

**Issue by munawarb** [stellar/stellar-core#1668]
# Issue type
  bug

# Version found
  * git hash of the version you're running `7561c1d`
  * version returned by `./stellar-core --version` `9.2.0`

# Your environment and setup
  * Operating System name and version `Distributor ID:	Ubuntu Description:	Ubuntu 16.04.4 LTS Release:	16.04 Codename:	xenial`
  * Postgresql 9.5
  * Horizon 0.12.3
  * Stellar-core 9.2.0 (tested on both production branch and testnet branch)
  * Are you running from the command line? From a container? Command line
  * Did you pass in special parameters when building the app? No

# Issue description
When I send a `manage data operation`, Horizon returns an empty `result_codes` array, as in the strings inside are empty but I get a 400 bad request. However, creating an account and sending a payment work just fine.

## Actual result
I have Horizon server 0.12.3 and Stellar-Core 9.2.0 running locally. When I send a create account operation using the root account as the source, the new account creates properly.
However, when I try to send a manage data operation, trying to save the data name "test" with value "hi", I get a tx_failed message, with a blank operations string: 
```{
  "type": "https://stellar.org/horizon-errors/transaction_failed",
  "title": "Transaction Failed",
  "status": 400,
  "detail": "The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this response contains further details.  Descriptions of each code can be found at: https://www.stellar.org/developers/learn/concepts/list-of-operations.html",
  "extras": {
    "envelope_xdr": "AAAAAN5DEJn9DwVZhhctyWBlUcyVHQ7AXerKrur0kNQCKhM7AAAAZAAAAGcAAAABAAAAAAAAAAAAAAABAAAAAAAAAAoAAAAEdGVzdAAAAAEAAAACaGkAAAAAAAAAAAABAioTOwAAAEDBWxUL8cBuFoTRz7rYqoFxfGU4f6klq0Targt78zyvIq9j4uPHykfWnUwUjCZUHXTCIwT5dUkfMrHuHavsuj0I",
    "result_codes": {
      "transaction": "tx_failed",
      "operations": [
        ""
      ]
    },
    "result_xdr": "AAAAAAAAAGT/////AAAAAQAAAAAAAAAK/////wAAAAA="
  }
}
Error code is
QNetworkReply::NetworkError(ProtocolInvalidOperationError)
```
## Expected result
Stellar-core should properly save the data.

## Supporting files
 Paste here or link to a gist/s3 bucket/etc material relevant to this issue:
    * configuration files (DON'T FORGET TO REMOVE SECRETS)
    * log files - best is to have logs running at DEBUG level (`-ll DEBUG` on the command line)

**Comment by MonsieurNicolas** [comment]
Looks like you're running a private network and didn't upgrade your network to the current version of the protocol.
`ManageDataOp` is not supported on version 0 (genesis).
You can verify this by running `info` and looking at the `ledger` section, you will see something like this:
```
      "ledger" : {
         "age" : 19,
         "baseFee" : 100,
         "baseReserve" : 100000000,
         "closeTime" : 1523913116,
         "hash" : "c45efd11e06f1c11fbc896aa090d3b785980093b384531a889fb651357252715",
         "maxTxSetSize" : 100,
         "num" : 14,
         "version" : 0
```
in this case `version` is 0, and what you really want is 9 (current version in testnet and production).

**Comment by munawarb** [comment]
Hi,
Thanks for the detailed response. Correct that I’m running a private network for testing. How would I upgrade the protocol? I thought compiling 9.2.0 will do it. I’m really new to Stellar so sorry for the obvious questions :)

**Comment by MonsieurNicolas** [comment]
cool. you can review this section of the admin guide https://github.com/stellar/stellar-core/blob/master/docs/software/admin.md#network-configuration
