### ISSUE TITLE
stellar-core crashes after downloading bad ledger file from history

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1676]
As reported in #1675 

version: v9.2.0

```
2018-04-27T08:48:27.385 GBT6G [History INFO] Catching up: verifying checkpoint 1/10385 (0%)
2018-04-27T08:48:27.385 GBT6G [Fs ERROR] failed to open XDR file: buckets/tmp/catchup-52d5d909f4b62698/ledger-0000003f.xdr, reason: 2 [XDRStream.h:49]
terminate called after throwing an instance of 'std::runtime_error'
  what():  failed to open XDR file: buckets/tmp/catchup-52d5d909f4b62698/ledger-0000003f.xdr, reason: 2
2018-04-27T08:48:27.971 GBT6G [default INFO] Starting stellar-core v9.2.0
```

While crashing may be appropriate in some cases, it doesn't seem to be one of those here.

It seems we're missing some basic checks in the code for when things go wrong.

We should harden the code to ensure that (not sure which one we're already doing):
* after downloading a file, we actually have a file on disk matching the name that we expect
* after unzipping a file, that we actually have a file on disk with the content
* do proper exception handling when opening/reading/writing files

**Comment by pavanvora** [comment]
@MonsieurNicolas Same issue here getting something similar output
`2018-10-21T16:33:33.799 GDWCY [History INFO] Catching up: verifying checkpoint 1/321744 (0%)
2018-10-21T16:33:33.799 GDWCY [Fs ERROR] failed to open XDR file: buckets/tmp/catchup-22c351b238806e5a/ledger-0000003f.xdr, reason: 2 [XDRStream.h:49]
terminate called after throwing an instance of 'std::runtime_error'
  what():  failed to open XDR file: buckets/tmp/catchup-22c351b238806e5a/ledger-0000003f.xdr, reason: 2
Aborted (core dumped)
`

**Comment by MonsieurNicolas** [comment]
Looks like this will be made irrelevant by the `Work` refactor. Moving out

**Comment by marta-lokhova** [comment]
To clarify, this issue tracks `Work` properly failing instead of crashing while dealing with bad files.
