### ISSUE TITLE
[BUG] Multi-signature unexpected failure (tx_bad_auth_extra while all signers are legit)

### ISSUE THREAD

**Issue by MisterTicot** [stellar/stellar-core#1692]
## Description

When a transaction is signed by more legit signers than required, it will be rejected with 'tx_bad_auth_extra' error.

## Expected behavior

The transaction should be validated and each legit signer should be recorded into the blockchain; Or at least the transaction should get validaded.

The rationale for including all the signatures is that there's usage cases where it does matters who signed, beyond the fact that the threshold have been met. For instance: voting system, legal contracts, proof of presence. Those are commons use of blockchain systems that could easily and cheaply get supported by Stellar.

## Consequences

In the current state of affairs wallets/authenticator multisig implementors have to implement additional routines to remove valid signatures from transaction so that the transaction get validated.

## Steps to reproduce

```
StellarSdk.Network.useTestNetwork()
var server = new StellarSdk.Server('https://horizon-testnet.stellar.org')
var account1 = StellarSdk.Keypair.random()
var account2 = StellarSdk.Keypair.random()

function fundAccount (publicKey) {
  return new Promise(function (resolve, reject) {
    const xhr = new XMLHttpRequest()
    xhr.open('GET', 'https://friendbot.stellar.org/?addr=' + publicKey, true)
    xhr.send()
    xhr.onloadend = function () {
      if (xhr.readyState === 4 && xhr.status === 200) resolve()
      else reject()
    }
  })
}

console.log('Fund account1')
fundAccount(account1.publicKey())
  .then(function() {
    console.log('Fund account2')
    return fundAccount(account2.publicKey())
  })
  .then(function() {
    console.log('Set account2 as signer for account1')
    return server.loadAccount(account1.publicKey())
  })
  .then(function(account) {
    var tx = new StellarSdk.TransactionBuilder(account)
      .addOperation(StellarSdk.Operation.setOptions({
        signer: { weight: 1, ed25519PublicKey: account2.publicKey() }
      }))
      .build()
    tx.sign(account1)
    return server.submitTransaction(tx)
  })
  .then(function() {
    console.log('Sign a transaction with both account1 & account2 and send')
    return server.loadAccount(account1.publicKey())
  })
  .then(function(account) {
    console.log(account)
    var tx = new StellarSdk.TransactionBuilder(account)
      .addOperation(StellarSdk.Operation.setOptions({}))
      .build()
    tx.sign(account1)
    tx.sign(account2)
    return server.submitTransaction(tx)
  })
  .then(console.log)
  .catch(console.log)
```

**Comment by vogel** [comment]
I think it is more stellar-protocol issue at this level, not stellar-core: https://github.com/stellar/stellar-protocol/issues

If that change gets accepted in stellar-protocol, it can be implemented in stellar-core

**Comment by MisterTicot** [comment]
@vogel Are you sure that having a transaction with "too much" valid signatures being rejected is part of the protocol? I mean: not registering the signatures beyond the threshold probably is, but rejecting the transaction seems like a odd behavior to me.

**Comment by MisterTicot** [comment]
@vogel Ok then, let's go to protocol repo. Thank you for helping with that.

**Comment by MonsieurNicolas** [comment]
I am closing this issue as it's already tracked in the protocol repo

**Comment by Thangarajmitosis** [comment]
hi @MonsieurNicolas  i am getting same error plz explain that one , show some sample code
