### ISSUE TITLE
Got "Bad public key" error when using the node seed

### ISSUE THREAD

**Issue by triamnetwork** [stellar/stellar-core#1713]
I have a docker image and already set up a server running Standalone Core with this image.
But when I trying to set up another server with this image, I generate another node seed with the same way as before (use Stellar Laboratory) but I got "[default FATAL] Got an exception: bad public key [main.cpp:915]" error and cannot start Core.
Thank you for all your assistance.

**Comment by MonsieurNicolas** [comment]
this doesn't seem to be a bug report but more of a support request. we do not use github for this - follow the links in the issue template that you deleted

**Comment by mkaliberda** [comment]
@triamnetwork i have similar issues. Could u help resolve it. What the reason did u have? Thanks!
