### ISSUE TITLE
How to use stellar define a ERC721 like asset

### ISSUE THREAD

**Issue by YoleYu** [stellar/stellar-core#1714]
Hi,
With the help of stellar, It's easy to issue and transfer asset like ERC20. But if we want to build some application based on stellar, for example, we are a handmade shoes shop, each shoes has different attributes, we give each shoes a QR code, how to define this kind of asset(shoes) in stellar?

**Comment by MonsieurNicolas** [comment]
# Before creating an issue
  * check the [documentation](https://www.stellar.org/developers/)
  * ask for help
    * There is a [Stellar Stack Exchange](https://stellar.stackexchange.com/)
    * For more general questions, discuss with [the community](https://www.stellar.org/community/) (Slack, forums, Reddit, ...)
  * check existing and closed issues (you may have to remove the `is:open` filter)
    * check that the version that you are running is newer than the one with the fix
    * re-open an old issue that is supposed to be fixed; be sure to include additional details

Issues opened here are to report actual problems with stellar-core; any other issues (general questions, issues unrelated to stellar-core) will be closed (sorry - we have only a small community of people that manage issues).
