### ISSUE TITLE
Stellar Mainnet not reaching Synced State

### ISSUE THREAD

**Issue by panther93** [stellar/stellar-core#1734]
I'm running Stellar-core with pubnet configuration. But even after 10hrs it hasn't reached synced state. It shows
    "state": "Catching up",
        "status": [
            "Catching up: downloading transactions files 137/137 (100%)"
        ]
What should be done? My stellar-core.cfg is same as that provided by the official docker stellar-core-horizon

@nullstyle @matschaffer

**Comment by MonsieurNicolas** [comment]
Closing this for now (reopen if you can add actionable repro steps that make this a bug).

# Before creating an issue
  * check the [documentation](https://www.stellar.org/developers/)
  * ask for help
    * There is a [Stellar Stack Exchange](https://stellar.stackexchange.com/)
    * For more general questions, discuss with [the community](https://www.stellar.org/community/) (Slack, forums, Reddit, ...)
  * check existing and closed issues (you may have to remove the `is:open` filter)
    * check that the version that you are running is newer than the one with the fix
    * re-open an old issue that is supposed to be fixed; be sure to include additional details

Issues opened here are to report actual problems with stellar-core; any other issues (general questions, issues unrelated to stellar-core) will be closed (sorry - we have only a small community of people that manage issues).
