### ISSUE TITLE
Handle catchup directory management better

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/stellar-core#1735]
Right now during catchup we use a single directory to store all ledger header and transaction files. If I try to do catchup complete, it's 159800 checkpoints as of now (and this number will only keep growing), meaning over 300,000 files in a single `buckets/tmp/catchup` directory!  This seems very inefficient from the file system point of view. 

I think we can improve it by using sub-directories, perhaps in the similar way we do it when resolving remote directories for archive publishing.

**Comment by MonsieurNicolas** [comment]
That seems like a good idea. This may be the same issue than https://github.com/stellar/stellar-core/issues/1045 (as we already do this on the archives themselves)
