### ISSUE TITLE
Consider sending full checkpoint to newly connected peer 

### ISSUE THREAD

**Issue by vogel** [stellar/stellar-core#1739]
# Issue type
  Feature request

# Issue description
 If MAX_SLOTS_TO_REMEMBER is set to 64 then node can start catchup as soon as it gets connected, thanks to sendGetScpState message.

## Actual result
 MAX_SLOTS_TO_REMEMBER is set to 12, so it means by average node must wait 130 seconds before it can start catchup, which is bad for acceptance tests.

## Expected result
 Node can start catchup as soon as it connects to another node.

**Comment by MonsieurNicolas** [comment]
I don't think this makes sense in general:
* current value of `12` (roughly 1 minute worth of ledgers) allows for validator maintenance (restart with some delay).
* typical case is that a node connects to another node and does not need historical data, 12 is already 12 too many and only delays establishing (or re-establishing) connectivity to the network. This is especially problematic if the transaction rate is high.

**Comment by theaeolianmachine** [comment]
@MonsieurNicolas you want to remove that label, or add a description to the label itself? Not sure what it represents, but it's the only issue the label is assigned to.

**Comment by MonsieurNicolas** [comment]
ah yes, it's a label we use to give a heads up when issues are on track to be closed. Closing this particular one that has been sitting in that state for a while. @theaeolianmachine

**Comment by theaeolianmachine** [comment]
Gotcha, thanks!
