### ISSUE TITLE
Unclear licencing of xdrpp

### ISSUE THREAD

**Issue by ssiloti** [stellar/stellar-core#1741]
Xdrpp's COPYING file indicates that it is distributed under GPL-3, but also includes a clause granting the Stellar Development Foundation the right to re-licence the code. It seems that the intent is to distribute xdrpp under a permissive licence as part of stellar-core, but I can't find any positive statement to that effect. An entry for xdrpp in stellar-core's COPYING file would clear this up.

**Comment by stanford-scs** [comment]
xdrpp is currently GPL-3.  SDF can relicense at any time if it's a problem.  I haven't seen any evidence that it's a problem.  The first time some credible project needs a different license, we can fix it.
