### ISSUE TITLE
Curl implementation with local stellar core 

### ISSUE THREAD

**Issue by SinghDavinder94** [stellar/stellar-core#1743]
Hello Everyone,
            I am new to stellar.Just I want to know that How can I connect to stellar core which I set up to locally at --------------- network IP.Just want to know its implementation using curl as well as with methods.Any referal link for that.

**Comment by theaeolianmachine** [comment]
Hi @SinghDavinder94,

If you're trying to interact with Stellar over HTTP, I'd suggest taking a look at setting up a [Horizon](https://github.com/stellar/go/tree/master/services/horizon) instance. It's the easiest way to interact with Stellar, and unless you're planning to develop directly on top of stellar-core, it's definitely a better route to go.

You can read about the API endpoints in the [Horizon Reference Documentation](https://www.stellar.org/developers/reference/), as well as learn about concepts in [Stellar's guides.](https://www.stellar.org/developers/guides/).

Hopefully that helps!

**Comment by MonsieurNicolas** [comment]
I am closing this issue, re-open if it's an actual bug report.

# Before creating an issue
  * check the [documentation](https://www.stellar.org/developers/)
  * ask for help
    * There is a [Stellar Stack Exchange](https://stellar.stackexchange.com/)
    * For more general questions, discuss with [the community](https://www.stellar.org/community/) (Slack, forums, Reddit, ...)
  * check existing and closed issues (you may have to remove the `is:open` filter)
    * check that the version that you are running is newer than the one with the fix
    * re-open an old issue that is supposed to be fixed; be sure to include additional details

Issues opened here are to report actual problems with stellar-core; any other issues (general questions, issues unrelated to stellar-core) will be closed (sorry - we have only a small community of people that manage issues).
