### ISSUE TITLE
Error MSB6006 "cmd.exe" exited with code 1.

### ISSUE THREAD

**Issue by nadendlaprasad** [stellar/stellar-core#1745]
Hi,

I have forked project into my local system. I have followed all windows installation instructions. when i build project from Visual studio I am facing the following error message.

**Error MSB6006	"cmd.exe" exited with code 1.	stellar-core**

could anyone help me out the reason for this

**Comment by MonsieurNicolas** [comment]
Hello;
Sorry, we do not use github issues for support questions. Try other channels.

# Before creating an issue
  * check the [documentation](https://www.stellar.org/developers/)
  * ask for help
    * There is a [Stellar Stack Exchange](https://stellar.stackexchange.com/)
    * For more general questions, discuss with [the community](https://www.stellar.org/community/) (Slack, forums, Reddit, ...)
  * check existing and closed issues (you may have to remove the `is:open` filter)
    * check that the version that you are running is newer than the one with the fix
    * re-open an old issue that is supposed to be fixed; be sure to include additional details

Issues opened here are to report actual problems with stellar-core; any other issues (general questions, issues unrelated to stellar-core) will be closed (sorry - we have only a small community of people that manage issues).
