### ISSUE TITLE
Update peer table to only include reacheable peers over time

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1753]
Right now the `peers` table contains a cesspool of peers received from other peers and the only indicator that peers may be bad is the `numfailures` column.

This makes peer discovery quite suboptimal as peers forwarded to other peers may not be reacheable.

I think we should make the following changes to the way we track peers:
* define a clear "validation" process for peers.
   * `new`: we do not know anything about this peer
   * `outbound_valid`: we could connect to this peer at some point
   * preferred and known peers would set the flags such that they would assume to be "healthy"
* only use `numfailures` for outbound connections, right now, I *think* we reset it when a peer connects to us, this is wrong
* only forward peers with `outbound_valid`
* probably delete peers that we could not connect to after X retries (probably should be equivalent to 1 or 2 weeks of attempts)

Second, we should ensure that we have logic in place to properly scrub the peers table:
right now we only attempt connections when we are below `TARGET_PEER_CONNECTIONS`, causing the entries in that table to rot away.

A few potential options:
* always connect to a bunch of peers, but drop them later if we find that we were already above our target and we were the initiator of those connections.
* add a "peer reaper" sub task that purpose is to scrub the peer table, I am not sure how we can ensure that this doesn't potentially negatively impact the normal connection process

**Comment by vogel** [comment]
I'm wondering if another solution, not based on states, would not be better.

I propose to save in PeerRecord several additional fields (all nullable datetimes):

- lastOutboundConnectionAttempt (set on connectTo)
- lastOutboundConnectionSuccess (set recvAuth when mRole = WE_CALLED_REMOTE, before getOverlayManager().acceptAuthenticatedPeer())
- lastInboundConnectionAttempt (set on recvHello when mRole = REMOTE_CALLED_US)
- lastInboundConnectionSuccess (set on recvAuth when mRole = REMOTE_CALLED_US, before getOverlayManager().acceptAuthenticatedPeer())

Of course when lastOutboundConnectionAttempt is NULL, also lastOutboundConnectionSuccess is NULL and when lastInboundConnectionAttempt is NULL, lastInboundConnectionSuccess is NULL.

Following states can be deducted from those values:

node is new when:
lastOutboundConnectionAttempt == NULL && lastInboundConnectionAttempt == NULL

node never accepted outbound connection:
lastOutboundConnectionAttempt != NULL && lastOutboundConnectionSuccess == NULL

node properly accepted last outbound connection:
lastOutboundConnectionAttempt < lastOutboundConnectionSuccess

node did not accept last outbound connection, but we assume problems are temporary:
lastOutboundConnectionAttempt > lastOutboundConnectionSuccess && lastOutboundConnectionAttempt - lastOutboundConnectionSuccess <= OUTBOUND_THRESHOLD

node did not accept last outbound connection, and we assume node is dead:
lastOutboundConnectionAttempt > lastOutboundConnectionSuccess && lastOutboundConnectionAttempt - lastOutboundConnectionSuccess > OUTBOUND_THRESHOLD

node connects to us, does not accept connections, and we do not want to remove it from our table (because if we did, next time it connected to us we would try to connect to it again):
now() - lastInboundConnectionAttempt <= INBOUND_REMOVE_THRESHOLD

node can be safely removed:
now() - lastOutboundConnectionSuccess > OUTBOUND_REMOVE_THRESHOLD
now() - lastInboundConnectionAttempt > INBOUND_REMOVE_THRESHOLD

**Comment by MonsieurNicolas** [comment]
I realize that the logic described so far are too complex, so I came up with a new strategy that should keep things relatively simple.

It's similar but simpler than what Bitcoin's [p2p code](https://github.com/bitcoin/bitcoin/blob/master/src/net.cpp) is doing.

## Split the peers table into 2 tables
* `peers` will become a list of known peers
* `connpeers` (new) is a list of peers that we can connect to

When receiving peers or when a peer connects to us, if the address is not in `connpeers`, it may be added to `peers`.

When connecting to a peer, it may be added to `connpeers` (or its last connection be updated).

Note: preferred peers should be stored in `connpeers` (ie: assume that they are peers that we can connect to).

This split allows to transition to the new approach fairly easily as a newly migrated node will start with:
* `peers` populated with all the peers that it talked to before (seeded with `KNOWN_PEERS`)
* `connpeers` populated with preferred peers

## Distinguish outbound from inbound connections
Right now the settings that control how a node connects to the network are:
* `TARGET_PEER_CONNECTIONS` : minimum number of peers, 
* `MAX_ADDITIONAL_PEER_CONNECTIONS`: number of peers above `TARGET_PEER_CONNECTIONS` that can connect to the node.

The issue here is that this policy biases towards inbound connections: nodes tend to be flooded by inbound connections, leaving no room for the node to "learn" about peers that accept connections.

Instead we should properly separate how those settings are used:
* `TARGET_PEER_CONNECTIONS` : target number of outbound peers
* `MAX_ADDITIONAL_PEER_CONNECTIONS`: number of inbound connections allowed
  * we should change the default (when set as -1) from `TARGET_PEER_CONNECTIONS` to `8*TARGET_PEER_CONNECTIONS`

## Updates to `OverlayManagerImpl::tick()`

In order:
1. Connect to preferred peers
2. Connect to some peers from `connpeers`
3. Attempt to promote peers from the `peers` table

Connection strategy:
* When picking peers to connect to, we should pick a random subset of peers for which `Nextattempt` is in the past.

Promotion strategy:
* When picking peers to promote, we should pick a random subset of peers for which `Nextattempt` is in the past.
* A connection is considered successful if it gets passed authentication, ie right before checking `acceptAuthenticatedPeer`
* We should keep track of how many peers are being checked for promotion, and not promote more peers.
* It should be possible to attempt promoting a peer that is already connected (inbound), so that addresses learned from inbound connections can be properly promoted for later
* We should use the "left over" count from "step 2" to speed things up (ie, if we can only take 4 entries from `connpeers` but our `TARGET_PEER_CONNECTIONS` is 10, we should attempt to promote an extra 10-4=6 peers from the `peers` table)

## Updates to `getPeers`
We should send random peers from `connpeers` and complement with random peers from `peers`

## What we are not doing for now

* We are not going to remove entries from `connpeers` or `peers` yet (ie: bad peers will stay there for now, pushed around by `Nextattempt`). Related to this, we are not implementing a strategy to enforce an upper bound for either of those tables (doesn't exist today, may be useful in the future).
* We are not promoting peers if we're connected (outbound) to enough peers, we'll need a ranking strategy to do this in the future (as we'd need to kick out peers that we consider not as useful as others).
* We are not bucketizing peers for now (in Bitcoin buckets are used to limit the influence of entire class B networks), we may not implement this as this mitigation is ineffective against botnets anyways.

**Comment by vogel** [comment]
I need I need some clarification

> When receiving peers or when a peer connects to us, if the address is not in connpeers, it may be added to peers.
> When connecting to a peer, it may be added to connpeers (or its last connection be updated).

I do not understand why the `may`. Does that mean `it will be added to peersconnpeers when authentication passes` or are there other conditions?

> This split allows to transition to the new approach fairly easily as a newly migrated node will start with:

Does that mean that we clear old `peers` table when doing migration to new db scheme?

> 1. Connect to preferred peers
> 2. Connect to some peers from connpeers
> 3. Attempt to promote peers from the peers table

Do we always run all 3 steps, or only we run next one when previous one didn't fulfill our `TARGET_PEER_CONNECTIONS` or do we split `TARGET_PEER_CONNECTIONS` between all 3 steps?

> We should send random peers from connpeers and complement with random peers from peers

As before, should we only use `peers` table if `connpeers` didn't get enough entries, or split like 75% from `connpeers` and rest from `peers`?

**Comment by MonsieurNicolas** [comment]
> I do not understand why the may. Does that mean it will be added to peersconnpeers when authentication passes or are there other conditions?

We'll be adding conditions later (see the "what we're not doing" section), for this version we just need to pass authentication (see promotion strategy).

> Does that mean that we clear old peers table when doing migration to new db scheme?

This is already called out explicitly already: we do not clear the peers table as they are "known".

> Do we always run all 3 steps, or only we run next one when previous one didn't fulfill our TARGET_PEER_CONNECTIONS or do we split TARGET_PEER_CONNECTIONS between all 3 steps?

step 1: we always attempt to connect to preferred peers.
step 2: we do not connect to more peers if target is reached (per definition of `TARGET_PEER_CONNECTIONS`)
step 3: this is already called out as well (see promotion strategy), on what to do when there are not enough peers in the `connpeers` table.

> As before, should we only use peers table if connpeers didn't get enough entries, or split like 75% from connpeers and rest from peers?

I imagine it's better to just send peers that we know are good in priority, so follow the same strategy than for connecting outbound (so load as many from `connpeers` and then load the reminder from `peers`). The difference is that because we only send 50 peers, we should load a larger number like 500 and pick a random subset of those 50.

**Comment by vogel** [comment]
That looks good.

**Comment by MonsieurNicolas** [comment]
maybe a concern with never attempting to promote more peers is that the network may not "learn" new peers over time as it has enough peers already. For example, if I need only 10 peers and I have 10 peers in my outbound table, I will never expand the outbound table beyond 10 even though I am forwarding 50 peers to other nodes.

> What we are not doing for now
    We are not promoting peers if we're connected (outbound) to enough peers, we'll need a ranking strategy to do this in the future (as we'd need to kick out peers that we consider not as useful as others).

So I think we should always run the promotion code (even it means dropping connections as we'd be over the target outbound target), at a small rate (like pick an extra 1 peer to promote every time `tick` runs). @vogel
