### ISSUE TITLE
How to do the swap between BTC and LTC?

### ISSUE THREAD

**Issue by zhouzhou84** [stellar/stellar-core#1758]
### Description
how do you deal with the swap between BTC and LTC?

I am so confused about it on stellar

**Comment by MonsieurNicolas** [comment]
Sorry this is the wrong place to ask questions.

# Before creating an issue
  * check the [documentation](https://www.stellar.org/developers/)
  * ask for help
    * There is a [Stellar Stack Exchange](https://stellar.stackexchange.com/)
    * For more general questions, discuss with [the community](https://www.stellar.org/community/) (Slack, forums, Reddit, ...)
  * check existing and closed issues (you may have to remove the `is:open` filter)
    * check that the version that you are running is newer than the one with the fix
    * re-open an old issue that is supposed to be fixed; be sure to include additional details

Issues opened here are to report actual problems with stellar-core; any other issues (general questions, issues unrelated to stellar-core) will be closed (sorry - we have only a small community of people that manage issues).
