### ISSUE TITLE
instrument code when resolving futures

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1765]
There is an assumption in the code base that processes that take a long time don't hang the main thread.

One of those long running processes is bucket merging that happens to be running on a separate thread, in the main thread we call [resolve](https://github.com/stellar/stellar-core/blob/6964a5ef991d27fbdc1dfab9e90d3f4f03f73df1/src/bucket/FutureBucket.cpp#L208) that normally should not hang.

Right now we don't have any insight if this is true.

We should add conditional logging to `FutureBucket::resolve` if waiting for the future takes too long (more than 1 second).
As this should "never" happen, a debug level of `INFO` should be used.

**Comment by marta-lokhova** [comment]
Merged
