### ISSUE TITLE
can't read ./docs/stellar-core.1.in: No such file or directory

### ISSUE THREAD

**Issue by rafaeltokyo** [stellar/stellar-core#1777]
System:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

Hi guys, i have the following  problem when compiling 

![screenshot from 2018-09-03 11-43-36](https://user-images.githubusercontent.com/38796439/44993022-755c1600-af6f-11e8-8e33-eb29cb65399f.png)

**Comment by marta-lokhova** [comment]
Hi there! It looks like `pandoc` is not installed?

**Comment by rafaeltokyo** [comment]
Its woked thanks you @marta-lokhova

**Comment by trongnmchainos** [comment]
thanks you so much!
