### ISSUE TITLE
Submit transaction timeout but still complete

### ISSUE THREAD

**Issue by trongcauhcmus** [stellar/stellar-core#1778]
when i call api submit new transaction. Horizon return me timeout exception because it can not receive any response from stellar-core, but when i check my address, the transaction included on network and complete. i use Java sdk first to submit transaction by function, after that, i create raw transaction by code and using api to submit, it still wrong
My docker version is: 
docker --version
Docker version 18.06.1-ce, build e68fc7a
stellar-core --version
v9.2.0

**Comment by MonsieurNicolas** [comment]
This doesn't seem to be a stellar-core issue; could be a Horizon bug.

reopen this issue if you have actual repro steps against stellar-core.

# Before creating an issue
  * check the [documentation](https://www.stellar.org/developers/)
  * ask for help
    * There is a [Stellar Stack Exchange](https://stellar.stackexchange.com/)
    * For more general questions, discuss with [the community](https://www.stellar.org/community/) (Slack, forums, Reddit, ...)
  * check existing and closed issues (you may have to remove the `is:open` filter)
    * check that the version that you are running is newer than the one with the fix
    * re-open an old issue that is supposed to be fixed; be sure to include additional details

**Comment by gituser** [comment]
check this issue - https://github.com/stellar/go/issues/305
