### ISSUE TITLE
How to get notification on new deposits.

### ISSUE THREAD

**Issue by AnkitRathore175** [stellar/stellar-core#1782]
Hello Everyone,
Can anyone provide me details regarding how can i set remote notification on new deposits via stellar-core,
Whenever a new transactions are found on any pair of accounts, i want to make notification to my remote wallet service.
Thanks

**Comment by MonsieurNicolas** [comment]
sorry this github is not used for this kind of request

# Before creating an issue
  * check the [documentation](https://www.stellar.org/developers/)
  * ask for help
    * There is a [Stellar Stack Exchange](https://stellar.stackexchange.com/)
    * For more general questions, discuss with [the community](https://www.stellar.org/community/) (Slack, forums, Reddit, ...)
  * check existing and closed issues (you may have to remove the `is:open` filter)
    * check that the version that you are running is newer than the one with the fix
    * re-open an old issue that is supposed to be fixed; be sure to include additional details

Issues opened here are to report actual problems with stellar-core; any other issues (general questions, issues unrelated to stellar-core) will be closed (sorry - we have only a small community of people that manage issues).
