### ISSUE TITLE
Error in running steller core windows set up project

### ISSUE THREAD

**Issue by manthanomy** [stellar/stellar-core#1787]
# Issue type
    Steller core Window based project not build

# Your environment and setup
  using windows 10 64 bit.

# Issue description
  Attach screen shot
![xlm 1](https://user-images.githubusercontent.com/33083387/45282582-f92a7b00-b4f8-11e8-8d41-520316522289.png)

**Comment by MonsieurNicolas** [comment]
To help narrow things down, can you add exact repro steps?
Did you follow instructions from https://github.com/stellar/stellar-core/blob/master/INSTALL-Windows.md ?
It seems there is something else going on as it can't even build xdrpp

**Comment by manthanomy** [comment]
![xlm 3](https://user-images.githubusercontent.com/33083387/45341383-1c682f80-b5b8-11e8-9bf8-d2865320bcd1.png)

**Comment by manthanomy** [comment]
Can some one please give an answer ? I really need it.

**Comment by manthanomy** [comment]
Can some one please give an answer ? I really need it.

**Comment by vogel** [comment]
Please try storing stellar-core source and project file in directory that does not have any spaces in its path.

**Comment by MonsieurNicolas** [comment]
Did you try @vogel 's suggestion?

**Comment by MonsieurNicolas** [comment]
closing for now, reopen this issue if the suggestion does not work
