### ISSUE TITLE
cleanup "info"

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1792]
# Issue type
  feature request

# Version found
10.0.0

# Issue description
The output of `info` is becoming too large (right now it's over 55 lines) that it doesn't even fit on a regular screen without scrolling.

We should rationalize `info` with the `metrics` endpoint and logging.

Using "archive" to illustrate, but there could be more.

My suggestion is to have
* `info` have critical information only that allows an operator "at a glance" to know if a node works properly / understand what a node is doing
   * archive information here should just be a "failure ratio" for example
   * move "static" information (such as build ID, supported protocol version, etc) to a different endpoint or controlled by a flag
* `metrics` have detailed stats
   * each archive should export metrics
* Logging 
   * critical errors with archives should show up here

## Supporting files

```json
   "info" : {
      "UNSAFE_QUORUM" : "UNSAFE QUORUM ALLOWED",
      "build" : "v10.0.0rc2-12-g81446c66-dirty",
      "history" : {
         "sdf1" : {
            "failure" : 0,
            "success" : 0
         },
         "sdf2" : {
            "failure" : 0,
            "success" : 0
         },
         "sdf3" : {
            "failure" : 0,
            "success" : 0
         }
      },
      "ledger" : {
         "age" : 1536781118,
         "baseFee" : 100,
         "baseReserve" : 100000000,
         "closeTime" : 0,
         "hash" : "39c2a3cd4141b2853e70d84601faa44744660334b48f3228e0309342e3f4eb48",
         "maxTxSetSize" : 100,
         "num" : 2,
         "version" : 0
      },
      "network" : "Public Global Stellar Network ; September 2015",
      "peers" : {
         "authenticated_count" : 1,
         "pending_count" : 6
      },
      "protocol_version" : 10,
      "quorum" : {
         "19953931" : {
            "agree" : 4,
            "disagree" : 0,
            "fail_at" : 2,
            "hash" : "0b0c60",
            "missing" : 3,
            "phase" : "EXTERNALIZE"
         }
      },
      "startedOn" : "2018-09-12T19:38:01Z",
      "state" : "Catching up",
      "status" : [
         "Catching up: Waiting for trigger ledger: 19953931/19953985, ETA: 270s"
 ]
   }
}
```

**Comment by vogel** [comment]
I think we could split info into three parts with URL parameter:

`info?mode=(health|ledger|configuration)`

with `health` being default one.

In each of them we could put this data:

```
"health" : {
    "history_failure_rate": 0,
    "authenticated_peers" : 1,
    "pending_peers" : 6,
    "ledger" : {
        "age" : 10,
        "closeTime" : 5,
        "hash" : "39c2a3cd4141b2853e70d84601faa44744660334b48f3228e0309342e3f4eb48",
        "num" : 2,
        "version" : 0
    },
    "quorum" : {
        "19953931" : {
            "agree" : 4,
            "disagree" : 0,
            "fail_at" : 2,
            "hash" : "0b0c60",
            "missing" : 3,
            "phase" : "EXTERNALIZE"
        }
    },
    "state" : "Catching up",
    "status" : ["Catching up: Waiting for trigger ledger: 19953931/19953985, ETA: 270s"]
}

"ledger" : {
    "current" : {
        "age" : 1536781118,
        "baseFee" : 100,
        "baseReserve" : 100000000,
        "closeTime" : 0,
        "hash" : "39c2a3cd4141b2853e70d84601faa44744660334b48f3228e0309342e3f4eb48",
        "maxTxSetSize" : 100,
        "num" : 2,
        "version" : 0
    }
}

"configuration" : {
    "UNSAFE_QUORUM" : "UNSAFE QUORUM ALLOWED",
    "build" : "v10.0.0rc2-12-g81446c66-dirty",
    "network" : "Public Global Stellar Network ; September 2015",
    "protocol_version" : 10,
    "startedOn" : "2018-09-12T19:38:01Z",
}
```

**Comment by MonsieurNicolas** [comment]
I think Horizon needs all the information so we would have to keep the combined view as a default.

We can keep things to a minimum for now:
* replace the `history` node with `history_failure_rate`
* we can remove `UNSAFE_QUORUM` - this is already in the logs on startup and doesn't really add value

Together this saves already 14 lines out of 49, this is probably enough for now.

Other questions though:
* what does `history_failure_rate` map to?
* do we need new metrics? is `history_failure_rate` derived from those?
* additional logging maybe to help diagnose when things go wrong?

**Comment by fuzzyami** [comment]
Hey guys, while you're on the topic, I humbly suggest you reformat the 'quorum' section. At its current state, it does not lend itself to parsing and tracking over time. The key issue is this: you're using the ledger number as a key for the metrics:

`"quorum" : {
         "580645" : {
            "agree" : 8,`

it would be better to have the variable element (ie the ledger number) as a *value* and not as a *key*. it would facilitate easier tracking of this info in time-series dbs.

something like this would be btter, IMO:
"quorum" : {
            "ledger": "580645" ,
            "agree" : 8,

**Comment by MonsieurNicolas** [comment]
Hey @fuzzyami sorry I missed this comment.

The "quorum" section under "info" is using the same format than the "quorum" command.
While we could use an array (and have a "ledger" property for each item) instead of a map there, the issue with it is that then it comes much harder to read for humans as properties get sorted alphabetically.

One thing you can do for your use case is just run a command like
```
# stellar-core-cmd info | jq '.info.quorum[]'
{
  "validated": true,
  "phase": "EXTERNALIZE",
  "missing": 0,
  "hash": "75b44e",
  "fail_at": 2,
  "disagree": 0,
  "delayed": 2,
  "agree": 3
}
```

**Comment by fuzzyami** [comment]
Thanks for this workaround! I understand your point about preferring
human-readability but I still think that using a ledger-number as key to a
dictionary is an unfortunate design choice when it comes to metric
collection. perhaps there's a middle ground? anyways, thanks again!
