### ISSUE TITLE
Transactions Non-deterministically fails with 2 types of "400: tx_bad_seq"

### ISSUE THREAD

**Issue by cesarmak** [stellar/stellar-core#1793]
As I used a JS thread pool to send 100 tx requests (randomly drawn from a pool of 300 sec keys), 2 types of bad_seq error appeared. 

After multiple trials, it is more common with no tx fee charged: 
“AAAAAAAAAAD////7AAAAAA==”
feeCharged: 0 result: [txBadSeq]

Occasionally, it failed with: 
“AAAAAAAAAGT////7AAAAAA==”
`feeCharged: 100` result: [txBadSeq]

Each tx request contained only 1 Payment Operation of 1XLM to himself, so even if I accidentally picked the same sec key, it is expected to fail deterministically. 

As it was charged in the 2nd case, I am not sure if its effect was included into the ledger...

---

Encountered this some time ago and not yet resolved: https://stellar.stackexchange.com/questions/946/for-txbadseq-when-is-tx-fee-charged

**Comment by MonsieurNicolas** [comment]
This is a side effect of how Horizon caches and generates results for transactions. The main issue it seems is that you are not given context (you don't know if the result is from a ledger or not). I imagine that https://github.com/stellar/go/issues/309 should take care of that.

At the core layer the `tx` endpoint is to submit transactions, failures there mean that it was not even accepted by that core instance.

Now, why do we return some value for `feeCharged`?
The idea behind the result returned by the `tx` endpoint was to return the same result that you would get if the transaction was included in the transaction set (and as we look into changing certain things about fee this can be interesting data).

We could change core to set `feeCharged` to 0 when the result is returned in the context of the `tx` endpoint but we would be hiding a bug:
people would then assume that the transaction was not included in a ledger which is incorrect (the answer is "maybe"). For example, if you submit the same transaction twice (with a 1 minute pause in between), the `tx` endpoint will return a result of bad sequence number - if for some reason the layer above passes that down to the client with no other information, the client could think that the transaction never made it and should just be resubmitted with a different sequence number (and bad things will happen).

**Comment by MonsieurNicolas** [comment]
closing as this is not really a stellar-core issue
