### ISSUE TITLE
ensure that messages logged with level FATAL, ERROR, INFO and WARNING are user friendly

### ISSUE THREAD

**Issue by bartekn** [stellar/stellar-core#1796]
# Issue type
  feature request

# Version found
  * 10.0.0

# Issue description
 Many users that haven't upgraded their core to 10.0.0 are seeing some strange errors about catchup but instead core should check if the latest ledger supports the current protocol version and if not exit with the simple, user-friendly message like: "Your stellar-core does not support protocol version X. Please upgrade to the latest version."

**Comment by MonsieurNicolas** [comment]
This is already the case, as per https://github.com/stellar/stellar-core/issues/1506

We output various messages, things like:
> ERROR "Catchup material failed verification - Catchup material failed verification, propagating failure unsupported ledger version, propagating failure"
> ERROR "Unknown ledger version: 10"

Are those the "strange errors" you're talking about?

**Comment by bartekn** [comment]
Yes exactly, but I think to make it more user friendly it should include instructions to upgrade to the latest stellar-core version. "Unknown ledger version: 10" says nothing to beginners.

**Comment by MonsieurNicolas** [comment]
good point, I am turning this issue into a more generic one. It will cover this message and others

**Comment by MonsieurNicolas** [comment]
In some cases, it means we may have to split the message into two parts: one part that explains the problem and the second part that when possible, points to a remedy

**Comment by MonsieurNicolas** [comment]
We have many reports/complaints about overlay messages, so we should tackle that as well @vogel
