### ISSUE TITLE
Support HOCON format config file.

### ISSUE THREAD

**Issue by hepin1989** [stellar/stellar-core#1802]
I more like the HOCON one.

**Comment by MonsieurNicolas** [comment]
I don't think we'd change the format of configuration files at this point unless there is an extremely good reason to do so as it would be a breaking change to the ecosystem.

**Comment by hepin1989** [comment]
I can see, thanks. but maybe sometime later as an alterative?

**Comment by MonsieurNicolas** [comment]
probably not: supporting two systems just makes it more expensive to maintain (not just code, but also documentation, troubleshooting guides, etc)
