### ISSUE TITLE
./configure does not creates makefile

### ISSUE THREAD

**Issue by Vishwas1** [stellar/stellar-core#1805]
I am trying to setup Stellar core. After running the command `./configure` I am getting this error

 > "configure: error: Package requirements (libsodium) were not met:" 

which prevents 'makefile' to be generated.

Can you please tell me how to fix it? I think one way could be I can ignore `libsodium` from `configure` file but would it be good solution?

*I am using ubuntu 18.04 machine*

**Comment by Vishwas1** [comment]
To fix this issue I installed `libsodium` from [here](https://download.libsodium.org/libsodium/releases/) and re-run `./confiugre` command again -  this time that error is gone but now another error:
> configure: error: Package requirements (xdrpp) were not met:

Not able to understand what is happening here.

**Comment by MonsieurNicolas** [comment]
Hello.
can you actually give repro steps that you followed? (from a clean state)

could be that you forgot to initialize submodules

**Comment by ManUnit** [comment]
Helo
I doing this 
wget https://download.libsodium.org/libsodium/releases/libsodium-stable-2018-10-26.tar.gz
tar -zxvf lib*
cd libsodium-stable/   
sudo ./configure 
sudo make

**Comment by MonsieurNicolas** [comment]
you don't need to manually install libsodium, I was asking about steps to build stellar-core
