### ISSUE TITLE
Transaction included in the ledger after a couple minutes since submission

### ISSUE THREAD

**Issue by bartekn** [stellar/stellar-core#1811]
# Issue type
  bug

# Version found
  10.0.0

# Your environment and setup
  https://horizon.stellar.org - connected to v10.0.0 stellar-core node

# Issue description
This report is a result of a long investigation of the bug described here: https://github.com/stellar/go/issues/305. In short: transaction submission system in Horizon forwards transactions to `/tx` endpoint of stellar-core and starts monitoring `txhistory` to update transaction state and send a result to the user. If the transaction is not present in `txhistory` Horizon returns [`504 Gateway Timeout`](https://www.stellar.org/developers/horizon/reference/errors/timeout.html) error after 60 seconds (recently this has been shortened to 30 seconds). This can happen because stellar-core removes transactions that haven't been included in 3 consecutive ledgers (so 15 seconds on average).

However, there has been reports that after receiving `504` response from Horizon, transaction is included in the ledger after some time (sometimes a couple minutes). [Horizon v0.14.2](https://github.com/stellar/go/releases/tag/horizon-v0.14.2) included more log entries to help understanding what's going on but also a lot of bug fixes in Horizon's `txsub` package.

After some time, I received an information from @andrenarchy about a transaction submitted to horizon.stellar.org that returned `504` response but was included in the ledger after around 8 minutes! It's worth noting that logs indicate that this transaction has not been resubmitted at a later time. Here's a screenshot from our ElasticSearch cluster with Horizon logs (the only log entries connected to this transaction hash):

![screen shot 2018-10-19 at 13 34 18](https://user-images.githubusercontent.com/464938/47216005-bd11f200-d3a3-11e8-9e22-370522326b73.png)

Transaction was submitted at `October 17th 2018, 06:36:12.148 UTC` (Kibana displays my local time) and timeout response was sent 30 seconds later, at `October 17th 2018, 06:36:42.828 UTC`. But if you check [`7dab1f4476555ee8d8d047435ef3c1d54c916943b5c5d91bb80663805d9e4924`](https://horizon.stellar.org/transactions/7dab1f4476555ee8d8d047435ef3c1d54c916943b5c5d91bb80663805d9e4924) in Horizon you will see that it was included in the ledger at `2018-10-17T06:42:53Z` so after ~8 minutes.

So I think that either there's a bug and transactions are not removed from the queue or the actual behaviour of stellar-core is different that expected. One thing to note is that network was under a high load when it happened, for example, a [ledger](https://horizon.stellar.org/ledgers/20520115) with this transaction was almost full (49/50 txs).

## Actual result
Transaction included after ~8 minutes since submission.

## Expected result
Transaction removed from a queue and not included in the ledger, or included in one of 3 ledgers closed after submission time.

## Supporting files

Can provide links to internal Kibana instance to log entries connected to this issue.

**Comment by MonsieurNicolas** [comment]
This is by design:
when a transaction is submitted to the network it is forwarded to other validators (ie: it's now available to anybody in the world) and the only way to censor a transaction is to submit a different transaction with the same sequence number and _hope_ that the new transaction will be the one processed by the network.

If you want to guarantee that a transaction will be "dropped" from queues after a specific timeout, you have to use time bounds.

**Comment by bartekn** [comment]
> when a transaction is submitted to the network it is forwarded to other validators (ie: it's now available to anybody in the world) and the only way to censor a transaction is to submit a different transaction with the same sequence number and hope that the new transaction will be the one processed by the network.

I understand this, but let's assume that the transaction was not resubmitted. In this case, is it possible that transaction was included in the ledger 8 minutes later?

**Comment by bartekn** [comment]
OK, going to fix this in SDKs as discussed: transaction builders will require `timeout` parameter, that, when set, will add a `timebounds.max_time` to the transaction.

**Comment by MisterTicot** [comment]
Any option to consistently track non time limited transactions until they get included in the ledger or rejected?

**Comment by MisterTicot** [comment]
Nevermind, it is in the docs:

> Please note that Horizon may still return 504 Gateway Timeout error, even for short timeouts. In such case you need to resubmit the same transaction again without making any changes to receive a status.
