### ISSUE TITLE
Clarify relationship between KNOWN_PEERS, PREFERRED_PEERS, PREFERRED_PEER_KEYS

### ISSUE THREAD

**Issue by JonasPf** [stellar/stellar-core#1812]
The documentation is unclear (at least to me) on the relationship/differences between KNOWN_PEERS, PREFERRED_PEERS, PREFERRED_PEER_KEYS.

From https://www.stellar.org/developers/stellar-core/software/admin.html#quorum-and-overlay-network:

> It is generally a good idea to give information to your validator on other validators that you rely on. This is achieved by configuring KNOWN_PEERS and PREFERRED_PEERS with the addresses of your dependencies.
> Additionally, configuring PREFERRED_PEER_KEYS with the keys from your quorum set might be a good idea to give priority to the nodes that allows you to reach consensus.
> Without those settings, your validator depends on other nodes on the network to forward you the right messages, which is typically done as a best effort.

This is a bit unclear to me:

* Should I use KNOWN_PEERS or PREFERRED_PEERS? The docs mention both.
* What exactly constitutes a dependency?
* Why should I use PREFERRED_PEER_KEYS instead of PREFERRED_PEERS for quorum sets? Wouldn't PREFERRED_PEERS be better because it already contains ip:port so my node wouldn't need to resolve public key to ip:port?

I've also asked here and will update it with an answer as soon as I know: https://stellar.stackexchange.com/questions/1702/best-practices-for-stellar-core-settings-known-peers-preferred-peers-and-prefer

**Comment by theaeolianmachine** [comment]
Hey @JonasPf , I went ahead and [answered on Stack Exchange](https://stellar.stackexchange.com/questions/1702/best-practices-for-stellar-core-settings-known-peers-preferred-peers-and-prefer).

@MonsieurNicolas, can you close out this issue?
