### ISSUE TITLE
command `--c  /testacc?name=N` does not accept keys over `32` characters

### ISSUE THREAD

**Issue by benxage** [stellar/stellar-core#1813]
# Issue type
bug

# Version
v10.0.0

# Operating system
Darwin Kernel Version 17.7.0; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64; MacOS Bash

# Issue description
The command `--c  /testacc?name=N` does not accept valid keys over the length of `32` characters. For example `--c testacc?name=GBRPYHIL2CI3FNQ4BXLFMNDLFJUNPU2HY3ZMFSHONUCEOASW7QC7OX2H` gives 

```
Content-Length: 46
Content-Type: application/json

2018-10-23T11:30:13.524 GDZNI [default INFO] {"exception": "seed does not match byte size"}
```

Note `GBRPYHIL2CI3FNQ4BXLFMNDLFJUNPU2HY3ZMFSHONUCEOASW7QC7OX2H` is the public key of root account of the public test network. 

The only except to that is if the name given is `root`. i.e. `--c testacc?name=root`

Since all valid keys are of `56` characters, such query should not be rejected.

**Comment by MonsieurNicolas** [comment]
hello

this is by design: you're supposed to pass in a seed (any string less than 32 characters), not a public key.
