### ISSUE TITLE
add an option to manual catchup to wait for publish to complete

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1814]
Command line catchup can be used to setup full validators, when used this way we need to also wait for publish to complete.

note: there might be an edge case if the target ledger happens to be a snapshot, when working with SCP we wait for the next ledger to close, when this command line option is specified we should probably fail and require people to catchup to a non snapshot ledger (as the reason we wait is to make sure we don't have bad data)

**Comment by vogel** [comment]
This is not a problem - https://github.com/stellar/stellar-core/commit/ee5e06ef3656766f716d51b3c54f40c04df3e091

I think it would be better to add just new command --publish.
So the script could look like this:

stellar-core --catchup-complete --publish (both at once, not possible with new command line interface that will come soon)

stellar-core --catchup-complete (separate commands)
stellar-core --publish (that just waits until publishqueue is empty or has at most one item that is on current ledger boundary)

**Comment by andrenarchy** [comment]
Both at once would of course be preferable but it's not possible at the moment, right?

**Comment by vogel** [comment]
Implemented as new command in new-command-line interface.

So it would look like this:
```
stellar-core catchup 2000/100 --conf live.cfg
stellar-core publish --conf live.cfg
```
