### ISSUE TITLE
steller smart contract

### ISSUE THREAD

**Issue by VtpVlan-oo7** [stellar/stellar-core#1841]
hi folks
i am new in steller ,i am going to write smart contract of steller coin , so please suggest me which language i have to use and in which platform i'll have to deploy

its urgent please help me asap !!

**Comment by MonsieurNicolas** [comment]
# Before creating an issue
  * check the [documentation](https://www.stellar.org/developers/)
  * ask for help
    * There is a [Stellar Stack Exchange](https://stellar.stackexchange.com/)
    * For more general questions, discuss with [the community](https://www.stellar.org/community/) (Slack, forums, Reddit, ...)
  * check existing and closed issues (you may have to remove the `is:open` filter)
    * check that the version that you are running is newer than the one with the fix
    * re-open an old issue that is supposed to be fixed; be sure to include additional details

Issues opened here are to report actual problems with stellar-core; any other issues (general questions, issues unrelated to stellar-core) will be closed (sorry - we have only a small community of people that manage issues).
