### ISSUE TITLE
data access: pre-fetching of data

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1859]
This issue tracks investigating pre-fetching changes for various data sets

**Comment by marta-lokhova** [comment]
A few clarifications: This issue tracks simple synchronous prefetching for most common operations, implemented in #1988.  

https://github.com/stellar/stellar-core/issues/2031 explores more complex prefetching strategies (e.g., for best offer) and prefetching for the remaining operations.
