### ISSUE TITLE
Impossible to build stellar-core v10.1.0 on Ubuntu 16.04

### ISSUE THREAD

**Issue by gituser** [stellar/stellar-core#1873]
Because of the - https://github.com/stellar/stellar-core/commit/a967f2a8497656bd717ad68cb9c6210ebd36760e it's now impossible to build stellar-core `v10.1.0` without installing test toolchain and/or clang-5.0.

Ubuntu 16.04 doesn't have clang-5.0 nor does it have gcc-6, so there is no way to build stellar-core using stock Ubuntu 16.04 toolchain anymore - you need to mess up your system either with a test toolchain or install clang-5.0 manually into /usr/local.

1. Why do you want to use test software for building something stable?
2. Why break the compilation process for the stable version (version change is not major)?
3. Why not reflect this change in the release changelog (not only INSTALL.md)?
4. Also here https://github.com/stellar/stellar-core/blob/v10.1.0/INSTALL.md#basic-installation you give example "Type ./configure (If configure complains about compiler versions, try CXX=clang-5.0 ./configure or CXX=g++-5 ./configure or similar, depending on your compiler.)" g++-5 which doesn't work.

**Comment by gituser** [comment]
Let's say you've decided to install clang from LLVM website (they claim that they won't mess up your system):
```
# apt-get install clang-8
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 clang-8 : Depends: libllvm8 (>= 1:8~svn298832-1~) but it is not going to be installed
           Depends: libstdc++6 (>= 5.2) but 4.9.2-10+deb8u1 is to be installed
           Depends: libstdc++-5-dev but it is not installable
           Depends: libgcc-5-dev but it is not installable
           Depends: libobjc-5-dev but it is not installable
           Depends: libclang-common-8-dev (= 1:8~svn349288-1~exp1+0~20181216011550.1958~1.gbp22d924) but it is not going to be installed
           Depends: libclang1-8 (= 1:8~svn349288-1~exp1+0~20181216011550.1958~1.gbp22d924) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by MonsieurNicolas** [comment]
A couple things:
* clang-5.0 is available in 16.04, you don't need to manually install it from alternate sources
* it is doable to build on stock 16.04 with clang-5.0 ; I've already added some more details that were not super obvious as additional packages and options are required to build with libc++. See the updated install instructions in [1871](https://github.com/stellar/stellar-core/pull/1871)

**Comment by gituser** [comment]
@MonsieurNicolas there is no clang-5.0 in default Ubuntu 16.04.
Can you point me where you got it from?

**Comment by gituser** [comment]
Alright this helped, thanks. Can be closed.
