### ISSUE TITLE
building master branch fails: bucket/BucketManagerImpl.cpp:36:12:

### ISSUE THREAD

**Issue by sgehrman** [stellar/stellar-core#1889]
using clang 5.  Let me know if I did something wrong.  I'm on Linux.

bucket/BucketManagerImpl.cpp:36:12: error: no viable conversion from returned value of type 'unique_ptr<stellar::BucketManagerImpl, default_delete<stellar::BucketManagerImpl>>' to function return type 'unique_ptr<stellar::BucketManager, default_delete<stellar::BucketManager>>'
    return bucketManagerPtr;
           ^~~~~~~~~~~~~~~~

**Comment by MonsieurNicolas** [comment]
Please provide exact repro steps and versions of distro etc.

Easiest for build issue is to report steps using a container. For example, to start a container with stock Ubuntu Xenial:
```
docker run -it --name "build" ubuntu:xenial bash
```

**Comment by sgehrman** [comment]
I'm on Debian, everything is updated.  I was just building it to generate a seed for my node.  I normally use a Docker image for deployment.  Building prod branch works fine.  Just not master.   I'm surprised your not seeing it as I'm 100% sure I have everything up to date and there is nothing weird on my end as far as I know.

go version go1.11.2 linux/amd64

**Comment by MonsieurNicolas** [comment]
we build on multiple flavors of Linux, including the 4 years old Ubuntu 14.04 LTS; I recommend using prebuilt binaries if you're not sure how to help diagnose this (Debian packages are available https://github.com/stellar/packages ).

Without exact repro steps (which includes which versions of all packages installed on your system) it's hard for anybody to really help.

**Comment by sgehrman** [comment]
Found out I was using clang 3.8.  5.0 works now.  The build instructions are for Ubuntu, so it tripped me up a bit.
