### ISSUE TITLE
storestate not define

### ISSUE THREAD

**Issue by HowJMay** [stellar/stellar-core#1901]
I was building stellar-core in the past a few weeks. and I met a problem that I get the error "ERROR:  relation "storestate" does not exist"
I found in this page the doc said storestate is defined in ` src/main/PersistantState.cpp`, but I found it didn't. 
How could I do?

**Comment by MonsieurNicolas** [comment]
Hello, I am not sure what this bug report is about. I thought you were saying that the docs are not accurate, but https://github.com/stellar/stellar-core/blob/75a7904c6d29eaf4327fdae756e2ab753cbbab41/src/main/PersistentState.cpp#L21 is where the table is defined.
