### ISSUE TITLE
properly refresh peers configured by hostname in configuration file

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1908]
Right now peers specified in the configuration file (`KNOWN_PEERS` and `PREFERRED_PEERS`) have their IP resolved on startup.

Problem is that if the IP address of one of those peers changes, stellar-core won't notice until restarted.

A way to avoid this could be to periodically (every X minutes) resolve the hostnames and add the new IPs to the list of peers.

**Comment by vogel** [comment]
This should wait for #1911 to avoid conflicts.
