### ISSUE TITLE
migrating the db without starting stellar-core

### ISSUE THREAD

**Issue by gracenoah** [stellar/stellar-core#1912]
# Issue type
  feature

# Version found
  all

# Your environment and setup
  n/a

# Issue description
There's no mechanism to migrate the database without starting stellar-core.  I need to do the migrations with a different user from the user that stellar-core uses normally. Database upgrades happen in only 2 places: when you wipe the database and on startup:
* https://github.com/stellar/stellar-core/blob/51295ad8029f05e47ab0d879d7acd65e0293c2da/src/main/ApplicationImpl.cpp#L146
* https://github.com/stellar/stellar-core/blob/51295ad8029f05e47ab0d879d7acd65e0293c2da/src/main/ApplicationImpl.cpp#L321

For now the best workaround seems to be to set THRESHOLD_PERCENT in QUORUM_SET to a very large number and make stellar core crash on startup after doing the migration. Another strategy is to somehow read stellar's logs, waiting for it to finish starting and then kill it. I would really prefer to just have a command that lets me run the migrations by themselves.

## Actual result
Stellar core has to start in order to migrate the database.

## Expected result
I should be able to migrate the database independently of starting stellar core

**Comment by MonsieurNicolas** [comment]
yeah that seems ok.

In addition to performing any database schema upgrade, I would like to have a way to run database maintenance on the command line as it's potentially time consuming (and suffers from the same problem).

**Comment by gracenoah** [comment]
One more thing to add: I think it would also be useful to be able to make stellar core fail on startup if it hasn't been migrated. This behaviour should probably be configurable for backwards compatibility. That way stellar core and horizon can be operated the same way.

For horizon you can use

(horizon db init || horizon db migrate up) && horizon serve

which would be equivalent to the current behaviour of stellar core.

With the proposed change, stellar core would support a similar set of commands, but with `init` happening automatically during `migrate up`.
