### ISSUE TITLE
unfair scheduling/processing of items on the ioservice queue

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1937]
It looks like there is a problem in how we process/queue events from the IO Service queue.

A node was constantly getting out of sync, and a first analysis of the logs shows that:
* the node is well behind compared to the network
* the node has a large backlog of SCP messages being downloaded
* the node was applying buckets

Full log can be found https://gist.github.com/MonsieurNicolas/69d1548a131f643c490f0b18786c2511

Why are we not processing that backlog? Is it that we're only executing so many messages at once before calling expensive (apply bucket) work, causing a throttling of IOService?

**Comment by graydon** [comment]
We've done a _lot_ of work on this since it was filed, including adding the action queue, load shedding, flow control at the overlay level, time slicing in bucket apply, etc.

I think it's "fixed enough" to close, but we can reopen if we find a new specific scenario causing trouble.
