### ISSUE TITLE
PaymentOpFrame cannot handle PATH_PAYMENT_MALFORMED result

### ISSUE THREAD

**Issue by jonjove** [stellar/stellar-core#1949]
`PathPaymentOpFrame::doApply` can produce the operation result `PATH_PAYMENT_MALFORMED` but `PaymentOpFrame::doApply` does not handle this result. This leads to `txINTERNAL_ERROR`, instead of producing the corresponding operation result `PAYMENT_MALFORMED`. Two options to fix this:
- Don't return `PATH_PAYMENT_MALFORMED` during apply, returning more specific results instead that `PaymentOpFrame` can handle
- Handle `PATH_PAYMENT_MALFORMED` in `PaymentOpFrame`

**Comment by MonsieurNicolas** [comment]
I see, I just looked and `PATH_PAYMENT_MALFORMED` is just wrong (MALFORMED is normally used to mean "bad arguments"), but here it returns that in other cases (not sure I understand when those actually happen as it's in the NATIVE case, is it liabilities related?)

**Comment by jonjove** [comment]
I see two places in `PathPaymentOpFrame::doApply` that can return `PATH_PAYMENT_MALFORMED`.

https://github.com/stellar/stellar-core/blob/48334657d06d1081ea15d0e432bb1f220470dd94/src/transactions/PathPaymentOpFrame.cpp#L78-L86

This return code was already there as of (at least) v9.0.0. But I think this was intended to be an unexpected error condition at that time, along the lines of how we use `txINTERNAL_ERROR` now. Since the introduction of liabilities, this case can occur (imagine the account owns an offer trying to buy a huge amount of native asset). I think we can make this return `PATH_PAYMENT_LINE_FULL` starting in version 11, which `PaymentOpFrame::doApply` is able to handle.

https://github.com/stellar/stellar-core/blob/48334657d06d1081ea15d0e432bb1f220470dd94/src/transactions/PathPaymentOpFrame.cpp#L202-L210

Correct me if I'm wrong, but I don't think this should be reachable in the current protocol version. `OperationFrame::checkValid` checks the existence of the source account and returns `opNO_ACCOUNT` if it does not exist, and it always executes before `OperationFrame::doApply`. Should we do anything for this case?

**Comment by MonsieurNicolas** [comment]
cool, yes both make sense (return line full when dealing with liabilities) and for the second one, I don't think there is anything to do as it's probably unreachable code now.
