### ISSUE TITLE
catchup: applying transactions should be done in the same work unit than downloading

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1951]
I noticed that we download a *lot* of checkpoint files when catching up, and those add up to GBs of data.

We should change the "unit" of work to follow a similar pattern than what we're doing to apply buckets, unit should be something like:
{ download tx file, verify tx file, {wait for the right ledger}, apply tx file, delete tx file }

That way we throttle how many checkpoints are in flight (limited by number of concurrent jobs that can exist at the same time).

#1747 would benefit also from that.

**Comment by marta-lokhova** [comment]
Note that WorkSequence would be useful here
