### ISSUE TITLE
stellar-core ignores SIGINT during tests on MacOS

### ISSUE THREAD

**Issue by jonjove** [stellar/stellar-core#1954]

**Comment by MonsieurNicolas** [comment]
when running tests we could just intercept the signal handler and invoke something like `exit(0)` maybe? From what I remember several systems (asio, catch, easylogging) are fighting for the handler

**Comment by jonjove** [comment]
I think that should work. To the best of my knowledge, only asio registers a handler; I think we use compile time flags to stop catch and easylogging from registering their handlers.
