### ISSUE TITLE
exclude "really dead" peers from peers that we connect to

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1962]
We should rethink a bit what to do with peers that are "probably dead".

Right now we keep trying to connect to peers forever.

What we should probably do is introduce a cuttoff for the number of failures, something like 120 (which would in average take about a week to reach given how we compute backoff).

When this cutoff is reached we should consider the peer "dead":
* do not try to connect to this peer (regardless of reason)
* do not forward this peer to other peers

Reason we need to do it like this (instead of deleting), is that this avoids resurrecting peers that are bad. We may want to add a "purge dead peers" command at some point, but it doesn't seem necessary yet.

**Comment by vogel** [comment]
Currently we do not forward peers that have more than 10 failures, but we connect without considering that value. Should I also change the "send peer" to use value of 120 or keep it as it is now?

**Comment by MonsieurNicolas** [comment]
this is fine, I am opening a couple more issues
