### ISSUE TITLE
build error in centos7

### ISSUE THREAD

**Issue by hhtlxhhxy** [stellar/stellar-core#1968]
# Issue type
  build error

# Your environment and setup
  * CentOS Linux release 7.5.1804 (Core)

# Issue description
 when I run make, it have a error as below:

> /opt/rh/devtoolset-6/root/usr/libexec/gcc/x86_64-redhat-linux/6.3.1/ld: ../lib/libsoci.a(session.o): undefined reference to symbol 'PQexec'
//lib64/libpq.so.5: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[3]: *** [stellar-core] Error 1
make[3]: Leaving directory `/home/hehaitao/stellar-core/src'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/hehaitao/stellar-core/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/hehaitao/stellar-core'
make: *** [all] Error 2

I have installed the libpq, like:

> Installed Packages
Name        : libpqxx-devel
Arch        : x86_64
Epoch       : 1
Version     : 4.0.1
Release     : 1.el7
Size        : 327 k
Repo        : installed
From repo   : epel
Summary     : Development tools for libpqxx
URL         : http://pqxx.org/
License     : BSD
Description : Development tools for libpqxx.

**Comment by QbiX90** [comment]
Hello.

Seems like you missing PostgreSQL.
Please provide Output of "httpd -M" and "find . / -name libpq"

Maybe try
yum: **postgresql-libs**.x86_64 : The shared libraries required for any PostgreSQL clients
