### ISSUE TITLE
Automatically purge database from bad peers 

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#1989]
First part of the change (1962) was to stop doing anything with peers when we've reached a certain number of consecutive failures.

Next step is to actually delete them from the database.

**Comment by MonsieurNicolas** [comment]
I wonder if we can just delete them as soon as we reach 120 (or whatever our threshold is) is met as we stop forwarding those peers anyways after 10 failures.

**Comment by vogel** [comment]
The value will never go over 120 (well, as long as nobody uses HTTP connect command), as to backoff we must first try to connect to peer. Connecting is done only in `OverlayManagerImpl::tick`, which uses `OverlayManagerImpl::getPeersToConnectTo` which gets list of peers from `mPeerSources`, that has limit `REALLY_DEAD_NUM_FAILURES_CUTOFF`.

So we can delete peers as soon as those get to that number.

I'm just not sure if we should merge that into 11.0 or wait until next version (to ensure all other nodes upgraded to 10.3 and won't send us more bad peers).
