### ISSUE TITLE
LedgerTxnOfferSQL.cpp References legacy column name - buyingasset.  Possible DB upgrade failure

### ISSUE THREAD

**Issue by ethode** [stellar/stellar-core#2022]
# Issue type
  bug

# Version found
  * HEAD: e621584d490a75b6726efdb7433be482f129bdb0
  * Stellar version: v10.2.0-68-ge621584

# Your environment and setup
  * Ubuntu 18.04
  * Yes, no container
  * No

# Issue description
 * LedgerTxnOfferSQL.cpp created a table (offers) that have column names which have changed over time.  Some queries in this file have updated with that change and some have not.  For instance, 'buyingasset' is referenced as a SELECT column but the new name is buyingassettype.  Some of the SELECT queries use the new column name, some do not.

After looking at other issues, I believe this is tied into issue (https://github.com/stellar/stellar-core/issues/1791) where an upgrade failure has occurred.  The DB Schema version I have is 9, so referencing the simplified column names is expected, however, the DB schema has not been updated to match the simplified version.

## Actual result
 * Query fails

## Expected result
 * Query runs

## Supporting files
Error was originally caught looking at horizon data, see below.

ERRO[2019-03-25T19:03:30.735-05:00] select failed: pq: column "buyingasset" does not exist  pid=13614 req=<removed for security>/KCX494CNaV-000974 stack="[main.go:43 session.go:262 session.go:235 offer.go:59 offer.go:35 search.go:168 search.go:162 search.go:117 finder.go:50 actions_path.go:48 actions_path.go:27 base.go:186 actions_path.go:24 base.go:57 main_generated.go:94 web.go:148 server.go:1947 mux.go:418 mux.go:354 server.go:1947 cors.go:190 server.go:1947 compress.go:66 server.go:1947 middleware.go:160 server.go:1947 middleware.go:171 timer.go:212 middleware.go:170 server.go:1947 middleware.go:73 server.go:1947]"
INFO[2019-03-25T19:03:30.736-05:00] Finished request                              bytes=470 client_name=js-stellar-sdk client_version=0.14.0 duration=0.002671498 forwarded_ip= host="horizon1.<removed>.com:8000" ip=<removed> ip_port="<removed>:64542" method=GET path="/paths?destination_account=GAQVMAA5BJTI3UT3BCWFC35IHSYUDVXFXRTLP4ILGGFRNU6L3DBYP5BS&source_account=GCZ4L3MYJPVG7PNPZQ3YWUZV5IRJUIZZRZRYOTPU76CD5D33CBT2Y6OX&destination_amount=20111&destination_asset_type=native&c=0.6834684872162107" pid=13614 req=<removed>/KCX494CNaV-000974 route=/paths status=500 streaming=false

**Comment by MonsieurNicolas** [comment]
database schema upgrades only work between major releases, if you're using an arbitrary commit off master you will have to reset your database.
Recommendation in general is to *not* run anything other than a dev environment from master

**Comment by ethode** [comment]
@MonsieurNicolas I am running a testnet off of master branch currently.  Is, is there a different branch that a testnet should be using?

**Comment by ethode** [comment]
Sorry, I guess the other question would be, in the event that there is an upgrade failure, do we have any command line options to force a new attempt to upgrade to the correct version?

**Comment by MonsieurNicolas** [comment]
Latest release is what you want to run in general, testnet branch if you want to track testnet
https://github.com/stellar/stellar-core/blob/master/INSTALL.md#picking-a-version-to-run

just run new-db and rejoin the network, testnet has very little data

**Comment by ethode** [comment]
@MonsieurNicolas I am still tracking down this odd upgrade behavior.

I just DROP'ed the offers table and manually created using the version 9 schema, the latest.  When I do --newdb, I can see it DROPs the table and recreates it using a schema version below 9 because offers is no longer using the simplified version which was implemented in the version 9 upgrade.

However, you can see in this screenshot, after --newdb that it does in fact state that it was updated to the version 9, when in fact it hasn't.

![image](https://user-images.githubusercontent.com/146134/55269574-7f2acb00-526b-11e9-9cb1-59cc55095f0d.png)

You can see here, immediately after the --newdb command the schema in postgres does not reflect the correct schema.

![image](https://user-images.githubusercontent.com/146134/55269610-c1540c80-526b-11e9-9858-35b38f03c097.png)

**Comment by MonsieurNicolas** [comment]
check that you're actually running the proper version
```
#  /usr/bin/stellar-core version
stellar-core 10.3.0 (de204d718a4603fba2c36d79a7cccad415dd1597)
```

**Comment by ethode** [comment]
I think we can close this.  After moving to the 10.3.0 version still had issues with /usr/bin/stellar-core not being replaced.  Wound up doing a make uninstall and removing everything, and went with pre-built binaries in APT, re-applied my configs and was able to see 10.3.0 instead of 10.2.0.  After doing a "new-db" I did indeed see the expected database architecture and the query issues with v0.17 of horizon went away with proper schema.

Thanks @MonsieurNicolas

**Comment by vogel** [comment]
Closing then.
