### ISSUE TITLE
Stellar-Core & Stellar-Horizon Block size mismatch

### ISSUE THREAD

**Issue by EminBudak** [stellar/stellar-core#2032]
My stellar-core "state" : "Synced!" and block size 23231136

But horizon returns block size 23218546

**When I try to run horizon with --ingest it returns**

`
INFO[2019-04-02T22:12:48.259+02:00] Ingesting ledgers... first_ledger=23218547 last_ledger=23231189 pid=13100 service=ingest

ERRO[2019-04-02T22:12:48.260+02:00] Error ingesting ledgers err="Gap detected in stellar-core database. Please recreate Horizon DB." first_ledger=23218547 last_ledger=23231189 pid=13100 service=ingest

INFO[2019-04-02T22:12:49.260+02:00] Ingesting ledgers... first_ledger=23218547 last_ledger=23231189 pid=13100 service=ingest

ERRO[2019-04-02T22:12:49.260+02:00] Error ingesting ledgers err="Gap detected in stellar-core database. Please recreate Horizon DB." first_ledger=23218547 last_ledger=23231189 pid=13100 service=ingest
`

**When I try to run command stellar-horizon-cmd db reingest it returns**

`
INFO[2019-04-02T22:08:45.207+02:00] reingest: all end=21539071 pid=12721 service=ingest start=23218546

INFO[2019-04-02T22:08:45.209+02:00] ingest: range complete end=21539071 err="Gap detected in stellar-core database. Please recreate Horizon DB." ingested=0 pid=12721 service=ingest start=23218546

INFO[2019-04-02T22:08:45.209+02:00] reingest: complete count=0 means="load: 0s clear: 0s ingest: 0s" pid=12721 rate=0

2019/04/02 22:08:45 Gap detected in stellar-core database. Please recreate Horizon DB.
`

**How can I fix this problem?**

**Comment by MonsieurNicolas** [comment]
Hello, issues here are used to track actual issues.

# Before creating an issue
  * check the [documentation](https://www.stellar.org/developers/)
  * ask for help
    * There is a [Stellar Stack Exchange](https://stellar.stackexchange.com/)
    * For more general questions, discuss with [the community](https://www.stellar.org/community/) (Slack, forums, Reddit, ...)
  * check existing and closed issues (you may have to remove the `is:open` filter)
    * check that the version that you are running is newer than the one with the fix
    * re-open an old issue that is supposed to be fixed; be sure to include additional details

Issues opened here are to report actual problems with stellar-core; any other issues (general questions, issues unrelated to stellar-core) will be closed (sorry - we have only a small community of people that manage issues).
