### ISSUE TITLE
Testnet is down

### ISSUE THREAD

**Issue by Varunram** [stellar/stellar-core#2065]
It looks like the upgrade that was planned for today has failed and the blockchain has stalled at various blocks for the past 2-3 hours. Starting this thread to compile what went wrong so devs can reference this issue for fixes.

**Comment by MonsieurNicolas** [comment]
it was an operational problem, not a code issue

**Comment by Varunram** [comment]
@MonsieurNicolas thanks for clarifying that it was an operational problem, was afraid there was something in the code that cause this.
