### ISSUE TITLE
bug/regression: Cannot set global log level using ll http command 

### ISSUE THREAD

**Issue by nebolsin** [stellar/stellar-core#2115]
# Issue type
  Regression bug

# Version found

```console
$ stellar-core version
 stellar-core 11.1.0 (324c1bd61b0e9bada63e0d696d799421b00a7950)
```

I think regression was introduced in #2083.

# Your environment and setup

```
$ uname -a
 Linux astrograph 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ apt-cache show stellar-core | head -3
 Package: stellar-core
 Architecture: amd64
 Version: 11.1.0-23
```
But the bug is probably global and affects all environments.

# Issue description

An attempt to set the global loglevel using `ll` command (as [documented](https://github.com/stellar/stellar-core/blob/master/docs/software/commands.md#http-commands)) results in `not a valid partition` error.

## Actual result

Command result in an error and new global log level is not applied.

```console
$ stellar-core version
 stellar-core 11.1.0 (324c1bd61b0e9bada63e0d696d799421b00a7950)

$ stellar-core-cmd 'll?level=INFO'
 {"exception": "not a valid partition"}
```

## Expected result

Global loglevel changes successfully, like it was in `11.0.0` and below:

```console
$ stellar-core version
 stellar-core 11.0.0 (236f831521b6724c0ae63906416faa997ef27e19)

$ stellar-core-cmd 'll?level=INFO'
 {
    "Global" : "Info"
 }
```

**Comment by MonsieurNicolas** [comment]
good catch, as a workaround you can change the log level using the command line (using `--ll` option)
