### ISSUE TITLE
Improve docs on adding 'self' node to the quorum and implicit adding of 'self'

### ISSUE THREAD

**Issue by pitsevich** [stellar/stellar-core#2120]
# Issue type
Documentation

# Issue description

Several times a conversation on validators channel mentioned the implication of adding a self node to the quorum set, or whether the 'self' node is already added implicitly to the quorum set. 

The documentation does not mention this, and it should be improved, since it's fairly common question.
Looks like there's an implicit quorum set being formed in the background, which ensures your node agrees with the chosen quorum set, otherwise it won't validate.

Would be nice to answer the questions and include the information mentioned in the conversations below.

## Supporting files

glebp
@andrenarchy We currently have only sdf in our q'set. 51% threshold -  2 out of 3 (sdf1, sdf2, sdf3)

andrenarchy
right, but your own node is always added implicitly
is that correct? @monsieurnicolas

marcinx
That's a very good question. I was recently wondering the same.

--------------------------

like, in the above version there's only an additional implicit requirement that says "self" must be included

jed
What it really does is it makes another level above everything you put in your qset with 100% threshold and puts self in that top level.

--------------------------

jed
```
[QUORUM_SET]
THRESHOLD_PERCENT=100
VALIDATORS=[
"$self"
]

[QUORUM_SET.stellar-core_cfg]
#Whatever you put in your qset in the .cfg
```

This is what it always does ^
so you and your qset always have to agree

**Comment by MonsieurNicolas** [comment]
This is now obsolete: automatic quorum configuration does that for you
