### ISSUE TITLE
Missing bucket recovery when user deletes bucket dir has bad diagnostic & recovery

### ISSUE THREAD

**Issue by graydon** [stellar/stellar-core#2123]
I've seen this happen multiple times with operators:

  - Using a container or some config that fails to mount BUCKET_DIR persistently (esp. during execution of new-db, which isn't especially obvious about the fact that it writes to BUCKET_DIR)
  - Or just deleting BUCKET_DIR because operator thinks it's transient
  - Node tries to start up, sees missing buckets
  - Last-gasp repair attempt tries to contact history to get missing buckets
  - User gets the impression history is damaged because it's trying to fetch a bucket that wasn't (and never should have been) published.
  - User wastes time trying to figure out what's wrong with the network, history archives, get commands, etc. etc. rather than being directed to correct diagnosis of the problem as "wrong lifetime of BUCKET_DIR"

I'm not entirely sure the right approach to issuing better diagnostics here would be. Maybe we can add a few special cases to the bucket-repair code. Like if the bucket dir is _empty_ that's a pretty clear sign that there's misconfiguration. Similarly if a large fraction of the bucket list is missing (say we have the genesis bucket but nothing else). Or perhaps it's possible to work out in reverse when a bucket shouldn't actually exist in a history archive (because it's not the input-to, shadow-of or output-of a checkpoint state) and avoid fetching it? Idk. This happens a lot though and current diagnostic story is bad and frustrating.

**Comment by MonsieurNicolas** [comment]
Maybe this code (download missing buckets) should be removed? I mean the chances of being on a snapshot (where this would work) is low (as in 1/64 = 1.5%).

**Comment by graydon** [comment]
This is happening more often than is likely due to operator error. I suspect we've got a bug where we're deleting unreferenced buckets too eagerly in exception cases, eg. when failing to connect to SQL.

I put some manual recovery instructions in another bug (here: https://github.com/stellar/stellar-core/issues/1395#issuecomment-511580240) but this needs to (a) stop happening altogether and (b) probably gain a new automatic recovery mode. Nobody should ever have to do those manual-recovery steps.

**Comment by MonsieurNicolas** [comment]
So we need 2 issues then: one that tracks stopping to try to download missing buckets and the other that tracks the investigation so that we stop getting into that state in the first place. Right @graydon ?

**Comment by graydon** [comment]
Opened #2202 and #2203 for fixes, having determined (I think) the root cause. Keeping this one open for "stopping trying to download missing buckets" since that's really the nature of the "bad diagnostic" here.
