### ISSUE TITLE
Not a bug but a question on the project

### ISSUE THREAD

**Issue by ytrezq** [stellar/stellar-core#2132]
[It’s sayed balances are already deduced but where ? I mean which file and which line ?](https://github.com/stellar/stellar-core/blob/master/src/transactions/TransactionFrame.cpp#L389)

**Comment by MonsieurNicolas** [comment]
try KeyBase

**Comment by ytrezq** [comment]
@MonsieurNicolas KeyBase ?? es‑ce que c’est un fichier ?

**Comment by theaeolianmachine** [comment]
@ytrezq please take the time to read the Issue Template; in general this issues repository is not a good forum for questions. You can find links to our Keybase along with other sites in the template: https://github.com/stellar/stellar-core/blob/master/.github/ISSUE_TEMPLATE.md
