### ISSUE TITLE
Merge HerderImpl::getJsonTransitiveQuorumIntersectionInfo and writeQuorumGraph

### ISSUE THREAD

**Issue by graydon** [stellar/stellar-core#2138]
These two functions are mostly doing the same thing. Should use the same codepath.

**Comment by graydon** [comment]
I actually think this bug was filed in the middle of PR review (it comes from this comment: https://github.com/stellar/stellar-core/pull/2127#discussion_r292220046) when we didn't know if the QI checker was going to be workable / useful and we were still possibly thinking we might be able to revive / leverage the infrastructure in the (old, not very useful) inferred-quorum path.

Since then (nearly 2 years) the QI checker has matured to be a key subsystem and the interred-quorum path has continued to sit I think entirely unused. I vote to change this bug to "remove InferredQuorum.{cpp,h} InferredQuorumUtils.{h,cpp} and everything that uses it as dead code that just confuses people / is a pointless maintenance burden".

What do you think @MonsieurNicolas ?

**Comment by MonsieurNicolas** [comment]
I like deleting code :) So yeah!
