### ISSUE TITLE
maxFee can be negative but is cast as unsigned in validation (Version: v11.1.0)

### ISSUE THREAD

**Issue by coinsquareMike** [stellar/stellar-core#2145]
## Issue Description

It is assumed that the fee to be paid for a transaction (which will be `feePaid` or `feeCharged` on-chain) must be below the fee the user is willing to pay (specified as `maxFee`, or just `fee`). Since a transaction can have a negative `maxFee`, when cast as an unsigned integer, validation can pass. This results in on-chain transactions where the fee paid was higher than was the user, however erroneously, defined as their max.

## Steps to Reproduce

Example
[https://stellarscan.io/transaction/7cf06b94575aa6e87112fbd58fea751a3c27f30e5fbe2ae47192c79d0a56bc07](https://stellarscan.io/transaction/7cf06b94575aa6e87112fbd58fea751a3c27f30e5fbe2ae47192c79d0a56bc07)

## Expected Result
Constructed transactions with negative `maxFee` should be considered invalid due to negative fees not being positive, or because the fee to be paid is greater than the `maxFee` when both remain unsigned.

## Actual Result
Transaction is considered valid, despite not looking like it should be.

**Comment by MonsieurNicolas** [comment]
Sorry, what is `maxFee` ? `fee` is `uint32` and cannot be negative.

The xdr for a transaction is this:
https://github.com/stellar/stellar-core/blob/ef3b08af9b16abf9909cd86dcf5d896e2d6a6dad/src/xdr/Stellar-transaction.x#L340

```
struct Transaction
{
    // account used to run the transaction
    AccountID sourceAccount;

    // the fee the sourceAccount will pay
    uint32 fee;

    // sequence number to consume in the account
    SequenceNumber seqNum;
    // ...
}
```

**Comment by MonsieurNicolas** [comment]
reopen if this is a valid bug
