### ISSUE TITLE
stellar-core's invocation of curl needs the parent directories to be created (Version: v11.1.0)

### ISSUE THREAD

**Issue by canselcik** [stellar/stellar-core#2148]
## Issue Description

While catching up, `stellar-core` invokes curl to do the download. However `stellar-core` hasn't created the directories to which it wants to download these files.

## Steps to Reproduce
Able to reproduce this with even the quickstart image.

## Expected Result
For those directories to be created ahead of time by stellar-core so that curl invocations don't fail.

## Actual Result
Those directories didn't exist and the following output was generated:

```
process 853 exited 22: curl -sf http://history.stellar.org/prd/core-live/core_live_001/history/01/6f/6a/history-016f6abf.json -o buckets/tmp/history-000b5e9dfba9888f/stellar-history.json
```

Since the files weren't downloaded due to this issue, the following `cp`s fail as well.
```
May 28th 2019, 18:46:16.626    cp: cannot stat '/opt/stellar/history-cache/ledger/00/00/00/ledger-0000007f.xdr.gz': No such file or directory    
```

```
May 28th 2019, 18:46:16.626    2019-05-29T01:46:16.374 GCEBT [Process WARNING] process 313 exited 1: cp /opt/stellar/history-cache/ledger/00/00/00/ledger-0000007f.xdr.gz buckets/tmp/catchup-a8bbb37367fc695f/ledger/00/00/00/ledger-0000007f.xdr.gz.tmp    
```

```
May 28th 2019, 18:46:16.626    2019-05-29T01:46:16.374 GCEBT [Process WARNING] process 314 exited 1: cp /opt/stellar/history-cache/ledger/00/00/00/ledger-000000bf.xdr.gz buckets/tmp/catchup-a8bbb37367fc695f/ledger/00/00/00/ledger-000000bf.xdr.gz.tmp
```

Also worth noting that the exit code of curl isn't checked here because if it had been, `cp` wouldn't have been attempted.

Additionally curl actually has a `--create-dirs` parameter however it didn't work fully with that either. It fixed the issue with the directory creation but the resource now was not available on the server.

## Your Environment and Setup
The quickstart docker image -- happens on both networks.

### stellar-core Version
Happens on various versions including v11.1.0.

## Additional Comments

Certainly seems related to this https://github.com/stellar/stellar-core/pull/1679.

**Comment by MonsieurNicolas** [comment]
can you provide actual repro steps to follow?

**Comment by canselcik** [comment]
@MonsieurNicolas Nothing out of the ordinary really. I'm experiencing the issue with the image from https://hub.docker.com/r/stellar/quickstart/dockerfile.

With and without `CATCHUP_COMPLETE=true`.

**Comment by MonsieurNicolas** [comment]
Most people are not seeing this particular problem so I think it would be useful to include not just the exact steps you're following (step by step commands that you're running would be great!) but also information on the host OS (including versions of docker that give some clues about what you're seeing)

**Comment by MonsieurNicolas** [comment]
closing for now; feel free to reopen with exact repro steps to take so that people can investigate this further
