### ISSUE TITLE
Refactor TransactionFrame to be immutable

### ISSUE THREAD

**Issue by jonjove** [stellar/stellar-core#2163]
`TransactionFrame` and `TxSetFrame` have interfaces that do not satisfy the criteria of "easy to use correctly and hard to use incorrectly". Specifically, these classes would be much more intuitive if they were immutable.

**Comment by MonsieurNicolas** [comment]
Work on `TxSetFrame` was done.

Work on `TransactionFrame???` is left.
There might be more to it than just `TransactionResult` -> easiest might be to move everything mutable into a `TxResultContext` object (that contains `TransactionResult` and also things like `mCachedAccount`).
