### ISSUE TITLE
README too sparse, consider adding information

### ISSUE THREAD

**Issue by ghost** [stellar/stellar-core#2171]
I tried to quickly build from source, following the README, but failed (needed to follow several links)

## Expected

README contains some short intro, a "build from source", pointers to further information (manuals, user-resources, dev-resources, ...)

## Possible Solutions

* Add a basic "build from source" example (e.g. pick ubuntu 18.04 LTS as example)
  * link to "Further Build Examples" (or similiar) document

Add the usual basic info to the readme, linking to "more info" documents. Minimum: a link to docs, or a simple "Further Documentation" link overview.

**Comment by theaeolianmachine** [comment]
Given that the installation instructions (`INSTALL.md`) are at the top level and referenced by the README, much like other projects, could you explain what feels insufficient for getting started? It feels like you want more information in the README proper, but I think the direction to each of the main docs feels clean, but also sufficient.

Perhaps you could show the exact workflow you went through and explain what was convoluted or difficult?

**Comment by lazaridiscom** [comment]
> referenced by the README, much like other projects

Nah, your README looks a bit unconventional...

> Perhaps you could show the exact workflow

Nothing special, followed the link to Install.md and got dizzy (from the different version etc.)

Expected (if not within the README, then at least in INSTALL.md)

Everything is there for the OS, copy&paste-able

## Build from Source

### Fetch Code

```bash
git clone https://github.com/stellar/stellar-core.git
cd stellar-core
git submodule init
git submodule update
```

### Ubuntu 18.04

#### Prerequisites

```bash
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install git build-essential pkg-config autoconf automake libtool bison flex libpq-dev parallel pandoc gcc-6 g++-6 cpp-6
```

#### Build, Test, Install
```bash
./autogen.sh
# on error, try `CXX=clang-5.0 ./configure` or `CXX=g++-6 ./configure`, depending on compiler
./configure
# or make -j (for aggressive parallel build)
make
make check
make install
```

#### Quick Run

[...]

**Comment by graydon** [comment]
INSTALL.md has this sort of stuff now.
