### ISSUE TITLE
Simulate mode is a little too willing to write to a live archive

### ISSUE THREAD

**Issue by graydon** [stellar/stellar-core#2196]
I ran simulation mode on what I wanted to be "real input data" so used the config file I typically use to run a test listener node. Unfortunately that listener config is also configured to write to a test history archive. Since simulation mode runs over a "real" ledger-number range but replays "not the real ledger history" (re-batching the real history at a different granularity) this means it wrote a bunch of simulation junk to a live ledger range in my test history archive.

No serious harm done -- it's a test archive, I can rebuild it -- but it seems like a relatively easy error to make, given the proximity we expect between "real" and "simulated" configs. Might be nice to make the default behaviour exit with an error if the user runs simulate with a writable history archive (perhaps overridable with a no-really-I-want-to-write-faux-history flag like `--write-simulated-history-to-archives` flag or such)

**Comment by MonsieurNicolas** [comment]
Maybe we could solve that in a more general way: archives should contain the network passphrase somewhere (I've had close calls in the past switching between test and prod configs), and we should ensure that it matches whatever we're doing.
Simulation mode would add `* simulation` to the passphrase. The plan is to not actually keep the original transactions (and their signatures) from the transaction stream during a simulation and instead only used "derived accounts".
