### ISSUE TITLE
CXXABI_1.3.11 and GLIBC_2.25 not found

### ISSUE THREAD

**Issue by ianeinser** [stellar/stellar-core#2197]
Hi,

i create a script to download stellar from source and try to compile it. I follow all instructions in Stellar github but when i run it as a container i got these reports:

stellar-core: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by stellar-core)
stellar-core: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by stellar-core)

i use gcc-7, g++-7 and cpp-7 as well as clang6.0. this is part of the script

if [ $BUILD_FROM_SRC == 1 ]
then
  # deploy stellar-core binary
    git clone --depth 1 --branch ${STELLAR_CORE_TAG} https://github.com/stellar/stellar-core /stellar-core \
    && cd /stellar-core \
    && git submodule init \
    && git submodule update \
    && ./autogen.sh \
    && ./configure \
    && make -j2 \
    && make install
  cd ..
  echo -e "\n${GREEN}Finish installing stellar-core from source...${NC}\n"
else

and these are the dependencies

apt-get install -y software-properties-common
add-apt-repository ppa:ubuntu-toolchain-r/test
apt-get update

apt-get install -y git parallel wget make build-essential pkg-config autoconf automake autoheader libtool bison flex libpq-dev parallel pandoc perl

apt-get install -y clang clang-format

# if using g++ or building with libstdc++

apt-get install -y gcc-7 g++-7 cpp-7

However if i use 

wget -O stellar-core.deb https://s3.amazonaws.com/stellar.org/releases/stellar-core/stellar-core-${STELLAR_CORE_VERSION}_amd64.deb
dpkg -i stellar-core.deb
rm stellar-core.deb

it works. What do i miss?

**Comment by MonsieurNicolas** [comment]
Please provide exact repro steps that lead to this problem, including how you setup the container

**Comment by MonsieurNicolas** [comment]
closing as we don't have repro steps. reopen if you have more details
