### ISSUE TITLE
I don't fully understand fail_with in stellar core administration doc

### ISSUE THREAD

**Issue by TheBubblePopped** [stellar/stellar-core#2212]
Hey there,

in my config file i have set a few known peers. Now some of them are failing. The stellar-core gives me the info fail_with: [2 servers i have]

How can i find out what exactly the error is?

**Comment by MonsieurNicolas** [comment]
Not a bug

* Take a look at Stellar's [developer portal][1], where you'll find comprehensive documentation
  related to Stellar.
* If you can't find an answer to your question, please submit a question to [Stellar's Stack
  Exchange][2].
* If your question is non-developer centric, take a look at [Stellar's Community][3].

In general, we close any issues that are questions best served elsewhere — we have a small
community of people that manages issues, and we want to ensure that the issues that remain open are
high quality (so we actually get around to implementing them!)

[1]: https://www.stellar.org/developers/
[2]: https://stellar.stackexchange.com/
[3]: https://www.stellar.org/community
