### ISSUE TITLE
Question about the mechanism sendtransaction || "network propagation"

### ISSUE THREAD

**Issue by TheBubblePopped** [stellar/stellar-core#2214]
If i submit a transaction to the horizon server it propagates it to the whole network. I saw in the docs that after the closing time of a ledger horizon collects all transactions it has received from the network but is this a global case or a local case? 
To illustrate. 
3 nodes [A,B,C]

i publish a transaction on A it checks if it s a valid transaction and propagates it to the network if so. While B noticed that transaction C hasn't yet. A and B close the ledger but C hasn't heard about it yet so it's missing from its ledger. How will the global consenus ledger close ?
How does it achieve consensus?

Also another relevant question on that example.
I, node A will check the signature. If it s correct i'll publish it. Will other validators check it as well or will they just take it as correct if i am in their quorum set they trust in?
(I am talking here only about full validator nodes)

#Sidenote
By the way, the "how to build a history" section falls short. While i understand what it is and how it works i don't fully understand how to make that reality.

**Comment by MonsieurNicolas** [comment]
Not a bug

* Take a look at Stellar's [developer portal][1], where you'll find comprehensive documentation
  related to Stellar.
* If you can't find an answer to your question, please submit a question to [Stellar's Stack
  Exchange][2].
* If your question is non-developer centric, take a look at [Stellar's Community][3].

In general, we close any issues that are questions best served elsewhere — we have a small
community of people that manages issues, and we want to ensure that the issues that remain open are
high quality (so we actually get around to implementing them!)

[1]: https://www.stellar.org/developers/
[2]: https://stellar.stackexchange.com/
[3]: https://www.stellar.org/community
