### ISSUE TITLE
Replay performance on stellar-core

### ISSUE THREAD

**Issue by TheBubblePopped** [stellar/stellar-core#2215]
I noticed that stellar-core isn't using my cpu at all neither does it touch my ram. Can i change settings to increase the speed it replays transactions? ( Full node catching up and repalying the network)

**Comment by MonsieurNicolas** [comment]
Not a bug

* Take a look at Stellar's [developer portal][1], where you'll find comprehensive documentation
  related to Stellar.
* If you can't find an answer to your question, please submit a question to [Stellar's Stack
  Exchange][2].
* If your question is non-developer centric, take a look at [Stellar's Community][3].

In general, we close any issues that are questions best served elsewhere — we have a small
community of people that manages issues, and we want to ensure that the issues that remain open are
high quality (so we actually get around to implementing them!)

[1]: https://www.stellar.org/developers/
[2]: https://stellar.stackexchange.com/
[3]: https://www.stellar.org/community
