### ISSUE TITLE
database credentials may get leaked into logs

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#2234]
Looks like f2069efa41168372ee47747f8b7350c90becb37a doesn't deal with some config formats:

```
DATABASE="postgresql://dbname=stellar user=stellar password=thisshouldbesecret host=/var/run/postgresql/"
```

yields:

```
2019-08-16T18:18:29.203 GDKXE [Database INFO] Connecting to: postgresql://dbname=stellar user=stellar password=thisshouldbesecret host=/var/run/postgresql/
```

**Comment by graydon** [comment]
Oh, we're being too narrow with the definition of a bareword. Postgres allows [anything non-whitespace](https://www.postgresql.org/docs/9.4/libpq-connect.html#LIBPQ-CONNSTRING). Easy fix.
