### ISSUE TITLE
Add support for "CRITICAL" quality validators

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#2247]
Right now we have `HIGH`, `MEDIUM`, `LOW`.

Even `HIGH` only enforces 67% threshold - we should add a `CRITICAL` quality level that when causes entities in that level to be required (threshold of that group is 100%).

There are many uses cases for this, one of them is to require that a node from an organization agrees to other nodes in the same organization.

This change will require increasing the maximum allowed nesting level as well.

**Comment by sisuresh** [comment]
@MonsieurNicolas Can you please explain what "maximum allowed nesting level" means?

**Comment by MonsieurNicolas** [comment]
a quorum set is a recursive data structure: it's how many recursions we can have.
See https://github.com/stellar/stellar-core/pull/2233 (where I increased it to handle HIGH + MEDIUM + LOW in the same quorum set)

**Comment by sisuresh** [comment]
@MonsieurNicolas Right now, regardless of quality, it looks like the innerSets (homeDomain level) have a threshold of >50%, and the set above will have a threshold of ~67%.

With this Critical quality level, should the innerSet threshold be 100%, with the set above still set to ~67%, or should the above set also be 100%? I think the above should be 67%, but wanted to clarify.
