### ISSUE TITLE
fatal error during commit to LedgerTxnRoot

### ISSUE THREAD

**Issue by tundak** [stellar/stellar-core#2261]
Error on build from source code, version 11.4.0 & when run on standalone mode with sqlite.

```
fatal error during commit to LedgerTxnRoot: sqlite3_statement_backend::loadOne: CHECK constraint failed: accounts
Aborted (core dumped)
```
with postgreql:
`fatal error during commit to LedgerTxnRoot: Cannot execute query. ERROR:  new row for relation "accounts" violates check constraint "accounts_balance_check"`

**Comment by MonsieurNicolas** [comment]
Thanks for the report. Can you paste the config file that you used and any other step that you followed (sequence of transactions?) so that we can repro this.

**Comment by tundak** [comment]
seems due to issue of compile... it's good now.
