### ISSUE TITLE
Asynchronously wait for in-progress bucket merges required to close ledger

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/stellar-core#2273]
Currently, `BucketList::addBatch` synchronously resolves merges to close ledger, relying on the fact that merges were started early enough to be finished before that ledger, when they are actually needed. It would be useful to improve this behavior by instead asynchronously waiting for the needed merges before we call `addBatch`. This would simplify the catchup flow post protocol 12, as we would not need to wait for resolved merges in `ApplyBucketsWork` anymore. Note that this will require setting up a timer to asynchronously wait for the merges, as well as a new function to calculate which merges we need to wait for.

**Comment by sisuresh** [comment]
@MonsieurNicolas Should this async wait only be done if we're in the catchup process, or while we're in sync as well?
