### ISSUE TITLE
Consider adding a "self-check" sub command family

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#2295]
Right now, the only way for operators to diagnose issues is to run a node, wait for something bad to happen and know how to interpret logs/metrics.

For example, if a node has bad archives (be, a malformed configuration file or points to an obviously bad archive, like wrong network) there is no easy way to pinpoint the source of the error.

What we can do is add a new `self-check` sub-command, with an optional scope (like `history` or `all`) that:
* performs sanity checks for the given scope
* gives a clear error message when a check fails
* it should be possible to run the command from the command line (for basic diagnostic), or as an http command (to perform checks for a running core instance)

For example, for `history`, such a check could be:
* for `get`-able archives, check that the archive has information for the "last known checkpoint" (based on the local node's LCL) both at the root (`.well-known/stellar-history.json`) and ledger header (`ledger-<XYZ>.xdr.gz`).
* for `write`-able archives, check that creating a dummy file (`.well-known/empty`) works

**Comment by graydon** [comment]
I'd like to start on this sometime soon-ish, and also I'd like to include in it the notion of doing some self-checking of performance characteristics, i.e. we should be able to report to a user when they're running on a node with a very slow disk, slow database, not enough memory, not enough CPU, etc.

**Comment by graydon** [comment]
Fixed in https://github.com/stellar/stellar-core/pull/2784 and https://github.com/stellar/stellar-core/pull/3030
