### ISSUE TITLE
Some buckets are leaked

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/stellar-core#2298]
Looks like fixing #2286 was not enough, and we still have bucket number constantly fluctuating (with total number of files being over expected 31). Checking the logs, the number of buckets referenced by the bucketlist, publishqueue and LCL is correct, so it must be failing the `refcount == 1` check in `forgetUnreferencedBuckets`

**Comment by MonsieurNicolas** [comment]
Here's a gist of an increase in number of shared-buckets https://gist.github.com/MonsieurNicolas/5436a26ac3c06e2edbb010d45aaab596 (not sure there is anything in there useful)
