### ISSUE TITLE
remove pandoc dependency

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#2301]
Right now we have a pandoc dependency to generate man pages, but:
* that pandoc dependency pulls a lot of packages (a significant subset of the internet it seems)
* those man pages are pretty much useless

We can instead just keep a hardcoded dummy man page (or remove it completely if it doesn't break things).

**Comment by MarcPow** [comment]
There are a few options for replacing pandoc as a markdown to man page converter.
1) [Ruby-Ronn](https://launchpad.net/ubuntu/+source/ruby-ronn) - which requires all of ruby to run on Ubuntu 16.04.   This scope of dependency (by MB) is wider than pandocs.  As a tool, it is also more strict than pandoc, and doesn't work on the markdown without modifications
2) [Remark-Man]: This is a straightforward nodejs plugin that will perform the markdown conversion, but as you might imagine, it needs all of node + 4 dependencies, which is also a larger set of downloaded dependencies than pandoc.

The simplest option is to check in the LKG ROFF (man database file) and use it as your stable base moving forward.

**Comment by MarcPow** [comment]
Note: To full remove pandoc from your build instructions, you'll need to also remove it from https://github.com/xdrpp/xdrpp/blob/master/Makefile.am
