### ISSUE TITLE
Leaked buckets when catching up

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#2314]
Reproed on 7b0da47779b390ce6fe4882bdf9c8156ae9026a1 (v12.1.0rc1)

Arch Linux current 2019-10-15 x86-64

Running command line catchup causes the "buckets" folder to have more and more buckets (tens of thousands on a large range).

Example:

replaying 1500 ledgers causes the bucket folder to have 4 buckets even though only 3 buckets are referenced by the LCL.

(replaying 5000 ledgers causes 11 buckets to be present, with only 3 referenced by the LCL)

```
$ ./stellar-core --conf ~/prod-tmp.cfg new-db ; ./stellar-core --conf ~/prod-tmp.cfg catchup 10000/1500
...
$ sqlite3 /tmp/stellar-prod.db 'select * from storestate where statename = "historyarchivestate"' | egrep '[0-9a-f]{64}' | egrep -v '0{64}' | cut -d\" -f 4 | sort | uniq | wc
      3       3     195
$ ls -al /tmp/buckets-prod/*.xdr | wc
      4      36     560

```

Configuration used for this:
```
PEER_PORT=8000
HTTP_PORT=11626
PUBLIC_HTTP_PORT=false

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
KNOWN_PEERS=[
"core-live-a.stellar.org:11625",
"core-live-b.stellar.org:11625",
"core-live-c.stellar.org:11625"
]

LOG_FILE_PATH="/tmp/stellar-prod.log"
BUCKET_DIR_PATH="/tmp/buckets-prod"
DATABASE="sqlite3:///tmp/stellar-prod.db"

UNSAFE_QUORUM=true
FAILURE_SAFETY=0

CATCHUP_COMPLETE=false
#AUTOMATIC_MAINTENANCE_PERIOD=0
CATCHUP_RECENT=100

INVARIANT_CHECKS=[
".*"
]

[QUORUM_SET]
THRESHOLD_PERCENT=51
VALIDATORS=["$SDF_validator_1", "$SDF_validator_2", "$SDF_validator_3"]

[HISTORY.sdf1]
get="curl -sf http://history.stellar.org/prd/core-live/core_live_001/{0} -o {1}"

[HISTORY.sdf2]
get="curl -sf http://history.stellar.org/prd/core-live/core_live_002/{0} -o {1}"

[HISTORY.sdf3]
get="curl -sf http://history.stellar.org/prd/core-live/core_live_003/{0} -o {1}"

**Comment by graydon** [comment]
Huh! Ok, I'm able to reproduce this and at a first pass of investigation I notice that it seems like it might be worse on _earlier_ ledger ranges -- those in the first few million ledgers of history, with few-to-no transactions, processing (usually) empty buckets -- though I'm not certain. If so, possible causes range from mishandling self-edges in the graph of `mFinishedMerges` (eg. cases where there's an HashX -> HashX input-to-output mapping stored) to races that only happen with instant / empty merges.

**Comment by graydon** [comment]
Example: when applying ledgers in the ledger-25-million range (where most ledgers have lots of churn), over 6000 ledgers applied we only get up to 97 retained buckets; whereas when applying ledgers in the ledger-5-million range (where most ledgers are empty), over just 500 ledgers applied we get 784 retained buckets.

**Comment by graydon** [comment]
I've isolated an example case that I'm a little worried about. It looks like a merge that's ... not being saved to the correct futurebucket, or something? I can't entirely figure it out. Will continue to try to isolate.

Another curiosity: we were leaking buckets during apply as far back as 10.2.0 (I expect earlier but 10.1.0 is giving me some other database error); but we're leaking _more_ on master. Replaying 1000 ledgers leaked 28 buckets up until July, at which point it started leaking 40 buckets.

Which culprit? Alas, cruel bisect points  the blame at me:

~~~~
6bfce1985efc9058d26d4a67bafb92e2d578c69f is the first bad commit
commit 6bfce1985efc9058d26d4a67bafb92e2d578c69f
Author: Graydon Hoare <graydon@pobox.com>
Date:   Tue Jul 9 17:11:20 2019 -0700

    bucket: add machinery to reattach to / resynthesize merge futures.

:040000 040000 2a80ba4ed32ccdf0bd79ef1b507bdb4c0b08f538 216a86b4c9f7222d71028130a0dbe8bf2e2fd265 M	src
~~~~

It's getting late so I'll stop for the night. Will carry on hunting tomorrow.

**Comment by graydon** [comment]
(Ok one more thing discovered: commenting out the call to `mLiveFutures.emplace(key, wp);` in `BucketManagerImpl::putMergeFuture` fixes the leak completely. So I think .. I'm getting close to an explanation!)
