### ISSUE TITLE
Increase Signer Limit

### ISSUE THREAD

**Issue by MuhammedKarakurt** [stellar/stellar-core#2322]
Hey, I am Muhammed Ali

I am working on a blockchain project and we are using stellar. For a use case  I need a multi signature account and I am using SetOptionsOperation for set signer to an account but we can add only 20 signers. So I have two questions.

1. Could you remove or increase this limit? 
2. Why did you need this limit?

**Comment by MonsieurNicolas** [comment]
This repo is to discuss implementation details of stellar-core; this question seems to be better fitted for protocol or stack exchange
