### ISSUE TITLE
Feature request : get transactions based on an account address and a specific memo

### ISSUE THREAD

**Issue by madetaille** [stellar/stellar-core#2323]
Hi,

I am currently developing an app based on the Stellar Blockchain.

To implement this app, one of my goal is to download the transactions of a specific address, including a specific memo. 

I tried to look for a method to do it but there is no argument to do it using the method provided on this documentation page : https://www.stellar.org/developers/horizon/reference/endpoints/transactions-all.html 

My problem is that the only alternative is to download all transactions for a specific address and filter locally for the transactions including the specific memo. This becomes quite long and painful when I have to download more than 400,000 transactions, especially when I can download pages of maximum 200 transactions at a time.

My question is : would it be possible to implement a feature that provides the transactions of a specific account having a specific memo?

This would prevent me from downloading the whole transactions of a specific account when I just need one or two specific transactions of the account. I think it could also reduce dramatically the number of requests my app (and other app?) make to the stellar blockchain.

Thanks in advance.

**Comment by MonsieurNicolas** [comment]
This is the wrong repo. Try asking over at https://github.com/stellar/go/tree/master/services/horizon
