### ISSUE TITLE
Allow set signer without account creation

### ISSUE THREAD

**Issue by MuhammedKarakurt** [stellar/stellar-core#2330]
Hi,

I am working on a blockchain project with stellar. Our use case require a multi signature wallet and I am implemented it. Problem: I am generating a key pair and set as signer to the another account, but I am not doing create account for this key pair. I think you are check this account exist or not.

**Comment by MonsieurNicolas** [comment]
This doesn't seem to be a bug. If you have questions on protocol semantics, start discussing on the dev mailing list or KeyBase
