### ISSUE TITLE
Question about setting AWS RDS PostgreSQL within **core schema ** in Production?

### ISSUE THREAD

**Issue by Cheny-chen** [stellar/stellar-core#2331]
in stellar-core.cfg, 
If I want to connect to AWS RDS PostgreSQL within **core schema ** in Production.
How to do ?

The following  is not working.
```
DATABASE="postgresql://dbname=core user=stellar password=xxxss 
host=pro-stellar.rds.amazonaws.com search_path=core"
```

**Comment by MonsieurNicolas** [comment]
@brahman81 ?

**Comment by brahman81** [comment]
@Cheny-chen, there is not enough information in this issue to allow me to help you, setting the search path varies depending on whether you are using psql or another client library. I would recommend using our more interactive support channels (Keybase) for this type of question.

If using psql you can use the below command:

`psql -d 'dbname=core user=stellar password=xxxss host=pro-stellar.rds.amazonaws.com options=--search_path=core'`
