### ISSUE TITLE
To start stellar-core from self-build AWS AMI is failed.

### ISSUE THREAD

**Issue by Cheny-chen** [stellar/stellar-core#2333]
We tried to build the stellar production with two stellar-cores.
One stellar-core are started up successfully.  
So we make AWS AMI and startup again. 
However, it failed.  Because it said 27 buckets are missing.

Do I need to rebuild another stellar-core with new bucket and new secret seed?

The following error messages

```
Nov 05 10:08:59 ip-10-31-26-52 stellar-core[2190]: 2019-11-05T10:08:59.109 GDQX4 [Ledger ERROR] 27 buckets are missing from bucket directory 'buckets' [LedgerManagerImpl.cpp:320]
Nov 05 10:08:59 ip-10-31-26-52 stellar-core[2190]: 2019-11-05T10:08:59.109 GDQX4 [default FATAL] Got an exception: Bucket directory is corrupt [ApplicationUtils.cpp:69]
Nov 05 10:08:59 ip-10-31-26-52 stellar-core[2190]: 2019-11-05T10:08:59.109 GDQX4 [default FATAL] Please report this bug along with this log file if this was not expected [ApplicationUtils.cpp:70]
```

**Comment by MonsieurNicolas** [comment]
reopen this issue with actual repro steps if you're reporting a bug, otherwise use dev channels like Keybase
