### ISSUE TITLE
Synchronization is always backward(v0.22.1)

### ISSUE THREAD

**Issue by quarksgluons** [stellar/stellar-core#2346]
stellar main network node Synchronization is always backward, and then wait a few hours to resume synchronization. 
Is this a bug? 
Or just the p2p nodes are unstable? Is there any other place to get the list of p2p nodes except https://github.com/stellar/docs/blob/master/other/stellar-core-validator-example.cfg?

**Comment by MonsieurNicolas** [comment]
The stellar-core issues repository is meant for reporting bugs and feature requests related to stellar-core's implementation.

If you have a question, we would recommend that you take a look at Stellar's [developer portal][1], where you'll find comprehensive documentation related to Stellar.

If you can't find an answer to your question you can:
* submit a question to [Stellar's Stack Exchange][2].
* or ask one of [Stellar's communities][3].

[1]: https://www.stellar.org/developers/
[2]: https://stellar.stackexchange.com/
[3]: https://www.stellar.org/community/#communities
