### ISSUE TITLE
how to set a stellar node to a watcher node?

### ISSUE THREAD

**Issue by harryweiyongjie** [stellar/stellar-core#2355]
I have seen your support docs, it shows me the config file which is to set a public network or testnet node,but it looks like a Full validators. Now I want to set to "Watcher" mode, but I can't find any examples or tutorials ,is there any way to make it?

**Comment by MonsieurNicolas** [comment]
If you have a question, we would recommend that you take a look at Stellar's [developer portal][1], where you'll find comprehensive documentation related to Stellar.

If you can't find an answer to your question you can:
* submit a question to [Stellar's Stack Exchange][2].
* or ask one of [Stellar's communities][3].

[1]: https://www.stellar.org/developers/
[2]: https://stellar.stackexchange.com/
[3]: https://www.stellar.org/community/#communities
