### ISSUE TITLE
Rows from ledgerheaders not removed during maintenance (Version: v12.0.0rc2)

### ISSUE THREAD

**Issue by bartekn** [stellar/stellar-core#2359]
## Issue Description

It looks like rows in `ledgerheaders` are not removed during maintenance. This can be a problem for downstream systems because it may suggest that there were no transactions in a given ledger.

I haven't tested it with the latest version because it requires some time and it's pretty late here but the [code](https://github.com/stellar/stellar-core/blob/v12.0.0rc2/src/ledger/LedgerManagerImpl.cpp#L951) suggests that table should be trimmed. Can do it tomorrow.

## Steps to Reproduce

Run stellar-core, wait for `Performing maintenance` log line.

## Expected Result

Old ledger data removed from `ledgerheaders` table.

## Actual Result

`txhistory` is correctly trimmed but not `ledgerheaders`:

```
core=# select min(ledgerseq), max(ledgerseq) from ledgerheaders;
  min   |  max   
--------+--------
 423807 | 435379
(1 row)

core=# select min(ledgerseq), max(ledgerseq) from txhistory;
  min   |  max   
--------+--------
 435083 | 435379
(1 row)

core=# select min(ledgerseq), max(ledgerseq) from scphistory ;
  min   |  max   
--------+--------
 435083 | 435379
(1 row)
```

There are transactions in testnet ledger: [423807](https://horizon-testnet.stellar.org/ledgers/423807).

### stellar-core Version
v12.0.0rc2

### Environment
* Darwin MacBook-Air 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64
* Are you running from the command line? From a container? Command line.
* Did you pass in special parameters when building the app? Custom `PKG_CONFIG_PATH`.

## Supporting Files

* Configuration files: https://github.com/stellar/docker-stellar-core-horizon/blob/master/testnet/core/etc/stellar-core.cfg
* Log files - it is best is to have logs running at DEBUG level when reproducing an issue (`-ll
  DEBUG` on the command line):
```
2019-11-26T21:55:26.645 GDOY4 [Ledger INFO] Got consensus: [seq=435146, prev=7fd98c, txs=3, ops=43, sv: [ txH: 91bf71, ct: 1574801726, upgrades: [ ] ]]
2019-11-26T21:55:26.647 GDOY4 [Tx INFO] applying ledger 435146 (txs:3, ops:43)
2019-11-26T21:55:26.703 GDOY4 [Ledger INFO] Closed ledger: [seq=435146, hash=bbbbcc]
2019-11-26T21:55:31.298 GDOY4 [default INFO] Performing maintenance
2019-11-26T21:55:31.312 GDOY4 [History INFO] Trimming history <= ledger 435082 (rmin=4294967295, qmin=435146, lmin=435082)
2019-11-26T21:55:41.138 GDOY4 [Herder INFO] Quorum information for 435145 : {"agree":3,"delayed":0,"disagree":0,"fail_at":2,"hash":"59d361","ledger":435145,"missing":0,"phase":"EXTERNALIZE"}
```

**Comment by MonsieurNicolas** [comment]
As you look into this, can you also include the values of cursors @bartekn ?
The basic premise is that you can only trust the data that is more recent than your cursor.

**Comment by MonsieurNicolas** [comment]
was this a real problem @bartekn ? There is not enough information here to tell if this is a bug or something else

**Comment by bartekn** [comment]
Thanks @MonsieurNicolas this is more clear now.
