### ISSUE TITLE
TxSetFrame is messy and confusing

### ISSUE THREAD

**Issue by graydon** [stellar/stellar-core#2363]
The TxSetFrame class needs an overhaul. Among its problems:

  - It is stateful, allowing addition and deletion of txs from the set, which corrupts its sort order.
  - It has methods like trimInvalid or checkOrTrim that implicitly call the deletion method.
  - The deletion method is linear in the size of the txset, and is called from linear trimming loops over the txset, with quadratic results.
  - It has a calculated field (the content hash) that's cached, with a validity flag that's flipped when it changes.
  - It has a sortForHash() method that also does a potentially slightly-expensive calculation but _doesn't_ track its state with a validity flag, meaning it potentially re-sorts anytime anyone calls it, even if it's already sorted
  - It has a sortForApply() method which doesn't change the order of the members, even though the name suggests it does, and some tests appear to think it does (see herder/test/HerderTests.cpp)
  - It has a somewhat awkward abstract base class with both full (TxSetFrame) and simulated (SimulationTxSetFrame) subtypes. It's not clear to a reader what the difference is or why there are two.

As a general sketch -- hopefully without disrupting its users too much! -- I'd recommend the following adjustments:

  - [ ] Keep the cached calculated content hash but make it mutable and invalidated by a `const` helper method, revalidated in the `const` hash-getter (copy what TransactionFrame does here)
  - [ ] Make it a (documented) invariant that a `TxSetFrame`'s transactions are always in hash-sorted order:
    - [ ] When constructed from a `TxSet` off-the-wire, pass a boolean saying whether to sort in the ctor (because we're just mucking around in a test) or whether to require the input is pre-sorted and throw if it's not (eg. for values off the wire, which we should reject immediately at `Peer::recvTxSet` level).
    - [ ] Either store values in a sorted form that's always sorted (`std::set`) ...
    - [ ] Or store them in a sorted `std::vector`...
        - [ ] And re-sort eagerly on each change (possibly batching changes)...
        - [ ] Or flip a mutable `mSorted` bit and re-sort before _observation_, as with the hash
    - [ ] Either way, remove the `sortForHash` function from the public API. Callers shouldn't care.
  - [ ] Remove quadratic filtering loop: build a `std::vector` of txs-to-remove during the filter loop, then sort that vector by hash once (unfortuntately it's _processed_ in apply order) and merge-remove it from the remaining sorted type.
  - [ ] Remove the `AbstractTxSetForApply` base type
    - [ ] Rename `SimulationTxFrame` to `TxSetInApplyOrder`; use this in LedgerCloseData.
    - [ ] Rename `TxSet::sortForApply` to `getTxSetInApplyOrder` and make it `const`; make this construct a `TxSetInApplyOrder`.
    - [ ] Keep `TxSetInApplyOrder` immutable but change its contents and constructors slightly:
      - [ ] Replace its `mTransactions` and `mResults` members with a `std::vector<TransactionFramePtr> mTxns` member 
      - [ ] Change its current ctor to take the same args but eagerly expand-out the `mTxns` member
      - [ ] Give it a new ctor that takes networkID, previousLedgerHash, contentsHash, and a `std::vector<TransactionFramePtr>`. This is called from `TxSetFrame::getTxSetInApplyOrder`.
      - [ ] Give it a method to produce a `TxSetFrame` (in hash order). Let users inter-convert, but not wonder which is which. `TxSetFrame` is hash-sorted, `TxSetFrameInApplyOrder` is apply-sorted. Always. The end.

**Comment by jonjove** [comment]
Related: https://github.com/stellar/stellar-core/issues/2163

**Comment by MonsieurNicolas** [comment]
Yeah I like that.

A few additional things to think about:
* `LedgerCloseData`'s input is from SCP, so I don't think you can pass only a "apply order" type of set (we also verify that the tx set is valid in there, which requires hash order). That said, this problem might be irrelevant if we keep both forms available and make the tx set immutable.
* the "typical" use of those is hash order, and only in a few places we need the "apply order", so I think it makes sense to lazy compute the apply order.
* outside of when a transaction set is constructed, we really want those to be immutable (most of the code assumes that the hash doesn't change, so keeps around maps of hash -> shared_ptr to txset). I would suggest extracting anything that mutates the set into some other utility class (this would be the `trimInvalid`, `surgePricingFilter`, `add`, `removeTx`) and just build a new tx set every time we want to change a txset (we don't care if it's a little slower to do this: it's not happening that often and changes should be batched anyways).
* I *think* that those changes don't require doing the same thing to `TransactionFrame` (for now); ideally we would also change `TransactionFrame` to also be immutable, but that seems to be a lot more work.

**Comment by graydon** [comment]
I'm going to say @jayz22 finished this in #3395 -- if someone disagrees, reopen?
