### ISSUE TITLE
[externally connect to my stellar node] (Version: [v12.2.0rc2-2-g628b9d24])

### ISSUE THREAD

**Issue by YasserNoureldin** [stellar/stellar-core#2374]
I created a private stellar node on my server using the documentation, when i am trying to externally connect to my node using curl i get the following error on stellar-core:

"[Overlay ERROR] TCP: message size unacceptable: 1195725856 while not authenticated [TCPPeer.cpp:360]"

and curl error, I get "cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)"

Could you help me with this,maybe miss configuration from my side?

**Comment by MonsieurNicolas** [comment]
As per the issue template, you're probably better off asking for this type of question in other places
## Read before creating an issue

In general, we close any issues that are
* unactionable (fill the template below under "Description")
* questions best served elsewhere

We have a small community of people that manages issues, and we want to ensure that the issues that remain open are high quality (so we actually get around to implementing them!).

### I have a question!

The stellar-core issues repository is meant for reporting bugs and feature requests related to stellar-core's implementation.

If you have a question, we would recommend that you take a look at Stellar's [developer portal][1], where you'll find comprehensive documentation related to Stellar.

If you can't find an answer to your question you can:
* submit a question to [Stellar's Stack Exchange][2].
* or ask one of [Stellar's communities][3].

[1]: https://www.stellar.org/developers/
[2]: https://stellar.stackexchange.com/
[3]: https://www.stellar.org/community/#communities
