### ISSUE TITLE
[COMPLAINT] "Be cordial, or see the door. "

### ISSUE THREAD

**Issue by ghost** [stellar/stellar-core#2436]
(please transfer issue to a more appropriate repo, did not find one)

## Problem

A developer which visits the developer group:

https://groups.google.com/forum/#!forum/stellar-dev

sees as the first thing this:

> "Be cordial, or see the door. No offensive posts, personal attacks, or hostile language will be tolerated."

And i'm asking you now: don't you see that you violate your own rules?

I mean "Be cordial, or see the door"? Really?

I posted a topic discussing this (something that is by definition a valid topic), but it was censored (it did not appear).

=> this is a governance tragedy

## Expected

* Rephrase the guidelines (and all the intro) to be more... cordial.
* Fire (or retrain) the moderator which has censored my valid topic

## Example

"This is a "core-developer" group, please limit your posts to stellar core-development related topics (e.g. topics related to the development of stellar itself)."

You don't need more (assuming you assume that the visitors have some basic intelligence).

.

**Comment by MonsieurNicolas** [comment]
not a core issue, I fwd your question to the right party

**Comment by rice2000** [comment]
> (please transfer issue to a more appropriate repo, did not find one)
> 
> ## Problem
> A developer which visits the developer group:
> 
> https://groups.google.com/forum/#!forum/stellar-dev
> 
> sees as the first thing this:
> 
> > "Be cordial, or see the door. No offensive posts, personal attacks, or hostile language will be tolerated."
> 
> And i'm asking you now: don't you see that you violate your own rules?
> 
> I mean "Be cordial, or see the door"? Really?
> 
> I posted a topic discussing this (something that is by definition a valid topic), but it was censored (it did not appear).
> 
> => this is a governance tragedy
> 
> ## Expected
> * Rephrase the guidelines (and all the intro) to be more... cordial.
> * Fire (or retrain) the moderator which has censored my valid topic
> 
> ## Example
> "This is a "core-developer" group, please limit your posts to stellar core-development related topics (e.g. topics related to the development of stellar itself)."
> 
> You don't need more (assuming you assume that the visitors have some basic intelligence).
> 
> .

We changed the welcome text, and added an outgoing message when posts get moderated.  Check it out:
https://groups.google.com/forum/#!forum/stellar-dev
