### ISSUE TITLE
[REGRESSION] Document new Regression Tests and Mechanisms Publicly

### ISSUE THREAD

**Issue by ghost** [stellar/stellar-core#2437]
(EDIT: this issue is general, and affects ALL stellar projects. Just the example affects another repo/release)

## Problem

> We noticed some bugs in the v1.8.0 release that prevented it from running correctly on the public network.
> We have patched these bugs in this release and have improved our QA process to catch similar issues sooner.

https://groups.google.com/forum/#!topic/stellar-dev/evEBqLSmV7E

## Expected (Generally)

The newly added regression tests and QA processes should be publicly available, thus any participant can assess them.

## Question

where can i find the full information re this actual incident?

**Comment by MonsieurNicolas** [comment]
from the issue template:

In general, we close any issues that are
* unactionable (fill the template below under "Description")
* questions best served elsewhere
