### ISSUE TITLE
[terminating with uncaught exception] (Version: [12.3.0])

### ISSUE THREAD

**Issue by JonasPf** [stellar/stellar-core#2452]
## Issue Description

Two Stellar validators crashed at the same time due to an unexpected exception. Please note that we are running other validators with a similar setup that didn't crash.

I don't know if it is related but surge pricing got activated just before the crash.

### stellar-core Version

stellar-core 12.3.0 (5a8f8b13af5f78704bf0e7b5de4314c16a3639a5)

### Environment

* Ubuntu 18.04
* Stellar Core running in Docker container

## Supporting Files

* Crash log from validator 1: https://gist.github.com/JonasPf/8e2c9601b3851ba9633cb0b2a3c658c8
* Crash log from validator 2: https://gist.github.com/JonasPf/12b658396243bc02fc236afa69a153b2

**Comment by jonjove** [comment]
Thank you for the report. I believe this issue was fixed in stellar-core 12.4.0 via https://github.com/stellar/stellar-core/pull/2429. Try updating to 12.4.0, and please let us know if you encounter this issue again after updating.
