### ISSUE TITLE
[PRODUCT] Onboarding with a hidden 4.5% fee?

### ISSUE THREAD

**Issue by lazaridiscom** [stellar/stellar-core#2462]
I visited stellar.org, and installed the suggested solar-wallet.

https://solarwallet.io/

Was happy about the simplicity (simple enough to send end-users there).

Moonpay is used to purchase lumens with FIAT-CC. All good.

Then I check https://www.moonpay.io/ , and see this:

> SIMPLE PRICING
> No onboarding, setup or contract fees.
> 4.5 % per transaction
> or a $4.99 minimum fee

## Questions

* Are you serious? Mentioning the super-low fees of stellar, and then this?
* What other methods are available to purchase lumens with near-zero fees?

## Expected

Stellar is not only low-fee for transactions, but additionally for FIAT funding of accounts.

**Comment by MonsieurNicolas** [comment]
not a core bug

**Comment by lazaridiscom** [comment]
@MonsieurNicolas , what are you? A mechanical bot, or an intelligent human being?

"[PRODUCT]" => either accept this categorization within this repo, or transfer the issue over to a more relevant repo, see #2464.

It's not wonder that Stellar usage goes down, this is a simply terrible UX/DX/CX.
