### ISSUE TITLE
[PROJECT] Revise Issue-Tracking-Process: Add "Transfer"

### ISSUE THREAD

**Issue by lazaridiscom** [stellar/stellar-core#2464]
## Situation

A user files an Issue in the wrong repository.

Team member closes, with a comment like "not a core bug" #2462 

## Expected

Use the github "Transfer Issue" functionality (bottom right) to transfer the issue to the relevant repository.

**Comment by MonsieurNicolas** [comment]
from the issue template:

In general, we close any issues that are
* unactionable (fill the template below under "Description")
* questions best served elsewhere
