### ISSUE TITLE
Improve Prefetch Hit-Rate Metric

### ISSUE THREAD

**Issue by jonjove** [stellar/stellar-core#2470]
The current prefetch hit-rate metric is an average over the entire time that the node has been running. After the node has been running for several days, it becomes essentially constant. It would be far more useful if this were a measure of the recent (last 5 minutes, for example) prefetch hit-rate so variations could more easily be correlated against other events.

**Comment by MonsieurNicolas** [comment]
That or make it that we track it on a ledger by ledger basis as we don't prefetch across ledger boundaries.
