### ISSUE TITLE
Generalize "Work yields every N ms while waiting" pattern

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/stellar-core#2519]
Currently, there are multiple places in the code (ResolveSnapshotWork, GenerateBucketsWork, ConditionalWork) that implement the same pattern: run, check if ready, sleep for a short time, then wake self up (done via creating a weak pointer, initializing a lambda to wake self up, then setting up a timer to wait). We should avoid the duplication, and generalize this. For example, we already have `wakeSelfUpCallback` in BasicWork that can be used. Also, as this pattern seems useful, it might make sense to make it a feature of BasicWork.

**Comment by MonsieurNicolas** [comment]
I agree, this could be a simple helper added at the BasicWork layer
