### ISSUE TITLE
Automatic maintenance run during `catchup` command (Version: v13.0.0)

### ISSUE THREAD

**Issue by bartekn** [stellar/stellar-core#2525]
## Issue Description

When running `stellar-core catchup` command older ledgers in the range are trimmed by the maintenance. I think it should not be run in `stellar-core catchup` command or be run every `AUTOMATIC_MAINTENANCE_PERIOD`. Instead, maintenance is performed many times.

## Steps to Reproduce
No `AUTOMATIC_MAINTENANCE_PERIOD` (defaults to 4 hours) and `AUTOMATIC_MAINTENANCE_COUNT` in the config.
```
stellar-core catchup 29502988/1000
```

## Expected Result
* In core DB I expect to have 1000 ledgers: [29503988, 29502988].
* I expected a maintenance to run one time at max.

## Actual Result
* Only 161 ledgers in a DB: [29502828, 29502988].
* Maintenance run many times:
```
2020-05-11T21:10:00.160 GBGFK [default INFO] Performing maintenance
2020-05-11T21:10:00.161 GBGFK [History INFO] Trimming history <= ledger 29502610 (rmin=4294967295, qmin=29502674, lmin=29502610)
...
2020-05-11T21:10:30.389 GBGFK [default INFO] Performing maintenance
2020-05-11T21:10:30.390 GBGFK [History INFO] Trimming history <= ledger 29502712 (rmin=4294967295, qmin=29502776, lmin=29502712)
...
2020-05-11T21:11:01.078 GBGFK [default INFO] Performing maintenance
2020-05-11T21:11:01.080 GBGFK [History INFO] Trimming history <= ledger 29502827 (rmin=4294967295, qmin=29502891, lmin=29502827)
...
```

### stellar-core Version
v13.0.0

### Environment
Latest `stellar/quickstart` image. I manually stopped stellar-core and horizon to reproduce https://github.com/stellar/docker-stellar-core-horizon/issues/175.

## Supporting Files

Log: https://gist.github.com/bartekn/861523055414dba7582f5ddb94caed06

**Comment by MonsieurNicolas** [comment]
Is this using the config from https://github.com/stellar/docker-stellar-core-horizon/blob/master/pubnet/core/etc/stellar-core.cfg ? This one doesn't seem to have a CURSOR configured, isn't that the bug?

If there is no CURSOR, we want to actually respect maintenance settings.

If your question is around catchup frequency during catchup: we actually force catchup to run more often (if it's not disabled) during command line catchup to avoid accumulating a lot of data only to remove it at arbitrary times.
Accumulating data during command line catchup is a huge problem for people as it basically borks their postgres database (and they'll need to perform a `VACUUM FULL` to recover from those big spikes).

**Comment by bartekn** [comment]
> If there is no CURSOR, we want to actually respect maintenance settings.

Correct, there is no CURSOR in the use case reported https://github.com/stellar/docker-stellar-core-horizon/issues/175. I wonder if there's any use case in which you run `stellar-core catchup x/y` but once the command is finished you don't expect to have `y` ledgers in a db?

In Horizon context, `stellar-core catchup` command is used for reingesting data and it's been surprising for many users ([[1]](https://stellar.stackexchange.com/questions/4105/horizon-reingest-not-working/4106), [[2]](https://stellar.stackexchange.com/questions/4114/horizon-ingest-the-historical-data/4115) and https://github.com/stellar/docker-stellar-core-horizon/issues/175.) that Horizon can't find ledgers in Stellar-Core DB after running `stellar-core catchup`.

> If your question is around catchup frequency during catchup: we actually force catchup to run more often (if it's not disabled) during command line catchup to avoid accumulating a lot of data only to remove it at arbitrary times.

Yes, this is another question. It can be confusing because user expects maintenance to run every 4 hours but it's run more often. Also, in example above I didn't have `AUTOMATIC_MAINTENANCE_COUNT` in the config file so it should default to 50000 but I had only 161 ledgers instead of 1000 in a db. Is `AUTOMATIC_MAINTENANCE_COUNT` also changed to a smaller number in `catchup` command?

**Comment by MonsieurNicolas** [comment]
If they don't have a CURSOR in their config file, they're going to run into arbitrary deletions down the line (like they spend hours/days prepping everything, and when they start up core "for real", maintenance runs and deletes their work).
So I think the issue here is that if they're planning on using horizon they should always have a CURSOR set.

As for when the maintenance is run: the important bit here is not "how often" but if it should be run at all. I suspect that setting a CURSOR fixes that problem as well.
Relying on when maintenance runs is super error prone as well: we run it on startup (so running multiple catchup or other commands will cause more deletions), and like I said earlier the reason we want to run maintenance very often during command line catchup is to avoid breaking the postgres data base (we had many people do this in the past, they would run out of disk space or have very slow performance because of this).

**Comment by bartekn** [comment]
Thanks for explanations from earlier today @MonsieurNicolas. Here's a `stellar/quickstart` fix that should solve it: https://github.com/stellar/docker-stellar-core-horizon/pull/177.
