### ISSUE TITLE
Include gcc and sed in INSTALL-Windows.md

### ISSUE THREAD

**Issue by cflint987** [stellar/stellar-core#2531]
## Description

As I was working through getting the source to compile in VS 2019, I came across a few compiler errors. In INSTALL-Windows.md for MinGW , it states that only Flex and Bison need to be installed. However, both gcc and sed also need to be installed. I didn't try cygwin, but I imagine that sed needs to be included there also.

Below is my recommended change:
## Building xdrc
 In order to compile xdrc and run the binary you will need to either
* Download and install MinGW from http://sourceforge.net/projects/mingw/files/
    * In the MinGW Installation Manager in `MSYS/MinGW Developer Toolkit` choose `Flex`, `Bison`, `gcc` and `sed` packages for installation
    * Add `C:\MinGW\msys\1.0\bin;C:\MinGW\bin` to the end of `%PATH%`
* Download and install cygwin 64 bit build from https://cygwin.com/install.html
    * Get cygwin setup to install
        * `Flex`
        * `Bison`
        * `sed`
        * `curl` (command line)
        * `gcc-core`
    * Add `c:\cygwin64\bin` to the end of `%PATH%` (at least for Visual Studio)

    > Note: if you're going to use 'cp'and 'mkdir' from cygwin (tests do),
        make sure that your install is correct by trying to copy a
        file from a `cmd.exe` console (not from a cygwin terminal).
        `cp in.txt out.txt` and then try to open *out.txt* with
        notepad. You should not get a permission denied error.

    > Note: both MinGW and CygWin may run into virtual memory address space
    conflicts on modern versions of Windows. You will run into errors like
    `Couldn't reserve space for mingw's heap, Win32 error 0`.
    A workaround is to reboot until you can run `bison.exe` from a cmd.exe
    prompt.

**Comment by MonsieurNicolas** [comment]
Thanks!
