### ISSUE TITLE
LoadManager could/should probably use overload signal from Scheduler

### ISSUE THREAD

**Issue by graydon** [stellar/stellar-core#2535]
The overload signal in the Scheduler class introduced in #2511 is probably worth trying to integrate into (or possibly replace) the load estimate currently driving overlay/LoadManager's decisions.

**Comment by marta-lokhova** [comment]
@graydon I believe this can be closed, since LoadManager was removed in https://github.com/stellar/stellar-core/pull/2794

**Comment by graydon** [comment]
Yes, good catch!
