### ISSUE TITLE
Display consensus round latencies in appropriate units 

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/stellar-core#2538]
Right now our logs can be a bit hard to read, because we use nanoseconds. 
```
externalize lag delta for slot 29758332 is 189298938 ns.
Nominate delta for slot 29758332 is 13858470148 ns.
Prepare delta for slot 29758332 is 50538432 ns.
```
It doesn't seem like we need this much precision, and it would be much easier to parse this if we used milliseconds instead.

**Comment by MonsieurNicolas** [comment]
yeah millisecond for anything tied to the network seems fine: I think even at the speed of light we'd have a resolution of ~300 meters of cable which is fine.
