### ISSUE TITLE
xdr_printer makes multiline printing difficult

### ISSUE THREAD

**Issue by jonjove** [stellar/stellar-core#2543]
Discovered this while reviewing #2536. Internally, `xdr_printer` uses a detail structure to track indentation. But that is a detail structure, so it is not provided as a parameter to `xdr_printer` making multiline printing difficult because the indentation level is not known. This is very tangentially related to #2520 in that it has to do with the xdrpp archiving machinery.

**Comment by MonsieurNicolas** [comment]
Maybe something worth investigating: ditch the custom format, use instead cereal to convert xdr into JSON, and only in the outer scope convert into a string.

I suspect this is going to be slower, but
* it may not be that much slower
* we'd have well formed JSON (a big win as this would make it possible to interop with other tools like `jq`)
* this would also allow us to have both a pretty printed JSON as well as "compact" single line JSON (single line JSON can be very useful for the streaming version, as we'd have one object per line, so easy to parse with scripts)

**Comment by MonsieurNicolas** [comment]
there is already a way to do this, closing in favor of https://github.com/stellar/stellar-core/issues/2681
