### ISSUE TITLE
subcommands that take file name as input can't be used to parse standard input

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#2560]
It looks like some subcommands require a file name to be passed in:

```
echo 'sdkjsjksjd' | /usr/bin/stellar-core print-xdr
FILE-NAME argument is required

pretty-print one XDR envelope, then quit

usage:
  stellar-core print-xdr <FILE-NAME> options

where options are:
  -?, -h, --help            display usage information
  --filetype <FILE-TYPE>    [auto|ledgerheader|meta|result|resultpair|tx
                            |txfee]
  --base64                  use base64
```

but there is no way to consume from standard input.

A few options:
* make the file name optional, defaulting to standard input (probably the easiest)
* make it possible to pass in `-` as file name. This is a bit more work because `-` is recognized as a bad option, and trying to invoke `stellar-core print-xdr --base64 -- -` doesn't seem to be supported by our parser (`--` is the standard for "stop parsing options from this point").

**Comment by MonsieurNicolas** [comment]
Actually, this is much worst than I originally thought, we use `-` in a lot of places (grep for `"-"`), not just as main argument but also as argument for certain options, like `--conf` (when doing things like `cat stellar.cfg | ./stellar-core --conf - offline-info`).

Fixing the "clara" library (that is now [Lyra](https://github.com/bfgroup/Lyra)) seems to be pretty involved.

The alternative is to use a different string for defaulting to "stdin":
* centralize where that special string is defined, right now it's all over the place (so we'd be left with just docs and that central place for code)
* pick a new string instead of `"-"`. `"/dev/stdin"` may be a good candidate as it happens to be the path to stdin on many systems (and on Windows it's fine to use)

**Comment by hidenori-shinohara** [comment]
For future reference: https://github.com/catchorg/Clara/issues/57

**Comment by MonsieurNicolas** [comment]
@hidenori-shinohara as I mentioned above, that fork is not maintained anymore, so we'd have to switch to "Lyra" *and* fix the bug there (if it's not fixed), but either task doesn't seem worth doing.

I was proposing using the special name `/dev/stdin` as an alternative instead of `-` - which is weird but seems like a lot less work. What do you think (maybe others have a different opinion?)?

**Comment by hidenori-shinohara** [comment]
Yes, that makes sense! I just wanted to post it because that was the closest discussion that I could find (I couldn't find the same issue under Lyra) & it wasn't super easy for me to find it. But yes, as you pointed out, the fork is not maintained anymore, so I'm just realizing it wasn't that relevant.

I'm good with the special name `/dev/stdin/`, and I'll try to centralize where that special string is defined so that it's easy to change it in the future if necessary.
