### ISSUE TITLE
Ensure duplicate entries are collapsed during bucket merge

### ISSUE THREAD

**Issue by graydon** [stellar/stellar-core#257]
If the input to a bucket merge contains two entries with the _same_ key back-to-back, they will not be collapsed together. Whether or not this can ever actually happen (it shouldn't), it's worth guarding against  by holding a 1-element buffer in the merge.

**Comment by MonsieurNicolas** [comment]
I think this could help in detecting abnormal behaviors. I noticed when making a change for Horizon that the bucket list doesn't use some information that we have in the system, namely: we know if live entries are supposed to be new vs updates (for a given ledger).
