### ISSUE TITLE
Add network_passphrase to stellar-history.json (Version: N/A)

### ISSUE THREAD

**Issue by bartekn** [stellar/stellar-core#2579]
## Issue Description

Currently, JSON in a HAS file in history archives does not have a `network_passphrase` field. This can be helpful to check if history archive actually contains the data for a specified network.

Since history archive is not specified by any CAP I'm adding this issue here.

## Additional context

One of Horizon users used pubnet config (connected to pubnet Stellar-Core) but testnet archive. Because of that Horizon was waiting indefinitely for a checkpoint ledger after a given pubnet ledger but it never appeared because testnet ledger sequence numbers are much smaller than in pubnet.

**Comment by hidenori-shinohara** [comment]
@MonsieurNicolas Can you assign this to me? I don't seem to have write access to assignees.
