### ISSUE TITLE
Why isn't gHasher in src/crypto/SecretKey.cpp protected by a mutex?

### ISSUE THREAD

**Issue by hdevalence** [stellar/stellar-core#2604]
### Explain in detail the incorrect or additional documentation you'd like to see.

I went to look at how Stellar Core does Ed25519 validation and came to this function:

https://github.com/stellar/stellar-core/blob/fdfbd76382df602db491288b928896ef3e27c5ef/src/crypto/SecretKey.cpp#L313-L346

If I understand correctly, it's maintaining a global cache of signature verification results here:

https://github.com/stellar/stellar-core/blob/fdfbd76382df602db491288b928896ef3e27c5ef/src/crypto/SecretKey.cpp#L36-L40

I don't really understand why a cache helps unless the code is repeatedly verifying the same signature, but I assume this is because of my lack of knowledge about Stellar's architecture.

What I'm concerned about is the potential for race conditions on the hasher.  The `gVerifySigCacheMutex` is used to control access to the cache.  The cache key is computed as
```
auto cacheKey = verifySigCacheKey(key, signature, bin);
```
before the cache lookup, which is in a sub-scope protected by a mutex guard:
```
    {
        std::lock_guard<std::mutex> guard(gVerifySigCacheMutex);
        if (gVerifySigCache.exists(cacheKey)) { /* ... */ }
    }
```
However, `verifySigCacheKey` uses `gHasher`, defined as `static std::unique_ptr<SHA256> gHasher = SHA256::create();`, using an IUF API that mutates the `gHasher` state.

What protects the `gHasher` from concurrent mutation? It appears that concurrent access is possible (otherwise, there would be no need to protect the cache with a mutex), but nothing seems to prevent concurrent calls to `verifySigCacheKey` from simultaneously writing the same hasher state, causing corruption in the hash calculation.

**Comment by graydon** [comment]
> unless the code is repeatedly verifying the same signature

Yes, it is. Perhaps not ideal, it's a bit of defensive coding in early design when we were hoping to get away with fewer overall places we'd cache notions like (semantic) message validity. This might not have been a great choice, and in practice we've had to cache at higher levels anyways, but this layer still gets lots of hits. I wouldn't object to a patch series to remove this cache but it'd involve reworking a number of higher-level structures that funnel into it. Fair bit of plumbing.

> What protects the gHasher from concurrent mutation

Nothing. You're right, this is a bug. The good news is that nothing currently verifies signatures on non-main threads, so it's not currently causing an issue (I believe this to be true at least, and I just ran the testsuite with an assert in that checks that we're always on main thread without issue). In general stellar-core runs "almost everything" on the main thread, only uses background threads for some self-contained long-running computations. But this should be fixed. Patch in a moment.

Good catch, thanks!
