### ISSUE TITLE
Discussion - historical data tables future in core

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#2607]
As we're making progress towards using a pipe for propagating the meta into downstream systems (Horizon's captive mode), we should decide on the changes we want to make when the new mode becomes standard as we can better separate how a full validator and a watcher (captive) instance work.

For example, we could eliminate storing the meta entirely as described in https://github.com/stellar/stellar-core/issues/1756 (as the only historical data needed is what will be eventually published to an archive).

There is an interesting question of what to do when it comes to debugging/diagnostics: for a watcher node, the responsibility can be delegated to the host process (so Horizon ingestion for example), but for a full validator we need some way to debug when things go wrong (corruption, etc).

While keeping the meta in the main tables would work, it adds a lot of overhead to "closing a ledger", so it may be a good time to start to separate "critical" (needed for consensus) from "non critical" data.

The simplest thing to do might be to just emit the same stream than what Horizon needs, but into a file or a set of files (~ managed like a ring buffer, so that we can keep the last N (64?) ledgers worth of debugging information) and with weak flushing guarantees (ie, if there is a hard system crash we may corrupt those files and this is fine).

We could also start experimenting with some alternate high performance store like https://ned14.github.io/llfio/index.html (that we may decide to use later on for the ledger itself).

**Comment by graydon** [comment]
I'd be ok keeping a circular log in memory that we dump on error, of even repeatedly writing (asynchronously) to disk in the buckets dir if it were helpful. it'd add a fair bit of write overhead but they'd just be sequential and bufferable, and I don't think we're usually keeping the disk saturated in the idle periods between closes.

**Comment by MonsieurNicolas** [comment]
In memory is probably too dangerous (potential for using a lot of memory over several ledgers) - also we don't want that blackbox to be destroyed on unexpected shutdown ; but yeah if there is a ~cheap way to get those on disk, it would work.

**Comment by MonsieurNicolas** [comment]
We probably need to bump this priority wise: as time goes on, the only meta around is the one on full validators that are likely not configured with cursors enabled - this means that meta may be discarded as soon as a publish occurs (so only 1 ledger left on disk at the extreme end)

**Comment by graydon** [comment]
agreed. I'm happy to take this, it should just be a matter of having a second meta stream and deciding a synchronicity, flush and rotate policy on it.
