### ISSUE TITLE
[Uncaught Exception] Cannot create PeerBareAddress with empty ip

### ISSUE THREAD

**Issue by terorie** [stellar/stellar-core#2613]
Shortly after a node goes out of sync, sometimes it crashes with the following uncaught exception.

```
[default FATAL] Got an exception: Cannot create PeerBareAddress with empty ip [ApplicationUtils.cpp:91]
terminating with uncaught exception of type std::runtime_error: Cannot create PeerBareAddress with empty ip
```

This error does not occur when a node is synced.

## Steps to Reproduce

unknown, but it should be possible to reproduce by forcing a node out of sync.

### stellar-core Version

The bug was observed with the following stellar-core versions:
- v13.2.0
- v13.1.0

### Environment
* Operation System & Version (Linux 4.15.0-1044-gcp on Ubuntu 18.04.2 LTS)
* Running official apt package in a Docker container

**Comment by MonsieurNicolas** [comment]
this was fixed in 14.0.0 (forgot to close it)
