### ISSUE TITLE
Resilience tests are flaky in the 002 environment

### ISSUE THREAD

**Issue by sisuresh** [stellar/stellar-core#2632]
## Issue Description
After enabling address sanitizer in the 002 environment, the `resilience tests` test case is failing a majority of the time. This test has always been flaky, but address sanitizer might be causing it to fail more.

I've also been able to reproduce this locally sometimes by running `src/stellar-core test 'resilience tests'` without address sanitizer.

## Expected Result
Test should pass.

## Actual Result
Resilience tests will fail with an error like - 

```
simulation/CoreTests.cpp:157: FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with messages:
  restart victim 0
  Simulation timed out
```

**Comment by hidenori-shinohara** [comment]
`src/stellar-core test 'resilience tests'  --rng-seed 3333` reproduces the bug.

**Comment by hidenori-shinohara** [comment]
I'm not sure if this is a fix, but replacing L152 in `CoreTests.cpp`

```
2 * nbLedgerStep * Herder::EXP_LEDGER_TIMESPAN_SECONDS, false);
```

with

```
20 * nbLedgerStep * Herder::EXP_LEDGER_TIMESPAN_SECONDS, false);
```

makes all the resilience tests pass with rng-seed 3333, 3334, ..., 3385.

**Comment by hidenori-shinohara** [comment]
Alternatively, not adding node `I` to the validator list of `A, B, C` seems to make the tests pass as well. (Node `I` is not added to the simulation network.)

I'm not sure if this is a fix either, but this might give an idea as to what the underlying issue is.
