### ISSUE TITLE
Captive Stellar-Core: Stream meta data starting from any ledger

### ISSUE THREAD

**Issue by bartekn** [stellar/stellar-core#2634]
## Description

Stellar-Core 12.3.0 added a great feature of streaming metadata (`LedgerCloseMeta`s) via a filesystem pipe:
> an experimental feature for generating meta data without inserting it into the database while replaying in memory, this allows to speed up meta data generation (for historical data) by several orders of magnitude

This really helped Horizon team to speed reingestion of entire pubnet history from weeks to around 1.5 days. Additional advantage of this new feature is decoupling Stellar-Core from Horizon. Currently Horizon is connecting to Stellar-Core database directly to get ledger data however it's causing many issues connected to operations (ex. missing ledgers if cursor is not updated).

It would be great to be able to use this mode not only in reingestion (offline mode) but also when ingesting newly closed ledgers (online mode).

### Explain why this feature is important

Allows completely decoupling Stellar-Core and Horizon and removing operational burden connected to running Stellar-Core used by Horizon.

### Describe the solution you'd like

We propose to add a new command to stellar-core: `run-from [starting_ledger]` that would start streaming from `starting_ledger` to the latest closed by a network and then would continue streaming new ledgers as they are closed.

### Describe alternatives you've considered

The current workaround we use when starting a new captive session is the following chain of commands that use a persistent DB:
* `stellar-core new-db`,
* `stellar-core catchup [starting_ledger-1]/0`,
* `stellar-core run`.

While it works fine, it has some disadvantages:
* It requires specifying a DB connection and maintaining a DB.
* Applying buckets stage is much slower when using a disk vs RAM.
* `stellar-core run` execution can be slow when it needs to wait for the next checkpoint.

The new command would solve all the issues above.

**Comment by MonsieurNicolas** [comment]
I don't know if we need a new subcommand with those semantics.

It seems to me that:
* the main functionality is actually related to `run` with the in-memory streaming mode, so maybe `run --in-memory`?
* we need is an additional option that allows to override the behavior when starting up from fresh (right now this is controlled by `CATCHUP_RECENT`).

I *think* that we also need to make sure that we pass in not only the ledger number but its hash as well as a way to have a contract that guarantees that states in different systems are in agreement.

We probably need to track what other features are needed for a "live" in memory watcher node. For example, we have (I think?) to ensure that the overlay database is persisted in that mode as to avoid (potentially very) long startup times when the node gets restarted.

**Comment by bartekn** [comment]
> we need is an additional option that allows to override the behavior when starting up from fresh (right now this is controlled by CATCHUP_RECENT).

Sounds good, except we need to be able to tell Stellar-Core exactly the ledger we want to start from. `CATCHUP_RECENT` would be guessing because we don't know exactly the sequence number of the last processed ledger by the network.

> I think that we also need to make sure that we pass in not only the ledger number but its hash as well as a way to have a contract that guarantees that states in different systems are in agreement.

This can be also done on a reader side (can check if hash of X-1 equals prev hash of X when X is read).

> For example, we have (I think?) to ensure that the overlay database is persisted in that mode as to avoid (potentially very) long startup times when the node gets restarted.

I think we don't want to use a DB at all in this mode. That's true that it would be faster for restarts but the init run (apply buckets) is actually much, much slower when using a DB compared to RAM (afair, 1 minute vs 15 minutes). Using a DB is also an ops burden which we want to avoid.

**Comment by MonsieurNicolas** [comment]
> Sounds good, except we need to be able to tell Stellar-Core exactly the ledger we want to start from. CATCHUP_RECENT would be guessing because we don't know exactly the sequence number of the last processed ledger by the network.

Yes, I didn't say we'd specify a value for `CATCHUP_RECENT`. Also, I imagine that that ledger to start from would always be a checkpoint ledger (with its hash), that way we can start to download & apply buckets on startup (without having to wait for SCP).

> This can be also done on a reader side (can check if hash of X-1 equals prev hash of X when X is read).

This is exactly what I don't want to happen as it's too critical to miss. The contract should make it impossible to have those kind of bugs.

> I think we don't want to use a DB at all in this mode. That's true that it would be faster for restarts but the init run (apply buckets) is actually much, much slower when using a DB compared to RAM (afair, 1 minute vs 15 minutes). Using a DB is also an ops burden which we want to avoid.

You're missing some context here. The database I am talking about would be a sqlite database that would live in the buckets folder and that would keep track of everything that overlay needs (a few hundred KBs), the ledger would still be in memory. I think we already have an (internal) operating mode in core already that allows to do this.
Without this, on restart, there would be significant overhead in just reconnecting to the network in a way that makes sense, and this would put pressure on "known peers" for no particularly good reason.

**Comment by graydon** [comment]
@bartekn posted a version of this in #2700, if you'd like to have a look and let me know if it's satisfactory?
