### ISSUE TITLE
Flaky test "LedgerTxnRoot prefetch"

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#2641]
Ran into this https://travis-ci.org/github/stellar/stellar-core/jobs/713841372

```
stellar-core test is a Catch v2.11.3 host application.
2	Run with -? for options
2	
2	Randomness seeded to: 18474
2	
2	-------------------------------------------------------------------------------
2	LedgerTxnRoot prefetch
2	  postgresql
2	  stop prefetching as cache fills up
2	-------------------------------------------------------------------------------
2	ledger/test/LedgerTxnTests.cpp:2388
2	...............................................................................
2	
2	ledger/test/LedgerTxnTests.cpp:2392: FAILED:
2	  REQUIRE( root.prefetch(keysToPrefetch) == (cfg.ENTRY_CACHE_SIZE / 2) )
2	with expansion:
2	  1000 (0x3e8) == 500 (0x1f4)
2	
2	<done>
2	===============================================================================
2	test cases:  2 |  1 passed | 1 failed
2	assertions: 22 | 21 passed | 1 failed
```

**Comment by rokopt** [comment]
It's possible that the test is flaky; the production code definitely is.  There's a copy/paste error in `LedgerTxnRoot::Impl::prefetch()`:

<pre><code>
[ ... ]
        case TRUSTLINE:
            insertIfNotLoaded(trustlines, key);
            if (trustlines.size() == mBulkLoadBatchSize)
            {
                cacheResult(bulkLoadTrustLines(trustlines));
                trustlines.clear();
            }
            break;
        case DATA:
            insertIfNotLoaded(data, key);
            if (data.size() == mBulkLoadBatchSize)
            {
                cacheResult(bulkLoadData(data));
                data.clear();
            }
            break;
        case CLAIMABLE_BALANCE:
            insertIfNotLoaded(claimablebalance, key);
            if (<b>data</b>.size() == mBulkLoadBatchSize)
            {
                cacheResult(bulkLoadClaimableBalance(claimablebalance));
                claimablebalance.clear();
            }
            break;
[ ... ]
</code></pre>

**Comment by rokopt** [comment]
> It's possible that the test is flaky; the production code definitely is.

The reason that I say it's possible that the test is flaky is that it reuses a reference to `getLedgerTxnRoot()` after a `commit()`:

```
        auto& root = app->getLedgerTxnRoot();

        auto entries = LedgerTestUtils::generateValidLedgerEntries(1000);
        LedgerTxn ltx(root);
        for (auto e : entries)
        {
            ltx.createOrUpdateWithoutLoading(e);
            keysToPrefetch.emplace(LedgerEntryKey(e));
        }
        ltx.commit();

        SECTION("prefetch normally")
        {
            LedgerTxn ltx2(root);
            std::unordered_set<LedgerKey> smallSet;
            for (auto const& k : keysToPrefetch)
            {
                smallSet.emplace(k);
                if (smallSet.size() > (cfg.ENTRY_CACHE_SIZE / 3))
                {
                    break;
                }
            }

            REQUIRE(root.prefetch(smallSet) == smallSet.size());
            ltx2.commit();
        }
        SECTION("stop prefetching as cache fills up")
        {
            LedgerTxn ltx2(root);
            REQUIRE(root.prefetch(keysToPrefetch) ==
                    (cfg.ENTRY_CACHE_SIZE / 2));
            REQUIRE(root.prefetch(keysToPrefetch) == 0);
            ltx2.commit();
        }
```

Is that allowed?  I thought that the `commit` potentially invalidated the `AbstractLedgerTxnParent` returned by `ApplicationImpl::getLedgerTxnRoot()`.  But that might just be me misunderstanding `LedgerTxn`s.

(If that _is_ wrong, then I think it will need to be fixed in `"Bulk load batch size benchmark"` as well; it appears to me to be doing the same.)

**Comment by jonjove** [comment]
Yes this is allowed. The semantics are:
- creating a nested `LedgerTxn` invalidates any existing `LedgerTxnEntry`s that were produced by the parent
- the parent will throw if asked to produce a new `LedgerTxnEntry` until the nested `LedgerTxn` has been rolled back
- the parent becomes usable again once the nested `LedgerTxn` has been committed

**Comment by rokopt** [comment]
> the parent becomes usable again once the nested LedgerTxn has been committed

Aha!  Thanks, that was the part I didn't gather.

**Comment by rokopt** [comment]
I don't know whether this is a problem or our intent, but it's also the case that even with the copy/paste fix, some lists of quantities of entries of each type can cause `prefetch()` to load more than `ENTRY_CACHE_FILL_RATIO * mMaxCacheSize` entries, if it ends up with enough entries modulo `mBulkLoadBatchSize` of each of multiple types.  For example, the following test...

```
        SECTION("prefetch to the max")
        {
            auto accountEntries =
                LedgerTestUtils::generateValidAccountEntries(199);
            auto offerEntries = LedgerTestUtils::generateValidOfferEntries(199);
            auto trustLineEntries =
                LedgerTestUtils::generateValidTrustLineEntries(199);
            auto dataEntries = LedgerTestUtils::generateValidDataEntries(199);
            auto claimableBalanceEntries =
                LedgerTestUtils::generateValidClaimableBalanceEntries(99);
            LedgerTxn ltx(root);
            std::unordered_set<LedgerKey> keysToPrefetch;
            for (auto e : accountEntries)
            {
                LedgerEntry le;
                le.data.type(ACCOUNT);
                le.data.account() = e;
                ltx.createOrUpdateWithoutLoading(le);
                keysToPrefetch.emplace(accountKey(e.accountID));
            }
            for (auto e : offerEntries)
            {
                LedgerEntry le;
                le.data.type(OFFER);
                le.data.offer() = e;
                ltx.createOrUpdateWithoutLoading(le);
                keysToPrefetch.emplace(offerKey(e.sellerID, e.offerID));
            }
            for (auto e : trustLineEntries)
            {
                LedgerEntry le;
                le.data.type(TRUSTLINE);
                le.data.trustLine() = e;
                ltx.createOrUpdateWithoutLoading(le);
                keysToPrefetch.emplace(trustlineKey(e.accountID, e.asset));
            }
            for (auto e : dataEntries)
            {
                LedgerEntry le;
                le.data.type(DATA);
                le.data.data() = e;
                ltx.createOrUpdateWithoutLoading(le);
                keysToPrefetch.emplace(dataKey(e.accountID, e.dataName));
            }
            for (auto e : claimableBalanceEntries)
            {
                LedgerEntry le;
                le.data.type(CLAIMABLE_BALANCE);
                le.data.claimableBalance() = e;
                ltx.createOrUpdateWithoutLoading(le);
                keysToPrefetch.emplace(claimableBalanceKey(e.balanceID));
            }
            ltx.commit();
            LedgerTxn ltx2(root);
            REQUIRE(root.prefetch(keysToPrefetch) ==
                    (cfg.ENTRY_CACHE_SIZE / 2));
            REQUIRE(root.prefetch(keysToPrefetch) == 0);
            ltx2.commit();
        }
```

...triggers the assertion...

```
REQUIRE( root.prefetch(keysToPrefetch) == (cfg.ENTRY_CACHE_SIZE / 2) )
   with expansion:
      895 (0x37f) == 500 (0x1f4)
```

**Comment by rokopt** [comment]
> I don't know whether this is a problem or our intent, but it's also the case that even with the copy/paste fix, some lists of quantities of entries of each type can cause `prefetch()` to load more than `ENTRY_CACHE_FILL_RATIO * mMaxCacheSize` entries, if it ends up with enough entries modulo `mBulkLoadBatchSize` of each of multiple types.

After further discussion, we do know about this, and are living with it for the moment at least.
