### ISSUE TITLE
autocheck is not integrated with RNG seed (Version: [1.32])

### ISSUE THREAD

**Issue by rokopt** [stellar/stellar-core#2663]
Issue #2641 is an example of a bug which turned out to be intermittent even in unit tests, which use virtual time and a reusable random-number-generator seed with the intent of allowing reproducible runs.

We've traced the cause of the non-determinism to the use within the `autocheck` library of a `std::random_device` which is not connected to the RNG with the fixed seed used by the rest of `stellar-core`.  `xdrpp` uses `autocheck` to generate random XDR values, and we in turn use `xdrpp`'s generators to generate random ledger entries.  So any unit tests which generate random ledger entries are subject to non-determinism.

As an experiment, I tried replacing `autocheck`'s `std::random_device` with `stellar::gRandomEngine`, which uses the seed from the command line.  With that change, instead of, for example, seed 18474 failing 1-2% of the time during my attempts to reproduce issue #2641 , I've now seen seed 18474 pass every one of 400 runs, whereas seed 32, for example, has failed every one of 750 runs.

That encapsulation-breaking change is obviously not one we will commit, but we should find a way to do this properly, as we're trying to eliminate all the sources of non-determinism in Catch unit tests that we can find.  Possibilities include:

- Using inline namespaces
- Modifying autocheck to parameterize it on an RNG, and submitting that code upstream

**Comment by MonsieurNicolas** [comment]
this may explain why we're having trouble with some of the bucket tests (that depend on autocheck to generate buckets)
