### ISSUE TITLE
[Build Failed] (Version: [stellar-core v14.0.0])

### ISSUE THREAD

**Issue by glenfidich75** [stellar/stellar-core#2718]
I try to build stellar-core v14.0.0 but it is failing every time.
Hope someone can help

OS: Ubuntu 16.04 LTS

**prerequisite:**
sudo apt-get install clang-8
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update

sudo apt-get install git build-essential pkg-config autoconf automake libtool bison flex libpq-dev parallel
sudo apt-get install clang-5.0
sudo apt-get install gcc-6
sudo apt-get install gcc-6 g++-6 cpp-6
sudo apt-get install clang-format-5.0

sudo apt-get install libc++-8-dev libc++abi-8-dev
sudo apt-get install libcapstone-dev libfreetype6-dev libglfw3-dev libgtk2.0-dev

**command:**
export CC=clang-8
export CXX=clang++-8
export CFLAGS="-O3 -g1 -fno-omit-frame-pointer"
export CXXFLAGS="$CFLAGS -stdlib=libc++"
export PKG_CONFIG_PATH=/home/stellar/pgsql/lib/pkgconfig
export LD_LIBRARY_PATH=/home/stellar/pgsql/lib

git clone https://github.com/stellar/stellar-core.git
cd stellar-core

git checkout -b v14.0.0 tags/v14.0.0 && git submodule init && git submodule update

./autogen.sh && ./configure --prefix=/home/stellar && make -j4

**result:**
libtool: link: g++ -std=c++14 -g -O2 -fno-omit-frame-pointer -pthread -DFMT_HEADER_ONLY=1 -Wall -Wno-unused-command-line-argument -Wno-unused-local-typedef -Wno-unknown-warning-option -Werror=unused-result                     -o stellar-core main/StellarCoreVersion.o bucket/BucketApplicator.o bucket/Bucket.o bucket/BucketInputIterator.o bucket/BucketList.o bucket/BucketManagerImpl.o bucket/BucketMergeMap.o bucket/BucketOutputIte                    rator.o bucket/FutureBucket.o bucket/MergeKey.o bucket/PublishQueueBuckets.o catchup/ApplyBucketsWork.o catchup/ApplyBufferedLedgersWork.o catchup/ApplyCheckpointWork.o catchup/ApplyLedgerWork.o catchup/Cat                    chupConfiguration.o catchup/CatchupManagerImpl.o catchup/CatchupRange.o catchup/CatchupWork.o catchup/DownloadApplyTxsWork.o catchup/VerifyLedgerChainWork.o crypto/Curve25519.o crypto/Hex.o crypto/KeyUtils.                    o crypto/Random.o crypto/SecretKey.o crypto/SHA.o crypto/ShortHash.o crypto/SignerKey.o crypto/SignerKeyUtils.o crypto/StrKey.o database/DatabaseConnectionString.o database/Database.o database/DatabaseUtils                    .o herder/Herder.o herder/HerderImpl.o herder/HerderPersistenceImpl.o herder/HerderSCPDriver.o herder/HerderUtils.o herder/LedgerCloseData.o herder/PendingEnvelopes.o herder/QuorumIntersectionCheckerImpl.o                     herder/QuorumTracker.o herder/TransactionQueue.o herder/TxSetFrame.o herder/Upgrades.o history/FileTransferInfo.o history/HistoryArchive.o history/HistoryArchiveManager.o history/HistoryManagerImpl.o histor                    y/InferredQuorum.o history/InferredQuorumUtils.o history/StateSnapshot.o historywork/BatchDownloadWork.o historywork/DownloadBucketsWork.o historywork/DownloadVerifyTxResultsWork.o historywork/FetchRecentQs                    etsWork.o historywork/GetAndUnzipRemoteFileWork.o historywork/GetHistoryArchiveStateWork.o historywork/GetRemoteFileWork.o historywork/GunzipFileWork.o historywork/GzipFileWork.o historywork/MakeRemoteDirWo                    rk.o historywork/Progress.o historywork/PublishWork.o historywork/PutFilesWork.o historywork/PutHistoryArchiveStateWork.o historywork/PutRemoteFileWork.o historywork/PutSnapshotFilesWork.o historywork/Resol                    veSnapshotWork.o historywork/RunCommandWork.o historywork/VerifyBucketWork.o historywork/VerifyTxResultsWork.o historywork/WriteSnapshotWork.o historywork/WriteVerifiedCheckpointHashesWork.o invariant/Accou                    ntSubEntriesCountIsValid.o invariant/BucketListIsConsistentWithDatabase.o invariant/ConservationOfLumens.o invariant/InvariantManagerImpl.o invariant/LedgerEntryIsValid.o invariant/LiabilitiesMatchOffers.o                     ledger/CheckpointRange.o ledger/GeneralizedLedgerEntry.o ledger/InMemoryLedgerTxnRoot.o ledger/LedgerHeaderUtils.o ledger/LedgerManagerImpl.o ledger/LedgerRange.o ledger/LedgerTxnAccountSQL.o ledger/LedgerT                    xnClaimableBalanceSQL.o ledger/LedgerTxn.o ledger/LedgerTxnDataSQL.o ledger/LedgerTxnEntry.o ledger/LedgerTxnHeader.o ledger/LedgerTxnOfferSQL.o ledger/LedgerTxnTrustLineSQL.o ledger/TrustLineWrapper.o main                    /Application.o main/ApplicationImpl.o main/ApplicationUtils.o main/CommandHandler.o main/CommandLine.o main/Config.o main/dumpxdr.o main/ExternalQueue.o main/main.o main/Maintainer.o main/PersistentState.o                     overlay/BanManagerImpl.o overlay/Floodgate.o overlay/ItemFetcher.o overlay/LoadManager.o overlay/OverlayManagerImpl.o overlay/OverlayMetrics.o overlay/PeerAuth.o overlay/PeerBareAddress.o overlay/Peer.o ove                    rlay/PeerDoor.o overlay/PeerManager.o overlay/PeerSharedKeyId.o overlay/RandomPeerSource.o overlay/SurveyManager.o overlay/SurveyMessageLimiter.o overlay/TCPPeer.o overlay/Tracker.o process/PosixSpawnFileAc                    tions.o process/ProcessManagerImpl.o scp/BallotProtocol.o scp/LocalNode.o scp/NominationProtocol.o scp/QuorumSetUtils.o scp/SCP.o scp/SCPDriver.o scp/Slot.o transactions/AllowTrustOpFrame.o transactions/Bum                    pSequenceOpFrame.o transactions/ChangeTrustOpFrame.o transactions/ClaimClaimableBalanceOpFrame.o transactions/ConfirmAndClearSponsorOpFrame.o transactions/CreateAccountOpFrame.o transactions/CreateClaimable                    BalanceOpFrame.o transactions/CreatePassiveSellOfferOpFrame.o transactions/FeeBumpTransactionFrame.o transactions/InflationOpFrame.o transactions/ManageBuyOfferOpFrame.o transactions/ManageDataOpFrame.o tra                    nsactions/ManageOfferOpFrameBase.o transactions/ManageSellOfferOpFrame.o transactions/MergeOpFrame.o transactions/OfferExchange.o transactions/OperationFrame.o transactions/PathPaymentOpFrameBase.o transact                    ions/PathPaymentStrictReceiveOpFrame.o transactions/PathPaymentStrictSendOpFrame.o transactions/PaymentOpFrame.o transactions/SetOptionsOpFrame.o transactions/SignatureChecker.o transactions/SignatureUtils.                    o transactions/SponsorFutureReservesOpFrame.o transactions/SponsorshipUtils.o transactions/TransactionBridge.o transactions/TransactionFrameBase.o transactions/TransactionFrame.o transactions/TransactionSQL                    .o transactions/TransactionUtils.o transactions/UpdateSponsorshipOpFrame.o util/FileSystemException.o util/Fs.o util/GlobalChecks.o util/HashOfHash.o util/Logging.o util/Math.o util/MetricResetter.o util/nu                    meric.o util/Scheduler.o util/SecretValue.o util/StatusManager.o util/Thread.o util/Timer.o util/TmpDir.o util/types.o work/BasicWork.o work/BatchWork.o work/ConditionalWork.o work/Work.o work/WorkScheduler                    .o work/WorkSequence.o bucket/test/BucketListTests.o bucket/test/BucketManagerTests.o bucket/test/BucketMergeMapTests.o bucket/test/BucketTests.o catchup/simulation/HistoryArchiveStream.o catchup/simulation                    /TxSimApplyTransactionsWork.o catchup/test/CatchupWorkTests.o crypto/test/CryptoTests.o crypto/test/ShortHashTests.o database/test/DatabaseConnectionStringTest.o database/test/DatabaseTests.o herder/simulat                    ion/TxSimTxSetFrame.o herder/test/HerderTests.o herder/test/PendingEnvelopesTests.o herder/test/QuorumIntersectionTests.o herder/test/QuorumTrackerTests.o herder/test/TransactionQueueTests.o herder/test/Upg                    radesTests.o history/test/HistoryTests.o history/test/HistoryTestsUtils.o history/test/SerializeTests.o historywork/test/HistoryWorkTests.o invariant/test/AccountSubEntriesCountIsValidTests.o invariant/test                    /BucketListIsConsistentWithDatabaseTests.o invariant/test/ConservationOfLumensTests.o invariant/test/InvariantTests.o invariant/test/InvariantTestUtils.o invariant/test/LiabilitiesMatchOffersTests.o ledger/                    test/LedgerCloseMetaStreamTests.o ledger/test/LedgerHeaderTests.o ledger/test/LedgerTests.o ledger/test/LedgerTestUtils.o ledger/test/LedgerTxnTests.o ledger/test/LiabilitiesTests.o main/test/CommandHandler                    Tests.o main/test/ConfigTests.o main/test/ExternalQueueTests.o overlay/test/FloodTests.o overlay/test/ItemFetcherTests.o overlay/test/LoadManagerTests.o overlay/test/LoopbackPeer.o overlay/test/OverlayManag                    erTests.o overlay/test/OverlayTests.o overlay/test/PeerManagerTests.o overlay/test/SurveyManagerTests.o overlay/test/SurveyMessageLimiterTests.o overlay/test/TCPPeerTests.o overlay/test/TrackerTests.o proce                    ss/test/ProcessTests.o scp/test/QuorumSetTests.o scp/test/SCPTests.o scp/test/SCPUnitTests.o simulation/CoreTests.o simulation/LoadGenerator.o simulation/Simulation.o simulation/Topologies.o test/fuzz.o tes                    t/FuzzerImpl.o test/TestAccount.o test/test.o test/TestExceptions.o test/TestMarket.o test/TestPrinter.o test/TestUtils.o test/TxTests.o transactions/simulation/TxSimCreatePassiveSellOfferOpFrame.o transact                    ions/simulation/TxSimFeeBumpTransactionFrame.o transactions/simulation/TxSimGenerateBucketsWork.o transactions/simulation/TxSimManageBuyOfferOpFrame.o transactions/simulation/TxSimManageSellOfferOpFrame.o t                    ransactions/simulation/TxSimMergeOpFrame.o transactions/simulation/TxSimScaleBucketlistWork.o transactions/simulation/TxSimTransactionFrame.o transactions/simulation/TxSimUtils.o transactions/test/AllowTrus                    tTests.o transactions/test/BumpSequenceTests.o transactions/test/ChangeTrustTests.o transactions/test/ClaimableBalanceTests.o transactions/test/ConfirmAndClearSponsorTests.o transactions/test/CreateAccountT                    ests.o transactions/test/ExchangeTests.o transactions/test/FeeBumpTransactionTests.o transactions/test/InflationTests.o transactions/test/ManageBuyOfferTests.o transactions/test/ManageDataTests.o transactio                    ns/test/MergeTests.o transactions/test/OfferTests.o transactions/test/PathPaymentStrictSendTests.o transactions/test/PathPaymentTests.o transactions/test/PaymentTests.o transactions/test/SetOptionsTests.o t                    ransactions/test/SignatureUtilsTest.o transactions/test/SponsorFutureReservesTests.o transactions/test/SponsorshipTestUtils.o transactions/test/TxEnvelopeTests.o transactions/test/TxResultsTests.o transacti                    ons/test/UpdateSponsorshipTests.o util/test/BalanceTests.o util/test/BigDivideTests.o util/test/BitSetTests.o util/test/CacheTests.o util/test/DecoderTests.o util/test/FsTests.o util/test/MetricTests.o util                    /test/SchedulerTests.o util/test/StatusManagerTest.o util/test/TimerTests.o util/test/Uint128Tests.o util/test/XDRStreamTests.o work/test/WorkTests.o  ../lib/libsoci.a ../lib/libmedida.a ../lib/lib3rdparty.                    a -lpq /home/hjyee/stellar/src/stellar-core/lib/xdrpp/xdrpp/libxdrpp.a ../lib/libsodium/src/libsodium/.libs/libsodium.a -pthread
bucket/BucketApplicator.o: In function `stellar::BucketApplicator::advance(stellar::BucketApplicator::Counters&)':
/home/hjyee/stellar/src/stellar-core/src/bucket/BucketApplicator.cpp:59: undefined reference to `stellar::Bucket::checkProtocolLegality(stellar::BucketEntry const&, unsigned int)'
bucket/BucketOutputIterator.o: In function `stellar::BucketOutputIterator::put(stellar::BucketEntry const&)':
/home/hjyee/stellar/src/stellar-core/src/bucket/BucketOutputIterator.cpp:70: undefined reference to `stellar::Bucket::checkProtocolLegality(stellar::BucketEntry const&, unsigned int)'
bucket/BucketInputIterator.o: In function `stellar::BucketInputIterator::loadEntry()':
/home/hjyee/stellar/src/stellar-core/src/bucket/BucketInputIterator.cpp:45: undefined reference to `stellar::Bucket::checkProtocolLegality(stellar::BucketEntry const&, unsigned int)'
collect2: error: ld returned 1 exit status
Makefile:2199: recipe for target 'stellar-core' failed
make[3]: *** [stellar-core] Error 1
make[3]: Leaving directory '/home/hjyee/stellar/src/stellar-core/src'
Makefile:1220: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/hjyee/stellar/src/stellar-core/src'
Makefile:546: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/hjyee/stellar/src/stellar-core'
Makefile:456: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by rokopt** [comment]
This looks like #2704 .  Can you retry after pulling #2705 ?
