### ISSUE TITLE
Can't build latest commit on MacOS

### ISSUE THREAD

**Issue by AndrejMitrovic** [stellar/stellar-core#2721]
## Steps to Reproduce

```
# Using commit 1b659cb0
./autogen.sh
./configure
make
```

Result:

```
/usr/local/include/xdrpp/cereal.h:98:5: error: no matching function for call to 'apply'
```

Using:

```
~/dev/stellar-core 1b659cb0 $ clang++ --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Is this a known issue?

**Comment by rokopt** [comment]
Do you have `xdrpp` installed locally?  I'd expect `stellar-core` to be picking it up from its `lib` directory, which contains git submodules, not from `/usr/local/include`.  I'm not on Mac, though, so I'm not sure.

There are some compilation errors in commit 1b659cb0 (commas missing in parameter lists, a constructor returning values, signatures of definitions being modified without the corresponding declarations being modified), but I am guessing that that `xdrpp` error is occurring before the compilation is getting to `stellar-core/src`.

**Comment by rokopt** [comment]
> Do you have xdrpp installed locally? I'd expect stellar-core to be picking it up from its lib directory, which contains git submodules, not from /usr/local/include.

It occurs to me that you didn't explicitly mention the `git submodule init` / `git submodule update` steps before `./autogen.sh`; did you do those?

**Comment by AndrejMitrovic** [comment]
> Do you have xdrpp installed locally? I'd expect stellar-core to be picking it up from its lib directory, which contains git submodules, not from /usr/local/include. I'm not on Mac, though, so I'm not sure.

Looks like that was the problem. Thanks a lot @rokopt.
