### ISSUE TITLE
Making isQuorumSetSane more informative

### ISSUE THREAD

**Issue by AndrejMitrovic** [stellar/stellar-core#2723]
Hi,

We have some downstream changes to SCP which we'd like to upstream into `stellar-core`. One of them is making `isQuorumSetSane` more informative so it's possible to see why a quorum set is considered unsafe to use.

In our fork we used `char**` for this reason (https://github.com/bpfkorea/agora/pull/549), however I can see alternative implementions:

- Use `std::string` for the `reason` parameter
- Alternatively, use logging instead

Do you have any preference, and would you accept such a feature if we provided the patch?

Thanks!

**Comment by MonsieurNicolas** [comment]
Yeah thank you.

This is fine. I would just make the interface a bit simpler:
`bool checkSanity(SCPQuorumSet const& qSet, int depth, char const*& errString)` as to mandate passing the error string (no default value, so that we never miss call sites) and avoid having to deal with `nullptr`.
