### ISSUE TITLE
Making the hash types and hashing routines user-definable in SCP

### ISSUE THREAD

**Issue by AndrejMitrovic** [stellar/stellar-core#2724]
Hi,

We have a downstream change to SCP which we're considering upstreaming to `stellar-core`. We wanted to use our own hashing routines. And secondarily we wanted to define our own Hash type. In our use-case we use `BLAKE2b` and require a 64-byte hash, compared to 32 byte hashes used in stellar-core.

The way we've modified SCP is as follows. We've introduced prototype functions `getHashOf` in a new header file `Hash.h`, and then defined them on our side. Here is [the diff](https://gist.github.com/AndrejMitrovic/c374651809a3b746e18531c0a579a817).

For changing the hashes into 64 bytes we made a less flexible change, by hardcoding the type to 64-bytes. The diff [is here](https://gist.github.com/AndrejMitrovic/356280d445bc6af551049bc25a3f056c). We want to make this flexible so the client code can define it. So this part of code will need more work.

Would you be open to accepting a patch which makes the hash type and hashing routines definable by the client code?

Thanks!

**Comment by MonsieurNicolas** [comment]
re: choice of hash function. The diff is incomplete/not against `stellar/master`, but the way we normally extend behavior is via the `SCPDriver` interface.
I suggest you add the appropriate method(s) to that interface, and move SHA256 specific behavior outside of the library entirely (ie to `herder/HerderSCPDriver.cpp`).

second diff: I suggest you figure out how to make the `Hash` type user defined first. I imagine that in your fork you would use your own `.x` files so you may not really need a change to do this (other than always using the type `Hash` in SCP and never `sha256`).

Does that make sense?

**Comment by AndrejMitrovic** [comment]
> The diff is incomplete/not against stellar/master

Right. We are actually trying to upgrade to the latest version, but realized our own patches are making it difficult - because we need to readjust them every time. So this is a diff against an older version.

Thank you for the tips!

**Comment by AndrejMitrovic** [comment]
> and move SHA256 specific behavior outside of the library entirely (ie to herder/HerderSCPDriver.cpp).

I should probably still make those SHA256 routines available and used by default as there might be other users of SCP which want to continue using SHA256. IOW the new routine(s) in SCPDriver would be virtual but would have a default implementation. 

Ideally downstream SCP users's code would not break when upgrading to a new version of SCP.
