### ISSUE TITLE
Figure out quadratic issue when we are collecting txs

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-core#275]

**Comment by jedmccaleb** [comment]
This doesn't seem quadratic to me. I think you first mentioned that it was @gmarceau ?

**Comment by gmarceau** [comment]
I don't know what Nicholas had in mind specifically. I do see that `HerderImpl::recvTransaction` does a full traversal of the `mReceiveTransaction` lists for every incoming transaction to check for duplicates and whether there is balance available to pay for fees.

**Comment by MonsieurNicolas** [comment]
for each new transaction, we verify the newly build transaction set is
valid. So yes, this is quadratic. (check includes signature verification in
particular that is expensive)

On Wed, May 13, 2015 at 8:41 AM, Guillaume Marceau <notifications@github.com
