### ISSUE TITLE
Tx Simulation: improve parameter checks and reporting

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/stellar-core#2759]
We should improve the experience of running simulation commands such as generate-bucketlist, generate-transactions, simulate-transactions. Currently, invalid parameters are not checked or surfaced right away (instead, we proceed and cause issues downstream, which makes it hard to understand what the problem is).

Potential improvements:
* generate-transactions, simulate-transactions:  because `--first-ledger-inclusive` depends on the state of the generated bucketlist, we can add a check that it is actually lcl + 1. Additionally, because we can only generate the bucketlist for checkpoint boundaries, we can round up `--first-ledger-inclusive` to the nearest checkpoint. 
* if `--first-ledger-inclusive` is definitely invalid even after the rounding, we should not start the simulation, and just fail with a proper message. Right now we silently start applying anyway, but I don't see a reason to allow gaps, as they only create additional errors during application.

**Comment by jonjove** [comment]
I don't think we should round up automatically. Better to just fail with a useful error message, so that the operator isn't surprised.
