### ISSUE TITLE
Memo porblem 

### ISSUE THREAD

**Issue by linecar** [stellar/stellar-core#2773]
Hi sir I will buy some stellar coin to my wallet. Wellat address confirmed my address but i am not add memo  code 
My memo code 3534875478
My gmail 
Linecarline653@gmail.com 
Please sir help me 
https://stellar.expert/explorer/public/tx/850f082d37a943c1e6bb5d69b465e2856ad0f05fd8bc7f7ce98a4f6c2b09eaee

**Comment by MonsieurNicolas** [comment]
this is not a core bug - please follow instructions in the issue template instead of deleting them

**Comment by linecar** [comment]
Hi sir I will buy some stellar coin to my wallet. Wellat address confirmed my address but i am not add memo code
My memo code 3534875478
My gmail
Linecarline653@gmail.com
Please sir help me
https://stellar.expert/explorer/public/tx/850f082d37a943c1e6bb5d69b465e2856ad0f05fd8bc7f7ce98a4f6c2b09eaee
