### ISSUE TITLE
The <= operator for BitSet is a bit confusing

### ISSUE THREAD

**Issue by hidenori-shinohara** [stellar/stellar-core#2800]
From the discussion on https://github.com/stellar/stellar-core/pull/2771... (The PR is not directly related)

The `BitSet` class implements the `<=` operator which shows whether a set is a subset of the other. This seems to be intentional as the test `src/util/test/BitSetTests.cpp` indeed checks the behavior of `<=`, and this is used at at least one place in the code (https://github.com/stellar/stellar-core/blob/master/src/herder/QuorumIntersectionCheckerImpl.cpp#L275)

However, this seems a bit confusing because
- Not all sets are comparable (e.g., `{1, 2}` and `{3, 4}` are neither `<=` nor `>=`.)
- It's not immediately clear what `b1 <= b2` is whereas `b1.isSubsetEq(b2)` is.

**Comment by graydon** [comment]
Hmm .. I dunno, I mean on the one hand I can't question the experience of feeling confusion on encountering it; on the other hand I'm not really sure it's out of place -- it's the standard partial order on the powerset lattice (of which sets are elements).

I can't decide if it meets (or if its associated `operator<` would meet) the C++ requirements for being a strict weak order. I think it would? But I guess if it's confusing we might as well remove it, I'm no particular fan of operator overloading anyways. I suspect I just added it to make the code read more like the paper.

**Comment by jonjove** [comment]
I'm not committed either way, but I think we should remove this definition of `operator<=`. My main argument for removing it is that there isn't an obvious definition of what `b1 <= b2` means. For example, comparison operators on `std::set` mean lexicographical comparison.  Meanwhile,`std::bitset` doesn't define comparison at all, as far as I can tell.

**Comment by rokopt** [comment]
> I can't decide if it meets (or if its associated `operator<` would meet) the C++ requirements for being a strict weak order.

I believe that it would fail those requirements because incomparability is not transitive?  For example {1} and {2} are incomparable and {2} and {1,3} are incomparable, but {1} and {1,3} are comparable.

**Comment by MonsieurNicolas** [comment]
The responses here confirm that we should remove it :)

And yes, @rokopt is right which implies it's not even close to something usable with the standard library.
