### ISSUE TITLE
Avoid corrupting local state when catching up

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#2813]
This is a relatively low hanging fruit.

Currently, when catching up to a target `LedgerHeader`, we first check that its `previousLedgerHash` corresponds to lcl's hash, then proceed to extract `LedgerCloseData` and call `LedgerManagerImpl::closeLedger`.

If there is a problem applying a ledger, the issue is detected when applying the *next* ledger in the chain, and the node is dead at that point (needs to be reset).

What we can do instead is modify `LedgerManagerImpl::closeLedger` so that it takes an expected `LedgerHeader` as a parameter and leave the node in its previous state (doesn't commit to SQL, doesn't discard any buckets, doesn't publish, doesn't publish any "meta" to the stream in captive mode) if there is a mismatch.

The only potentially tricky part here is that the side effects of `LedgerManagerImpl::transferLedgerEntriesToBucketList` have to be undone.
I am not 100% sure how this works today if there is an exception after calling that method, so probably a good place to start.

**Comment by MonsieurNicolas** [comment]
Technically the parameter needed is just the expected ledger header hash, not the full object

**Comment by MonsieurNicolas2** [comment]
I think we already do something acceptable.

We crash the node with
https://github.com/stellar/stellar-core/blob/2f9ce11b2e7eba7d7d38b123ee6da9e0144249f8/src/ledger/LedgerManagerImpl.cpp#L757-L761
