### ISSUE TITLE
Unverified ledgers streamed in `run --start-at-ledger` in catchup stage (Version: v15.1.0)

### ISSUE THREAD

**Issue by bartekn** [stellar/stellar-core#2832]
## Issue Description

I noticed that when running `run` with `--start-at-ledger` some ledgers (I think ledgers between last checkpoint before `[start-at-ledger]` and `[start-at-ledger]`) are streamed before verifying them. While Horizon ignores ledgers before `[start-at-ledger]` (fast-forward to requested ledger) other users may think these ledgers are verified and process them. I think Stellar-Core should not send these ledgers to the meta pipe.

## Steps to Reproduce

```
stellar-core run --in-memory --start-at-ledger=596030 --start-at-hash 4ac1c2c3c029c8ff8d9da7e28c1974376a3bc37bb7f7608883fd4b5a8fd63594 --conf stellar-core-testnet.cfg
```

I can provide a demo script if required.

## Expected Result

Ledgers not streamed until chain verified.

## Actual Result

Some ledgers sent to a stream before connecting to other nodes (and ensuring chain is correct).

### stellar-core Version
v15.1.0
Built locally from git tag.

### Environment
* MacOS Catalina 10.15.7
* Are you running from the command line? From a container? Command Line
* Did you pass in special parameters when building the app? No.

## Supporting Files

In this [log file](https://gist.github.com/bartekn/69e3b5bf595bad8a42e14b5433d243a0) you can see that ledgers are applied but the first `Got consensus` message appears later.

**Comment by MonsieurNicolas** [comment]
This is by design: you specified a trusted hash for ledger 596030 so core could verify that ledgers before (going back one ledger at a time from that trusted ledger) were correct.
So you're not seeing "untrusted ledgers": just the work needed to rebuild ledger 596030 based on the proof that was supplied on the command line.

**Comment by bartekn** [comment]
OK, I understand how it's able to verify chain now, thanks!
