### ISSUE TITLE
Sync full history

### ISSUE THREAD

**Issue by VladyslavLeveniukSecurrency** [stellar/stellar-core#2842]
Hi. I want to have full stellar history, but I can't. Please tell me what am I doing wrong?

I am trying to make full sync of Stellar test network. I have been trying to make several changes in the configuration, but none of them worked. 

Some more details on what I have tried:

1. Build stellar core and horizon from source code and make catchup before running core. 

stellar-core catchup 2 $last_ledger - 2

2. I set CATACHUP_RECENT to 2 
3. I used the CATCHUP_COMPLETE=true environment variable

In all the cases my node is in sync, but the best result I achieved is to get elder_ledger as 50000 which doesn't look like a full sync. Or in some cases it shows something near newest ledger.

Thus, the question is if I am doing anything wrong or missed something?

Here my latest configs. 

###CORE###

Docker image: stellar/stellar-core:15.1.0rc1-1405-90b27805

ENV variables:

 env = [
    "POSTGRES_PASSWORD=${random_password.stellar_core_postgres_password.result}",
    "HORIZON_PASSWORD=${random_password.stellar_horizon_postgres_password.result}",
    "compat_complete_PEER_PORT=11625",
    "compat_complete_HTTP_PORT=11626",
    "compat_complete_PEER_SEED=SBTEQJMDYCNRXRBEUUK7PTC737GVE24VSFVEHQXRALAARQCU5O246KVT",
    "compat_complete_VALIDATION_SEED=SACTBO4KQ3LYYRRKBST3ZCO24FYRDP2CYN3W5IPP2OTC3NUIKFGZSRRY",
    "CATCHUP_COMPLETE=true",
    "PREFERRED_PEERS=[\"core-testnet1.stellar.org\", \"core-testnet2.stellar.org\", \"core-testnet3.stellar.org\"]",
    "UNSAFE_QUORUM=true",
    "FAILURE_SAFETY=0",
    "VALIDATORS=[\"GDKXE2OZMJIPOSLNA6N6F2BVCI3O777I2OOC4BV7VOYUEHYX7RTRYA7Y\", \"GCUCJTIYXSOXKBSNFGNFWW5MUQ54HKRPGJUTQFJ5RQXZXNOLNXYDHRAP\", \"GC2V2EFSXN6SQTWVYA5EPJPBWWIMSD2XQNKUOHGEKB535AQE2I6IXV2Z\"]",
    "HISTORY_PEERS=[\"core_testnet_001\", \"core_testnet_002\", \"core_testnet_003\"]",
    "HISTORY_GET=wget -q -O {1} https://history.stellar.org/prd/core-testnet/%s/{0}",
    "NETWORK_PASSPHRASE=Test SDF Network ; September 2015"
  ]

CMD in Docker:

CMD ["/usr/local/bin/stellar-core", "run", "--conf", "/stellar-core.cfg”]

###HORIZON###

Entry point commands:

horizon_init_db

export LATEST_LADGER=$(curl -ks https://horizon-testnet.stellar.org/ | jq .core_latest_ledger)

horizon db reingest range 0 $LATEST_LADGER

CMD in Docker

CMD ["horizon”]

Thanks for your help.

**Comment by MonsieurNicolas** [comment]
In general, we close any issues that are
* unactionable (fill the template below under "Description")
* questions best served elsewhere

We have a small community of people that manages issues, and we want to ensure that the issues that remain open are high quality (so we actually get around to implementing them!).

### I have a question!

The stellar-core issues repository is meant for reporting bugs and feature requests related to stellar-core's implementation.

If you have a question, we would recommend that you take a look at Stellar's [developer portal][1], where you'll find comprehensive documentation related to Stellar.

If you can't find an answer to your question you can:
* submit a question to [Stellar's Stack Exchange][2].
* or ask one of [Stellar's communities][3].

[1]: https://www.stellar.org/developers/
[2]: https://stellar.stackexchange.com/
[3]: https://www.stellar.org/community/#communities
