### ISSUE TITLE
consider replacing `assert` in our codebase

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#2852]
We have plenty of calls to `assert` that should really be `releaseAssert`.

I noticed that we have them in archive/bucket related code.

**Comment by seekaddo** [comment]
@MonsieurNicolas  Hi Happy New Year.  😄 

I will like to work on this issue if nobody is currently working on it.

**Comment by MonsieurNicolas** [comment]
yeah go for it @seekaddo - before opening a PR check the [contributing guide](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md) in particular running tests, format and filling the license agreement

**Comment by seekaddo** [comment]
@MonsieurNicolas Thanks for the response and pointing me to the first steps.
1. I have already signed the "Contributor License Agreement."

2. I have setup the project and all testcases for the package bucket  and others are working after the build.

3. Concerning the issue `Improve HAS validation #2843` are the cleanup already done or planned or Can I just add them to my upcoming PR.

Package to work on:
src/bucket --> (I hope that is what you mean with comments above `archive/bucket` )
src/catchup
src/scp
src/herder
src/histroy
src/invariant
src/ledger
src/overlay
etc .....

**Comment by MonsieurNicolas** [comment]
Yeah ignore other PRs: what will happen is that you'll have to rebase anyways when we're ready to merge. So just take notes on which search/replace you had to do. As we're getting close to a release, I think that we should be able to get a bunch of PRs out of the way before this one.

**Comment by seekaddo** [comment]
Ok that sounds like a good plan. I will apply the changes to the remaining packages.
