### ISSUE TITLE
Unexpected txBadSeq error returned by /tx (Version: 15.1.0)

### ISSUE THREAD

**Issue by bartekn** [stellar/stellar-core#2871]
## Issue Description

I noticed a strange, unexpected behaviour in /tx endpoint. It returned `txBadSeq` error but at a time of submission the sequence number of the source was not taken yet. Here are the events according to Horizon log.

Time - January 8th 2021 [UTC] | Event
-|-
11.05.51 | [Transaction `f10fd64`](https://horizon.stellar.org/transactions/f10fd642b6027d7be8122af3bf3cff0f89b22c49c4bd0ae6170a658b290159f8) with sequence number 81111642797072807 is included in ledger 33445111.
11:05:56.110 | Horizon ingested ledger 33445111.<sup>1</sup>
11:06:18.702 | User submits [`bb941b7`](https://laboratory.stellar.org/#xdr-viewer?input=AAAAAgAAAAC68GMRUsA3cK6vJ7V89T5jONztW%2FJL1VGqJPB%2Bd579dQAAAH0BICqcABFhqAAAAAEAAAAAAAAAAAAAAABf%2BDzIAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAAAAAQqJAAAAAC68GMRUsA3cK6vJ7V89T5jONztW%2FJL1VGqJPB%2Bd579dQAAAAAAAAAAAAQqJAAAAAIAAAABTFRDAAAAAAC6t0dhV5SHK%2BZQKD6Qx4CYVxjpmL6NkWH3nzGW7oi1VgAAAAFVU0RUAAAAAKEzZhDpuPmzRl%2FENBVUCh5Bd0GLgQQB9u7uGKat9lNZAAAAAAAAAAF3nv11AAAAQNLgpSd4hIRwWzP7kueIxMoIeG2yN3sVFMk%2FQJZQ6PVaCn9nEgzMIzKG6hCP1yvU8%2FGdD%2BA3vWHsrzWuE5Fs6ww%3D&type=TransactionEnvelope&network=public) with sequence number equal 81111642797072808 to Horizon `/transactions`. Tx is submitted to Stellar-Core.
11:06:18.709 | Stellar-Core returns `AAAAAAAAAGT////7AAAAAA==` (bad sequence).
11:07:13.088 | Horizon ingested ledger 33445123.
11:07:18.698 | User submits another tx with the same sequence number (81111642797072808): [`e963bd2`](https://laboratory.stellar.org/#xdr-viewer?input=AAAAAgAAAAC68GMRUsA3cK6vJ7V89T5jONztW%2FJL1VGqJPB%2Bd579dQAAAH0BICqcABFhqAAAAAEAAAAAAAAAAAAAAABf%2BD0EAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAAAAAEO9QAAAAC68GMRUsA3cK6vJ7V89T5jONztW%2FJL1VGqJPB%2Bd579dQAAAAAAAAAAAAEO9QAAAAMAAAABRVRIAAAAAABGStPbx5szphDKFVmLW22XCr92TqKNOnJM24cgyBSn4QAAAAFVU0RUAAAAAKEzZhDpuPmzRl%2FENBVUCh5Bd0GLgQQB9u7uGKat9lNZAAAAAUxUQwAAAAAAurdHYVeUhyvmUCg%2BkMeAmFcY6Zi%2BjZFh958xlu6ItVYAAAAAAAAAAXee%2FXUAAABACrPJelpm0sh5gz3wfoAEel%2Bi%2FgM5ZyXZVmX5GzOiAKzJAwl9kR0pAMKfpkLhWBcEsQ6miNBIt%2B8I%2BdKSJ%2BURAw%3D%3D&type=TransactionEnvelope&network=public).
11:07:18.708 | Stellar-Core accepts tx with no errors.
11:07:20.586 | Horizon ingested ledger 33445124.
11:07:22 | [Transaction `e963bd2`](https://horizon.stellar.org/transactions/e963bd253ca178c01998809bb69534b4a161b08fa80849d7bb699edfc3ca8e41) is included in ledger 33445125.
11:07:25.382 | Horizon ingested ledger 33445125.

<sup>1</sup> Horizon ingestion events added to ensure that Stellar-Core was not out of sync at this time.

## Expected Result

I would expect the `/tx` endpoint to accept [`bb941b7`](https://laboratory.stellar.org/#xdr-viewer?input=AAAAAgAAAAC68GMRUsA3cK6vJ7V89T5jONztW%2FJL1VGqJPB%2Bd579dQAAAH0BICqcABFhqAAAAAEAAAAAAAAAAAAAAABf%2BDzIAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAAAAAQqJAAAAAC68GMRUsA3cK6vJ7V89T5jONztW%2FJL1VGqJPB%2Bd579dQAAAAAAAAAAAAQqJAAAAAIAAAABTFRDAAAAAAC6t0dhV5SHK%2BZQKD6Qx4CYVxjpmL6NkWH3nzGW7oi1VgAAAAFVU0RUAAAAAKEzZhDpuPmzRl%2FENBVUCh5Bd0GLgQQB9u7uGKat9lNZAAAAAAAAAAF3nv11AAAAQNLgpSd4hIRwWzP7kueIxMoIeG2yN3sVFMk%2FQJZQ6PVaCn9nEgzMIzKG6hCP1yvU8%2FGdD%2BA3vWHsrzWuE5Fs6ww%3D&type=TransactionEnvelope&network=public).

## Actual Result

Instead, it returned bad sequence error. The next transaction with the same sequence number got accepted and included in the ledger.

## Your Environment and Setup

This is Stellar-Core connected to Horizon in SDF pubnet cluster.

### stellar-core Version
15.1.0

**Comment by jonjove** [comment]
Based on my observations of transaction queue sizes and surge pricing at these times, I don't think there is anything particularly unusual here. It is plausible that there was already a transaction in the queue with sequence number 81111642797072808 when bb941b7 was submitted, in which case bad sequence would have been the expected result. Then if that transaction was subsequently banned, the later submission of e963bd2 would have a valid sequence number.

**Comment by MonsieurNicolas** [comment]
Closing for now as I don't think there is evidence of unexpected behavior at this time. We can reopen later.
