### ISSUE TITLE
[Special-case `LedgerKey` when fuzzing] (Version: 15.2.0])

### ISSUE THREAD

**Issue by rokopt** [stellar/stellar-core#2896]
## Special-case `LedgerKey` when fuzzing

I'm filing a separate issue for one of the potential fuzzing enhancements mentioned in [this comment](https://github.com/stellar/stellar-core/issues/1376#issuecomment-738278327) to #1376 :

> right now it's pretty much impossible for the fuzzer to generate operations that will operate on LedgerKey (like sponsorship), because the space is just too big.
a possible alternative could be to map a LedgerKey into 1(?) byte, and use that number as an index in the list of all LedgerKeys known when the operation gets executed. This can be done in a few ways:
The simplest way could be to just incorporate sponsorship into the setup (so have some accounts, trustlines, etc sponsored in the original Ledger state).
a more advanced way might be to split up the code that maps "compact binary form" and "in memory xdr". Where the first pass would do most of what it does today, and the second pass, done between operation application, would be to update some fields in a deterministic way.

I figure it would be useful to have a dedicated issue for discussion of just that, since it's a bigger piece than most of the others, and will likely involve multiple phases and PRs.

In addition to the sponsorships that Nicolas mentioned, another important use case for `LedgerKey` is `ClaimableBalance`s.

**Comment by rokopt** [comment]
I think my preference is for something built on the second ("more advanced way") of Nicolas's suggestions, because the code is already organized in such a way that I think would make it straightforward to plug in.  We already have a single place, `attemptToApplyOperations()`, which is responsible for submitting every operation performed during both setup and test runs.  It already post-processes certain specific operations:  it detects whether any `ManageOffer` returns something other than `MANAGE_OFFER_CREATED`, and if we're in setup, throws an exception, since that would indicate that we're not setting up the initial state that we meant to.  (For the same reason, it also detects errors and throws if they happen during setup -- that's operation-independent.)

It could therefore _pre_-process certain specific operations as well; we could special-case one class of operation at a time (sponsorship operations, claimable balance operations, and then any further ones that we wish to involving `LedgerKey`s, if there are any others).

Here's my first proposal for what pre- and post-processing to do.

Each class of operation -- such as "sponsorship-related" or "claimable-balance-related" any of whose operations uses `LedgerKey`s within the operation XDR will have an ordered map of hashes of `LedgerKey`s to `LedgerKey`s in the `TransactionFuzzer` object.  The map will contain all the `LedgerKey`s that have appeared within operation XDR during the setup phase or during a particular test run (whichever is running).  It will be cleared before each new test, in `resetTxInternalState()`, like the ledger entry cache.

When an operation succeeds which creates one or more `LedgerEntry`s which are legal to refer to in one or more of the operations for which we support `LedgerKey` mapping (we can incrementally add both the detection of entry-creating operations and the support for specific `LedgerKey`-using operations), we will hash the `LedgerKey` and add the hash/key pair to the maps for the specific operations that can use that type of `LedgerKey`.

When a fuzz test (not the setup phase!) submits an operation which refers to a `LedgerEntry` via a `LedgerKey` (or a key such as `Claimant` for a `ClaimableBalance`), `attemptToApplyOps()` will hash the key and search the appropriate map for the `LedgerKey` with the least key greater than or equal to the hash of the key in the submitted operation.  It will then modify the operation to convert the key into the one found by the lookup.  If no key is found (meaning that the hash of the key in the submitted operation was greater than the hash of any key in the map), then the key will be submitted unmodified, which will provide the occasional test of submitting an invalid key.

The effect, I believe, would be that operations that submit keys to `LedgerEntry`s will be distributed roughly equally among all the possible valid keys, as well as testing invalid keys a fraction of the time (equal to `1/(#(possible valid keys)+1)`).

**Comment by MonsieurNicolas** [comment]
I am not sure I understand the "hashing scheme" and the reason to find "keys greater than". That seems pretty slow in the context of fuzzing.

What I wrote in the issue was more like what we do for Account Entry: we simplify them down to "1 byte", we can do something simular with those other "key" types.
Dumbest thing I can think of is: imagine that we assign each ledger key a counter (incremented every time we have a new ledger key), and when we "unpack" a key, we just look things up by index - we only need 1 or 2 bytes worth of data for this to work per ledger key.

**Comment by rokopt** [comment]
> What I wrote in the issue was more like what we do for Account Entry: we simplify them down to "1 byte", we can do something simular with those other "key" types.
Dumbest thing I can think of is: imagine that we assign each ledger key a counter (incremented every time we have a new ledger key), and when we "unpack" a key, we just look things up by index - we only need 1 or 2 bytes worth of data for this to work per ledger key.

As it happens, @jonjove suggested the same simplification, and I'm already implementing exactly that!
