### ISSUE TITLE
stellar-core run Doesn't Work in version v15.2.0

### ISSUE THREAD

**Issue by YasinFaraji** [stellar/stellar-core#2901]
after stellar-core run command in terminal (Ubuntu18) log this output in terminal:
2021-02-03T17:00:44.095 GAOAR [Herder INFO] Asking peers for SCP messages more recent than 1

and repeat this after 10 seconds.
I install this version from source.

**Comment by MonsieurNicolas** [comment]
Looks like a config problem.

## Read before creating an issue

In general, we close any issues that are
* unactionable (fill the template below under "Description")
* questions best served elsewhere

We have a small community of people that manages issues, and we want to ensure that the issues that remain open are high quality (so we actually get around to implementing them!).

### I have a question!

The stellar-core issues repository is meant for reporting bugs and feature requests related to stellar-core's implementation.

If you have a question, we would recommend that you take a look at Stellar's [developer portal][1], where you'll find comprehensive documentation related to Stellar.

If you can't find an answer to your question you can:
* submit a question to [Stellar's Stack Exchange][2].
* or ask one of [Stellar's communities][3].

[1]: https://www.stellar.org/developers/
[2]: https://stellar.stackexchange.com/
[3]: https://www.stellar.org/community/#communities
