### ISSUE TITLE
Account Merge not working when account is sponsored (Version: 15.2.0)

### ISSUE THREAD

**Issue by secondclaw** [stellar/stellar-core#2914]
## Description
Account Merge does not work and fails with an Unknown Error (tx_internal_error) when any of account's entries (or at least Account and Signer) are sponsored. 

## Steps to Reproduce
Create an account that's sponsored by another. Example:
Sponsoring Account:
   public: GBA3SEKH7ACGPBKWBGOWVGRAKYI5IKLBDGXFJ4VC22Z5ICJMGZMNAUVS
 
New sponsored account:
   public: GDZZSVFJDKHNYOMXQO7V46M4USD6SK3UV67GW6RDZPTB27C43REJSSUT

Sponsored account created using the following:
Source Account: GBA3SEKH7ACGPBKWBGOWVGRAKYI5IKLBDGXFJ4VC22Z5ICJMGZMNAUVS
Operations:
1. Begin Sponsoring Future Reserves
Sponsored Id: GDZZSVFJDKHNYOMXQO7V46M4USD6SK3UV67GW6RDZPTB27C43REJSSUT
2. Create Account
Destination: GDZZSVFJDKHNYOMXQO7V46M4USD6SK3UV67GW6RDZPTB27C43REJSSUT
Starting Balance: 1
3. End Sponsoring Future Reserves
Source Account: GDZZSVFJDKHNYOMXQO7V46M4USD6SK3UV67GW6RDZPTB27C43REJSSUT

Account is created successfully

Attempt to merge account:
Source: GDZZSVFJDKHNYOMXQO7V46M4USD6SK3UV67GW6RDZPTB27C43REJSSUT
Operations: 
1. Account Merge
Destination: GBA3SEKH7ACGPBKWBGOWVGRAKYI5IKLBDGXFJ4VC22Z5ICJMGZMNAUVS

## Expected Result
Expectation is transaction is successful and Account Merge completes, or if deletion of sponsored accounts is not allowed, a specific error message (op_account_sponsored?) instead of generic one.

## Actual Result
extras.result_codes:
 {"transaction":"tx_internal_error"} 
Result XDR:
 AAAAAAAAAGT////1AAAAAA== 

## Your Environment and Setup
Reproduced in latest testnet stellar laboratory

This also happens if Signer is sponsored instead of account, and I suspect, its a general issue with deletion of anything that is sponsored.

The workaround for Account Merge is to first transfer sufficient quantity of Lumens to remove sponsorship, revoke sponsorship, then perform Account Merge.

**Comment by jonjove** [comment]
Hi @secondclaw, thank you for the report! We are already aware of this issue, and we are working on a fix which will be released in protocol version 16.

**Comment by MonsieurNicolas** [comment]
@secondclaw - you've included secret keys in your report, if those are not test accounts you should probably change your keys asap.

**Comment by secondclaw** [comment]
> Hi @secondclaw, thank you for the report! We are already aware of this issue, and we are working on a fix which will be released in protocol version 16.

Awesome, thank you! I just tested a workaround of adding revocation steps prior to Account merge operation, and it seems to work.

**Comment by MonsieurNicolas** [comment]
this is merged into master but the fix will only be visible when protocol 16 becomes active

**Comment by jonjove** [comment]
Protocol 16 is live, so this is fixed.
