### ISSUE TITLE
Fuzzer bug when attemptToApplyOps is called with more than 100 operations.

### ISSUE THREAD

**Issue by sisuresh** [stellar/stellar-core#2928]
https://github.com/stellar/stellar-core/blob/6b99ef893c7f13f22c7c72a7f66ea912aeb4ad73/src/test/FuzzerImpl.cpp#L532

`begin` should be `beginOpsInThisTx` on that line. This bug currently isn't being hit because `attemptToApplyOps` is never called with more than 100 operations. If it were hit, it would cause on infinite loop.

**Comment by rokopt** [comment]
Good catch!  I've created PR #2929.

**Comment by allysa08** [comment]
thankyuuu 💋
