### ISSUE TITLE
Change default behaviour for empty LOG_FILE_PATH to no log file

### ISSUE THREAD

**Issue by bartekn** [stellar/stellar-core#2943]
### Explain in detail the additional functionality you would like to see in stellar-core.

In some deployments sending log to stdout only is enough. It would be great to allow this by changing a default behaviour of empty `LOG_FILE_PATH` to: no log written to a file.

### Explain why this feature is important

Starting with Horizon 2.0.0 Captive Stellar-Core is a default method for obtaining ledger data. Right now we create a temporary folder where we store buckets (https://github.com/stellar/stellar-core/issues/2942) and a log file. However, we embed Stellar-Core logs in Horizon logs by reading stdout. Changing the default behaviour of `LOG_FILE_PATH` along with https://github.com/stellar/stellar-core/issues/2942 would allow Horizon to not store any files on disk (right now we store them in `/tmp`) and this will make initial setup much easier.

### Describe the solution you'd like

If `LOG_FILE_PATH` is not set or set to `""` Stellar-Core will not create a log file and will only print logs to stdout.

**Comment by MonsieurNicolas** [comment]
Defaults are hard :) This would be a breaking change for non captive core.

I am not sure I understand the ask: in the context of captive core, don't you have a _core_ configuration file anyways?

Like how are people configuring their quorum sets for example?

**Comment by Shaptic** [comment]
According to the [existing documentation](https://github.com/stellar/stellar-core/blob/71e8b431be12219f041c6e302aa0b00bfe197be3/docs/stellar-core_example.cfg#L12-L15), an empty string is supposed to do exactly this. Is that not true?

**Comment by ire-and-curses** [comment]
It doesn't have to be a default (although maybe that's cleaner). For our purposes it would also be fine if there was some non-default way to specify "no log file please".

@Shaptic when we tested it, we found that core writes logs to the current directory if no directory is specified.

The point is that we don't need a core log file at all, because all captive core logs are duplicated to Horizon logs.

**Comment by MonsieurNicolas** [comment]
@Shaptic is right: the default is to log to a file, but setting it to `LOG_FILE_PATH=""` should log to stdout

**Comment by bartekn** [comment]
> Defaults are hard :) This would be a breaking change for non captive core.

We can make a non-breaking change by adding a new value like `LOGGING_ENABLED` that defaults to `true`. `LOG_FILE_PATH` would be just the file location.

> I am not sure I understand the ask: in the context of captive core, don't you have a core configuration file anyways?

Yes, but the file is static and, I guess, we can even remove it after Core starts. Log file can grow up to gigabytes.

> According to the existing documentation, an empty string is supposed to do exactly this. Is that not true?

> @Shaptic is right: the default is to log to a file, but setting it to LOG_FILE_PATH="" should log to stdout

Hmm, it's confusing because in the first line it says the default is `stellar-core.log` (this is where I stopped reading 😉 ) but then: `You can set to "" for no log file`). If the latter is true (and I can see @MonsieurNicolas confirms), we can just close this issue. Will double check tomorrow and close it.

**Comment by bartekn** [comment]
Oh, I get it now... 🤦 I was thinking that the if the value was unset it was changed to an empty string so even if put `""` it would use `stellar-core.log` as a default. But in reality there are 3 options:
* value not set at all - defaults to `stellar-core.log`,
* empty string - no log at all,
* value set - the value is used as file name.
