### ISSUE TITLE
stellar-core_example.cfg has incorrect NETWORK_PASSPHRASE

### ISSUE THREAD

**Issue by NickJH** [stellar/stellar-core#2945]
## Issue Description

Using the configuration in the file stellar-core_example.cfg, stellar never gets past the `"state" : "Joining SCP"`

## Steps to Reproduce
run stellar-core with `--conf {path}stellar-core_example.cfg` (or copy it somewhere and modify it as required). In my file I updated just `LOG_FILE_PATH`, `BUCKET_DIR_PATH` and `DATABASE`.

## Expected Result
I would expect stellar to start syncing

## Actual Result
It sits forever on `"state" : "Joining SCP"`

## Your Environment and Setup
Probably n/a, but using ClearOS 7 (Centos 7 binary compatible) and postgresql 12.5 from the SCLo repos running on an alternative port

### stellar-core Version
`v15.3.0-7-gcfe1485-dirty` at commit `cfe1485fef236cdb969f536f656ec8c672358ab6`

### Environment
* ClearOS 7.9 (equivalent to Centos 7.9)
* run from the command line
* No special parameters passed to the compiler, just `libpq_CFLAGS=/usr/lib64/libpq.so` and `export libpq_LIBS=/usr/lib64/libpq.so`

### The fix
* Change `NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"` to `NETWORK_PASSPHRASE="Test SDF Network ; September 2015"` as the rest of the parameters in the file are for the test network. Alternatively change all the rest of the parameters to the live network.
* Note that after making the change you need to redo the `new_db`

**Comment by MonsieurNicolas** [comment]
this is on purpose: this file is used to document all possible configuration elements not to join any particular network
