### ISSUE TITLE
Introduce more variety into fuzzer setup configuration

### ISSUE THREAD

**Issue by rokopt** [stellar/stellar-core#2949]
https://github.com/stellar/stellar-core/issues/1376#issuecomment-738278327 lists some aspects of fuzzer setup that are overly symmetrical and don't exercise some features that we wish to fuzz:

> Trustlines and orders seem "uninteresting". Setup is fully symetrical. No variations on issuer/trustline flags.

As of #2904 and #2933 , fuzzer setup can set up account flags, trustline flags, and offers (as well as claimable balances, and sponsorships for each of those types of ledger entries) through `constexpr` arrays without modifying the executable code.  We should now take advantage of that to provide the variety suggested in #1376 , as well as whatever else we decide is potentially high-impact, which we could discuss in this issue.

**Comment by MonsieurNicolas** [comment]
done as per #3039
