### ISSUE TITLE
Parallel test information is incomplete in CONTRIBUTING.md

### ISSUE THREAD

**Issue by jonjove** [stellar/stellar-core#2972]
This was noticed by @leighmcculloch. We need to add information about `ALL_VERSIONS` and `BATCHSIZE` in order to synchronize documentation with the set of available features.

**Comment by leighmcculloch** [comment]
Unless you're working on this already in happy to take it.

**Comment by jonjove** [comment]
I would appreciate that. I opened this issue because I didn't have time to fix it at the moment. Also you just used it, so you might have a better perspective on what information would be helpful.

**Comment by leighmcculloch** [comment]
I have opened a PR addressing the missing configuration parameters in this issue, along with some other parameter and a configure flag that are important to know about: https://github.com/stellar/stellar-core/pull/2984.
