### ISSUE TITLE
Catchup should sanitize archive names used in filenames

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/stellar-core#2976]
Discovered while playing with the `--in-memory` mode. My config is taken directly from Stellarbeat:
```

[[VALIDATORS]]
NAME = "SDF 1"
PUBLIC_KEY = "GCGB2S2KGYARPVIA37HYZXVRM2YZUEXA6S33ZU5BUDC6THSB62LZSTYH"
ADDRESS = "3.90.255.55:11625"
HISTORY = "curl -sf http://history.stellar.org/prd/core-live/core_live_001/ -o {1}"
HOME_DOMAIN = "www.stellar.org"

[[VALIDATORS]]
NAME = "SDF 3"
PUBLIC_KEY = "GABMKJM6I25XI4K7U6XWMULOUQIQ27BCTMLS6BYYSOWKTBUXVRJSXHYQ"
ADDRESS = "3.238.240.236:11625"
HISTORY = "curl -sf http://history.stellar.org/prd/core-live/core_live_003/ -o {1}"
HOME_DOMAIN = "www.stellar.org"

[[VALIDATORS]]
NAME = "SDF 2"
PUBLIC_KEY = "GCM6QMP3DLRPTAZW2UZPCPX2LF3SXWXKPMP3GKFZBDSF3QZGV2G5QSTK"
ADDRESS = "52.207.236.180:11625"
HISTORY = "curl -sf http://history.stellar.org/prd/core-live/core_live_002/ -o {1}"
HOME_DOMAIN = "www.stellar.org"
```
The problem is that catchup uses archive names to construct filenames for downloaded data. If whitespaces are present, then catchup fails to download the files correctly:
```
2021-03-22T18:15:19.895 GD7GO [Process WARNING] process 92530 exited 6: curl -sf http://history.stellar.org/prd/core-live/core_live_003/history/02/0e/a8/history-020ea87f.json -o buckets/tmp/history-8b99e716d6d3d000/SDF 3-stellar-history.json
```

Removing any whitespaces from the archive names fixes the issue, so we should make sure that in the code archive names are properly sanitized before they are used in local filenames.

**Comment by MonsieurNicolas** [comment]
I think the problem is higher up in the stack as you can also have conflicts because of case (on Windows, the filesystem is case insensitive, but if the string contains non ascii codes, it may cause problems on arbitrary filesystems): `NAME` is supposed to be something that can be used as an alias for the public key for that validator (see `VALIDATOR_NAMES` in config).

We should only allow proper "identifiers" here: something like `[A-Za-z][_A-Za-z0-9]*` and make `VALIDATOR_NAMES` lookup in a way as to ignore case.

It's a breaking change, but it's better than allowing garbage in there.

**Comment by marta-lokhova** [comment]
Depends on how you look at it - we don't really _have_ to name these temp files using the node names, it's just something that we do and since the node names don't provide any guarantees on special characters, it's a bad thing to do. For this particular issue, simplest thing is probably to use random bytes (and avoid user input altogether)

**Comment by MonsieurNicolas** [comment]
I agree.
We'll just need to check if we need names to be deterministic (for retries or whatever)

**Comment by graydon** [comment]
I'm surprised at this -- I think temp filenames ought to be at worst random/nonces, not derived from config values.

**Comment by marta-lokhova** [comment]
agreed Graydon. Looks like it was like this since the beginning though. I opened a PR that should fix this issue.
