### ISSUE TITLE
Allow captive core to catchup from multiple archives

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/stellar-core#2977]
Currently, when running core with the `--in-memory` flag with `--start-at-ledger/hash`, we select a single archive to catchup from. The problem is that if the selected archive has issues (it's corrupt or stale or something else), then core ends up being stuck, unable to make progress. 
A better option would be to allow core to select from multiple available archives, similar to what we do during the normal catchup flow. Then in case of a failure, core can retry with a different archive. The fix for this seems very simple, as we need to remove the archive selection code in the in memory mode logic, and pass nullptr instead.

**Comment by MonsieurNicolas** [comment]
Yes this makes sense!

In the context of captive core, what we can do is stop the core process if catchup fails: Horizon will just restart it (so if we pick a random archive we're likely to get unstuck).

**Comment by marta-lokhova** [comment]
I don't think this will help: we don't reseed PRNG on restart, so you'd end up selecting the same archive (we already exit if the initial catchup fails in captive core)

What I'm proposing is allowing core to retry a failed download with a different archive (like we do in normal catchup) to get it unstuck.
