### ISSUE TITLE
Missing money from XLM was sent to my own wallet without memo id 

### ISSUE THREAD

**Issue by Zueilly777** [stellar/stellar-core#2983]
![Screenshot_20210324-125233_Coinbase](https://user-images.githubusercontent.com/81341276/112585501-4b3dfe00-8dd0-11eb-8f1f-dd5c46147ca2.jpg)
![Screenshot_20210324-173012_Chrome](https://user-images.githubusercontent.com/81341276/112585506-4c6f2b00-8dd0-11eb-9577-3f6fac7ed665.jpg)

**Comment by Zueilly777** [comment]
I can't found the money

**Comment by MonsieurNicolas** [comment]
not a bug
