### ISSUE TITLE
Problem running in ClearOS7/Centos7 when compiled with postgres support

### ISSUE THREAD

**Issue by NickJH** [stellar/stellar-core#2995]
## Steps to Reproduce
Compile stellar-core with postgres support in Centos7/ClearOS7. I have attached the spec file I used so you can see the manual steps, but compiliing from git gave the same problem when testing a few weeks ago.
[stellar-core.spec.txt](https://github.com/stellar/stellar-core/files/6250598/stellar-core.spec.txt)
Note this uses packages from the SCLo repos.
I used the spec file to create an rpm and then installed the rpm, but the problem should be the same if you directly compile and install stellar-core.

Then try to initialise the database using the configuration supplied. This will be an sqlite3 database:
```
[root@microserver ~]# runuser -l stellar -c '/usr/bin/stellar-core --conf /etc/stellar-core/stellar.cfg new-db'
runuser: warning: cannot change directory to /home/stellar: No such file or directory
/usr/bin/stellar-core: error while loading shared libraries: libpq.so.rh-postgresql12-5: cannot open shared object file: No such file or directory
```
This is odd for two reasons:
1. It should know the location of the file as is was exported as a parameter during compilation.
2. It should not need libpq.so.rh-postgresql12-5 as it is using an sqlite3 database

note the runuser warning is irrelevant.

## Expected Result
It should init the db

## Actual Result
It fails with the error message above

## Your Environment and Setup
ClearOS7

### stellar-core Version
15.4.0 self-compiled

### Environment
* Operation System & Version (You can usually obtain from `uname -a`)
ClearOS 7.9 `Linux microserver.howitts.local 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* Are you running from the command line? From a container?
Command line
* Did you pass in special parameters when building the app?
```
export libpq_CFLAGS=/opt/rh/rh-postgresql12/root/usr/lib64/libpq.so.rh-postgresql12-5
export libpq_LIBS=/opt/rh/rh-postgresql12/root/usr/lib64/libpq.so.rh-postgresql12-5

scl enable llvm-toolset-7 rh-postgresql12 ./autogen.sh
scl enable llvm-toolset-7 rh-postgresql12 '%{configure} --docdir=/usr/share/doc/%{name}-%{version}'
scl enable llvm-toolset-7 rh-postgresql12 make
```
* Please add any additional relevant configuration related to this bug report.

## Supporting Files
I can also supply a sources.download and the stellar-core.service file if you want to create an rpm, but you won't need them if compiling and installing from the command line directly. Or I can give you the srpm and rpm.

## Additional context
I think you can get round the problem by installing the stock postgres 9.2 at the same time and not exporting the two parameters, but you can't compile with postgres 9.2 on it s own as the requirement is for postgres>=9.5, and iirc, it leads to other issues if you do this.

My workaround is to symlink from /usr/lib64 to the file `ln -s /opt/rh/rh-postgresql12/root/usr/lib64/libpq.so.rh-postgresql12-5 /usr/lib64/libpq.so.rh-postgresql12-5`.

**Comment by MonsieurNicolas** [comment]
Hello.

if you don't need postgresql you can run configure with `--disable-postgres`

If you need it, you probably need to ask around - there are probably specific LDFLAGS that you need to pass in so that it links to the right postgres dev kit.

**Comment by NickJH** [comment]
It is linking correctly and compiling using the two flags I mentioned:
```
export libpq_CFLAGS=/opt/rh/rh-postgresql12/root/usr/lib64/libpq.so.rh-postgresql12-5
export libpq_LIBS=/opt/rh/rh-postgresql12/root/usr/lib64/libpq.so.rh-postgresql12-5
```
There is only one other libpq_ variable, `libpq_PKG_ERRORS` and that does not seem to be applicable.

Using thes flags, it knows to go for `libpq.so.rh-postgresql12-5` and not `libpq.so`, but it does not seem to be using its non-standard location.

Where can I ask about LDFLAGS?

**Comment by BOPOHA** [comment]
@NickJH

`/usr/bin/stellar-core: error while loading shared libraries:` means you have built a binary with dynamic modules.

if you run `ldd /usr/bin/stellar-core`
and you will see paths to linked modules, like `/usr/lib64/libpq.so.rh-postgresql12-5`

but the real file is located here `/opt/rh/rh-postgresql12/root/usr/lib64/libpq.so.rh-postgresql12-5`
to run binary the shared library must be loaded even if it won't use
thats why you see the error.
this is because you are using chroot (i.e. scl enable) to create Makefiles in your rpm  spec:

```
scl enable llvm-toolset-7 rh-postgresql12 ./autogen.sh
```

and i think we could find a way to build right,
but
since 
stellar-core requires clang>=10 and gcc>=8
there is no reason to use Centos 7 at all.


so, the issue doesn't make sense now

**Comment by NickJH** [comment]
@BOPOHA I do have a requirement to use ClearOS7 (built on Centos7), but I have it building correctly without postgresql support using llvm-toolset7. For the moment I will just accept it using sqlite.
