### ISSUE TITLE
历史数据越来越多，怎么配置修剪数据？

### ISSUE THREAD

**Issue by Black52** [stellar/stellar-core#3019]
"horizon_version": "2.1.1-fee60c9c1d96605258250cd5b83c373b9f5490cd",
  "core_version": "v15.1.0-86-g4ab5a20c",
  "ingest_latest_ledger": 32747292,
  "history_latest_ledger": 32747292,
  "history_latest_ledger_closed_at": "2020-11-23T16:00:03Z",
  "history_elder_ledger": 30683840,
  "core_latest_ledger": 34861065,
  "network_passphrase": "Public Global Stellar Network ; September 2015",
  "current_protocol_version": 15,
  "core_supported_protocol_version": 15

请问stellar-core.cfg里面哪个配置参数是控制保留历史数据的？

**Comment by MonsieurNicolas** [comment]
I am not sure what this issue is about. Please re-open in English and also fill in the information from the issue template.
