### ISSUE TITLE
[question] how to set one xlm account to destinationtag-required

### ISSUE THREAD

**Issue by past2017** [stellar/stellar-core#3036]
I am developer for an exchange, many of our users deposit to our platform's xlm address without an destinationtag which make us need deposit manually.
so i want to know is there a way to set one account is destinationtag-required, just like below ripples code 
```
const prepared = await api.prepareTransaction({
  "TransactionType": "AccountSet",
  "Account": "rPT1Sjq2YGrBMTttX4GZHjKu9dyfzbpAYe",
  "SetFlag": 1 // RequireDest
})
```
After set it, user will get an error when deposit to our xlm address without destination tag

**Comment by MonsieurNicolas** [comment]
This kind of thing in Stellar is done with "multiplex accounts" (already supported at the core protocol layer) - see https://github.com/stellar/stellar-protocol/issues/617 tracking the work remaining in various SDKs
