### ISSUE TITLE
expose individual peer information tracked by overlay via the peers endpoint

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#3041]
Right now core expose aggregate overlay metrics (exported via the metrics endpoint) and computes per peer metrics (not exposed as metrics).

We should export those as part of the `peers` endpoint (maybe with a new flag if it's too verbose).

This would allow to get a sense of certain things like number of bytes transferred etc on a per peer basis when debugging.

From a quick look at the code, it looks like many metrics are not computed on a per peer basis (because this information is not useful in the "network survey" context), but should be exposed as part of this work.
For example, `getOverlayMetrics().mMessageDrop` doesn't have a per peer equivalent.

On that note, we may want to use some template helper of sorts to update both metric types at once instead of manually keeping metrics them in sync with code like
```
    getOverlayMetrics().mByteRead.Mark(byteCount);
    mPeerMetrics.mByteRead += byteCount;
```

**Comment by hidenori-shinohara** [comment]
As Nicolas mentioned above, we have two classes for metrics:
- `OverlayMetrics` => aggregated over peers
- `PeerMetrics` => Per peer metrics.

`PeerMetrics` is _almost_ a subset of `OverlayMetrics`. The two major differences are:
- `PeerMetrics` keeps track of `mConnectedTime` and `OverlayMetrics` doesn't. This makes sense and I think we should keep this as is.
- `PeerMetrics` keeps track of message counts on top of byte counts for some metrics. Specifically, it's the following 4.

```
        uint64_t mUniqueFloodMessageRecv;
        uint64_t mDuplicateFloodMessageRecv;
        uint64_t mUniqueFetchMessageRecv;
        uint64_t mDuplicateFetchMessageRecv;
```

As far as I know, we are not going to calculate and expose all of these metrics for each peer.

- Question 1: Which aggregated metrics in `OverlayMetrics` do we want to expose for each peer?
- Question 2: What do we want to do for the 4 metrics that we only keep track of for each peer and don’t aggregate?
    - We can either
        - Option 1: Keep them as is (only do per-peer)
        - Option 2: Keep track of them for each peer AND aggregate by adding them to `OverlayMetrics`
        - Option 3: Not track of them at all.
    - Option 3 seems bad since we’ve added those metrics for a reason. I’m not sure about Option 1 or 2.

I think these will change the approach (e.g., if we add many metrics to `PeerMetrics`, maybe we should stop using `PeerMetrics` as there'd be a lot of duplicates?)

The following is the list of metrics in `OverlayMetrics` and I marked the ones that we already keep track of for each peer.

```cpp
struct OverlayMetrics
{
    OverlayMetrics(Application& app);
    medida::Meter& mMessageRead; // per-peer
    medida::Meter& mMessageWrite; // per-peer
    medida::Meter& mMessageDrop;
    medida::Meter& mAsyncRead;
    medida::Meter& mAsyncWrite;
    medida::Meter& mByteRead; // per-peer
    medida::Meter& mByteWrite; // per-peer
    medida::Meter& mErrorRead;
    medida::Meter& mErrorWrite;
    medida::Meter& mTimeoutIdle;
    medida::Meter& mTimeoutStraggler;
    medida::Timer& mConnectionLatencyTimer;

    medida::Meter& mItemFetcherNextPeer;

    medida::Timer& mRecvErrorTimer;
    medida::Timer& mRecvHelloTimer;
    medida::Timer& mRecvAuthTimer;
    medida::Timer& mRecvDontHaveTimer;
    medida::Timer& mRecvGetPeersTimer;
    medida::Timer& mRecvPeersTimer;
    medida::Timer& mRecvGetTxSetTimer;
    medida::Timer& mRecvTxSetTimer;
    medida::Timer& mRecvTransactionTimer;
    medida::Timer& mRecvGetSCPQuorumSetTimer;
    medida::Timer& mRecvSCPQuorumSetTimer;
    medida::Timer& mRecvSCPMessageTimer;
    medida::Timer& mRecvGetSCPStateTimer;
    medida::Timer& mRecvSendMoreTimer;

    medida::Timer& mRecvSCPPrepareTimer;
    medida::Timer& mRecvSCPConfirmTimer;
    medida::Timer& mRecvSCPNominateTimer;
    medida::Timer& mRecvSCPExternalizeTimer;

    medida::Timer& mRecvSurveyRequestTimer;
    medida::Timer& mRecvSurveyResponseTimer;

    medida::Timer& mMessageDelayInWriteQueueTimer;
    medida::Timer& mMessageDelayInAsyncWriteTimer;

    medida::Timer& mOutboundQueueDelaySCP;
    medida::Timer& mOutboundQueueDelayTxs;

    medida::Meter& mSendErrorMeter;
    medida::Meter& mSendHelloMeter;
    medida::Meter& mSendAuthMeter;
    medida::Meter& mSendDontHaveMeter;
    medida::Meter& mSendGetPeersMeter;
    medida::Meter& mSendPeersMeter;
    medida::Meter& mSendGetTxSetMeter;
    medida::Meter& mSendTransactionMeter;
    medida::Meter& mSendTxSetMeter;
    medida::Meter& mSendGetSCPQuorumSetMeter;
    medida::Meter& mSendSCPQuorumSetMeter;
    medida::Meter& mSendSCPMessageSetMeter;
    medida::Meter& mSendGetSCPStateMeter;
    medida::Meter& mSendSendMoreMeter;

    medida::Meter& mSendSurveyRequestMeter;
    medida::Meter& mSendSurveyResponseMeter;

    medida::Meter& mMessagesBroadcast;
    medida::Counter& mPendingPeersSize;
    medida::Counter& mAuthenticatedPeersSize;
    medida::Counter& mFlowControlPercent;

    medida::Meter& mUniqueFloodBytesRecv; // per-peer, we also count the number of messages per per.
    medida::Meter& mDuplicateFloodBytesRecv; // per-peer, we also count the number of messages per per.
    medida::Meter& mUniqueFetchBytesRecv; // per-peer, we also count the number of messages per per.
    medida::Meter& mDuplicateFetchBytesRecv; // per-peer, we also count the number of messages per per.
};
```

@marta-lokhova What do you think?

**Comment by marta-lokhova** [comment]
> What do we want to do for the 4 metrics that we only keep track of for each peer and don’t aggregate? 

Not sure I understand, why do we need to change this? The issue is around exposing this information in the peers endpoint. We don't need to rework the metrics, we just need to identify what we need to track. We shouldn't remove any of the PeerMetrics, because they are used in the survey. 

> I think these will change the approach (e.g., if we add many metrics to PeerMetrics, maybe we should stop using PeerMetrics as there'd be a lot of duplicates?)

I'm not sure I understand what you mean. Why will there be duplicates?

Regarding what information we need to expose in the peers endpoint, I'd add:
* async read/write metrics, as well as the write queue delay (see `overlay.delay.async-write` and `overlay.delay.write-queue`)
* flow control metrics (see `overlay.outbound-queue.*`)
* message drop rate
* I don't think we need to expose metrics per individual message type, as it's really verbose and not that helpful. We just want to give a general idea about how the connection is doing.

**Comment by hidenori-shinohara** [comment]
I'll work on adding those!

> why do we need to change this?
We don't. I was wondering if we wanted to change this!

> Why will there be duplicates?
The `PeerMetrics` struct and the `OverlayMetrics` struct have a lot of members with the exact same. If we continued to add more members of the same name, I figured that it might make sense to consolidate those two structs.

**Comment by marta-lokhova** [comment]
> The PeerMetrics struct and the OverlayMetrics struct have a lot of members with the exact same. If we continued to add more members of the same name, I figured that it might make sense to consolidate those two structs.

I don't think we should consolidate those, as they track different things (per peer internal counters that are only available on demand vs aggregate metrics that are stored in the global registry)
