### ISSUE TITLE
Retention Guarantees for Transaction Meta

### ISSUE THREAD

**Issue by jonjove** [stellar/stellar-core#3047]
### Explain in detail the additional functionality you would like to see in stellar-core.
There should be some retention guarantee for transaction meta. There are a few variations on how this could be designed, for example we might always retain the previous 24h or we might retain when a specific event occurs (eg. a node in your quorum set does not reach consensus).

### Explain why this feature is important
With changes to default maintenance scheduling and the introduction of the captive core model, it is possible that transaction meta will not be available for relatively recent ledgers. Transaction meta is an important debugging tool.

**Comment by MonsieurNicolas** [comment]
Forgot about issue #2607 that tracks this topic
