### ISSUE TITLE
Stellar Core missing config.h in for windows builds. (Version: 17.0.0)

### ISSUE THREAD

**Issue by wu-ziching** [stellar/stellar-core#3067]
## Issue Description

stellar-core/src/util/Backtrace.cpp contains an include:

`#include "config.h"`

This file is not generated during the build process for Windows, which means it must be created or copied over somehow in order to complete the build process outlined in the INSTALL-Windows.md instructions.

## Steps to Reproduce

Follow the INSTALL-Windows.md build instructions. Attempt to a Release build on the x64 architecture.

## Expected Result

Successful build.

## Actual Result

Visual Studio 2019 reports E1696: Cannot open source file: "config.h" in Backtrace.cpp

## Your Environment and Setup

Windows x64
Visual Studio Code 2019
PostgreSQL 13 (Project updated to reflect different include and linker input location)
Cygwin, installed Flex, Bison, curl, gcc-core, sed

### stellar-core Version
Master, v17.0.0

### Environment

Windows 10 x64
Visual Studio 2019
Release, x64 Build
Project updated to point to PostgreSQL 13 include and linker directory

## Additional context
Build works for v12.0.0, prior to the introduction of Backtrace.cpp.

**Comment by MonsieurNicolas** [comment]
Thanks for the report. Let me try this out

**Comment by MonsieurNicolas** [comment]
this was made irrelevant by the linked PR: we don't include that header anymore
