### ISSUE TITLE
make account creation an explicit operation

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#307]
Right now account creation is done implicitly by sending a payment to an account.

Issue with this approach is that:
* it is very easy for a sender to send to completely bogus "black hole" address
* an account that was merged can be revived by accident where
    * the private key may have been discarded
    * the account was a joint account (multiple signers) but it is being recreated with the master key
    * the master key may have been compromised
* maybe not as much of a problem but not having an atomic way to fund an account makes account creation racy.

We should just have a new operation "FundAccount".
As it's a "Test and Set" type of operation, it can be combined with other operations in a transaction:
For example, a gateway can then just submit transactions like [FundAccount, set options, etc...] that guarantee that the operations after the FundAccount only succeed if the account is new.

**Comment by jedmccaleb** [comment]
ok doing this.
