### ISSUE TITLE
race conditions (crash) on startup

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#3076]
Current master sometimes crashes on startup. This became more visible because of the time it takes to rebuild state after schema upgrades.

From what I see the races are in `ApplicationImpl::initialize`:

* `mCommandHandler = std::make_unique<CommandHandler>(*this);` is initialized fairly early - this exposes the HTTP port (allowing people to call commands before the app is fully initialized)
*  `mProcessManager = ProcessManager::create(*this);` is called after `newDB` and `upgradeToCurrentSchemaAndMaybeRebuildLedger` - the later ends up calling `applyBucketsForLCL` which calls `crank` (which allows http commands to be invoked)

The crash I ran into is that the command `metrics` is called by prometheus probes which tries to update metrics for all subsystems, in particular `mProcessManager` (which is not initialized).

**Comment by graydon** [comment]
This is may also be running in to the fact that we issue to the application a faux "self-check" HTTP command on startup (the diagnostics PR changes this behaviour but not too importantly).

**Comment by marta-lokhova** [comment]
I don't think the self-check command is impacted as the app is fully initialized by the time we schedule it.
