### ISSUE TITLE
Performing maintenance (?) slow in Captive-Core (Version: 17.1.0)

### ISSUE THREAD

**Issue by bartekn** [stellar/stellar-core#3083]
## Issue Description

I'm testing Horizon 2.5.0 release with Stellar-Core 17.1.0 which persists buckets between executions. I noticed that maintenance step (or procedure just before that step) is slow. It takes around 25 seconds on my local machine. This is causing Core to lose track of consensus and wait for the checkpoint. Stellar-Core logs (embedded in Horizon log) below and in linked Gist:
```
INFO[2021-06-15T15:09:00.018+02:00] Overlay: Connected to 116.202.133.115:11628   pid=58467 service=ingest subservice=stellar-core
INFO[2021-06-15T15:09:00.051+02:00] Overlay: Connected to 173.249.47.186:11625    pid=58467 service=ingest subservice=stellar-core
INFO[2021-06-15T15:09:00.264+02:00] Overlay: Connected to 3.83.213.217:11625      pid=58467 service=ingest subservice=stellar-core
INFO[2021-06-15T15:09:00.269+02:00] Overlay: Connected to 54.211.227.163:11625    pid=58467 service=ingest subservice=stellar-core
INFO[2021-06-15T15:09:00.269+02:00] Overlay: Connected to 54.80.125.159:11625     pid=58467 service=ingest subservice=stellar-core
INFO[2021-06-15T15:09:00.310+02:00] Overlay: Connected to 34.73.193.216:11625     pid=58467 service=ingest subservice=stellar-core
INFO[2021-06-15T15:09:00.753+02:00] Overlay: Connected to 3.112.83.11:11625       pid=58467 service=ingest subservice=stellar-core
INFO[2021-06-15T15:09:03.186+02:00] Overlay: Connected to 178.128.197.232:11725   pid=58467 service=ingest subservice=stellar-core
INFO[2021-06-15T15:09:27.905+02:00] default: Performing maintenance               pid=58467 service=ingest subservice=stellar-core
INFO[2021-06-15T15:09:27.905+02:00] History: Trimming history <= ledger 1482111 (rmin=4294967295, qmin=1482175, lmin=1482111)  pid=58467 service=ingest subservice=stellar-core
WARN[2021-06-15T15:09:32.903+02:00] Herder: Lost track of consensus               pid=58467 service=ingest subservice=stellar-core
```
Note: ~25 second delay before `default: Performing maintenance` log line.

## Steps to Reproduce

Run Horizon from `release-horizon-v2.5.0` branch.

## Expected Result

Captive-Core startup is fast.

## Actual Result

Captive-Core startup is slow: around 25s doing maintenance / something else.

### stellar-core Version
17.1.0

### Environment
* Operation System & Version (You can usually obtain from `uname -a`) MacOS
* Are you running from the command line? From a container? Captive-Core
* Did you pass in special parameters when building the app? None.
* Please add any additional relevant configuration related to this bug report.

## Supporting Files

Horizon logs (include Stellar-Core logs, filter by: `subservice=stellar-core`): https://gist.github.com/bartekn/bf1b26c21e82fca40d877f21c5ecdac5

**Comment by bartekn** [comment]
Debug logs: https://gist.github.com/bartekn/d5e0f7e6170faaf45d96dba740ddec5e

**Comment by bartekn** [comment]
I run non-captive mode (`stellar-core run` in terminal) with the same config (but using Postgres) and there's no pause.

**Comment by bartekn** [comment]
I also don't experience this problem in non-captive mode with `DATABASE="sqlite3://test.db"` so I assume it's something isolated to Captive-Core.

**Comment by MonsieurNicolas** [comment]
My guess is that this is a stale captive-core instance (Horizon + captive-core was down for more than 1 minute), so it starts up "in sync" and has to wait to be "out of sync" before seeing current SCP messages.

A way to confirm this is to run with `TRACE` level debugging for the `Herder` partition (I am opening an issue with Horizon: core logs seems to be truncated, which makes this harder than it should to debug) and look for messages `Ignoring SCPEnvelope outside of range`.

**Comment by bartekn** [comment]
It's working! I realized that out sync was happening because Captive-Core did some special `--start-from` calculations to support faster catchup in case of restart: it was always trying to start from the last checkpoint to prevent having to wait for the next checkpoint which includes a starting ledger (this should make Horizon state ingestion start faster if stet rebuild was necessary). Fixing the math there solved the problem.

**Comment by csokun** [comment]
Hi @bartekn, would you be able to share your solution? I believe I ran into the same issue.
