### ISSUE TITLE
I am using PostgreSQL but it gives SQLite error (Version: 17.1.0)

### ISSUE THREAD

**Issue by EminBudak** [stellar/stellar-core#3091]
stellar-core works fine with PostgreSQL. But stellar-horizon gives an SQLite error (I am using postgresql) after the upgrade.

stellar-horizon Version
2.4.1-74a59685619ed24fac872cfa7322a08ca7f1369f
go1.16.3

stellar-core Version
17.1.0 (fbc0325759ff75dd250cb5e175978669cdb4e90a)

**This my command to run horizon.**
`sudo -u stellar /usr/bin/stellar-horizon serve --ingest=true --network-passphrase="Public Global Stellar Network ; September 2015" --db-url="dbname=horizon user=stellar host=/var/run/postgresql" --stellar-core-db-url="dbname=stellar user=stellar host=/var/run/postgresql" --stellar-core-url="http://127.0.0.1:11626" --port="8000" --history-archive-urls="https://history.stellar.org/prd/core-live/core_live_001" --per-hour-rate-limit="9000" --stellar-core-binary-path="/usr/bin/stellar-core" --captive-core-peer-port="11625" --captive-core-config-path="/etc/default/stellar-captive-core-stub.toml" --captive-core-storage-path="/var/lib/stellar"`

INFO[2021-06-21T10:24:20.826Z] Starting horizon on :8000 (ingest: true)      pid=1326499
INFO[2021-06-21T10:24:20.826Z] Ingestion system initial state                current_state=start pid=1326499 service=ingest
INFO[2021-06-21T10:24:20.832Z] Resuming ingestion system from last processed ledger...  last_ledger=1 pid=1326499 service=ingest
INFO[2021-06-21T10:24:21.834Z] Ingestion system state machine transition     current_state=start next_state="resume(latestSuccessfullyProcessedLedger=1)" pid=1326499 service=ingest
INFO[2021-06-21T10:24:21.834Z] Preparing range                               from=2 pid=1326499 service=ingest
INFO[2021-06-21T10:24:22.592Z] default: Config from /var/lib/stellar/captive-core-026b1473/stellar-core.conf  pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:22.593Z] default: Generated QUORUM_SET: {              pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:22.593Z] "t" : 2,                                      pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:22.593Z] "v" : [ "sdf_live_3", "sdf_live_1", "sdf_live_2" ]  pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:22.593Z] }                                             pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:22.593Z] default: Assigning calculated value of 1 to FAILURE_SAFETY  pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:22.595Z] **Database: Connecting to: sqlite3://buckets/minimal.db**  pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:22.602Z] SCP: LocalNode::LocalNode@GCQFB qSet: 75b44e  pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:22.602Z] default: Listening on 127.0.0.1:11626 for HTTP requests  pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:22.603Z] default: Application destructing              pid=1326499 service=ingest subservice=stellar-core
ERRO[2021-06-21T10:24:22.604Z] **default: Exception occurred while shutting down: sqlite3_statement_backend::prepare: no such table: storestate**  pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:22.605Z] default: Application destroyed                pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:22.606Z] **default: Minimal database not found, creating one...**  pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:22.608Z] Database: Connecting to: sqlite3://buckets/minimal.db  pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:22.614Z] SCP: LocalNode::LocalNode@GCQFB qSet: 75b44e  pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:22.615Z] default: Listening on 127.0.0.1:11626 for HTTP requests  pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:22.615Z] default: Application destructing              pid=1326499 service=ingest subservice=stellar-core
ERRO[2021-06-21T10:24:22.616Z] **default: Exception occurred while shutting down: sqlite3_statement_backend::prepare: no such table: storestate**  pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:22.617Z] default: Application destroyed                pid=1326499 service=ingest subservice=stellar-core
ERRO[2021-06-21T10:24:22.618Z] **default: Got an exception: bind: Address already in use**  pid=1326499 service=ingest subservice=stellar-core
ERRO[2021-06-21T10:24:22.618Z] **default: Please report this bug along with this log file if this was not expected**  pid=1326499 service=ingest subservice=stellar-core
ERRO[2021-06-21T10:24:22.622Z] Error in ingestion state machine              current_state="resume(latestSuccessfullyProcessedLedger=1)" error="error preparing range: Error fast-forwarding to 2: stellar core exited unexpectedly: exit status 1" next_state=start pid=1326499 service=ingest
INFO[2021-06-21T10:24:23.624Z] Ingestion system state machine transition     current_state="resume(latestSuccessfullyProcessedLedger=1)" next_state=start pid=1326499 service=ingest
INFO[2021-06-21T10:24:23.628Z] Resuming ingestion system from last processed ledger...  last_ledger=1 pid=1326499 service=ingest
INFO[2021-06-21T10:24:24.629Z] Ingestion system state machine transition     current_state=start next_state="resume(latestSuccessfullyProcessedLedger=1)" pid=1326499 service=ingest
INFO[2021-06-21T10:24:24.629Z] Preparing range                               from=2 pid=1326499 service=ingest
INFO[2021-06-21T10:24:25.320Z] default: Config from /var/lib/stellar/captive-core-cb356ffc/stellar-core.conf  pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:25.320Z] default: Generated QUORUM_SET: {              pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:25.320Z] "t" : 2,                                      pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:25.320Z] "v" : [ "sdf_live_3", "sdf_live_1", "sdf_live_2" ]  pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:25.320Z] }                                             pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:25.320Z] default: Assigning calculated value of 1 to FAILURE_SAFETY  pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:25.324Z] **Database: Connecting to: sqlite3://buckets/minimal.db**  pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:25.342Z] SCP: LocalNode::LocalNode@GDHNB qSet: 75b44e  pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:25.342Z] default: Listening on 127.0.0.1:11626 for HTTP requests  pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:25.343Z] default: Application destructing              pid=1326499 service=ingest subservice=stellar-core
ERRO[2021-06-21T10:24:25.344Z] default: Exception occurred while shutting down: sqlite3_statement_backend::prepare: no such table: storestate  pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:25.347Z] default: Application destroyed                pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:25.349Z] **default: Minimal database not found, creating one...**  pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:25.352Z] Database: Connecting to: sqlite3://buckets/minimal.db  pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:25.360Z] SCP: LocalNode::LocalNode@GDHNB qSet: 75b44e  pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:25.361Z] default: Listening on 127.0.0.1:11626 for HTTP requests  pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:25.361Z] default: Application destructing              pid=1326499 service=ingest subservice=stellar-core
ERRO[2021-06-21T10:24:25.362Z] default: Exception occurred while shutting down: sqlite3_statement_backend::prepare: no such table: storestate  pid=1326499 service=ingest subservice=stellar-core
INFO[2021-06-21T10:24:25.367Z] default: Application destroyed                pid=1326499 service=ingest subservice=stellar-core
ERRO[2021-06-21T10:24:25.368Z] **default: Got an exception: bind: Address already in use**  pid=1326499 service=ingest subservice=stellar-core
ERRO[2021-06-21T10:24:25.368Z] **default: Please report this bug along with this log file if this was not expected**  pid=1326499 service=ingest subservice=stellar-core
ERRO[2021-06-21T10:24:25.380Z] Error in ingestion state machine              current_state="resume(latestSuccessfullyProcessedLedger=1)" error="error preparing range: Error fast-forwarding to 2: stellar core exited unexpectedly: exit status 1" next_state=start pid=1326499 service=ingest
INFO[2021-06-21T10:24:26.381Z] Ingestion system state machine transition     current_state="resume(latestSuccessfullyProcessedLedger=1)" next_state=start pid=1326499 service=ingest
INFO[2021-06-21T10:24:26.383Z] Resuming ingestion system from last processed ledger...  last_ledger=1 pid=1326499 service=ingest

**Comment by sokiaoba** [comment]
Same here. How did you solve the problem?
