### ISSUE TITLE
stellar-core in-memory mode: consider supporting bucket consistency invariant

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/stellar-core#3095]
We have BucketListIsConsistentWithDatabase invariant, which ensures that the bucketlist and the database do not deviate. However, when using in-memory mode, we have a special in-memory LedgerTxn, which does not support some of the functionality required for this invariant (specifically, `countObjects` is not allowed to be called on non-root LedgerTxn). As it might be useful to have the invariant enabled for this mode, we should investigate a fix for this.

**Comment by MonsieurNicolas** [comment]
To clarify is `BucketListIsConsistentWithDatabase` completely disabled (as in not even registered) when running "in memory mode" or it crashes if enabled (like when enabling all invariants)?

**Comment by marta-lokhova** [comment]
it's the latter.
