### ISSUE TITLE
ManageOfferSuccessResult in results-wwxxyyzz.xdr.gz does not contain offerID for deleted offers

### ISSUE THREAD

**Issue by programmer4567** [stellar/stellar-core#3172]
## Issue Description

`ManageOfferSuccessResult` (declared in [Stellar-transaction.x](https://github.com/stellar/stellar-core/blob/97aeb244ecde4926086f6797f2ee9c146b6b7116/src/xdr/Stellar-transaction.x#L933)) in the history file `results/ww/xx/yy/results-wwxxyyzz.xdr.gz` has the offerID if the offer was created or updated, but not when deleted, so it is not known which offer is being deleted. The [history docs](https://github.com/stellar/stellar-core/blob/master/docs/history.md) say `results-wwxxyyzz.xdr.gz` files "allow reconstruction the history of changes to the ledger without actually running the stellar-core transaction-apply logic", but this can not be possible without knowing which offers are deleted.

## Steps to Reproduce
Download a `results-wwxxyyzz.xdr.gz` history file and view any instance of `ManageOfferSuccessResult`

## Expected Result
`ManageOfferSuccessResult` should have the offerID for a deleted offer

## Actual Result
`ManageOfferSuccessResult` does not have the offerID for a deleted offer

**Comment by MonsieurNicolas** [comment]
yeah that sentence is misleading. I'll get it updated.

That file allows for rebuilding a simplified view which is enough for the vast majority of use cases.
In this case, there is a back link to the transaction, and the transaction tells you which offer is being deleted.

**Comment by programmer4567** [comment]
Thanks for the info. I see how the offer is linked to the transaction, but could you clarify how the transaction tells you which offer is being deleted since I don't see the orderID of a deleted order in any of the xdr definitions for the contents of `results-wwxxyyzz.xdr.gz`. Or would the orderID of a deleted order have to be found in `transactions-wwxxyyzz.xdr.gz`?
