### ISSUE TITLE
A double free in connection_pool::give_back?

### ISSUE THREAD

**Issue by anson-lo** [stellar/stellar-core#3184]
Hi developers, thank you for your checking. Is there a double-free at Line 172 and 178 due to the double unlocking of `pimpl_->mtx_`?

https://github.com/stellar/stellar-core/blob/ff56e7f207b918aae53710abcc001511ead7ece9/lib/soci/src/core/connection-pool.cpp#L157-L181

Best,

**Comment by jonjove** [comment]
There is not: only one of lines 172 and 178 can be reached in a single invocation due to the throw on line 173.
