### ISSUE TITLE
How to reserve a transaction sequence number ? 

### ISSUE THREAD

**Issue by tundak** [stellar/stellar-core#3224]
I have a multisig account and need to initiate a transaction for `set option` operation. So prepared a transaction which will be expired in 7 days and within this time all (3 out 3 signers) has to sign transaction.

How i can reserve this transaction sequence so another transaction can't use this sequence ? can't use Bump Sequence as document says 

[This operation invalidates any transactions with a smaller sequence number, and is often utilized in complex contracting scenarios.](https://developers.stellar.org/docs/start/list-of-operations/#bump-sequence)

how can i do this ?

**Comment by MonsieurNicolas** [comment]
This is not a core bug.
## Read before creating an issue

In general, we close any issues that are
* unactionable (fill the template below under "Description")
* questions best served elsewhere

We have a small community of people that manages issues, and we want to ensure that the issues that remain open are high quality (so we actually get around to implementing them!).

### I have a question!

The stellar-core issues repository is meant for reporting bugs and feature requests related to stellar-core's implementation.

If you have a question, we would recommend that you take a look at Stellar's [developer portal][1], where you'll find comprehensive documentation related to Stellar.

If you can't find an answer to your question you can:
* submit a question to [Stellar's Stack Exchange][2].
* or ask one of [Stellar's communities][3].

[1]: https://www.stellar.org/developers/
[2]: https://stellar.stackexchange.com/
[3]: https://www.stellar.org/community/#communities

**Comment by tundak** [comment]
at-lest if you can mention that it is possible with stellar or not @MonsieurNicolas ? i will write to community.
