### ISSUE TITLE
Fast Captive-Core Restart

### ISSUE THREAD

**Issue by jonjove** [stellar/stellar-core#3237]
If captive-core is slow to rebuild, it can lose sync causing a 5 minute delay. One way to potentially avoid this would be to add a network-only-client that buffers ledgers from the previously synced captive-core state until it completes its rebuild. Then the network-only-client streams the relevant buffered ledgers back to captive-core, completing the catchup.

**Comment by MonsieurNicolas** [comment]
this would work, another option maybe simpler would also be to move the captive core rebuild step into the normal "run" flow so that overlay etc gets started while the local state is being rebuilt (I think this is safer to do now that we've done changes to herder)
