### ISSUE TITLE
[History Archive Corruption prevents Core syncing as of ledger 38116434] (Version: 18.1)

### ISSUE THREAD

**Issue by gentrysherrill** [stellar/stellar-core#3263]
## Issue Description

When trying to catch up using the latest rev of stellar (18.1), as well as 18.0, Core seems to get stuck at ledger 38116434

From here, Core continually downloads history via the archives specified in the config file and then attempts to validate them

It determines downloaded history is bad, notifies via error message, then tries again, but never makes progress

A sample of the error messaging shown in Core's logs is:

```
2021-11-04T11:52:49.492 GD4C7 [History INFO] Catching up to ledger 38128639: Succeeded: batch-download-ledger-02459c7f-0245cc3f : 191/191 children completed
2021-11-04T11:52:49.492 GD4C7 [History INFO] Verifying ledgers [38116435,38128640)
2021-11-04T11:52:49.492 GD4C7 [History INFO] Verifying ledger [seq=38128639, hash=2f938d] against SCP hash
2021-11-04T11:52:49.492 GD4C7 [History INFO] Catching up to ledger 38128639: verifying checkpoint 1/191 (0%)
2021-11-04T11:52:49.572 GD4C7 [History ERROR] Bad ledger-header history entry: claimed ledger [seq=38116434, hash=780f0c] does not agree with LCL [seq=38116434, hash=90c3d6]
2021-11-04T11:52:49.572 GD4C7 [History ERROR] Catchup material failed verification - hash mismatch, propagating failure
2021-11-04T11:52:49.572 GD4C7 [History ERROR] One or more of history archives may be corrupted. Update HISTORY configuration entry to only contain valid ones
```

For reference, here are the currently configured history archive URLs from our `stellar-core.cfg` file:

```
# History archives

# Stellar.org history store
[HISTORY.sdf1]
get="curl -sf http://history.stellar.org/prd/core-live/core_live_001/{0} -o {1}"

[HISTORY.sdf2]
get="curl -sf http://history.stellar.org/prd/core-live/core_live_002/{0} -o {1}"

[HISTORY.sdf3]
get="curl -sf http://history.stellar.org/prd/core-live/core_live_003/{0} -o {1}"
```

## Steps to Reproduce
1. Stop Stellar-Core cleanly (i.e. ensure core is stopped before stopping underlying postgres database)
2. Restart postgres database
3. Restart Stellar-Core
4. Tail logs (`docker logs -f <core-container-name>` if using docker) and observe the continuous attempts to catch up and validate ledgers, followed by history archive corruption messaging

## Expected Result
Stellar Core should successfully catch up to the current network quorum, and ledger pages downloaded from archives should pass verification checks

## Actual Result
Stellar core is unable to sync new ledgers successfully or catch up, and displays error messaging indicating possible corruption with configured history archive sources

### stellar-core Version
18.1

### Environment

Running containerized within docker version 19.03.13, off of stellar-core latest tag (https://hub.docker.com/layers/stellar/stellar-core/latest/images/sha256-f39dbc9872ae65f1877c88d72673feda23e70bea2129304ff161e98a568ae076?context=explore)

## Additional context
Have tried this on both 18.1 and 18.0 with the same result; have not had problems previously

**Comment by jonjove** [comment]
Hi @gentrysherrill, thank you for the report. I will try to reproduce this now.

**Comment by gentrysherrill** [comment]
Thanks @jonjove - I'm currently testing syncing forward using 18.1 after rolling back to a zfs snapshot from ~30 hours ago on one of my Stellar nodes (had been running an earlier 18.0.x release on them when the network protocol upgrade went live first time around)

After rollback, core was able to download the full history archives and pass validation, but we're still applying ledgers and haven't quite reached 38116434 yet.  Will detail outcome once I have more.

**Comment by jonjove** [comment]
Not able to reproduce at this time. I'll need more information from you. Would you be willing to share the log file and your configuration file (secrets removed, of course)? If so, please make sure that the log file includes when it applied ledger 38116434 (there should be a log line like "applying ledger 38116434").

**Comment by Scobiform** [comment]
Same problem here. Looking into it.

**Comment by MonsieurNicolas** [comment]
closing as this issue has been inactive. reopen if you're still having this problem and have a repro
