### ISSUE TITLE
Irregular time of ledger close (Version: 13.1.0)

### ISSUE THREAD

**Issue by azakerjob** [stellar/stellar-core#3275]
Hi every one.
In my network, there are 6 quorums that each have 3 nodes. The network protocol is 13.1.0
The global threshold of network is 51% and inside threshold of each quorum is 33%
All nodes are sync but time of ledger close is very irregular
Some ledgers were closed in 50 seconds and just after that closed in one second.
This picture is 200 last closed ledgers in the network.
All nodes have a same NTP server.
Do you know its cause?
![close_ledger_time](https://user-images.githubusercontent.com/82448481/143050338-2d6a4b0a-6571-416c-9282-250041d62b1e.png)

**Comment by naghiloo** [comment]
Hi, we have the exact problem too. please help me.

**Comment by naghiloo** [comment]
for me, that was NTP problem.

**Comment by MonsieurNicolas** [comment]
Did you mean to report a bug on v13.1.0? If it's 18.1.0, please share your config files to see how you configured your quorum for all 6 nodes.

**Comment by jonjove** [comment]
No response since November, we can reopen if additional information ever arrives.
