### ISSUE TITLE
decide what to do wrt trust line deletion when offers are present

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#328]
When trying to delete a trust line and there are offers on either side for that currency, we should decide to either:
 * fail the deletion (and ask that people delete all offers)
 * delete all offers dealing with this currency
 * keep what we do now and just leave the offers behind (and spamming the order book)

**Comment by jedmccaleb** [comment]
@MonsieurNicolas  you ok with option 3?

**Comment by MonsieurNicolas** [comment]
If we make option 3 appealing (through the proper adjustment of reserve), it's OK.
I am in general worried that we don't have a good "garbage collection" policy: a lot of bogus entries can stay in the ledger for long period of time (in this case if the offers have a really bad rate, they will stick around forever). I guess the proper discussion to have is https://github.com/stellar/stellar-core/issues/466

**Comment by jedmccaleb** [comment]
Yeah the idea is that the reserve requirement is the incentive to clean up your bogus offers.

**Comment by jedmccaleb** [comment]
ok I'm closing
