### ISSUE TITLE
Very hard to start a validator cluster on a new network

### ISSUE THREAD

**Issue by NickJH** [stellar/stellar-core#3292]
## Issue Description

A new network of 3 Horizon nodes has been created. I'll call them dex1, dex2 and dex3. I am trying to set up a 3 validator cluster to join the horizon nodes. I'll call them v1, v2 and v3.

v1, v2 and v3 will have high quality. If they are configured with high quality, and `KNOWN_PEERS` and  `PREFERRED_PEERS` of dex1, dex2 and dex3, and `VALIDATORS` of dex1, dex2, dex3 and v1, v2 and v3 (but excluding their own node which is one of them), The nodes start but all get stuck on `"state" : "Joining SCP",` and make no progress.

The only way to get going seems to be make one of v1, v2 or v3 standalone by removing the v2 and v3 validators from its config and set its `QUALITY` to `MEDIUM` then restart the node. It will then start catching up. If you then restart the other nodes, they also start catching up.

It goes wrong again once the standalone node catches up if you add back in the other validators and change its `QUALITY` to `HIGH` and restart it before the other nodes have caught up. It gets stuck on `"state" : "Joining SCP",` and the other nodes stall and stop catching up.

It seems to be OK to rejoin the standalone node to the other two nodes once they have all caught up.

As a corollary of this, because of an error of mine, all three validators, v1, v2 and v3 went offline a few days ago. As soon as I noticed, I brought them back online but they, again, all got stuck on `"state" : "Joining SCP",` and made no progress. I had to go through the process of making one standalone and restarting the other two again until they caught up.

## Expected Result
Especially with the `KNOWN_PEERS` and  `PREFERRED_PEERS` set, I would have expected the nodes to have bootstrapped themselves. It is also bad that you can have an outage and not be able to just bring the nodes back online again.

## Your Environment and Setup
As this is a testing set up, all three validator nodes are running on a single hypervisor, but each has a different public IP (this is why they all went offline together as the hypervisor rebooted and the nodes were not set to auto-start).

### stellar-core Version
Validator Nodes are running stellar-core 18.1.0 (a9bf26e)
The horizon nodes are running stellar-core 17.3.0 (0b4c12a37b207dff0bfe5785ead403a000ca0f13) as part of Horizon 2.7.0-4228fac899e6040d5667e018871f34db19d76779

### Environment
* Operation System & Version: ClearOS 7.9 (binary compatible with Centos 7.9)
* Running from the command line.
* Special build parameters: Only to build without postgresql as I am running with sqlite3

I am not sure of the Stellar Horizon set up. It is running in docker on Ubuntu 20.04.2 LTS (Focal Fossa) running on Digital Ocean with AWS history.

## Supporting Files
I have attached one cfg file renamed to .txt to attach it here. [stellar.txt](https://github.com/stellar/stellar-core/files/7697201/stellar.txt).
The others are the same but with different VALIDATOR sections commented out and different secrets.

## Additional context
I tried an identical setup on the Stellar Public Network and it worked OK but I used 7 external HOME_DOMAINS with all their VALIDATORS. I did not notice a problem joining the Stellar Public Network but I may not have brought up all the nodes at the same time.

I would also like to be able to get this going without `KNOWN_PEERS` and  `PREFERRED_PEERS`

**Comment by leighmcculloch** [comment]
I saw the same thing when I tried to have a few validators join pubnet recently. They all got stuck joining SCP unless I configured one of the validators so it wasn't aware of it's peers. However, I was not using `KNOWN_PEERS` or `PREFERRED_PEERS`, so it's possible the scenario I experienced is very different.

**Comment by NickJH** [comment]
I tried without `KNOWN_PEERS` and `PREFERRED_PEERS` first and it didn't work either I then added them hoping it would solve the problem and it didn't. I have not reverted to without them both then tried to join by making one node standalone. I would guess it would work and it would be like you, but it is not ideal.

**Comment by MonsieurNicolas** [comment]
I am not sure what you're trying to do with the 2 domains/6 validators (quality here is irrelevant as you end up requiring both domains to vote).
Your logs should show you the generated quorum set which should allow you to make adjustments as needed.
In this case I suspect you're configuring nodes as validators even though you don't really need to (but I am not sure what your intent is).

**Comment by leighmcculloch** [comment]
@MonsieurNicolas independent of what we're each trying to do, is this situation we both describe a known issue? The situation being where the nodes start but are unable to join SCP unless one of the nodes is configured not to connect to its home domain peers.

**Comment by NickJH** [comment]
I have been asked to help someone set up a new network. There will be further domains appearing with three or four validator nodes in them. Are you saying that once the second domain is added the third will join without problems as it will be outvoted by the two domains already online, forcing it to come into line with them? If so, then I am not too concerned as it is only a transient issue, although it perhaps does show a vulnerable point in the network if a substantial part of the network goes out as an edge case. If not, what can I do to diagnose?

**Comment by NickJH** [comment]
The description of my set up appears to be slightly wrong.
There are 2 horizon nodes behind a load balancer.
Then there are 3 full validators (the dex1, dex2 and dex3 I mentioned above) running on one domain. They are in sync with the Horizon nodes.
I am than trying to add another set of 3 validators, v1, v2 and v3, on another domain and this is where I am running into problems unless I make one standalone to get it into sync with dex1-3 and then wait for the others to sync up before making v1, v2 and v3 know about each other.

**Comment by MonsieurNicolas** [comment]
closing as this issue has been inactive. reopen if you're still having this problem
