### ISSUE TITLE
Got an exception: Local node's ledger corrupted during close [Version: 18.2.0-798.b63c1622e.focal]

### ISSUE THREAD

**Issue by Denis-score** [stellar/stellar-core#3300]
I have a full node synced from genesis to ledger : 38765272 (used https://github.com/satoshipay/stellar-core-parallel-catchup to sync).

The server looks trying to get the lasts ledgers missing from the last synced and the last produced.

The archive looks correctly downloading : 
`Dec 31 16:02:06 rpc-stellar-dev-01 stellar-core[217872]: 2021-12-31T16:02:06.209 GC4Y6 [History INFO] Catching up to ledger 38973183: downloading ledger files 3249/3249 (100%)`

But after that, the server-core crash with the logs below :  

```
  stellar-core[217872]: 2021-12-31T16:02:32.864 GC4Y6 [History INFO] Verifying ledgers [38765272,38973184)
  stellar-core[217872]: 2021-12-31T16:02:32.864 GC4Y6 [History INFO] Verifying ledger [seq=38973183, hash=a5a2c4] against SCP hash
  stellar-core[217872]: 2021-12-31T16:02:32.864 GC4Y6 [History INFO] Catching up to ledger 38973183: verifying checkpoint 1/3249 (0%)
  stellar-core[217872]: 2021-12-31T16:02:33.299 GC4Y6 [History INFO] History chain [38765272,38973183] verified
  stellar-core[217872]: 2021-12-31T16:02:33.299 GC4Y6 [History INFO] Catching up to ledger 38973183: Succeeded: verify-ledger-chain
  stellar-core[217872]: 2021-12-31T16:02:33.299 GC4Y6 [History INFO] Catching up to ledger 38973183: Ready to run: herder-state-consistency-work
  stellar-core[217872]: 2021-12-31T16:02:33.299 GC4Y6 [History INFO] Catching up to ledger 38973183: Succeeded: herder-state-consistency-work
  stellar-core[217872]: 2021-12-31T16:02:33.299 GC4Y6 [History INFO] Downloading, unzipping and applying transactions for checkpoint 38765311
  stellar-core[217872]: 2021-12-31T16:02:33.299 GC4Y6 [History INFO] Downloading, unzipping and applying transactions for checkpoint 38765375
  stellar-core[217872]: 2021-12-31T16:02:33.299 GC4Y6 [History INFO] Downloading, unzipping and applying transactions for checkpoint 38765439
  stellar-core[217872]: 2021-12-31T16:02:33.299 GC4Y6 [History INFO] Downloading, unzipping and applying transactions for checkpoint 38765503
  stellar-core[217872]: 2021-12-31T16:02:33.299 GC4Y6 [History INFO] Downloading, unzipping and applying transactions for checkpoint 38765567
  stellar-core[217872]: 2021-12-31T16:02:33.299 GC4Y6 [History INFO] Downloading, unzipping and applying transactions for checkpoint 38765631
  stellar-core[217872]: 2021-12-31T16:02:33.299 GC4Y6 [History INFO] Downloading, unzipping and applying transactions for checkpoint 38765695
  stellar-core[217872]: 2021-12-31T16:02:33.299 GC4Y6 [History INFO] Downloading, unzipping and applying transactions for checkpoint 38765759
  stellar-core[217872]: 2021-12-31T16:02:33.299 GC4Y6 [History INFO] Downloading, unzipping and applying transactions for checkpoint 38765823
  stellar-core[217872]: 2021-12-31T16:02:33.299 GC4Y6 [History INFO] Downloading, unzipping and applying transactions for checkpoint 38765887
  stellar-core[217872]: 2021-12-31T16:02:33.299 GC4Y6 [History INFO] Downloading, unzipping and applying transactions for checkpoint 38765951
  stellar-core[217872]: 2021-12-31T16:02:33.299 GC4Y6 [History INFO] Downloading, unzipping and applying transactions for checkpoint 38766015
  stellar-core[217872]: 2021-12-31T16:02:33.299 GC4Y6 [History INFO] Downloading, unzipping and applying transactions for checkpoint 38766079
  stellar-core[217872]: 2021-12-31T16:02:33.299 GC4Y6 [History INFO] Downloading, unzipping and applying transactions for checkpoint 38766143
  stellar-core[217872]: 2021-12-31T16:02:33.299 GC4Y6 [History INFO] Downloading, unzipping and applying transactions for checkpoint 38766207
  stellar-core[217872]: 2021-12-31T16:02:33.299 GC4Y6 [History INFO] Downloading, unzipping and applying transactions for checkpoint 38766271
  stellar-core[217872]: 2021-12-31T16:02:33.299 GC4Y6 [History INFO] Catching up to ledger 38973183: Download & apply checkpoints: num checkpoints left to apply:3249 (0% >
  stellar-core[217872]: 2021-12-31T16:02:33.326 GC4Y6 [Herder INFO] Quorum information for 38973239 : {"agree":22,"cost":24701524,"delayed":0,"disagree":0,"fail_at":5,"ha>
  stellar-core[217872]: 2021-12-31T16:02:33.328 GC4Y6 [Ledger INFO] Got consensus: [seq=38973241, prev=5e129b, txs=433, ops=705, sv: [ SIGNED@COINQVEST_Germany txH: 80db8>
  stellar-core[217872]: 2021-12-31T16:02:33.328 GC4Y6 [Ledger INFO] Close of ledger 38973241 buffered. mSyncingLedgers has 58 ledgers
  stellar-core[217872]: 2021-12-31T16:02:33.344 GC4Y6 [Process WARNING] process 228712 exited 22: curl -sf https://stellar-history-de-fra.satoshipay.io/transactions/02/4f>
  stellar-core[217872]: 2021-12-31T16:02:33.344 GC4Y6 [History ERROR] Could not download file: archive SatoshiPay_DE_Frankfurt maybe missing file transactions/02/4f/83/tr>
  stellar-core[217872]: 2021-12-31T16:02:35.327 GC4Y6 [Tx INFO] applying ledger 38765272 (txs:821, ops:1000, base_fee:1000)
  stellar-core[217872]: 2021-12-31T16:02:35.560 GC4Y6 [default FATAL] Got an exception: Local node's ledger corrupted during close
  stellar-core[217872]: backtrace unavailable
  systemd[1]: stellar-core.service: Main process exited, code=killed, status=6/ABRT
  systemd[1]: stellar-core.service: Failed with result 'signal'.
  systemd[1]: stellar-core.service: Scheduled restart job, restart counter is at 14.
  systemd[1]: Stopped SDF - stellar-core.
```

Any idea of what happen ? And what I can do ? Thanks

**Comment by jonjove** [comment]
Hi @Denis-score, thank you for the report. I have not been able to reproduce the issue at this point. Are you able to reliably reproduce this? Do you have any further information?

**Comment by Denis-score** [comment]
Yes. Tried to reuse the script to resync the full blockchain. And same error.

Tried debug logs, but nothing relevant. 

Is there a way to repair the buckets folder ? Is there a way to fast synchronize a full archive node ? 

Thanks

**Comment by MonsieurNicolas** [comment]
> Yes. Tried to reuse the script to resync the full blockchain. And same error.

you mean if you run your script on an empty node, you run into the same issue? If so, can you share that script? It sounds like you have a repro :)

> Is there a way to repair the buckets folder ? Is there a way to fast synchronize a full archive node ?

The way to get passed such a corrupt state is to:
* write down the ledger number where your node got corrupted (I think this is `38765272` as per above)
* rebuild the state (`new-db`)
* then run `catchup` manually to a ledger before that corruption (like a hundred ledgers before to be safe, so something like `catchup 38765172/0`)
* and then start up the node normally using the `run` command

Note: do *not* reset your archive (ie, do not run `new-hist`), the steps above will add/replace in the archive as needed.

**Comment by Denis-score** [comment]
Thanks @MonsieurNicolas for your response.

The script I use to sync the full blockchain is : https://github.com/satoshipay/stellar-core-parallel-catchup a bit adapted with a stellar-core v18 docker image.
At the end it provide a postgresql db with the data and a buckets folder. 


Thanks for he procedure to repaid. I will try it.

**Comment by MonsieurNicolas** [comment]
if one of the containers fails with that error what would help would be to share the full logs for that container and the changes you made to that script

**Comment by Denis-score** [comment]
Sorry for the late reply @MonsieurNicolas 

What I changed to the script, was only to use stellar-core version 18 and commenting line 

``` docker-compose -f $DOCKER_COMPOSE_FILE -p catchup-job-${JOB_ID} run stellar-core stellar-core publish --conf /stellar-core.cfg 2>&1 >> $JOB_LOG_FILE```

I don't know if i'm right, but for me this line is only used to publish history archives for a "public" validator ?

Regarding the errors during running the script, I checked all logs file, and no errors was provided. All was looking working well.

I tried to do the steps you provide, after syncing with the script, but the new-db command only erased all data in the DB.

**Comment by MonsieurNicolas** [comment]
@Denis-score to make progress on this, what we're looking for is the full logs of the container that ends up crashing with the error `  stellar-core[217872]: 2021-12-31T16:02:35.560 GC4Y6 [default FATAL] Got an exception: Local node's ledger corrupted during close`

**Comment by MonsieurNicolas** [comment]
I am closing this as it's not actionable. Reopen if you can repro/give more details
