### ISSUE TITLE
overlay: remove the option to disable flow control

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/stellar-core#3387]
Currently, peers can opt out of flow control. With protocol 19, we have an opportunity to force nodes to upgrade to the latest version of core, so we should take advantage of that and make flow control mandatory for all connections.

**Comment by MonsieurNicolas** [comment]
not just remove the option but also require flow control to be enabled. This will have to be done when all nodes have flow control enabled

**Comment by marta-lokhova** [comment]
So I just looked at the dates, and I think adding this change to 19.1.0 is too early - we're on schedule to release at the end of May, but the protocol vote is June, 8. So we need to put this in 19.2.0 to be sure that all peers on the network have flow control is enabled by default (and probably also notify validators to make sure they don't switch it off in configs)
