### ISSUE TITLE
Host functions [jump cannon]

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#3403]
Issue tracking everything related to "host function" functionality in Jump Cannon

- [x] update the list below of host functions to add, in priority order
- [x] add host functions for storage
- [x] add host functions for binary objects
- [x] add host functions for BigInt
- [x] add host functions for crypto operations
- [x] finalize limits and gas cost
- [x] finalize tests
- [x] security review
- [x] performance testing
- [x] fuzzing

**Comment by MonsieurNicolas** [comment]
list was not finalized, I opened [#312](https://github.com/stellar/rs-soroban-env/issues/312) to discuss adding some new ones

**Comment by graydon** [comment]
Done
