### ISSUE TITLE
Cannot directly pipe stellar-core http-command info into anything (Version: 18.5.0+])

### ISSUE THREAD

**Issue by NickJH** [stellar/stellar-core#3420]
## Issue Description

It is no longer possible to do commands like `stellar-core --conf /etc/stellar-core/stellar.cfg http-command info | grep sta` and get any result

## Steps to Reproduce
Do `stellar-core --conf /etc/stellar-core/stellar.cfg http-command info | grep sta`

## Expected Result
You should be able to get something like:
```
[root@tysnode ~]# stellar-core --conf /etc/stellar-core/stellar.cfg http-command info | grep sta
      "startedOn" : "2022-03-30T15:31:42Z",
      "state" : "Synced!"
```
It is something easy to `watch` to see how synchronisation is going.

## Actual Result
You just see the full output of `stellar-core --conf /etc/stellar-core/stellar.cfg http-command info`

### stellar-core Version
v18.5.0 and v19.0.0

### Environment
* ClearOS 7.9 (binary compatible with Centos 7.9)
* Running from the command line.
* Did you pass in special parameters when building the app? 
Yes, to build without posgresql support

## Additional context
This is fallout from https://github.com/stellar/stellar-core/pull/3326.

Now you need to do `stellar-core --conf /etc/stellar-core/stellar.cfg http-command info 2&>1 | grep sta` as the `http-command info` now outputs to sterr and not stdout.

I know of no other program where you have to pipe stderr into grep to get basic screen output handled by grep.

**Comment by MonsieurNicolas** [comment]
ah yes this was not the intent. I think we just forgot that we have "http-command" (we ship a `stellar-core-cmd` wrapper with our debian package that just uses `curl` as it's basically the same thing), and the purpose in that PR was to make `offline-info` work like you would expect (so only emit in stdout the json to make it _easier_ to use from scripts). We'll do a sweep for the various subcommands and get this fixed for the next release.
