### ISSUE TITLE
Smart Contracts: Current-state RPC Node for contract querying

### ISSUE THREAD

**Issue by paulbellamy** [stellar/stellar-core#3484]
This is the real production version of https://github.com/stellar/soroban-cli/issues/58

Contracts need to be able to run preflight requests to:
- figure out which contract data keys are used
- estimate gas usage, and get fees
- simulate transaction calls and get back the result function output

For local sandbox the CLI can serve these requests itself (without core, see cli issue). But for pubnet/testnet the CLI (or horizon, wherever) would proxy these requests through to core. Hence, the API implementations should match.

**Comment by paulbellamy** [comment]
But, for local sandbox, we should have a mock http API server (which mirrors the core one) the CLI can start up for local development.

**Comment by paulbellamy** [comment]
A bunch of the text here was talking about the cli sandbox version of this. I moved that to issue soroban-cli#58, and focussed this on the core implementation.

**Comment by graydon** [comment]
@paulbellamy do you think there's a reason to do this in multiple separate requests, or can we just do a single preflight HTTP request that returns all of this information?

**Comment by paulbellamy** [comment]
Single request with all the info seems like a good idea, IMO.

**Comment by graydon** [comment]
https://github.com/stellar/stellar-core/pull/3500 is an initial stab at this.

**Comment by graydon** [comment]
Currently pending completion of events in txmeta for preflight. Not sure what needs doing on RPC server. https://github.com/stellar/stellar-core/pull/3516 -- probably won't get done this week, maybe next sprint.

**Comment by sisuresh** [comment]
Closed by https://github.com/stellar/stellar-core/pull/3516 (@paulbellamy let me know if something is missing).
