### ISSUE TITLE
add event/log recording and reporting machinery for contracts

### ISSUE THREAD

**Issue by graydon** [stellar/stellar-core#3487]
- [x] Make event-log buffer in host
- [x] Make host functions and host infrastructure for logging diagnostic / error messages
- [x] Define general / non-diagnostic event type in XDR-next
- [x] Emit relevant host events into event-log buffer
- [x] Route events back to transaction-invoker / preflight-invoker
- [x] Emit events into the meta stream

**Comment by graydon** [comment]
This is done enough for now. There will be ongoing work on the events-and-logging subsystem but there's one there now.

**Comment by graydon** [comment]
Reopening with more clarity on partial progress.

**Comment by graydon** [comment]
Progress on the host side as of https://github.com/stellar/rs-soroban-env/pull/342 -- just need to route it back to the invoker in the core endpoint / emit into the meta stream now.

**Comment by smac711** [comment]
@graydon Should the iteration and priority of this issue be updated given it is in the past and is it still a critical issue to close prior to Meridian? 

1.  iteration = ? 
2. priority = ?

**Comment by graydon** [comment]
stellar/stellar-core#3516 is now complete enough to review. There are a few rough edges in the design (CAP-0056 isn't entirely complete) but it should work.
