### ISSUE TITLE
checkpoint http-command not implemented (latest)

### ISSUE THREAD

**Issue by aabkn301** [stellar/stellar-core#3494]
## Issue Description

Looking at docs [1] https://github.com/stellar/stellar-core/blob/master/docs/software/commands.md there is a _checkpoint_ http-command

Looking at the code https://github.com/stellar/stellar-core/blob/master/src/main/CommandHandler.cpp#L104-L112 that command isn't implemented.

## Steps to Reproduce

- Starting a test network with 1 node as described in the docs https://github.com/stellar/stellar-core/blob/master/docs/software/testnet.md
- After the node is up and running use `stellar-core http-command checkpoint`, you'll got a 404

## Expected Result

As stated in the docs [1] the checkpoint command will _Triggers the instance to write an immediate history checkpoint. And uploads it to the archive._

## Actual Result

The command end with a 404.

**Comment by aabkn301** [comment]
Seems removed since 2018... https://github.com/stellar/stellar-core/commit/7f3e1d07b85def62c5f713d0f99d4d2c3beef5da

How we can trigger a checkpoint on demand instead of waiting the first 5 minutes?

**Comment by MonsieurNicolas** [comment]
This is a doc issue (missed when the command was removed).
That command was used for debugging some time ago and was unusable in production environments
