### ISSUE TITLE
Nomination: consider reducing which values to use from round leaders

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#3524]
Right now we pick the "highest value" from the set of values that a leader votes for as per https://github.com/stellar/stellar-core/blob/96951d3de4b12c7ad63577c878178f16a602fe3d/src/scp/NominationProtocol.cpp#L335

But if a round leader has already accepted at least one value (meaning a quorum already saw those values) we should limit our value selection to one of those values (assuming at least one of them is considered "valid" by the local node).

This would reduce the chance of multiple values having to compete during nomination, and as a consequence speed up consensus.

**Comment by marta-lokhova** [comment]
@nano-o it would be great to get your input on this optimization

**Comment by nano-o** [comment]
Is this saying that if the current leader has accepted a value `v` and also voted for a value `v'`, then other nodes should only vote for `v` and not `v'`?

**Comment by MonsieurNicolas** [comment]
To be exact:
```
if valids(leader.accepted) != {} ->
    pick_value_from(valids(leader.accepted))
else
    pick_value_from(valids(leader.votes))
```
where `valids` is a function to generate a set of valid values for the local node from a set of values.
and `pick_value_from` is a function that selects a value to vote for that the local node didn't vote for yet from a set of valid values.

**Comment by marta-lokhova** [comment]
Yeah, each node needs to select a value from the round leader to vote for, so current behavior is to select a value with the highest hash in the set {v, v'}. The updated behavior selects highest accepted value (v) if there are accepted valid values

**Comment by nano-o** [comment]
So is the reasoning is that `v'` should be closer to being confirmed than `v` and so it's better to "help" `v'`? It seems better than breaking ties based on hashes.
