### ISSUE TITLE
Allow InvokeHostFunctionOp to call the host function that creates token wrappers

### ISSUE THREAD

**Issue by sisuresh** [stellar/stellar-core#3547]
This issue depends on https://github.com/stellar/rs-soroban-env/issues/446. The name of the host function will be finalized once  that issue is completed.

**Comment by paulbellamy** [comment]
Does this also include the core work to be able to invoke the token contracts once created? or is there a separate issue for that?

**Comment by sisuresh** [comment]
There's no difference between how built-in contracts and wasm contracts are invoked.

**Comment by sisuresh** [comment]
Closed by https://github.com/stellar/stellar-core/pull/3553.
