### ISSUE TITLE
Set LedgerInfo on the host

### ISSUE THREAD

**Issue by sisuresh** [stellar/stellar-core#3548]
It looks like we never set [LedgerInfo](https://github.com/stellar/rs-soroban-env/blob/d43b29760d95a7fa5994e14756dbbfe6d79f8323/soroban-env-host/src/host.rs#L100) on the host, so information like the ledger timestamp will be missing. This information is required to run the crowdfunding dapp with core since it uses the timestamp to determine when the crowdfund ends.

**Comment by graydon** [comment]
https://github.com/stellar/stellar-core/pull/3557 is open with a small, not-tested implementation of this
