### ISSUE TITLE
Finalize soroban-era hashing, storage and emitting of TransactionResultSet vs. TransactionResultSetV2

### ISSUE THREAD

**Issue by graydon** [stellar/stellar-core#3555]
In PR https://github.com/stellar/stellar-core/pull/3516 we have a new class `TransactionResultSetFrame` that abstracts over `TransactionResultSet` and `TransactionResultSetV2` (the soroban-era TRS). At present, there's a flag `V2_CONSUMERS_READY=false` that causes all the V2-handling code to be disabled. This includes both the accumulation and hashing paths of TransactionResultSetFrame as well as the bottom of `LedgerManagerImpl::applyTransactions` where we call `storeTransaction` with -- currently -- the V1 XDR.

We need to figure out how to adapt everyone downstream to the V2 output before we switch over to it: both in meta and headers and also in checkpoint files emitted to the archives. This will therefore effect horizon and archivist, and also any catchup/replay machinery in core that depends on the presence of V1 checkpoints.

**Comment by sisuresh** [comment]
A less disruptive alternative to this change came up during a discussion with @MonsieurNicolas -
1. Remove the [SCVal](https://github.com/stellar/stellar-xdr/blob/c9c50a4e728f27a413dfaa9cf3a66654c635d78a/Stellar-transaction.x#L1744) returned on `INVOKE_HOST_FUNCTION_SUCCESS`.
2. Make that return value available to users in the meta by either adding a system event, or adding another vector in [TransactionMetaV3](https://github.com/stellar/stellar-xdr/blob/c9c50a4e728f27a413dfaa9cf3a66654c635d78a/Stellar-ledger.x#L437-L455).

If we did the above, we could keep transaction results in the archive without worrying about the cost of Soroban transaction results growing the archives. The downside is that classic Stellar operations will continue to grow the archives, but that can be addressed later if needed. We still need a location to include the hash of `TransactionMetaV3` in the ledger hash though. I think we could do this by including the hash in a `LedgerHeaderExtensionV2`. This would allow us to get rid of TransactionResultSetV2.

**Comment by graydon** [comment]
Interesting possibility. I also wonder though if the return `SCVal` is likely to be very big. Or I guess more concretely, if given our discussion of size limits, it might be reasonable to just limit it to the small-value size limit, which I _think_ we'd be enforcing anyways as a limit on any event we emit.

**Comment by graydon** [comment]
(Maybe I'm misunderstanding: are you suggesting that contract calls don't themselves return values at all? Or merely that at the top level of a transaction invocation, we wouldn't record the return value in the TRS? The former seems like it'd break a lot, the latter might be ok, given that nobody really even knows when their transaction is going to be applied after submission, or even _if_ it's going to be applied; users have to "wait and listen" for _something_ anyways)

**Comment by sisuresh** [comment]
The latter - We wouldn't record the return value in the TRS. It'll be in the meta instead.

**Comment by sisuresh** [comment]
I pushed what I have so far for this [here](https://github.com/stellar/stellar-core/pull/3714).
