### ISSUE TITLE
Invoking host function tests are incomplete

### ISSUE THREAD

**Issue by jayz22** [stellar/stellar-core#3559]
The [tests](https://github.com/stellar/stellar-core/blob/master/src/transactions/test/InvokeHostFunctionTests.cpp#L205) are missing for cases: `HostFunction::HOST_FN_CREATE_TOKEN_CONTRACT_WITH_SOURCE_ACCOUNT` and `HOST_FN_CREATE_TOKEN_CONTRACT_WITH_ASSET`.

**Comment by sisuresh** [comment]
`HostFunction` has been [updated](https://github.com/stellar/stellar-xdr/blob/next/Stellar-transaction.x#L523) (and it will probably be renamed soon), but we should still evaluate the core test case. For example, it looks like the `HostFunction` types are covered, but not all cases of `HOST_FUNCTION_TYPE_CREATE_CONTRACT` are covered (like creating the Stellar Asset Contract).

**Comment by dmkozh** [comment]
This has been changed quite a bit and now we should have decent test coverage (inclluding e2e test for SAC in core). We might be adding more tests, but that's not what the issue is about.
