### ISSUE TITLE
[Soroban] Use the InvokeHostFunctionOp source account

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/stellar-core#3571]
@sisuresh was telling me that the source account attached to the InvokeHostFunctionOp is ignored.

This seems surprising and limiting for invoking source accounts.

This binds account sequence numbers with the source account invoking a transaction, which seems unnecessary.

I expect we ignored the source account because all authentication in Soroban would be done by contracts and the source account would have no material impact on the invocation. That seems right. However, Soroban's auth model has changed to support source accounts and the source account of the operation should take precedence over the transaction source account if it is present.

cc @sisuresh @graydon @MonsieurNicolas @tomerweller

**Comment by sisuresh** [comment]
I think there was a misunderstanding. The source account on the `Operation` is not ignored for `InvokeHostFunctionOp`. CAP-0052 specifies that the `Operation` source account must be null, but as far as I can tell, this restriction was never implemented.

If the `Operation` source account is set, `InvokeHostFunctionOp` will use it.

**Comment by leighmcculloch** [comment]
Thanks for clearing up my misunderstanding. 

Does the "use it" mean that the operation's source account will be passed into the host and be used as the invoker?

**Comment by sisuresh** [comment]
Yes, the operation source account will be used as the invoker.

I think the restriction in CAP-0052 was specified because in the pre `msg.sender` world, the only thing the source account would do is pay the fee, and setting the operation source account did nothing. This restriction does not make sense with what we have today like you mentioned.

**Comment by leighmcculloch** [comment]
Got it. Closing as it already works the way this issue described.
