### ISSUE TITLE
Output a history JSON file next to buckets when running stellar-core catchup

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/stellar-core#3616]
### Explain in detail the additional functionality you would like to see in stellar-core.

Output a history JSON file next to buckets when running `stellar-core catchup` when run in any mode, such as `--in-memory`. 

### Explain why this feature is important

Stellar core is the only tool that I know of that can construct buckets for any ledger in the history of a network. While it is possible to download buckets from history archives, those buckets will only be for checkpoint ledgers.

The `stellar-core catchup` command is a convenient way to construct a set of buckets that contain a specific ledger's state, but there is no way to conveniently ingest them to render the final state because entries can be duplicated across the buckets. The history JSON is required for understanding what the order of the buckets are.

While some stellar-core commands like `run` store the history JSON in a sqlite db, that is quite an implementation to depend on, and when using `catchup` in isolation the file is never written.

### Describe the solution you'd like

`stellar-core catchup N/M` result in a `buckets/` directory containing the buckets for at least ledger N, which it does today, and a .json file containing history JSON for ledger N.

Any application be able to reconstruct ledger state from the files in `buckets/`.

### Describe alternatives you've considered

Downloading checkpoint buckets from history archives, but doing so would not provide buckets at any ledger.

### Additional context

https://stellarfoundation.slack.com/archives/C0367MGFL/p1669930604478989

**Comment by MonsieurNicolas** [comment]
I think it makes more sense to a new option to the `info` endpoint (like a `compact=false` to be consistent with other commands) that adds bucket information to the `ledger` node (and I can see adding more information over time).

Then for this particular use case you would run `./stellarc-core offline-info --full` and get a json blob that would include something like:
```
     "ledger" : {
         "age" : 1,
         "baseFee" : 100,
         "baseReserve" : 5000000,
         "closeTime" : 1663305365,
         "hash" : "c28647a9d0aa7cf46cc722b7582f56411ee0d27339015f0e066a2ba2aa976554",
         "maxTxSetSize" : 100,
         "num" : 30000,
         "version" : 19,
         buckets = [ "00263753eb070dc68e48cabee0a47ce1d94e46c043bff1134dbc5dbebc6f2b3c", "a18409096181514428ae0bde65664a005e246e32142ee2b9e936bf33cdaadca0", ... ]
      }
```

**Comment by graydon** [comment]
@MonsieurNicolas No, he wants to download the buckets (and drive them forward to a specific ledger) and then ingest the state into a separate tool, and needs to know the buckets to read (in some way that's more reliable than "just ingest whatever is in the buckets directory")

**Comment by graydon** [comment]
(We already emit a catchupinfo json object when doing offline catchup, we can just tack this on the end of it, it will not be a hard change)

**Comment by leighmcculloch** [comment]
Is the catch-up info something that is easily readable by a tool? It looks like it is dumped to stdout, so to confirm I think the workflow would be to:

- run the catch-up command redirecting stdout to file
- run the custom tool giving it that file and the bucket files

I just want to make sure that the format and way that the history json is delivered is in a way that a tool can easily access it. It wouldn't be ideal if a human had to look at a bunch of mixed output and pull out the relevant info by hand.

**Comment by leighmcculloch** [comment]
> Then for this particular use case you would run `./stellarc-core offline-info --full` and get a json blob

Would this command be able to retroactively figure out what the history was that was downloaded? When I run catch-up I don't see any state being stored that would help stellar-core know. 

I think it makes sense to do something like what @graydon describes or in the description where the history json is outputted at the same time as building the buckets, which means the output of that command will be more complete and standalone in a single shot.

**Comment by MonsieurNicolas** [comment]
Maybe I am missing something but the original problem described at the top is to rebuild a specific ledger from buckets outside of a checkpoint as to match where core is currently stopped at (like after running catchup to a specific ledger).
If core gives you exactly which buckets are in the bucket list (in the right order) you should be able to use that and grab them from that folder directly (so I also don't understand the comment around "downloading buckets" in that context).

**Comment by leighmcculloch** [comment]
If I run these commands, how do I guarantee the information I get from stellar-core matches between the two, the ledgers might progress between them. As far as I can tell offline-info gives me the latest network information, not the buckets I just downloaded.

```
stellar-core catchup current/1
stellar-core offline-info
```

**Comment by graydon** [comment]
`offline-info` is offline. tells you the state of the database you're looking at. sorry, I misread what @MonsieurNicolas was suggesting, I think `offline-info` would also work for this.

(In terms of "does it go to stdout or a file" we can make it -- offline-info or catchupinfo -- write to a named file if you want to avoid file descriptor reads, that's fairly easy to add to any comment)

**Comment by graydon** [comment]
(`catchup` actually already has `--output-file` to write its catchupinfo struct to a file)

**Comment by leighmcculloch** [comment]
> `offline-info` is offline. tells you the state of the database you're looking at.

When I run it, with no database, it prints the latest ledger, with a different value every few seconds.

**Comment by graydon** [comment]
Can you show me the command? Running `stellar-core offline-info` with a config file pointing to a missing database, I get:

```
2022-12-02T13:19:31.255 GBKBJ [default FATAL] Got an exception: No DB schema version found, try stellar-core new-db
2022-12-02T13:19:31.255 GBKBJ [default FATAL] Please report this bug along with this log file if this was not expected
```

Which is what it should do. It runs with the network disabled, so I'd be surprised if it connects to someone!

**Comment by leighmcculloch** [comment]
```
stellar-core catchup current/1
stellar-core offline-info
```

`stellar-core.cfg`:
```
LOG_COLOR=true
LOG_FILE_PATH=""

COMMANDS=[
    "ll?level=INFO",
    "ll?partition=Herder&level=WARNING",
]

DATABASE="sqlite3://:memory:"

NETWORK_PASSPHRASE="Test SDF Future Network ; October 2022"

UNSAFE_QUORUM=true

[[HOME_DOMAINS]]
HOME_DOMAIN="futurenet.stellar.org"
QUALITY="MEDIUM"

[[VALIDATORS]]
NAME="sdf_futurenet_1"
HOME_DOMAIN="futurenet.stellar.org"
PUBLIC_KEY="GBRIF2N52GVN3EXBBICD5F4L5VUFXK6S6VOUCF6T2DWPLOLGWEPPYZTF"
ADDRESS="core-live-futurenet.stellar.org"
HISTORY="curl -sf http://history-futurenet.stellar.org/{0} -o {1}"
```

**Comment by graydon** [comment]
So .. I just ran this with this config, and it keeps giving me the same ledger _number_ (that is, `info.ledger.num=1` in the output) just with a different _age_ (`info.ledger.age`) from one run to the next -- the age is just listed as the current unix epoch-age in seconds (currently `1670030429`) since that's .. how old ledger 1 (that happens at time 0) is, at the moment.

Are you sure you're seeing the ledger _number_ increasing?

**Comment by leighmcculloch** [comment]
Ah, I think I misread the output. In any case if you're seeing ledger 1 that doesn't seem to be good, doesn't that mean it's giving you details for a different ledger of the buckets?
