### ISSUE TITLE
config: consider keeping more ledgers in-memory to improve developer experience

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/stellar-core#3622]
@leighmcculloch pointed out a potential improvement to the experience running core: currently, we store 12 ledgers (~1 minute of consensus) in memory by default. If a new node joins the network with its LCL too far behind, it will have to wait until the next checkpoint publish, which can take minutes. However, if we store a checkpoint worth of ledgers in-memory, we shouldn't have this problem, because new nodes would apply previous checkpoint from the archives, then replay ledgers buffered from the network, minimizing delay to get in sync. This issue tracks a few things:
* Verifying that current core implementation works correctly and allows to catchup without waiting (this should be the case already due to the buffered ledgers trimming logic added to catchup not too long ago)
* Analyzing memory profile of core with the updated config. Each in-memory ledger stores quite a bit of data, so we should evaluate memory growth patterns. If it's tolerable, we should consider increasing how many ledgers are kept. 
* I _think_ this change should also improve liveness and recovery guarantees during catastrophic events (for example, if a validator in a v-blocking set goes down and requires new-db)

**Comment by MonsieurNicolas** [comment]
The other thing to consider is the amount of traffic generated by this.
Nodes send (and can potentially request) 64 legers worth of SCP messages at once which could be problematic without some sort of rate limiting.

**Comment by MonsieurNicolas** [comment]
Something that might be good enough (even in prod) is that if we were going to keep just the SCP messages that allows to replay the last checkpoint, this would allow new nodes to start catching up, and by the time they've reconstructed their ledger state & replayed the last checkpoint, the latest checkpoint + recent ledgers will be available like normal.

The change would only require keeping around only one more ledger worth of data.

**Comment by leighmcculloch** [comment]
> by the time they've reconstructed their ledger state & replayed the last checkpoint

Does this assume that it takes nodes a certain amount of time to reconstruct the previous checkpoint? When I connect to futurenet it looks to me like core spends most of its time waiting, not reconstructing.

**Comment by MonsieurNicolas** [comment]
futurenet has no state right now so it's not representative of what will happen in prod: it takes a while just to download & verify buckets (like order of 10 minutes) for pubnet on fast hardware using buckets-db, and that's core, I don't know how much time other parts of the system are going to need.

**Comment by leighmcculloch** [comment]
Got it. Maybe we should just use this configuration, which would optimize for developer experience, for smaller networks like `futurenet` and `testnet`. Those networks are more likely to be interacted with by developers building on Soroban when they're in their development workflow, and given those networks smaller data sets it should be less of a problem to enable it.

**Comment by leighmcculloch** [comment]
But the more achievable change you mentioned for production, just adding one more ledger, sounds good if it speeds up sync.
