### ISSUE TITLE
XDR mismatch between core and env is making it through CI

### ISSUE THREAD

**Issue by sisuresh** [stellar/stellar-core#3658]
The xdr version between rs-soroban-env in core and xdr/protocol-next must match up. If not, then core will fail on startup with an xdr mismatch. This error should be caught when github runs the `next` tests, but for some reason this doesn't happen and the mismatched versions make it into master.

**Comment by sisuresh** [comment]
It looks like the mismatch happens in the action, but the action doesn't fail - https://github.com/stellar/stellar-core/actions/runs/4108964519/jobs/7090247696

```
make  check-TESTS
make[3]: Entering directory '/home/runner/work/stellar-core/stellar-core/src'
current exception: std::runtime_error("XDR hash mismatch: rust has "xdr/next/Stellar-contract-spec.x"=83f5adc57ccaea49a67063352b869641049c4caf198a3070c4825c5f6e82802a, C++ has "protocol-next/xdr/Stellar-contract-spec.x"=f1b4562b21a38708e15b2e7f371d9171802ef7756bf5af2cb49b517149228e9c")
backtrace unavailable
Aborted (core dumped)
current exception: std::runtime_error("XDR hash mismatch: rust has "xdr/next/Stellar-contract-spec.x"=83f5adc57ccaea49a67063352b869641049c4caf198a3070c4825c5f6e82802a, C++ has "protocol-next/xdr/Stellar-contract-spec.x"=f1b4562b21a38708e15b2e7f371d9171802ef7756bf5af2cb49b517149228e9c")
backtrace unavailable
```

**Comment by MonsieurNicolas** [comment]
Maybe this is actually caused by our crash handler that causes the process to return 0 in this situation?

**Comment by sisuresh** [comment]
Yeah I think we need to log and return 1 instead of throwing an exception.
