### ISSUE TITLE
The ifdefs around Soroban specific code need to be removed 

### ISSUE THREAD

**Issue by sisuresh** [stellar/stellar-core#3662]
All Soroban related code is behind `#ifdef ENABLE_NEXT_PROTOCOL_VERSION_UNSAFE_FOR_PRODUCTION` conditional checks. Prior to the release that enables Soroban, these need to be removed, and conditional checks on the protocol version need to be added in. 

Note that once the ifdefs should only be removed once we are comfortable releasing Soroban.

**Comment by MonsieurNicolas** [comment]
note that this requires adding the proper checks so that protocol 19 behaves like protocol 19 when encountering protocol 20 xdr

**Comment by anupsdf** [comment]
The dependent XDR [issue #144](https://github.com/stellar/stellar-xdr/issues/144) is will handle moving next branch to curr.
