### ISSUE TITLE
The Next github checks are taking ~90 minutes.

### ISSUE THREAD

**Issue by sisuresh** [stellar/stellar-core#3665]
You can see [here](https://github.com/stellar/stellar-core/actions/runs/4198078548/jobs/7281232311) that both GCC Next and Clang next took around 90 minutes, while GCC current and Clang Current took around 15 minutes. This results in a much longer wait time to get a change merged into master, affecting how quickly we can release a build.

Some guesses as to where the issue could be - 
- Caching issue
- rust bridge header could be included in a widely used header, resulting in full rebuilds

**Comment by sisuresh** [comment]
This might not be a rust issue. This GCC current run took around 90 minutes - https://github.com/stellar/stellar-core/actions/runs/4126381089/jobs/7128229604.

**Comment by MonsieurNicolas** [comment]
it is expected to see ~ full rebuilds (we expire caches). So the question is: are rust builds always slow?

**Comment by sisuresh** [comment]
The checks now run in < 60 minutes, not 90 minutes.
