### ISSUE TITLE
Nodes can lose sync while assuming LCL state on startup

### ISSUE THREAD

**Issue by SirTyson** [stellar/stellar-core#3667]
During startup, whenever we assume LCL state, we block until `AssumeStateWork` finishes. `AssumeStateWork` must index the entire BucketList and can take some time (up to 5 minutes at the current ledger size). While assuming state, we do not buffer ledgers, so nodes lose sync.

We should either buffer ledgers while assuming LCL state or save `BucketIndexes` on disk so that `AssumeStateWork` can finish quickly to prevent losing sync.

**Comment by MonsieurNicolas** [comment]
If we're trying to not trigger a catchup on restart, we have to ensure that all tasks up to "receiving enough SCP messages as to externalize" takes less than 60 seconds (roughly the amount of ledgers we can get without relying on archives unless we extend this somehow as originally discussed in #3622).

It will be interesting to see how long it actually takes to rebuild the in memory index based off the on disk one in that context. Currently I think we're talking about a couple of GBs, but I don't know what the overhead is compute wise and how much room we'll have, we had surprises in the past with the (poor) performance of C++ containers.
