### ISSUE TITLE
Containerized dev environment installation complaining about install-rush.sh

### ISSUE THREAD

**Issue by anupsdf** [stellar/stellar-core#3679]
Following the steps in [Containerized dev environment](https://github.com/stellar/stellar-core/blob/master/INSTALL.md#containerized-dev-environment), I am getting this error when trying to open container in VSCode.
```

 => ERROR [dev_container_auto_added_stage_label  9/11] RUN ./install-rust  0.2s
------
 > [dev_container_auto_added_stage_label  9/11] RUN ./install-rust.sh:
#0 0.193 /bin/sh: 1: ./install-rust.sh: not found
------
ERROR: failed to solve: executor failed running [/bin/sh -c ./install-rust.sh]: exit code: 127
```

**Comment by graydon** [comment]
@anupsdf [this](https://github.com/stellar/stellar-core/pull/3680) ought to get you unblocked, but .. I also don't think you're going to have a good time with devcontainers in general. core should build outside of them and inside it seems to be just excruciatingly slow (probably docker's amazingly bad union-filesystem performance). I would recommend building outside.
