### ISSUE TITLE
Soroban rent_balance

### ISSUE THREAD

**Issue by SirTyson** [stellar/stellar-core#3697]
As a first step to implementing the [rent proposal](https://docs.google.com/document/d/1edn0IHIlHhukidQkq8tiVJ3djULXiEyypJJQ3RhyB7g/edit#), we should add the rent_balance field to Soroban entry types and begin deducting rent_fees. In this initial version, there will be no way to increase rent_balance and there will be no penalties for entries with a rent_balance <= 0. This initial step will allow us to validate our rent charging schemes and solidify XDR changes.

Following this issue, the next step will be to enable rent payments and expose the rent_bump host function is Soroban.

**Comment by sisuresh** [comment]
Closed by https://github.com/stellar/stellar-core/pull/3762 - (@SirTyson please reopen if this is incorrect).
