### ISSUE TITLE
Look into using read only LedgerTxns for the LedgerTxns that were introduced in the config upgrade change.

### ISSUE THREAD

**Issue by sisuresh** [stellar/stellar-core#3716]
The LedgerTxns added in the [config upgrade PR](https://github.com/stellar/stellar-core/pull/3674/files) should be using `READ_ONLY_WITHOUT_SQL_TXN` since they should all be read only. If we do this, we should make sure there are no concurrent writers present.

1. https://github.com/stellar/stellar-core/blob/bff2c2b37402acc61166c0f369da1205efbe8c9d/src/herder/HerderImpl.cpp#L1210
2. https://github.com/stellar/stellar-core/blob/bff2c2b37402acc61166c0f369da1205efbe8c9d/src/herder/HerderImpl.cpp#L1278
3. https://github.com/stellar/stellar-core/blob/bff2c2b37402acc61166c0f369da1205efbe8c9d/src/herder/Upgrades.cpp#L632

**Comment by marta-lokhova** [comment]
I would suggest a broader audit of LedgerTxn usage in vNext outside of application phase. I'm seeing more recently added instances that should be switched to read-only:
https://github.com/stellar/stellar-core/blob/e38ee728dcc47deb7e4cc68b82ce43dbd5b321d1/src/overlay/OverlayManagerImpl.cpp#L1209
https://github.com/stellar/stellar-core/blob/e38ee728dcc47deb7e4cc68b82ce43dbd5b321d1/src/herder/TransactionQueue.cpp#L1339
https://github.com/stellar/stellar-core/blob/e38ee728dcc47deb7e4cc68b82ce43dbd5b321d1/src/herder/TransactionQueue.cpp#L1544

**Comment by sisuresh** [comment]
@marta-lokhova I'm closing this because you're going to remove these LedgerTxn usages anyways.
