### ISSUE TITLE
Soroban settings shortcuts: kill switch and reset to defaults

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#3719]
We introduced the ability to update individually Soroban settings.

We talked about introducing a "Big Red Switch" type of shortcut, to disable Soroban completely -- validators would vote for this in the event of a catastrophic bug that requires to stop processing Soroban transactions (in this type of situation, we do not want to go through the process of having to first update ledger entries etc as it may not even be possible depending on what is going on).

Internally, this could be as simple as setting the "maximum Soroban transaction size" to 0.

After this functionally is used, there is an interesting problem that we would not be able to bring Soroban back online as upgrades rely on updating ledger entries first.

A second shortcut we can use instead is one to "reset Soroban settings to defaults":
* "defaults" here would be whatever we decide. I think for protocol 20, we could just use the same settings than what Soroban will have when first activated. In the future, we can always adjust this to be protocol dependent: this could allow to make it easier for example to reset settings to something simple post parallel processing.

In both cases, those would simply be new values for `LedgerUpgradeType` with no arguments, and should be fairly easy to add.

**Comment by dmkozh** [comment]
> Internally, this could be as simple as setting the "maximum Soroban transaction size" to 0.

A cleaner approach would be setting the per-ledger limits to 0, so that we're sure we also get all the classic capacity back (the details would depend on tx prioritization implementation).


> After this functionally is used, there is an interesting problem that we would not be able to bring Soroban back online as upgrades rely on updating ledger entries first.

That's a great catch actually. Probably the most obvious option is to replay the config initialization from v20 till the current version (until we need something more special, that is).
