### ISSUE TITLE
Use the ledger size dependent fee for writes

### ISSUE THREAD

**Issue by dmkozh** [stellar/stellar-core#3729]
The initial fees implementation just uses the flat value for the write fee for the sake of testing. The proper implementation should have `wfee_rate` from https://github.com/stellar/stellar-protocol/blob/master/core/cap-0046-07.md implemented. This requires the way to get the bucket list size though, which is why it's postponed compared to the other fees work.

**Comment by MonsieurNicolas** [comment]
related issue https://github.com/stellar/stellar-core/issues/3698 (FYI @SirTyson )
