### ISSUE TITLE
overlay: support Soroban max tx size upgrades

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/stellar-core#3746]
now that https://github.com/stellar/stellar-core/pull/3737 is merged, we should add support for soroban network config upgrades at the overlay layer, and tweak throttling parameters appropriately.

**Comment by mbsdf** [comment]
We should also ensure that MAX_CLASSIC_TX_SIZE_BYTES is set correctly (i.e. #3744) What are the chances of rejecting a valid classic transaction?
