### ISSUE TITLE
Follow up issue to track max tx size for classic when flow control in bytes is enabled

### ISSUE THREAD

**Issue by mbsdf** [stellar/stellar-core#3747]
The current MAX_CLASSIC_TX_SIZE_BYTES is 100KB for classic transactions (when  flow control in bytes enabled).  What are the chances of rejecting a valid classic transaction? One may have a large claimable balance in transaction and can go over this limit (100 operations per transaction). However they will be able to resubmit the same by splitting into multiple transactions. Historical data shows we are within this max transaction limits for classic (max tx size is set to 100KB for now). And also one may argue that permitting to submit such large transactions without a limit is not right and not good for the network. Soroban has max transaction size already (see #3746). This is a follow up after #3744 and #3737 (flow control in bytes).

**Comment by marta-lokhova** [comment]
@mbsdf I think we agreed that 100KB is acceptable based on the historical data. Shall we close this issue?
