### ISSUE TITLE
Core crash seen in quickstart when running against futurenet

### ISSUE THREAD

**Issue by sisuresh** [stellar/stellar-core#3756]
https://github.com/stellar/quickstart/issues/456#issuecomment-1562996616

Looks like we've only seen this once so far.

**Comment by leighmcculloch** [comment]
From https://github.com/stellar/quickstart/issues/456#issuecomment-1562996616:

```
...
stellar-core: Catching up; Waiting for trigger ledger: 14336/14337, ETA: 5s
stellar-core: Catching up; Catching up to ledger 14335: Downloading state file history/00/00/37/history-0000377f.json for ledger 14207
stellar-core: Catching up; Catching up to ledger 14335: downloading and verifying buckets: 10/11 (90%)
supervisor: 2023-05-25 14:19:01,352 INFO exited: stellar-core (terminated by SIGABRT; not expected)
supervisor: 2023-05-25 14:19:01,352 INFO reaped unknown pid 1007 (exit status 0)
supervisor: 2023-05-25 14:19:01,356 INFO spawned: 'stellar-core' with pid 1008
stellar-core: Connected
...
```

The above logs are supervisor logs combined with status updates from reading the stellar-core info endpoint.

Unfortunately we don't have stellar-core logs during this.

But maybe it is an issue ingesting ledger 14335?

**Comment by dmkozh** [comment]
That's an old crash, should have been closed a while ago.
