### ISSUE TITLE
Soroban: consider emitting a few key metrics to track resources per transaction in the meta

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#3759]
As I was reviewing the kind of reports that we'd like to enable in Hubble, I noticed that we don't really have a way to slice & dice data related to common tasks for smart contract developers:
* contract optimization based on actual "real network utilization" as to minimize fees
* fee stats to calculate effective resource price
* identifying & fixing issues in contracts proactively (high watermarks)

This is also discussed in [CAP-0046-007](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0046-07.md#resources) as validators need to vote on a regular basis on updating the "network base price" for resources.

In order to do this, we need core to emit in the meta information on resource utilization:
* key resources like "cpu instructions", but also I/O related ones (without having to duplicate the logic that lives in core in downstream systems).
* high watermark against limits. For example, we should emit how much memory was used by a transaction (limit that should be compared to the network limit), or the `max(ledger entry size)`.

I imagine that a lot of the same information should be returned by the host in preflight as well.

**Comment by MonsieurNicolas** [comment]
@jayz22 FYI

**Comment by MonsieurNicolas** [comment]
I just thought about something that could allow us to implement this *without* xdr changes:
* this issue tracks the minimum information needed for downstream systems to aggregate data related to resource utilization
* in the future, we'll probably want to add the next level of detail (like current stats when entering/exiting contract methods), similar to debug events

So the question is: would it be possible to add those as debug events instead? That way:
* they're not "part of the protocol" (easy to enable/disable on a per instance basis)
* we can extend them as needed without a lot of coordination other than with consumers of those data streams

@jayz22 @sisuresh what do you think?

**Comment by jayz22** [comment]
Some of these resources we are interested are only available at the operation level (outside the host), so I don't think diagnostic events would be able to cover them? 
Such as fee input related: `max(LedgerEntry)`, meta data size, or any actual measurement results such as the wall-time for the host execution.

**Comment by graydon** [comment]
Core can also synthesize diagnostic events. I think it's fine for this to be based on diagnostic events (in which case I think this should be punted from preview 10).

**Comment by jayz22** [comment]
> Core can also synthesize diagnostic events. 

Ah I see, then it makes more sense to add them as diagnostic events in core then.

> in which case I think this should be punted from preview 10

Depending on whether we have the downstream system ready to digest the events and Hubble setup to query them. The sooner we have it means we can start getting feedback on the what the right level of network limits are?

**Comment by MonsieurNicolas** [comment]
> Some of these resources we are interested are only available at the operation level (outside the host), so I don't think diagnostic events would be able to cover them?
> Such as fee input related: `max(LedgerEntry)`, meta data size, or any actual measurement results such as the wall-time for the host execution.

I think we can easily add entries in `diagnosticEvents` for the given transaction?
Those would just have `contractID` not set.

if this seems workable, we can punt from preview 10, and instead track this as an "add metering systems events" that cover multiple levels of granularity (and make sure we prioritize emit the op/tx level ones first).

**Comment by jayz22** [comment]
> if this seems workable, we can punt from preview 10, and instead track this as an "add metering systems events" that cover multiple levels of granularity (and make sure we prioritize emit the op/tx level ones first).

Just want to double check, what do you mean by "multiple levels of granularity"? The diagnostic events are part of a transaction (`TransactionMetaV3`) so they cannot exceed above the tx/op level? 
Or are you referring preflight as the other level?

Otherwise it makes sense, I will update the issue title and target milestone.

**Comment by MonsieurNicolas** [comment]
> Just want to double check, what do you mean by "multiple levels of granularity"? The diagnostic events are part of a transaction (`TransactionMetaV3`) so they cannot exceed above the tx/op level? Or are you referring preflight as the other level?
> 

What I wrote above (which allows to do things like per method/contract reports):
> in the future, we'll probably want to add the next level of detail (like current stats when entering/exiting contract methods), similar to debug events

For "ledger level" stats, aggregators will do that if they want.

**Comment by jayz22** [comment]
We have added relevant metrics as diagnostic events in the https://github.com/stellar/stellar-core/pull/3847. Closing this.
