### ISSUE TITLE
Make tx size limits consistent across the codebase

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/stellar-core#3765]
This issue tracks a slight inconsistency between the tx queue and overlay when it comes to validating transactions against max allowed size. Specifically, tx queue takes into account envelope size only (https://github.com/stellar/stellar-core/blob/287fe4c5d7f7ebce1a327cd26f25dd5858cd37a0/src/transactions/TransactionFrame.cpp#L603), while overlay computes the size of the whole message (which includes signatures) https://github.com/stellar/stellar-core/blob/287fe4c5d7f7ebce1a327cd26f25dd5858cd37a0/src/overlay/FlowControlCapacity.cpp#L76

We should ensure we validate size consistently to prevent any unnecessary drops at the overlay layer.

**Comment by dmkozh** [comment]
We'll use full tx size for the fees, so there won't be discrepancy. I'll keep this open to update when the change is merged.

**Comment by marta-lokhova** [comment]
@dmkozh Looks like there are still discrepancies in two places:
* tx validation https://github.com/stellar/stellar-core/blob/03fa3a7a4f76ae1131ced5d9f0342c0af13374ba/src/transactions/TransactionFrame.cpp#L738
* tx resource count https://github.com/stellar/stellar-core/blob/03fa3a7a4f76ae1131ced5d9f0342c0af13374ba/src/transactions/TransactionFrame.cpp#L233

I thought the idea was to use full tx size across codebase; the limit itself is bandwidth-related, and we never flood just the tx portion of the tx envelope, so it makes sense to count the whole transaction. If we don't, this is also problematic for overlay as it relies on `txMaxSizeBytes` for calculations that expect full tx size.
