### ISSUE TITLE
Bump with EXPIRATION_EXTENSION

### ISSUE THREAD

**Issue by SirTyson** [stellar/stellar-core#3772]
The state expiration PR #3762 added support for `EXPIRATION_EXTENSION` entries, but does not yet actually use them. We should use `EXPIRATION_EXTENSION` instead of `DATA_ENTRY` when bumping read-only entries to avoid redundant data writes in the BucketList.

**Comment by SirTyson** [comment]
This is purely a core optimization, could potentially be moved to post testnet. Should not affect downstream systems.

**Comment by graydon** [comment]
I don't think it's really "just an optimization" that we can or should safely defer; in the strictest sense it may be but treating it as such is a big future headache. 

The choice to do this or not changes the byte-by-byte canonical content of the buckets, which we hash to designate the canonical state of the ledger. Having options about how we write buckets will require future-us to maintain the logic to produce each exact "flavor" of bucket at specific times during replay. It is much better to have no options and only one canonical representation for any logical content.

**Comment by graydon** [comment]
Closing obsolete -- in the EXPIRATION_ENTRY solution there's no such ambiguity, bumps always hit that entry.
