### ISSUE TITLE
Make ConfigUpgrade Entries Persistent

### ISSUE THREAD

**Issue by SirTyson** [stellar/stellar-core#3790]
I realized that ConfigUpgrade entries are currently stored in `ContractData` entries but do not define a storage type. We should choose a storage type and make sure the change is consistent across the env and core. Dima suggested using `PERSISTENT`. We should also set the entry lifetime to something reasonable, either the minimum lifetime or the same lifetime as the contract instance being upgraded.

**Comment by dmkozh** [comment]
> the same lifetime as the contract instance being upgraded.

I'm not sure what is this supposed to mean. The lifetime of the entry used to store the upgrades can be arbitrarily manipulated by the contract that uploads it. We don't need to do anything from the protocol standpoint, besides setting the durability explicitly when we're looking up this key during the upgrade process.

**Comment by anupsdf** [comment]
This would be fixed by core [PR](https://github.com/stellar/stellar-core/pull/3918) I think.

**Comment by dmkozh** [comment]
This issue states 'persistent', while we're converged on using 'temporary'. So I think this particular issue can be just closed now.
