### ISSUE TITLE
scrub logs to properly output information about peers

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#380]
Right now we use "PEER_PORT" in places where we should really be using PeerID (or a short form of it)

This doesn't really give any useful information:

``` C++
void
Peer::sendHello()
{
    LOG(DEBUG) << "Peer::sendHello "
               << "@" << mApp.getConfig().PEER_PORT << " to "
               << mRemoteListeningPort;
```

instead we should do something like

``` C++
void
Peer::sendHello()
{
    LOG(DEBUG) << "Peer::sendHello "
               << "@" << mApp.getLoggingID() << " to "
               << remoteID();
```

both `getLoggingID` and `remoteID()` would be some representation of the PeerID (like the first n digits of it)

**Comment by MonsieurNicolas** [comment]
All log lines already have the local peer's nodeID - so this cleanup is really about removing any redundant information form the logs (which includes local port, nodeID, etc).

**Comment by perimetral** [comment]
hi. is this issue still actual? i mean im ready to go to fix it but im not sure if its still needed to.

**Comment by MonsieurNicolas** [comment]
yeah looks like this was fixed. Thanks for pointing this out!
