### ISSUE TITLE
Enable checkStellarCoreMajorVersionProtocolIdentity check

### ISSUE THREAD

**Issue by sisuresh** [stellar/stellar-core#3810]
The `checkStellarCoreMajorVersionProtocolIdentity` check [here](https://github.com/stellar/stellar-core/blob/master/src/main/main.cpp#L262-L267) was commented out in https://github.com/stellar/stellar-core/pull/3808, but needs to be re-enabled in a way that works.

**Comment by MonsieurNicolas** [comment]
would that check never work for vnext? Like when we release 20.0, vnext will want to have a protocol version that is 21

**Comment by sisuresh** [comment]
Yeah the check as-is is not what we want. This issue is about re-enabling the check in a way that works, or making sure it can stay removed.
