### ISSUE TITLE
Change Soroban settings in code base (for protocol 20) to be "safe mode" settings

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#3820]
#3719 talks about having a mechanism to flip back to the "default network settings".

What this issue tracks is actually deciding & implementing what those "default network settings" should be.

Specifically, right now the code base hard codes "best guesses" on what the public network could use. I think this is flawed as the requirements are very different:
* "default settings" are actually "safe mode" settings.
    * Goal of those defaults is to ensure that it's easy to transition back into "production" settings (via vote) while limiting exposure to "bad behavior" as much as possible.
    * They're trying to answer the question "how small should limits be while allowing contracts at most as complicated as the network settings helper contract" (so goal here is to minimize limits in some way).
    * Limits can be arbitrary low as the expectation is that they're the first in the chain of "permanent settings changes" (when Soroban gets switched on), or the result of a temporary reduction of settings during outages.
* "best guesses" settings:
    * are a lot more arbitrary
    * are assumed to be "permanent"
    * try to answer the question "how large limits need to be as to maximize utility with reasonable risk assumption" (so goal here is to maximize limits in a different way).
    * limits can only "increase" for the most part (as a decrease of any limit is a breaking change for contracts)

Here are a few things that we probably want to achieve with "safe mode" settings:
* Must
    * allow to install 1 contract that saves state "network settings helper contract" (state that can be used as part of network settings contract)
    * entry limit large enough to store any network setting
    * limit to 1 transaction per ledger (ie: global limits are the same than per transaction limit)
    * limit transactions to 1 VM instantiation (VM instantiation is a "high risk" event)
* Should
    * limit as many host functions as possible (calling one of them would require too many cpu instructions)
    * limit meta production as much as possible

Related issues that track figuring out "best guesses":
 * #3694 
 * #3695

**Comment by sisuresh** [comment]
From the backlog grooming meeting - we should write a core test case that uses the [upgrade contract](https://github.com/stellar/stellar-core/tree/master/scripts/soroban-settings/write_upgrade_bytes) to do an upgrade with the soroban settings set to the hardcoded `MinimumSorobanNetworkConfig` values.
