### ISSUE TITLE
stellar-core crash, 19.12.1-1393

### ISSUE THREAD

**Issue by tsachiherman** [stellar/stellar-core#3840]
## Issue Description

Captive core crash with the following
```
INFO[2023-07-18T18:40:20.196Z] Tx: applying ledger 11570 (classic phase: 1 component(s): [{discounted txs:1, ops:1, base_fee:100}], soroban phase: 0 component(s): [])  pid=1077
third errorINFO[2023-07-18T18:40:20.220Z] Tx: applying ledger 11573 (classic phase: 0 component(s): [], soroban phase: 1 component(s): [{discounted txs:1, ops:1, base_fee:100}])  pid=1077
INFO[2023-07-18T18:40:20.234Z] default: Application destructing              pid=1077
INFO[2023-07-18T18:40:20.238Z] default: Application destroyed                pid=1077
ERRO[2023-07-18T18:40:20.253Z] default: Got an exception: Local node's ledger corrupted during close  pid=1077
ERRO[2023-07-18T18:40:20.253Z] default: Please report this bug along with this log file if this was not expected  pid=1077
FATA[2023-07-18T18:40:20.276Z] could not read operations: error getting ledger from the backend: stellar core exited unexpectedly: exit status 1  pid=1077
root@83e16affa31a:/etl# stellar-core
```

## Steps to Reproduce

1. Run stellar-core with in-memory mode.
```
stellar-core --conf core.cfg --console catchup 11583/65 --in-memory
```

## Expected Result
No crash.

## Actual Result
Crash

## Your Environment and Setup
```
HTTP_PORT=0
PUBLIC_HTTP_PORT=false

NETWORK_PASSPHRASE="Test SDF Future Network ; October 2022"

# DATABASE="sqlite3://stellar.db"
PEER_PORT=11725

FAILURE_SAFETY=0
UNSAFE_QUORUM=true

# Stellar Futurenet validators
[[HOME_DOMAINS]]
HOME_DOMAIN="futurenet.stellar.org"
QUALITY="MEDIUM"

[[VALIDATORS]]
NAME="sdffuture1"
HOME_DOMAIN="futurenet.stellar.org"
PUBLIC_KEY="GBRIF2N52GVN3EXBBICD5F4L5VUFXK6S6VOUCF6T2DWPLOLGWEPPYZTF"
ADDRESS="core-live-futurenet.stellar.org:11625"
HISTORY="curl -sf [http://history-futurenet.stellar.org/{0}](http://history-futurenet.stellar.org/%7B0%7D) -o {1}"
```

### stellar-core Version
* If using a standard release, please add the version returned by `./stellar-core --version`
* If working off of master, please add the git hash of the version you're running using `git rev-parse HEAD`

### Environment
* Operation System & Version (You can usually obtain from `uname -a`)
* Are you running from the command line? From a container?
* Did you pass in special parameters when building the app?
* Please add any additional relevant configuration related to this bug report.

## Supporting Files

If you have any supporting files, please paste them or link to a relevant Github gist or archive link (such as an S3 bucket).

Potential items to attach:
* Configuration files (**DON'T FORGET TO REMOVE SECRETS**)
* Log files - it is best is to have logs running at DEBUG level when reproducing an issue (`-ll
  DEBUG` on the command line).

**Comment by anupsdf** [comment]
Closing this since the issue was resolved in [PR](https://github.com/stellar/stellar-core/pull/3857).
