### ISSUE TITLE
Improve Soroban upgrade script

### ISSUE THREAD

**Issue by sisuresh** [stellar/stellar-core#3863]
- [ ] Specify which settings to upgrade with a better UX than updating the hardcoded setting in the script. Maybe a JSON file with the upgrades will work well.
- [ ] Update the network used (futurenet vs standalone vs pubnet) on the command line.
- [ ] Fund the source account with friendbot if it doesn't exist.
- [ ] Add an endpoint in stellar-core that takes a proposed ConfigUpgradeSetKey and returns what the upgrade diff will be.
- [ ] Remove dependency on python SDK and build transactions in stellar-core. (Added after the issues we had on 9/15)

**Comment by sisuresh** [comment]
Related to https://github.com/stellar/stellar-core/issues/3822

**Comment by leighmcculloch** [comment]
This issue is a blocker for the following issue that is impacting contract developers today:
- https://github.com/stellar/quickstart/issues/508

**Comment by leighmcculloch** [comment]
> * build transactions in stellar-core

It would be convenient to have this in stellar-core, but also since the lack of this script is causing problems today, and the next release of stellar-core is not for sometime, it would be ideal if we build this tool behavior into its own tool that we could ship today/soon.

**Comment by leighmcculloch** [comment]
This issue is a blocker for the following feature issue:
- https://github.com/stellar/quickstart/issues/512

**Comment by sisuresh** [comment]
This issue is about improving the Python upgrade script (which we're going to get rid of). I'm closing it issue in favor of https://github.com/stellar/stellar-core/issues/3822.
