### ISSUE TITLE
Can't build core with tracy on MacOS

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/stellar-core#3870]
Having trouble building core at df613c24082b48f4575c149a30cedfaa594706c7 (latest master) with tracy enabled:
```
ld: warning: option -s is obsolete and being ignored
ld: framework not found UniformTypeIdentifiers
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [Tracy-release] Error 1
make[3]: *** [release] Error 2
make[2]: *** [lib/tracy/profiler/build/unix/Tracy-release] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

I'm on MacOS 12.4 (Monterey), Intel processor.

**Comment by marta-lokhova** [comment]
for Mac users experiencing the same problem, following [this issue](https://github.com/wailsapp/wails/issues/1140) and re-installing command line tools fixed it:
```
xcode-select --install
sudo xcode-select --switch /Library/Developer/CommandLineTools
```

**Comment by MonsieurNicolas** [comment]
Should those instructions be included in MacOS section under https://github.com/stellar/stellar-core/blob/master/INSTALL.md#building-with-tracing section ?
