### ISSUE TITLE
diagnostic tools: investigate availability of backtraces

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/stellar-core#3882]
Core has built-in functionality to print backtraces. However, depending on configuration/environment, backtraces may not work (see this comment from @graydon, for example https://github.com/stellar/stellar-core/pull/2770#issuecomment-740372416). This issue tracks efforts to improve backtrace availability. Note that if improvements aren't feasible at this time, we should at least have an understanding of the environments where backtraces do work, and cross-check those with environments used by the network today.

**Comment by MonsieurNicolas** [comment]
Something that could be useful if we can make it work: dumping backtrace even if symbols are not installed, as I think that with some minimum scripting it's easy to lookup symbols from the (separate) package with symbols.
Something else that we could consider is keep symbols for core packages: maybe we can reduce the amount of symbols generated to keep overhead reasonable (I think test enabled builds have 500MB symbols, but we should be able to keep this relatively low)
