### ISSUE TITLE
Allow captive core to turn on soroban debug mode

### ISSUE THREAD

**Issue by graydon** [stellar/stellar-core#3889]
When soroban is running in a captive core, it should be possible to turn on debug mode so that txmeta carries diagnostic events on failure.

_Most_ failures will be caught during preflight (in the RPC server) and that already turns on diagnostics on its own copy of the env. But for failures that happen after a successful preflight, we should still produce some diagnostics into the txmeta stream of a captive so that it can be fed back to a user.

**Comment by graydon** [comment]
(this probably involves some coordination with the RPC to plumb its argument about diagnostic events through to captive)

**Comment by MonsieurNicolas** [comment]
I thought that this was achieved already via the (undocumented) `ENABLE_SOROBAN_DIAGNOSTIC_EVENTS` ? See https://github.com/stellar/stellar-core/blob/2920f3e1ad8232108c9d4f4f2fe0582ad1a6517c/src/transactions/InvokeHostFunctionOpFrame.cpp#L321

**Comment by graydon** [comment]
Interesting. We didn't observe this happening this afternoon. Possibly RPC isn't setting that? Hmm.

**Comment by MonsieurNicolas** [comment]
It should according to https://github.com/stellar/soroban-tools/issues/806 (but that's not enabled in futurenet ; I don't know where you tested this).

**Comment by anupsdf** [comment]
I think we saw this issue because @graydon and I were testing on Preview 10 version in Quickstart standalone image (c5562b5 hash from July 17th). While this [#806](https://github.com/stellar/soroban-tools/issues/806) fix was after that. I will re-test this when we have a stable testnet release across repos.

**Comment by graydon** [comment]
The thing you want to test specifically here is:

- a contract invocation that makes it _past_ preflight, in the env linked into RPC
- that nonetheless _fails_ at execution time, in the env linked into core running as a captive of the RPC

You want to see if the errors generated by that second env are emitted in the meta stream and returned to the user.

**Comment by anupsdf** [comment]
In my local branch of soroban-tools synced to v20 rc4, I tweaked the function [finalize_transaction_data_and_min_fee](https://github.com/anupsdf/soroban-tools/commit/edb8e0893031cd423058f5edfee23e9d02450b4a) to set refundable fee to zero. After that deploying a contract through CLI returned an error, TxInsufficientFee. This error is not a simulateTransaction error but is coming from core during submission of tx.
```

soroban contract deploy \
  --wasm target/wasm32-unknown-unknown/release/soroban_increment_contract.wasm \
  --source anup \
  --network standalone
2023-09-29T17:29:45.313099Z ERROR soroban_cli::rpc: error=Ok(TxInsufficientFee)
error: transaction submission failed: TxInsufficientFee

```

**Comment by anupsdf** [comment]
Nothing actionable on this. Please re-open if you think this doesn' work.
