### ISSUE TITLE
Don't store secrets in log files

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#389]
Right now we have at least one occurence of this: we log soci connection strings (that contain passwords).
We should double check that we also cover when there are exceptions at connection time for example. If so, we should just catch the right exception and "*" out the connection string portion. There might be a better way to pass the password string to soci.

We should also make sure that we don't log things like secret keys (that we read from the config file).

**Comment by vogel** [comment]
Currently we log secret key only in two places:
1. in tests (that is OK)
2. when doing --newdb (not sure, what do you think @jedmccaleb @stanford-scs ?)

**Comment by jedmccaleb** [comment]
@vogel this is done right?

**Comment by vogel** [comment]
@jedmccaleb Yes, that is done. Displaying secret key of root account is not a bad thing, as this is not a real secret (generated from network passphrase).
