### ISSUE TITLE
Stop charging for ledger key reads/writes

### ISSUE THREAD

**Issue by dmkozh** [stellar/stellar-core#3891]
Bucket list stores just the `LedgerEntry` XDR. However, due to an oversight we count the ledger key sizes in a lot of places, e.g. when metering/charging fees for the ledger reads, when writing the entries etc. We should make a pass over all places where `LedgerEntry` size is needed and make sure we don't take keys into account.  The places are in `doApply` of all the soroban ops (when computing read/write sizes) and `fees.rs` where we need to update the constant for `ExpirationEntry` size.

**Comment by MonsieurNicolas** [comment]
To be clear we're charging keys twice in the current implementation? Once using the computer ledger key, and again because we use the ledger entry?

**Comment by dmkozh** [comment]
Yeah, we count read/write sizes as key + entry (which also contains the key data).
