### ISSUE TITLE
Provide a simple mechanism for users to increase the initial Soroban settings limits

### ISSUE THREAD

**Issue by sisuresh** [stellar/stellar-core#3897]
The initial Soroban settings are low so when we launch on testnet, they'll be in what we call "safe mode". The issue with this is that users that are testing on a fresh local network will have issues with hitting the low max values. We should provide a simple way to increase these value.

**Comment by MonsieurNicolas** [comment]
This is probably related to https://github.com/stellar/stellar-core/issues/3822 and/or https://github.com/stellar/stellar-core/issues/3863 ?

**Comment by sisuresh** [comment]
Yeah but the current mechanisms are too complex for users to rely on. I think for now the simplest this is to provide a boolean config flag called `TESTING_HIGH_SOROBAN_LIMITS` and just set values to something we don't expect users to hit.

**Comment by sisuresh** [comment]
This would be used for standalone quickstart and platform e2e tests.

**Comment by MonsieurNicolas** [comment]
As a short term band-aid this could be enough if you're trying to unblock e2e testing.

That being said, in e2e tests and standalone, I imagine that some tests will want to use values that are in production? 

In the linked issue I thought people would prepare a few "profiles" that match whatever scenario people expect to test.

Similarly, even in core supercluster missions, we'll need "high tps" profiles that allow to properly flood transactions.

**Comment by sisuresh** [comment]
Yeah this is a quick fix. We need to add someway for users to set settings to our different "phases".
