### ISSUE TITLE
Update configuration for quickstart image

### ISSUE THREAD

**Issue by mbsdf** [stellar/stellar-core#3905]
Update configuration for quickstart image and update changed urls. Update removed entries. Coordinate with horizon and devrel team.

https://github.com/stellar/quickstart/blob/master/pubnet/core/etc/stellar-core.cfg

**Comment by marta-lokhova** [comment]
Needs to remove Wirex, and add Franklin Templeton

**Comment by ThomasBrady** [comment]
PR https://github.com/stellar/quickstart/pull/532
