### ISSUE TITLE
Discussion: is there any problem with taking offers in reverse order of a path payment?

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#393]
background on path payment:

A sends to B 1000 XYZ via path [ABC, DEF] where ABC, DEF and XYZ are currency,issuer pairs
The network will complete the transaction by walking the chain backwards to find offers:

C is an account with an offer 1000 XYZ for 9000 DEF
D is an account with an offer 9000 DEF for 100 ABC
B <--- 1000 XYZ --- C <---- 9000 DEF --- D <---- 100 ABC --- A

The system takes the top offers in order to construct the cheapest intermediate payment possible using a greedy algorithm that starts from the end.

Balances are reconciled at each step; in the previous example, the updates are done as follows:
1000 XYZ deposited to B
1000 XYZ taken from C
9000 DEF deposited to C
9000 DEF taken from D --> used to take C's offer
100 ABC deposited to D
100 ABC taken from A -> used to take D's offer

This algorithm applied like this means that we allow a form of leverage (or is it just a settlement rule?):

changing the example a bit by for example making B == D
B does not need to hold ABC before this transaction, just 9000 DEF

I wanted to make sure that we have a discussion about this, the current implementation has the benefit of being the simplest.

**Comment by jedmccaleb** [comment]
I think no
