### ISSUE TITLE
Remove deprecated LIMIT_TX_QUEUE_SOURCE_ACCOUNT flag

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/stellar-core#3933]
Starting with v20.0.0, setting LIMIT_TX_QUEUE_SOURCE_ACCOUNT has no effect as it's always on: https://github.com/stellar/stellar-core/blob/ecb24df104c2453a00fa5097d2e879d7731b9596/src/main/Config.cpp#L1026

Once we ensure that downstream systems update their configs to stop using LIMIT_TX_QUEUE_SOURCE_ACCOUNT, we should cleanup the code to remove the flag completely.

**Comment by marta-lokhova** [comment]
@mollykarcher and @tsachiherman, wanted to get your input on this. There's no more need to set this flag manually, so it can be removed from core config. Would you please let us know when it's safe to remove this flag from core?

**Comment by tsachiherman** [comment]
> @mollykarcher and @tsachiherman, wanted to get your input on this. There's no more need to set this flag manually, so it can be removed from core config. Would you please let us know when it's safe to remove this flag from core?

yes, of course. Let me put that on my calendar post testnet release ?

**Comment by mollykarcher** [comment]
@marta-lokhova this should be unblocked, all reference removal PRs tagged here. We haven't yet released the version of the go monorepo with the removal of the reference (and that likely won't happen until past stable release of protocol 20), but all places sending this value upstream of Horizon have been removed and we never documented this value externally so I don't believe there are any external users/partners running Horizon that are sending it.
