### ISSUE TITLE
Bump Command fails to bump entry (Version:stellar-core 19.13.1 (3acf6dd26452a3d3ca719cb0cc6c3cae97ec1be8))

### ISSUE THREAD

**Issue by willemneal** [stellar/stellar-core#3940]
## Issue Description

Reported here: https://github.com/stellar/soroban-tools/issues/969

It seems that the bump CLI subcommand is failing to bump the entry. Strangely this isn't the case in the integration tests in the soroban-tools repo.

A local update to the `read` subcommand that queries the ledgerKey's matching expiration key reveals that while the transaction is successful, the bump is treated as a no-op and there is no update to the expiration.

## Steps to Reproduce

Follow steps in issue above.

## Expected Result

Should return operations that include the changes.

## Actual Result

> operations: VecM([OperationMeta { changes: LedgerEntryChanges(VecM([])) }])

**Comment by sisuresh** [comment]
@willemneal this is no longer an issuer right?
