### ISSUE TITLE
Improve Soroban reporting

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/stellar-core#3960]
It looks like stellar-core `info` endpoint and logging are missing some basic information about Soroban. This makes it harder to understand what's going on with the node and debug. We should:
* Update the `info` endpoint to include current Soroban network limits. If this gets too verbose (ideally info should be as compact as possible), we can put all limits behind a `compact=false` flag, and only expose max soroban tx set size (or create a new endpoint `sorobaninfo` instead).
* During upgrades, it would be helpful to log values the network upgraded to. Note that when the node is armed for an upgrade but hasn't performed it yet, node's status should reflect the new upgrade values as well.

**Comment by MonsieurNicolas** [comment]
+1 on new endpoint for this

we should log network settings changes (even if it means dumping entire ledger entries) as this only occurs when applying ledgers

as far as "armed upgrades" -- aren't we already logging the argument of the upgrade that can be used with #3964 ?

**Comment by anupsdf** [comment]
As part of this, we can also include the Soroban contract interface version number as well to the info endpoint.

**Comment by 2opremio** [comment]
> As part of this, we can also include the Soroban contract interface version number as well to the info endpoint.

I skimmed through the closing PR and it doesn't seem it's included. @marta-lokhova Am I wrong?

**Comment by marta-lokhova** [comment]
@2opremio sorry I missed your comment; are you referring to https://github.com/stellar/rs-soroban-env/blob/c03cc14b44d7591df24283fe65c92e032e589b46/soroban-env-common/src/meta.rs#L61? If so, this can we viewed with `stellar-core version`. If needed, we can add this to the `info` endpoint.

**Comment by 2opremio** [comment]
Ah! So for released versions the interface version matches the protocol version? Then I am not sure it is worth exposing it.

**Comment by marta-lokhova** [comment]
Yeah, core won't start if core protocol version doesn't match interface protocol version, so we decided not to add it to info endpoint to avoid confusion (@sisuresh can correct me if I'm wrong)
