### ISSUE TITLE
Adding a new http endpoint to fetch the ConfigSettingEntry based on input ConfigSettingID

### ISSUE THREAD

**Issue by anupsdf** [stellar/stellar-core#3964]
### What?
With Soroban, we have added resource limits that are stored in ConfigSettingEntry. It would help to provide a http endpoint that fetches the ConfigSettingEntry based on input ConfigSettingID. This would help the users know what the current resource limits are.
The output might be in XDR which can be parsed using https://laboratory.stellar.org/ that has XDR types for various ConfigSettings. 

### Workaround?
Other than the [python script](https://github.com/stellar/stellar-core/blob/2e2d1ef2e1e4c2a89c61285baaad124af67d06ea/scripts/README.md#soroban-settings-upgrade), curl can be used to invoke getLedgerEntries if one knows the XDR for the ledgerKey for the configSetting. Example [here](https://gist.github.com/anupsdf/5d0af20ac7f1e6e9f9fee2132a1f75dd) where output is XDR that needs to be parsed.

**Comment by SirTyson** [comment]
The `sorobaninfo` endpoint has been added in #4048. This returns Network config setting info in a JSON format. I don't see any reason why XDR output or a ConfigSettingID input would be useful when the JSON payload should be easier to work with, so closing this as completed.
