### ISSUE TITLE
Add TRACE logging for Soroban transactions

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#3980]
We need to get *some* insight into what Soroban is doing when debugging issues as to speed up investigations.

In the host, the functionality should be "0 overhead", ie if not logging at TRACE level nothing should happen (other than check for a bool).

Logging should occur "real time" (ie: env should call back core as to emit logs right away) as to assist debugging when combined with the use of a debugger for example (or in case there is some crash).

As this is used when debugging core only, there is no need to check for any limit (and expect the overhead to be potentially significant).

When the "Tx" partition is at "TRACE" level, emit:
* the same data than what goes into "diagnostic" events, in particular
    * information on which contract is invoked
    * before calling a host function, basic information about the context (name of the host function being invoked)
 * additional detailed information to complement diagnostic events
    * full argument list (contract invocation, host function invocation). Note that this will cause most ledger updates to be output to log, which is fine.
    * return values (contracts and host functions)

There might be more things to log in that way, but this should be a good start.

**Comment by graydon** [comment]
https://github.com/stellar/stellar-core/pull/4141 and https://github.com/stellar/rs-soroban-env/pull/1324
