### ISSUE TITLE
Prefetch keys for Soroban TXs

### ISSUE THREAD

**Issue by SirTyson** [stellar/stellar-core#3987]
It looks like Soroban TXs (Restore, Extend, InvokeHostFunction) don't prefetch any keys. For SQL, this makes sense. We prefetch all keys in a single query, so there is no way for us to enforce byte read limits. We could potentially do something like [this](https://stackoverflow.com/questions/63512114/limit-sql-query-based-on-memory-size-of-a-column) but the query performance may be significantly limited by such measures, defeating prefetch gains in the first place. However, for BucketListDB, we can enforce a byte limited prefetch, where we prefetch keys until we reach the given limit. This would provide more efficient disk access but prevent IO DOS attacks, where a malicious TX includes lots of very large keys with a small `readBytes` value.

**Comment by anupsdf** [comment]
Possibly related to https://github.com/stellar/stellar-core/issues/3651

**Comment by SirTyson** [comment]
Closing, didn't realize there was already an issue tracking this. I'll copy my thoughts over there.
