### ISSUE TITLE
[Test] Cover ledger entry size reductions

### ISSUE THREAD

**Issue by dmkozh** [stellar/stellar-core#4002]
While it is unlikely, we might need to reduce the maximum key or ledger entry size via a network upgrade. We need to cover that in the tests. Currently the expected behavior is that we allow reading, but not writing such entries. We need to cover:

- [ ] Reading the existing ledger key that is larger than the key size limit
- [ ] Reading the existing ledger entry larger than the entry size limit

**Comment by SirTyson** [comment]
After discussion, we have decided that both reading and writing entries beyond the limit will not be allowed.
