### ISSUE TITLE
[test] Cover catchup with Soroban transactions

### ISSUE THREAD

**Issue by dmkozh** [stellar/stellar-core#4005]
We need a Core test that runs the catchup with some Soroban transactions. There should be several Soroban transactions per ledger and several transactions should access the same entries. The types of access should be RO, RW and expiration bumps.

The entry access patterns aren't critical so can be simplified as necessary, but they will be as we get to parallelization.

**Comment by marta-lokhova** [comment]
resolved in https://github.com/stellar/stellar-core/pull/4015
