### ISSUE TITLE
The trigger timer will always drift later and later

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-core#402]
Do we want to make the window based on network ledger close time?

**Comment by MonsieurNicolas** [comment]
Actually not using network time to "realign" in some way can cause a node to first trigger at the very first externalize time.
This means the node could be joining consensus basically when other nodes are done: the effect (and I saw it locally), is that other nodes continue to move on as they are in consensus, and the one node left behind is still convinced that it's participating (and reaches consensus), except that none of its positions are taken into account (are per the statement history for the other nodes).

**Comment by jedmccaleb** [comment]
How do you think we should fix this?

**Comment by MonsieurNicolas** [comment]
the node is participating to consensus, just doesn't get to be considered
for the initial prepare statement so may miss its opportunity to be "king".
This may be a problem for the initial trigger but also for subsequent bumps
occurring as part of the algorithm. The answer probably is somewhere around
looking for the network bumping after not seeing the local instance. Not
sure if we need to use a different timeout when we know we're going to be
king next round.
As this is in flux, we should get David to think about those considerations.

Nicolas
