### ISSUE TITLE
Implement SQL invariants in BucketDB

### ISSUE THREAD

**Issue by sisuresh** [stellar/stellar-core#4034]
We have certain invariants enforced in our ledger SQL logic like - https://github.com/stellar/stellar-core/blob/5a6d8502b6b6b12a40b133bcbae9e1abf1901041/src/ledger/LedgerTxnTrustLineSQL.cpp#L22

These invariants should be reflected in BucketDB as well.

**Comment by sisuresh** [comment]
The PR that closed this was reverted due to the fact that some ops allow prefetching an issuer trustline.

**Comment by SirTyson** [comment]
Closing, invariants in SQL were buggy
