### ISSUE TITLE
--newdb should also delete buckets

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-core#412]

**Comment by gmarceau** [comment]
This [commit](https://github.com/stellar/stellar-core/commit/3fc82d9243c9afabc23636532c27011ff7a74852#diff-a78f219a0d6f16db26f0c45498e92131R43) intended to implement this. I gather it's not working?

**Comment by gmarceau** [comment]
Seems to be working here. `--newdb` leaves behind a `buckets` directory with an single bucket file containing the root account balance.
