### ISSUE TITLE
Add command-line function to report eviction related metrics

### ISSUE THREAD

**Issue by SirTyson** [stellar/stellar-core#4138]
We should expose a new command to report the number of entries that have expired, but are still in the BucketList. Specifically, this command should return both the "logical" and "physical" size of outstanding entries waiting to be evicted. The "logical" size does not count entries that are still in the BucketList, but are shadowed by a DEADENTRY. The "physica" metric records all entry bytes, whether they are shadowed or not.

**Comment by anupsdf** [comment]
Should we add this after we have switched to BucketsDB? Reading the expired entries will be faster then.

**Comment by SirTyson** [comment]
No, we should have this before the protocol vote. Since this a cli command, it will never execute on a running validator node. This means we can always enable BucketsDB when this command is run and not interfere with validator behavior.
