### ISSUE TITLE
Deprecate old-style survey responses after v20 upgrade

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/stellar-core#4164]
After the upgrade, it won't be possible for nodes to generate v0 survey response (since all nodes must be on overlay version 31), so we should deprecate it.

**Comment by bboston7** [comment]
Closing because #4275 deprecated the V0 and V1 surveys. #4332 tracks the removal of these older survey versions.

**Comment by marta-lokhova** [comment]
https://github.com/stellar/stellar-core/issues/4332 looks like a dupe of this issue to me: this issue originally tracked code removal and cleanup on older versions of survey.

**Comment by marta-lokhova** [comment]
I don't mind using https://github.com/stellar/stellar-core/issues/4332, just seems like we already had an issue tracking old-style survey deprecation (the issue needed to be updated to include v1 though).

**Comment by bboston7** [comment]
Ah, I guess I saw deprecation and removal as two separate actions. These are now deprecated (they emit warnings upon use and the docs no longer refer to them), but still need to be removed.

**Comment by bboston7** [comment]
Next time I'll use the same ticket for both.
