### ISSUE TITLE
network survey: truncated topology on large networks

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/stellar-core#4174]
On the most recent survey run of the public network, ~50% of nodes discovered did not respond to survey requests. We should revisit throttling/timeout policy to ensure requests/responses are not dropped too aggressively. Some ideas:
* Too many surveyor-surveyed pairs causing requests to get dropped
* Flooding requests/responses takes too long, timeouts and causes core to drop messages (see NUM_LEDGERS_BEFORE_IGNORE)

**Comment by bboston7** [comment]
After looking more closely at the data it appears this non-response rate is dominated by other factors (such as alternate implementations on the network). Due to that, and because addressing #2592 will also require re-evaluating these throttling/timeout parameters, I'm closing this issue.
