### ISSUE TITLE
Reduce history tables for typical deployments

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#4211]
Right now some historical tables contain:
* information needed to publish to history archives
* information needed for supporting legacy (non captive core) meta consumers

We should probably look into optimizing for the common cases
* dedicated validators on one hand
* captive-core on the other

In both cases, the "meta" does not need to be stored in the database, yet it represents 90% of the data stored in the database!

As meta represents significant stress on the database, this would help reduce churn that is triggered by the "maintenance" process (which in turn gets translated into vacuum operations in databases).

There is a `MODE_STORES_HISTORY_MISC` internal config that could be used for captive-core case, but this one disables historical tables entirely (which is not compatible with publishing to archives -- we could just disallow publish to archives from captive-core).

On validators, when archives are enabled more granular control is needed as to not store meta
* `storeTransaction` --> pass a default init `TransactionMeta` (minimal meta) or wire up as to store an empty string in the `txmeta` column
* do not call `storeTransactionFee` and `Upgrades::storeUpgradeHistory` at all

As some people may still depend on this kind of meta, there is a need to continue to emit it until fully deprecated.

**Comment by graydon** [comment]
I think in general all we _need_ to use the DB for is queueing the txsets / txresultsets going into the next checkpoint. the fine-grained per-tx stuff is unnecessary, as is meta, yeah.

**Comment by anupsdf** [comment]
Closing this issue since a replacement [issue](https://github.com/stellar/stellar-core-internal/issues/263) has been filed to track removal of SQL backend support.
