### ISSUE TITLE
Squash DB schema upgrades before version 21

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/stellar-core#4225]
Now that the network is on protocol 20, we can squash older schema upgrades in the codebase

**Comment by SirTyson** [comment]
See https://github.com/stellar/stellar-core/blob/b0662113ed5dda5f560f5a7b12f7c3fd60412a1b/src/database/Database.cpp#L208C1-L209C1

**Comment by marta-lokhova** [comment]
Sample PR from the past: https://github.com/stellar/stellar-core/pull/2225
