### ISSUE TITLE
Transaction validation criteria: maxFee less than fee

### ISSUE THREAD

**Issue by johansten** [stellar/stellar-core#426]
https://github.com/stellar/stellar-core/blob/master/src/transactions/readme.md#validity-of-a-transaction
Should say "fee should be less than or equal to maxFee"?

**Comment by MonsieurNicolas** [comment]
thank you. fixed in https://github.com/MonsieurNicolas/stellar-core/commit/429400a3084603de257b89593fb548f4178ba389
