### ISSUE TITLE
Callbacks invoked on deleted objects

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#428]
I found that we are not using timers correctly.

For example in TrackingCollar::tryNextPeer(), we do things like
```C++
            mTimer.cancel(); // cancel any stray timers
            mTimer.expires_from_now(
                std::chrono::milliseconds(MS_TO_WAIT_FOR_FETCH_REPLY));
            mTimer.async_wait([this](asio::error_code const& ec)
                              {
                                  if (!ec)
                                  {
                                      this->tryNextPeer();
                                  }
                              });
```
(or just mTimer.cancel() ) to cancel the timer.

The problem is that this will crash at random time:
cancel does not guarantee that the callback is not already in the queue.

so basically we need to capture "this" using counted_ptr for example to avoid having this being deleted when we destroy this type of object

**Comment by gmarceau** [comment]
I need to rework how we do cancellation to fix the performance bug. I can do this change as well while I'm there.

**Comment by gmarceau** [comment]
Not an issue with our virtual timers.
