### ISSUE TITLE
Refactor ApplyBuckets Work

### ISSUE THREAD

**Issue by SirTyson** [stellar/stellar-core#4290]
Currently, `ApplyBuckets` work reasons at the `BucketLevel` instead of at the per-bucket level. Especially after the BucketListDB apply optimization, this means that there's some tricky logic required to keep our current place in the BucketList and make sure our iteration order is correct. We should refactor this to apply per-bucket instead of per-level to simplify the logic.

**Comment by AungkoMCM** [comment]
[README.md](https://github.com/user-attachments/files/15541900/README.md)

**Comment by marta-lokhova** [comment]
Resolved by https://github.com/stellar/stellar-core/pull/4314
