### ISSUE TITLE
Update overlay survey script to support new time sliced survey

### ISSUE THREAD

**Issue by bboston7** [stellar/stellar-core#4302]
#4275 adds a new time sliced survey mechanism with new HTTP endpoints for running a survey. We should update the python script to use the new endpoints.

**Comment by marta-lokhova** [comment]
Just double checking here: there is no dependency between this issue and https://github.com/stellar/stellar-core/pull/4275, because we'd still support old-style survey, so the script can be updated whenever we're ready to run/test survey V2, right?

**Comment by marta-lokhova** [comment]
Quick note here: I bumped priority of this issue to P0, since we'd need the new script to test survey v2 (ideally, we can do this during RC stage of our v21.1.0 release process to catch any issues before bumping to stable)

**Comment by bboston7** [comment]
Good point. At this point I don't think the interfaces in #4275 will change significantly (if at all), so I'll start working on updating the script.
