### ISSUE TITLE
incrementalize or multithread bucket-apply and txn-replay

### ISSUE THREAD

**Issue by graydon** [stellar/stellar-core#432]
There are a couple spots in catchup where we take a potentially-long pause while applying the contents of a potentially-big xdr file in sequence. These happen on the main thread and thus may block SCP keeping up with incoming consensus / incoming network traffic, and thereby defeat catchup and cause us to restart.

The solution here is to either break the apply up into pieces and bounce off the event loop while we're applying (probably easiest?) or else throw the apply task over to a worker thread and let main return to buffering / awaiting the apply-completion signal.

**Comment by MonsieurNicolas** [comment]
I think that the less risky approach is to go with the worker threads on this one as
* trying to break up the flow using callbacks etc is going to make the code much harder to read
* a bunch of timers are going to break in the consensus modules (I doubt we'll get down to order of a few seconds)
* the node is going to be flagged as "not contributing to flooding", and get a bad rep
* we're re-inventing time slicing except we don't have control over some components (like SQL)

alternative seems more scoped:
* make the "apply bucket" code capable of running on a worker thread (no callbacks involved for this code)
* the trickier part is to decide on what to do when replaying transaction sets - it may make sense to queue those individually on the main thread (same overhead on the rest of the system than a regular "closeLedger")

**Comment by graydon** [comment]
Thing is no matter what you do, it's not a synchronous operation anymore. You don't just send it to a worker thread; you send it to a worker thread then fall back into your event loop in a "still applying stuff" state which you have to be able to handle being-in while data is arriving. And at some point the worker will post-back the completion.

The amount of work you have to do to make all that practical is the hard part; whether or not you have the main thread do the work increments or a worker thread is a minor detail. Main thread just has less racing to worry about.

**Comment by graydon** [comment]
So I did _some_ of this in #680 but evidently not enough. We're still seeing negative consequences of too-large-granularity work units here, in terms of starving the overlay layer during catchup. In particular:

  - Dropping ledger-close events that happen while we're applying, causing retry to restart.
  - Dropping connections and thereby engaging in exponential backoff / marking the peers as problematic in the peer database, resulting in long reconnection stalls when catchup finishes.
  - (Minor) not letting ctrl-C interrupt / kill the process while it's applying.

These are all tolerable -- none actually _breaks_ catchup, just delay it -- but they're annoying and cause more confusion and aggravation for node operators than necessary.

The nuts and bolts of doing catchup-apply work in finer granularity are mostly in place. `CatchupStateMachine::advanceApplyingState` is already there for incremental application, `CatchupStateMachine::ApplyState` just needs to be further enriched with Yet More State to track sub-file-level work. In particular, it needs to keep 2 `XDRInputFileStreams` open for stepping through ledger and tx files one ledger at a time (rather than one checkpoint at a time) and/or a persistent bucket-cursor open with an incremental / resumable apply function, rather than the current `Bucket::apply` path that goes entire-bucket-at-once.

**Comment by graydon** [comment]
This behavior was fixed during the rewrite in #951
