### ISSUE TITLE
Have the flag enable-protocol-upgrade-via-soroban-env-host-prev set by default

### ISSUE THREAD

**Issue by anupsdf** [stellar/stellar-core#4357]
### What:
Have the flag enable-protocol-upgrade-via-soroban-env-host-prev set by default. Introduce a new flag to exclude prev so it can be used for minor releases after the protocol upgrade.

### Why:
Nodes without the prev host will reject protocol upgrades during consensus. During protocol 21 upgrade we saw a validator had built core from source and missed setting this flag. This caused them to loose sync during the upgrade.

**Comment by sisuresh** [comment]
I wonder if we should just remove the flag and always have prev enabled. @graydon Is there any benefit to removing the prev crate other than slightly reducing the binary size?

**Comment by graydon** [comment]
Nothing comes to mind,  I'd certainly be willing to try it and see if anything goes wrong.

**Comment by sisuresh** [comment]
Closed by https://github.com/stellar/stellar-core/pull/4434
