### ISSUE TITLE
Benchmark for measuring ledger apply time

### ISSUE THREAD

**Issue by dmkozh** [stellar/stellar-core#4391]
Currently the go-to way of measuring Core's performance is the 'max TPS' test, that relies on generating transactions and sending them to a synthetic network. Unfortunately, this test does not care about the ledger close times, which has been serviceable thus far, but is not sufficient for the most of Soroban performance improvements. For example, it can't provide a good answer to a question like 'how does increasing a ledger-wide instruction limit from 500M to 1B affects the ledger close time?' or 'how much more capacity we could get if we applied transactions with 8 parallel threads?' etc.

In order to be able to reason about the Soroban performance, a new type of test/benchmark is necessary. The basic requirements are as follows:

- Runs on a single machine, without setting up the whole network in order to isolate the costs and use hardware that is closer in specs to the real validators (max TPS tests use worse machines)
  - It would be nice to run the test as a part of CI, but probably on-demand mode only is sufficient initially
- Allows customization of the network config
- Generates a stream of synthetic Soroban transactions with configurable resource consumption and _reasonably tight_ declared resource estimations. The transactions also have to succeed most (at least 95+%) of the time. Both properties are important as to not inflate the modelled/real resource usage ratio
- Builds a transaction set and applies it to the ledger
  - During the application we need to make sure that we hit the necessary ledger-related logic, such as prefetch 
- Measures the apply time metrics (such as avg/p99/max) and potentially allows to make assertions on that

There are also features that could be nice to have, but are not critical initially, such as:
- Also generate a stream of reasonable classic transactions, including DEX transactions. This will allow us to reason about classic vs Soroban impact on the close time and scaling classic up or down
- Measure the tx set building timing. That's useful for building tx sets with parallel support which has non-trivial cost
- Provide eviction-related scenarios, such as generating transactions that create short-lived temporary entries
  - This requires ensuring that we're triggering the eviction logic as well
- Start with a pubnet ledger snapshot in order to ensure we have more realistic ledger I/O timing

Some basic ideas for the initial version:
- Factor out the tx generation logic from loadgen 
- Fix the resource estimation logic for tighter estimates (I _think_ we should be reasonable close there)
- For the benchmark itself:
  - Do preparation similar to loadgen (generate accounts, upload wasm, instantiate the necessary contracts, do settings upgrade), but by directly applying the transactions (no need to go through consensus here)
  - Define reasonable generated resource/inclusion fee distributions and generate transactions following these distributions until hitting the tx queue limits (i.e. 2x the ledger capacity for each resource)
    - Resource fees can be arbitrarily high
  - Build a tx set from the generated transactions and run the logic for closing the ledger with the generated tx set
  - Generate a new batch of transactions until we hit the 2x resource limit again

**Comment by MonsieurNicolas** [comment]
I guess you have a couple scenarios to keep in mind:
* can we get "ultra realistic benchmarks"? For this, we may want to expand on https://github.com/stellar/supercluster/blob/main/src/FSLibrary/MissionHistoryPubnetPerformance.fs -> picking "interesting" ranges from the public network history allows to compare changes "side-by-side" without having to worry about differences in other parts of the system (like tx queues, SCP, etc)
* some sort of synthetic benchmarks (those are quite tricky). What we tried in the past (maybe went a little overboard) was to generate history archives (ledgers, and checkpoints) by mutating an existing one. We applied a few transformations there: scaling the bucket list (buckets ass to ensure that we have a realistic distribution across levels), scaling tx sets (same thing, to ensure that we'd keep distribution in use cases).
    * what I like with that approach (generating history archive), is that it allows to decouple test corpus generation from actual execution (so we can ensure that when we perform side by side tests, we really test only implementation differences)
    * relying on catchup, allows the test to be more or less like the "ultra realistic benchmark", the difference here is just that some modes may need to exist (like use as "apply order" the hash order, and skip hash verification from the archive as changing any parameter will cause drift -- those are things that we were already doing in the "scaling" approach)
    * I don't think you'd want to try to scale pubnet traffic (that was quite a headache already in classic), but being able to construct an interesting bucket list is probably part of the requirements

**Comment by dmkozh** [comment]
> picking "interesting" ranges from the public network history allows to compare changes "side-by-side" without having to worry about differences in other parts of the system

That is not very useful for Soroban given that historical traffic won't have much volume for a while. It's also not very interesting to know that we could close a historical ledger a bit faster; a lot of changes increase the capacity without necessarily making the replay faster (parallelization is an obvious example). Last, but not least, I don't even think this needs to be a mission vs just a Core command (unless that somehow simplifies the setup, that is).

> What we tried in the past (maybe went a little overboard) was to generate history archives (ledgers, and checkpoints) by mutating an existing one. 

I think with Soroban we don't need to rely on historical data at all and I'd say we don't even need to be super realistic in terms of the resource distribution for a given transaction (as long as it's small enough to allow us to get close to the maximum per-ledger capacity on most dimensions). Unless metering inaccuracy has huge variance (which we don't think it does), just doing a certain amount of work lets us not care much about what work it is. Synthetic txs also have a benefit of being able to tailor the generation to the benchmark needs; e.g. for parallelization we can generate traffic with different I/O conflict patterns.

>  is that it allows to decouple test corpus generation from actual execution (so we can ensure that when we perform side by side tests, we really test only implementation differences)

I'm not sure what's the point of jumping through the hoops to generate the archive. The approach suggested here is almost the same, but just skips the archive as well. Another benefit is that this allows us to also account for tx set generation time when necessary. If your concern is about data generation stability, why not just use the same generation seed if you wanted to run the tests over the same data?

Also FWIW for the most of the future work I'd rather be interested in evaluating the ledger close time given different limit configurations vs comparing the improvement on the tx sets (we actually don't expect any improvement in the first place). So I think it would make sense to make sure we can do at least that. But it also shouldn't be hard to make sure that the same tx set parameters + seed will yield the same tx sets.

> (like use as "apply order" the hash order, and skip hash verification from the archive as changing any parameter will cause drift

I'm not sure we should skip anything; we're going to perform sort for apply when closing the ledger, why should we skip it? If we need more fine-grained evaluation, we could use more granular measurements, more metrics, tracy etc.

> being able to construct an interesting bucket list is probably part of the requirements

What makes BL 'interesting'? We can synthesize certain amount of data during setup in order to cover the reads/updates. Simulating data in old buckets is tricky, but I'm not sure if history helps with that much (though I guess we could emulate large BL if we wanted?)

**Comment by dmkozh** [comment]
> I agree that at this point in time Soroban production data is not that interesting, but I imagine that whatever we do here wrt benchmarking would hold for some time.

Yeah, that makes sense. I think that instead of trying to scale the production traffic (even if it has much more meaningful volume than we have now), it's always better to compute the statistics of that traffic (which can be done separately from the benchmark). Scaling logic was already quite tricky for the classic operations, and I think it's pretty much impossible to scale Soroban traffic, because we have no clue as to what any given transaction does and whether repeating it will not fail almost immediately (e.g. at the first auth check). I.e. if we have a statistical model as an input to the benchmark, then we'll be able to improve it in the future just by providing better statistics.

> basically when replaying a range, I want to know that I am actually benchmarking the work and not have to substract the (potentially significant) noise from the generator

That's a fair point. But given that we probably don't need to run this over _that_ time periods (like 100s-1000s ledgers at most?), we can just generate all the transactions beforehand. We can even output them if the generation takes long time and we need to run several benchmarks. Basically the main difference is that we don't need to mock the history and that we account for the tx set building time, which is not irrelevant for the parallelization work (even though it should be subtracted in some cases).

> Also the alternation of work and generation may give an artificial advantage to the IO subsystem as periods of generation are basically free of IO.

That's kind of debatable; isn't that what happens now to the apply time?  We do fetch some data for tx queue, but that probably doesn't make much difference in terms of IO rate difference between the 'idle' period of gathering transactions and 'busy' period of prefetching the data and outputting the ledger changes.

> the same transaction will behave differently (fee charged at a minimum), so you can't predict certain things like the hash of the ledger.

I'm not sure I understand, why should we care about the hash of the ledger in the first place? My suggestion is to take a fork of the ledger (maybe empty one, maybe one with some real or synthetic data), apply N batches of transactions to it using the normal apply logic and reach a certain new state of the ledger. I don't think we care about which state we arrive at; we should only care about the transaction success rate not going down and the ledger close time. That's the reason why I don't want to deal with the history at all.

 >  interesting means that we have to have the right distribution of updates/shadowed entries

I don't think we can replicate that with scaling for the reasons mentioned above. But it is not hard to replicate that synthetically by just configuring the distributions correctly.

I believe the key point of disagreement/misunderstanding is the intended usage of the benchmark. It feels like what you're suggesting leans more towards answering the question like 'how long would it take us to apply a tx set on build X vs build Y?', whereas the question that I want to answer is 'will the ledger capacity of A instructions, B reads, C writes be applicable within N ms?'. I think the latter is much more important for Soroban, because a good chunk of improvements has nothing to do with the apply time of any historical tx sets.

**Comment by MonsieurNicolas** [comment]
Yeah I thought from the title and description of the issue that you were trying to come up with a way to answer questions like:
* did build X introduce some performance regression (not observable from protocol point of view)
* what's the impact of a protocol change. things like switching wasmi runtime (what we're looking at doing now), or caching of VM instantiation (what we did in protocol 21)

Where as it seems that the focus instead is more towards scheduling choices which include understanding the impact of lane choices (in the parallelization context), and other settings like block/stage capacity.

**Comment by dmkozh** [comment]
> more towards scheduling choices which include understanding the impact of lane choices (in the parallelization context), and other settings like block/stage capacity.

Exactly, though I think it should work well for changes like VM caching - if we replay a historical transaction (pre-VM caching) and apply VM caching to it, we'll get faster real time of application, but at the cost of the declared instruction underutilization. However, if we generated 500M worth of instructions via transactions that use caching and tighter VM cost estimation, we might actually get _longer_ application time due to higher real/modelled instruction ratio. That is admittedly a harder setup to reproduce, but I just wanted to demonstrate that sometimes even something that's formally an 'optimization' might actually reduce the capacity (resource-wise, not TPS-wise) in practice due to how metering works.
