### ISSUE TITLE
Add per-bucket Entry size Metrics

### ISSUE THREAD

**Issue by SirTyson** [stellar/stellar-core#4426]
Currently, we only track the size of the whole BucketList. This doesn't give us much insight into the makeup of the BucketList. We should add a size and count metric grouped by `LedgerEntry` type (and persistent vs. temporary for soroban types) to each Bucket. This could be efficiently calculated during Bucket merges. We should then aggregate BucketList level metrics and log these to grafana, as well as output them in meta.

**Comment by ThomasBrady** [comment]
- [ ] Code changes
- [ ] Grafana dashboard change
- [ ] Hubble ingestion / coordinate with data team

**Comment by ThomasBrady** [comment]
https://github.com/stellar/puppet-v4/pull/4081 grafana changes

**Comment by ThomasBrady** [comment]
XDR changes https://github.com/stellar/stellar-xdr/pull/219
