### ISSUE TITLE
allow running `verify-checkpoints` incrementally

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/stellar-core#4454]
Currently, `verify-checkpoints` command always starts verification at genesis, and either stops at the most recent network ledger, or at a specified `--history-ledger`. The problem is verifying all the way back to genesis takes hours, and typically operators want to keep trusted hashes file up-to-date, so verifying the whole chain isn't efficient. We should design a solution to amortize the cost of trusted hash generation.

**Comment by ThomasBrady** [comment]
Design / planning doc https://docs.google.com/document/d/1GRzHAO4_YrfanXqoVc1UDIMhUV10PFqIMQyOxlPOW_s/edit?usp=sharing
cc @marta-lokhova / @anupsdf
