### ISSUE TITLE
Trying to connect to the same peer too many times. 

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-core#447]
seems like the # of failures isn't being recorded or something

**Comment by sacarlson** [comment]
I'm not sure this is related but I see after my IP has changed on my ADSL line that my old ip is still displayed in the list

**Comment by graydon** [comment]
This bug will probably not be fixable without a little more detail. Steps to reproduce? Version number? Logs of what it looks like? Is it still happening?
