### ISSUE TITLE
Permit forced checkpoint / forced catchup

### ISSUE THREAD

**Issue by graydon** [stellar/stellar-core#452]
Periodically the network finds itself lacking a sufficient consensus and its next-available slice members are behind it, history-wise; they would catch up and produce a new quorum, if only the "ahead" members would publish their history prefix. But they have not yet advanced to a checkpoint-time, so no checkpoint is published and the would-be peers never join the quorum. This scenario apparently happens and causes the network to stall. To fix:

  - [x] Switch checkpoints from "checkpoint numbers" to ledger numbers
  - [x] Add a http command to manually force a checkpoint-publish
  - [x] Add a cmd line command to manually catchup to a given checkpoint (ledger) number and then exit.
  - [ ] Optionally: try to make all this automatic. Specifically:
    - [ ] Add a timer reset on checkpoint that forces a new one after enough time (~10min or so?) and sets a "we're stalled" flag
    - [ ] Add a message type that's rebroadcast on a timer, continuously, that broadcasts the recommended-ledger to anchor catchup on: either current ledger (if current ledger == last checkpoint and "we're stalled" is true), or else next checkpoint.
    - [ ] Run catchup on the broadcast anchor if you hear it.

**Comment by jedmccaleb** [comment]
I wouldn't do the optional stuff. I think it will be tricky to get right and may lead to more problems. I'd rather it just be very simple for a human to correct it once we get the alert that something has gone wrong

**Comment by graydon** [comment]
Ok. I'm concerned that if this happens often we might be putting strain on humans by having them in the loop. But I won't have time to do the optional part before vacation anyways :)

**Comment by graydon** [comment]
I no longer think it's really a good idea to try to automate the remaining bit here, so I'm closing this bug. Reopen if you disagree.
