### ISSUE TITLE
TCPPeer::sendMessage is not safe

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#455]
the method kicks off an "async_write" on the underlying socket but there is no queuing done (at the Peer level?). so multiple writes are dispatched to the OS.

This may result in out of order messages, or worst, corrupted interleaved messages

**Comment by graydon** [comment]
Oh goodness: http://think-async.com/Asio/asio-1.10.2/doc/asio/reference/async_write/overload1.html

"The program must ensure that the stream performs no other write operations (such as async_write, the stream's async_write_some function, or any other composed operations that perform writes) until this operation completes."

So much for my "ASIO will serialize multiple writes for us" theory :(

**Comment by donovanhide** [comment]
Worth a read:
http://stackoverflow.com/a/12801042

**Comment by MonsieurNicolas** [comment]
Cool, yes moving to strands seems to be the simplest way to serialize writes. Graydon confirmed that it's included in our header only implementation.
