### ISSUE TITLE
Consider adding a short list of additional ledger links

### ISSUE THREAD

**Issue by graydon** [stellar/stellar-core#458]
In the previous server there was an auxiliary data structure in the ledger header called the "skip list" that served two purposes beyond merely being an index:

  - It indexed the _trusted path_ from current consensus root to a given txn or ledger state, such that someone wanting to look deep into the past could verify a trust path to the point they were interested in in only logarithmic time.
  - It added _redundant trust links_ to mitigate the risk of loss of a single ledger, which would cut the past off from verification in the present. Given our history design -- it's entirely possible to have the history archives just drop some history, if we don't store it sufficiently redundantly or due to operator error or such -- this risk is arguably magnified for the redesign.

I'd therefore like to discuss the possibility of adding such a structure to our ledger header, before we finalize it. I do not think it's especially risky or difficult to support; at this point we really don't need to _do_ anything much with it, just form it while calculating the current/next ledger headers. The way it works is you store (say) 8 old-ledger hashes in the list, each 16x further-back in history from the last. If you're passing a ledger with 0 in its low 4 bits, you promote current ledger hash to the 0th history slot. If you're passing a ledger with 0 in its low 8 bits, you promote 0th to 1st, and then curr to 0th. And so forth. It would cost (say) 32 * 8 = 256 bytes extra per ledger header, or about 67kb per day in long term storage; but it'll mean that our history storage is not completely invalidated in the presence of gaps: we can publish a summary-description of the transactions missing from such a gap by diffing its before/after states (from the buckets), and history on either side will remain cryptographically trusted.

(16x was again pulled out of the air; perhaps the 4x bucketlist multiplier should be our guide here as well)

**Comment by jedmccaleb** [comment]
Yeah we should probably do something like this. 16x doesn't seem like the right fanout though:
16x would be:

Index | Ledgers | Time in past
----- | --------- | -------------
0 | 16 | 80s
1 | 256 | 21 min
2 | 4096 | 5.7 hours
3 | 65536 | 3.8 days
4 | 1048576 | 60 days
5 | 16777216 | 2.6 years 
6 | 268435456 | 42 years
7 | 4294967296 | 681 years

8x would be:

Index | Ledgers | Time in past
----- | --------- | -------------
0 | 8 | 40s
1 | 64 | 5.3 min
2 | 512 | 42.6 min
3 | 4096 | 5.7 hours
4 | 32768 | 1.9 days
5 | 262144 | 15 days 
6 | 2097152 | 121 days
7 | 16777216 | 2.6 years

That seems about right. I'd also drop the first 4 of those. Doesn't seem like we really need to store the checkpoints for under 1 day.

**Comment by jedmccaleb** [comment]
we agree waiting for graydon

**Comment by MonsieurNicolas** [comment]
putting comments here as the actual specification discussion was never completed. Proposal PR is there https://github.com/stellar/stellar-core/pull/519

I would go with base 8 (like proposed above) and not base 5 like in the PR.

As far as which link to include:
I think that given that this thing is to help mitigate losses of a given ledger or range of ledgers in history, we should actually got for the lower indexes. So index 0..6 : skipping the 2.6 years (anything larger than 6 months) doesn't seem useful to me. In base 8, this gives the capability to jump between 40s and ~5 months, which is pretty good.

Also, I would update the backpointers using Graydon's scheme as it keeps the size of the jumps constant.
