### ISSUE TITLE
tx memos

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-core#460]
Here is a possible solution for including extra info in transactions. We add an optional memo field to transactions. It is a max of 32 bytes. 

We also add an optional “content server” field to the accounts. This is a string of max length 32 bytes.

If the memo is less than 32 bytes it can be interpreted however the client or consuming application want to, possibly as a string or destination id.

If it is the full 32 bytes then it is interpreted as a hash of some content that is stored by the sending account’s content server. The client will ask the specified content server for the sending account to look up the memo. The client will get the full memo from the content server and can check the hash.

The format of the full memo can be decided later and evolve independently of the main stellar protocol.
The parts of full memo can be encrypted with the receiving account’s public key.

How does this work when the receiver needs to reject a tx? 
       probably just say “reject” in source memo so receiver knows to look the content up in its own server.

**Comment by codeck** [comment]
how about let wallet providers track txs by themselves and map tx->memo/extra info in their own db?

**Comment by jedmccaleb** [comment]
That makes the common case of either no memo or a destination tag like memo more hassle since now the consumer has to do a lookup. The most used memos will probably just be equivalent to the destination tag in stellard. It is way nicer to have this info right in the tx rather than require this extra lookup.

**Comment by graydon** [comment]
I don't have thoughts about usage scenarios; encoding-wise though, I think a fixed-length field with two interpretations is not the right encoding choice. You can't enlarge it if you need to, you can't contract or omit it if it's unused or partly empty, there are only two interpretations for it (what happens if you want to wire in a third state / interpretation?), and neither interpretation is obvious to the reader of the protocol definition file; either interpretation prone to accidental use as the other.

I recommend, like with most of our fields, an explicit, enumerated union. It will cost 4 bytes in txs without memos and 8-or-more when there's a memo-with-some-value. But it leaves the interpretation explicit, expandable in the future, and able to accommodate both fixed and variable-length fields.

**Comment by donovanhide** [comment]
My feeling is that variable length fields in transactions are the root of all evil :-) Mr Spambot agrees with this sentiment.

An fixed length 8 byte field filled with an id generated before the transaction is signed would be sufficient in my view for all external reference cases. For example:

* As a destination id for payments/transfers. If the id was generated sequentially, it is straightforwards. If it is a hash, then the account id and sequence of the transaction allow for collision resolution, or alternatively the transaction id can be used as the discriminator. This means the gateway has to also store some fields of the transactions destined to it, as they are received, but this seems like a good thing to me.

* This same id can then be reused for extra storage on that gateway's server for things like memo information.

I think an encoded transaction already has enough entropy in it to let it be uniquely identified globally, but the pre-generated transaction-specific data should be as small as possible to avoid the abuses of attackers. I'd also recommend not including any variable length arrays for the same reason. Signers in Account is already a candidate for abuse.

**Comment by MonsieurNicolas** [comment]
Same here, I am actually wondering why we need all those bytes?
If the purpose is to map a payment to a specific invoice in a company's database of sorts, 64 bits like Donovan says should already be plenty? I don't see why we need a secure hash for this.

**Comment by jedmccaleb** [comment]
@donovanhide > Signers in Account is already a candidate for abuse.
How so? Your min balance increases with each signer

**Comment by donovanhide** [comment]
Well, I'm not a spammer, but I could imagine one might enjoy rotating the contents of the Signers field:
https://github.com/stellar/stellar-core/blob/master/src/transactions/SetOptionsOpFrame.cpp#L61-L106
So, for the cost of 20x the balance per signer and n transaction fees, a spammer can bloat the history log  with a fair amount of random bytes.

**Comment by donovanhide** [comment]
P.S. An interesting approach is to scale the transaction fee to the byte length of the transaction itself, minus all obligatory fields. Thus a spammer pays extra to spam, and if you need the optional feeds, well, you have to pay for them.

**Comment by MonsieurNicolas** [comment]
re: fee model, we need to open an issue about that and discuss it. We could
not figure out a model that is a real deterrent to spam without hurting
legit users.

**Comment by jedmccaleb** [comment]
Yeah I guess you can use the hash of the tx itself as the key to look up the longer memo. So I would say we make the memo field a union of one of the following: {empty,lookup,64bit id}

**Comment by MonsieurNicolas** [comment]
So what is "lookup" then?

**Comment by jedmccaleb** [comment]
Lookup means that the client needs to ask the sender's content server for the memo attached to the tx. And I remembered why it needs to be a hash of the memo and not just the tx hash is so the client can be sure it is getting the correct memo back from the content server.

so memo field would be union of: {empty, 32byte hash to lookup at content server, 64bit int}
