### ISSUE TITLE
reverse federation

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-core#461]
Add a "federation" field to account.
This is a 32bit array that is either a domain or another account ID. If it is another account ID then the client should look up that accounts federation field to get the domain that handles reverse federation for this account.

**Comment by codeck** [comment]
don't limit address to only one federation. we need a list if we want maximize the interlinking between integrater.  A user may use wallet from stellarwallet.com , and associate the address with a organization improvestellar.org which get donation by integrate payment processing platform getstellar.com.

the address may have 3 reverse resolving results,  tom@stellarwallet.com, donation@improvestellar.org, uid_127341241234@getstellar.com.

**Comment by jedmccaleb** [comment]
Hmm the point of this is that when you get a tx in from someone you want to look up and see who sent it. Do you really think you would need to get several names back from them? When you get an email you only get one of the senders email addresses even though the person sending probably has multiple.

**Comment by liangran** [comment]
One account with one federation is ok. As people can have different address. The client to handle the federation protocal should support more controls like textbox, select, labels etc.

**Comment by codeck** [comment]
Actually I was denying adding any field look like domain name to Account in ledger, by  reductio ad absurdum(if we need one, why not more). These approaches are making stellar centralized. It's quite like in early days of internet, email addresses are tightly bond to telephone number by ISPs. 
telephone number -> email address -> crypto address.

the federation protocol support form is the way to solve #460 I prefer. 
plus we may need a tx info exchange protocol to make non-privacy tx info that shared by 3rd party institutes acquirable from whole network. so any wallet providers can choose providers to get tx info to decord tx history list.

further more,  processing all address info, tx info in a parallel consensus network using SCP would be wonderful.

It was a great step moving ledger history out from stellar-core, why we put other less important stuff in again? I wish stellar could concentrate on address-balance-transaction stuff, no distractions.

**Comment by codeck** [comment]
Address usually created by a wallet associate with a domain, this is the usual case which corresponding to webmail in SMTP. In a pure wallet software without online service, as general email client in SMTP, users have option to set there federation domain. So we can assume almost all wallets know the federation domain of addresses they manage.
Then just an enhancement to the federation protocol can fulfill the requirement: sender's wallet piggyback the address and federation domain of sender when request receiver's federation server, so receiver has hints where to reverse the federation address.

**Comment by MonsieurNicolas** [comment]
The part I don't understand is why do we even need one at all? It's like adding DNS inside TCP.
This field is controlled by the account owner, so why bother with it?
If an external entity can answer a question like "myCustomer(stellarID) ?", all we need at the protocol layer is to ensure that people can't forge stellarID - and this is exactly what the private key provides already.

**Comment by jedmccaleb** [comment]
@MonsieurNicolas : I don't follow?
The point is that in UIs we would rather not have people deal with stellar addresses. It is way more friendly to deal only in common names. The problem is when you get a tx in all you have is the stellar address not the common name.  This is a proposal to allow accounts to tell you where to find their common name.

**Comment by MonsieurNicolas** [comment]
Reverse lookup when receiving payments from random addresses doesn't seem like a super high priority to me: the memo field should cover this pretty well as the sender is sending something for a reason (and the reason is not necessarily tied to identity).
The other direction is address book management and there is no need for support in the ledger for that.

What I am also saying is that having unverified claims (like "I have an account with XYZ") in the ledger seems like a bad thing.

The way I see this, it's really about identity/claims management:
for KYC (that should be on top of the priority list) we need to give the right building blocks - this scenario can be seen as a very weak identity lookup, but in other context you may want to get to other type of information about the sender. Some should be available to anyone, some other should only be only available in some context.

Lastly, even in this context, I have concerns about privacy implications if we don't do the public stuff right as it creates even stronger links between accounts; I don't want end users to become experts in profile management to protect their privacy. People that use friendly names are the ones most likely that don't know how to protect their identity: we'd be leaving a loaded gun to a bunch of toddlers.

**Comment by liangran** [comment]
From my view, the federation field is important. I agree the momo field can cover a lot of cases. But all the cases is based on a end user view. The field can help gateways or other organizations to run a better business on the network.

**Comment by codeck** [comment]
@liangran I don't follow. will an address not in "ripplefox.com" federation be able to charge/deposit from you?

**Comment by liangran** [comment]
@codeck There are two cases. If user start a transaction with gateway, the wallet can check the website for the address. Just like the existing federation. 
However, if user received a payment, how can this user know which gateway did this? A federation field in account can resolve such case.

**Comment by jedmccaleb** [comment]
> Reverse lookup when receiving payments from random addresses doesn't seem like a super high priority to me
Well it is essential if we want people to almost never deal with the public keys.

> What I am also saying is that having unverified claims (like "I have an account with XYZ") in the ledger seems like a bad thing.
It isn't unverified. The account sets the server other people should look up their name from. The receiving account still has to go look it up. so if you set your domain to be google.com people will still go ask google.com if that is true.

**Comment by codeck** [comment]
incoming transaction annotation could be done in wallet/client together with their federation servers. so it *should* not be in core protocol, using Ockham's Razor.

**Comment by jedmccaleb** [comment]
codeck: how are you saying it could work?  if you get a payment from some random address how do you know the common name?

**Comment by codeck** [comment]
bob@microsoft.com is using a wallet from microsoft which tracks the address&federation name of coz. when he is going to send to alice@google.com, the client will inform stellar.google.com bob@microsoft.com(who's address is g123) are requesting alice@google.com
's address to send. a well implemented fereation server of google.com will verify and cache the mapping of g123<->bob@microsoft.com and shown it in the wallet which alice uses to view transactions.  

The right place need redesign/enhance is the federation protocol.

**Comment by jedmccaleb** [comment]
codeck: that is a good idea but requires more coordination and doesn't solve the issue of when you just get in a random payment. I added one new field that can be used for this and memos.
