### ISSUE TITLE
What are appropriate fees to prevent spam?

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-core#463]
We have two types of spam prevention, the tx fee and the reserve that goes up and down depending on how much a particular account holds in the ledger. What is the ideal amount for each of these?

**Comment by thejollyrogers** [comment]
2.9-7% of the transaction

**Comment by MonsieurNicolas** [comment]
I don't know about the numbers - but I can add a few things to help frame
the problem:
I am not sure we defined "spam", the way I would define it is something
that increases the cost of running and managing the service abnormally.

We have a couple areas that I can think of:
ledger state - balances, trust lines etc.
historical data - data stored "forever" include transactions and ledger
state snapshots.

A transaction is stored once in the overall system, costs some CPU and disk
I/O.
A state object on the other hand translates to permanent cost in the
system: it increases both the size of the ledger state and the size in
history.
The incremental cost of a ledger entry change on the overall historical
subsystem is something like log(t)/log(4) (with t=n*T, T being the period
of change) ie: if something changes all the time it gets replicated in
history much more often than if it changes less.
The cost of history itself is tied to how much data it has: if we have
100TB of data in there one day, we have 100TB + increment the next day and
so on.

Now, a couple things to consider:

ledger state is something that all nodes have to deal with and makes
catching up etc much less efficient.
History on the other hand can be trimmed over time. Maybe some
organizations will store it forever, some will store subsets of it.

If we were to bias towards charging for the cost of running the ledger, the
model might be different:
IOPS is number of object changes (could be add/delete/modify, doesn't
matter)
CPU is roughly the number of signature verifications in a transaction.
storage is ongoing cost - so the reserve model as it may not be right as
right now it's a flat rate for infinity. Maybe needs to be combined with a
scheme to increase the reserve over time.

Nicolas

**Comment by jedmccaleb** [comment]
So fee on the tx is where we charge them for the ledger churn and signature verification. Right now we increase this fee per operation in the tx. but maybe we should also bump it per signer?

I don't get why you would want to increase the reserve over time? Longer lived stuff should drift down to the lowest level and just sit there not causing much strain. If it changes a lot then they are being charged tx fee.

We need some idea of how much it costs the network to store a ledger entry and how much it costs to process a tx.

@MonsieurNicolas It also just occurred to me, do you have some assert if the account is ever under the min balance? Cause it can happen if the reserve fee goes up over the network.

**Comment by MonsieurNicolas** [comment]
re assert: I opened https://github.com/stellar/stellar-core/issues/465 to track adding a unit test - it seems that we're OK from looking at the code (we check when reducing the balance, not at save time)

re increasing the reserve: it would be increased for all it's just an incentive to delete entries, not recreate/modify them, sum(reserve in accounts) = cost(number_of_entries_in_ledger) ; simplest cost model is something like sum(nb_entries in history from genesis)*rate. Then the question is a policy question around how often to adjust it.

**Comment by MonsieurNicolas** [comment]
actually I am not sure that increasing the reserve will work: for an account with high balance, we're still providing "free storage" (the entire reserve is recovered when deleting entries).

The way out of this may just be to charge a fee proportional to the reserve: that way accounts with large number of objects occur more cost over time if they don't clean up their entries (and using more accounts doesn't make things cheaper).

I am not sure how to deal with inactive accounts that created a lot of entries "just for fun".

**Comment by thejollyrogers** [comment]
Monsieur Nicolas, regarding inactive accounts, what about an inactivity fee
where say every 100 ledgers your account is charged a fee? That will give
your account a lifetime of 2 million ledgers starting with a minimum
balance of 20 XLM after which it will be deleted when reaching 0.

**Comment by MonsieurNicolas** [comment]
Ideally we could just delete stuff like this - the problem is that some
accounts cannot be deleted right now: issuers for example cannot be deleted
if somebody holds some of their issued currencies.
Also, if an account has a balance in one of their trust line, we cannot
delete it either (would be give their $1M USD back to their bank if they
happen to not have XLM? Probably not).

**Comment by jedmccaleb** [comment]
For the tx side of this, I think we should have a max # txs that can be included in any ledger close.  If the max is reached then the txs with the highest fees get in and the rest are put off till a later ledger. This way the network can get a sense of how many txs it can handle and just scale up the max # rather than trying to adjust this base fee to discourage a spam attack

**Comment by jedmccaleb** [comment]
Reserve system is fine. do above but outside of the protocol. It is up to servers to limit the tx set.
