### ISSUE TITLE
`herderOutOfSync` makes operating a test node in "MANUAL_CLOSE_MODE" cumbersome

### ISSUE THREAD

**Issue by nullstyle** [stellar/stellar-core#464]
I am presently trying to build an automation library to aid in creating testing scenarios for horizon that reflect actual output data from stellar core.  My plan is to automate transaction submission and ledger close events from a central script that will manage an instance of `stellar-core` and save data at appropriate moments.

To do this, I operate `stellar-core` in MANUAL_CLOSE=true as well as --forcescp.

Unfortunately, if 35 seconds (i.e. `CONSENSUS_STUCK_TIMEOUT_SECONDS`) elapses between manually triggered ledger closes, stellar-core will trigger its "out of sync" logic `HerderImpl::herderOutOfSync` and after that moment you can no longer close a ledger until you stop, initialize --forcescp again and relaunch.

Can someone recommend a way we can improve the system such that this style of automation is more clean?  At the very least, adding a status in the response from `/manualclose` to signify that we did not close the ledger would improve things a bit.

**Comment by MonsieurNicolas** [comment]
Or just disable this check for out of sync in manual mode. It should not even participate in SCP

-----Original Message-----

**Comment by nullstyle** [comment]
Yep, that would be ideal.  I didn't want to presume it was easy, though,  hence the "at the very least" solution that I new would be simple the implement.
