### ISSUE TITLE
should we make offers always expire

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#466]
People will have to recreate offers once in a while (we can make it some good number like 3 months).
Issue with keeping them around forever is that it's possible to have offers that are unfunded in the system that will never get cleared if they happen to have a really bad rate (and thus never get hit).

**Comment by jedmccaleb** [comment]
But is there then something that goes through and cleans them up? Seems like this should just be handled by the reserve requirement.

**Comment by MonsieurNicolas** [comment]
Yeah we would need some sort of GC transaction. We can assume that the fee model will take care of this, but I don't know how just yet.

**Comment by jedmccaleb** [comment]
needs to be fixed with the fee structure
