### ISSUE TITLE
Create account and Send from that account in the same transaction

### ISSUE THREAD

**Issue by thejollyrogers** [stellar/stellar-core#469]
Had this discussion with @MonsieurNicolas today, basically the use case I want to enable is:

Transaction, root account is source account:
operation 1: root account pays and funds account b
operation 2: account b pays root account

Nicolas says that you can't create an account and send from the account in a later operation in the same transaction because "we can't verify the signature" because "with multi sig the master key can be disabled." I'm wondering if there's some work around to this to enable this use case. Some use cases:

* Some software creates accounts on behalf of someone else and wants to automatically add signers or set other options to the account. 
* An account wants to be created, funded, and create an offer automatically, for some automated trading software use case. 

Without this capability, the only alternative is to wait 1 ledger to close, which is nasty.

**Comment by MonsieurNicolas** [comment]
Remember that we do not attempt to verify the validity of transactions between each other inside a transaction set. We can only do basic validation of transactions individually.

If we were to allow to allow for operations without source account through at verification time, we're just increasing the number of scenarios where people get charged a fee when they submit bogus transactions.

Here are some that fail today at submit time that would end up being processed by the network only to fail and charge fees:
* payment done "on behalf of" by a payment processor ; processor would be charged a fee if the account doesn't exist 
* multi sig multi-party payment - the 3rd party ends up paying a fee

So yes, while implementation wise we're just doing it the way it is to keep the code simple (we don't have to special case the "no account" case); I think that the actual scenarios still point to not removing this check.
I'd rather have calls fail right away "for free" than charge people fees.

**Comment by jedmccaleb** [comment]
So we will check if account is in the DB and if not just use the public key to check sig.
