### ISSUE TITLE
standardize enums in XDR files

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#478]
so that we can automatically adjust the names for languages that define enum values in their own namespace.

For example:
```
enum MemoType
{
    MEMO_TYPE_NONE = 0,
    MEMO_TYPE_TEXT = 1,
	MEMO_TYPE_ID = 2,
    MEMO_TYPE_HASH = 3,
	MEMO_TYPE_RETURN =4
};
```

the problem I see with this, is that it makes some values quite redundant
```
enum OperationType
{
    PAYMENT = 0,
    CREATE_OFFER = 1,
    SET_OPTIONS = 2,
    CHANGE_TRUST = 3,
    ALLOW_TRUST = 4,
    ACCOUNT_MERGE = 5,
    INFLATION = 6
};
```
becomes
```
enum OperationType
{
    OPERATION_TYPE_PAYMENT = 0,
    OPERATION_TYPE_CREATE_OFFER = 1,
    OPERATION_TYPE_SET_OPTIONS = 2,
    OPERATION_TYPE_CHANGE_TRUST = 3,
    OPERATION_TYPE_ALLOW_TRUST = 4,
    OPERATION_TYPE_ACCOUNT_MERGE = 5,
    OPERATION_TYPE_INFLATION = 6
};

```

So maybe instead of always prefixing, we make it optional:
if we prefix the enum members by something, we make it the enum type, so that it can be programmatically removed.

**Comment by jedmccaleb** [comment]
Yeah scott said he could remove any prefix whether it matches the enum name or not.
