### ISSUE TITLE
publishing domain identity in the ledger

### ISSUE THREAD

**Issue by thejollyrogers** [stellar/stellar-core#479]
publishing domain identity in the ledger provides a secure way to associate a domain with a stellar account. once an account links their domain name, they can publish hashes of content their domain provides, such as a hash of their current stellar.txt file. this provides greater security than using tls alone, which is vulnerable to mitm attacks or a compromised server.

For example, let's say example.com domain has a stellar.txt file. Currently, anyone who wants to send a payment to user@example.com using federation must get the example.com/stellar.txt, which includes the federation endpoint. We use https to secure the connection, but if an attacker is able to compromise the server, they can change the federation endpoint in the stellar.txt file to point to a malicious endpoint. Additionally, root CAs have been known to be compromised and the server serving the stellar.txt file might not even be in the control of the example.com organization (for instance it might be cached in a CDN). This increases the chances of a man in the middle attack.

If example.com could link their domain name with their stellar address, they could sign the stellar.txt file with their stellar secret key, provide the signature (via a stellar.sig file for instance) along with the stellar.txt file, and anyone could verify that signature using their stellar public key. Alternatively, we could also add a "stellar.txt content hash" field in the Account entry instead of having a stellar.sig file in the organizations domain.

How do we verify the account owns the domain they want to link? To assure the stellar account linking a domain actually owns that domain, we can piggy back of the current CA system in use in browsers. there will need to be some defined set of root CAs and policy to keep these updated, which should be worked out via discussion. one possible solution would be to use a single browser vendor's CA list. also, once an account has linked their domain name, it should be accompanied with an expiration date, which can be the expiration date of the certificate used to verify the account or some stellar specific expiration date.

@MonsieurNicolas @stanford-scs

**Comment by jedmccaleb** [comment]
how is this different then what is in there now with the "homeDomain" ?

**Comment by thejollyrogers** [comment]
we would use existing ssl certificates to verify the domain an account publishes.

**Comment by jedmccaleb** [comment]
this can be done with data entry now
