### ISSUE TITLE
`bumpToBallot` should never to called once we commited

### ISSUE THREAD

**Issue by gmarceau** [stellar/stellar-core#480]
We need to turn [this line](https://github.com/gmarceau/stellar-core/blob/4365f7997b699c7bf70b9f06f5441335ffcc1ce1/src/scp/Slot.cpp#L235) back into an assert.

It's tripping somehow because of the out-of-order processing caused by the `mBallotValidationTimer`s.

**Comment by MonsieurNicolas** [comment]
this was resolved with the rewrite
