### ISSUE TITLE
Hold the proposed set event in edge cases where `externalize` / `triggerNext` are out of order.

### ISSUE THREAD

**Issue by gmarceau** [stellar/stellar-core#481]
@MonsieurNicolas says
> `mProposedSetTrackers` only contains txset for the ledger that just closed - which I think is incorrect - there are some edge cases where externalize could be called out of sync with triggernext. It's safer to just index on ledger sequence number (triggernext is only called once per ledger)

**Comment by MonsieurNicolas** [comment]
code does not exist anymore
