### ISSUE TITLE
homeDomain field should be 255 bytes

### ISSUE THREAD

**Issue by thejollyrogers** [stellar/stellar-core#486]
in accordance with dns rfc 1035 https://www.ietf.org/rfc/rfc1035.txt homedomain should allow up to 255 bytes.

**Comment by jedmccaleb** [comment]
you think we need to support 255 character domain names? I don't think so. is there a domain name you can think of that is over 30 characters?

**Comment by graydon** [comment]
They exist.
~~~~
$ whois 1-internet-casinos-online-gambling-online-casino-gambling-atlas.com

Whois Server Version 2.0

Domain names in the .com and .net domains can now be registered
with many different competing registrars. Go to http://www.internic.net
for detailed information.

   Domain Name: 1-INTERNET-CASINOS-ONLINE-GAMBLING-ONLINE-CASINO-GAMBLING-ATLAS.COM
   Registrar: TIERRANET INC. D/B/A DOMAINDISCOVER
   Sponsoring Registrar IANA ID: 86
   Whois Server: whois.domaindiscover.com
   Referral URL: http://www.domaindiscover.com
   Name Server: NS1.GAMBLINGATLAS.COM
   Name Server: NS2.GAMBLINGATLAS.COM
   Status: clientTransferProhibited http://www.icann.org/epp#clientTransferProhibited
   Updated Date: 13-may-2014
   Creation Date: 08-jun-2002
   Expiration Date: 08-jun-2015
~~~~

Standards are standards, I don't see why we'd randomly restrict this. It's a varchar anyways, right? Like people don't charge the ledger space they don't use here.

**Comment by graydon** [comment]
~~~
$ whois delhiarchitecturallysignificanthomes.in

Domain ID:D4389336-AFIN
Domain Name:DELHIARCHITECTURALLYSIGNIFICANTHOMES.IN
Created On:09-Aug-2010 19:53:16 UTC
Last Updated On:11-Jul-2014 00:19:52 UTC
Expiration Date:09-Aug-2015 19:53:16 UTC
Sponsoring Registrar:GoDaddy.com, LLC (R101-AFIN)
~~~
...

**Comment by jedmccaleb** [comment]
Yeah 1-INTERNET-CASINOS-ONLINE-GAMBLING-ONLINE-CASINO-GAMBLING-ATLAS.COM would be sol.  It is a varchar so in most cases allowing it to be longer has no downside but it is just more potential for abuse. And I don't think we would be cutting out anyone legitimate.

**Comment by thejollyrogers** [comment]
You're not considering the case that homedomain includes subdomains. This is perfectly legitimate usecase, for instance: gateway.visa.com. In this case, according to the rfc, we should allow up to 255 bytes. Additionally, the stellar.txt protocol makes no assumptions that DOMAIN is a simple domain with no subdomain. It would be perfectly valid to include subdomains and still be compliant with stellar.txt:
> Given the domain “DOMAIN”, the stellar.txt will be searched for in this order:
>
>https://stellar.DOMAIN/stellar.txt
>https://DOMAIN/stellar.txt
>https://www.DOMAIN/stellar.txt

**Comment by nyetwurk** [comment]
We have long domain names in our hyperledger networks... e.g. `ca-server-{index}.{organization}.{network-identifier}.{region}.blockdaemon.com`

That can easily be 30 characters or longer,
