### ISSUE TITLE
Add extension points in protocol for making it easier to upgrade

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#499]
Distinguish long lived structures (that live in history) vs ones where it's easier to deprecate things (wire protocol).

**Comment by MonsieurNicolas** [comment]
Let me know if you have any comments https://github.com/MonsieurNicolas/stellar-core/blob/versioning/docs/versioning.md

I also made the changes to the xdr files to illustrate https://github.com/MonsieurNicolas/stellar-core/commit/7720fceaf039b110eb02f2142032dc0aa19ca422

**Comment by jedmccaleb** [comment]
Why is maxProtocolVersion in the config? Shouldn't it just be hard coded in the software? Not like you can suddenly support a higher version just because you put it in the .cfg

**Comment by MonsieurNicolas** [comment]
I think it's needed when deploying a new protocol as it allows to decouple bits deployed vs the version of the protocol you really want to use.
You can imagine that a new version of the protocol has a bug but rolling back the bits is not possible (it would break history/catchup), so the only alternative is to stop the bleeding by bumping down the max version until a real fix can be applied.
Now that I think of it, maybe we need a list of banned versions to deal with this type of situation; in the example:
 1. minV = 10, maxV=11
 2. 11 has the critical bug -> set minV = maxV = 10
 3. new fixed version "12" comes up,  set minV = 10, maxV=12, bannedV={11}

**Comment by jedmccaleb** [comment]
So just banned and min in the config. max comes from the binary.  
If a peer connects outside your range you drop them. 
Any ballot for a ledger version outside of range won't be flooded.
