### ISSUE TITLE
txINTERNAL_ERROR during offerCreate

### ISSUE THREAD

**Issue by thejollyrogers** [stellar/stellar-core#504]
2015-05-18T00:47:40.907 29a443 [] [Ledger] ERROR Exception during tx->apply: Cannot execute query. ERROR:  value too long for type character varying(4)
 [LedgerManagerImpl.cpp:610]
2015-05-18T00:47:40.907 29a443 [] [Tx] ERROR invalid tx [LedgerManagerImpl.cpp:622]
2015-05-18T00:47:40.907 29a443 [] [Tx] ERROR Transaction: { tx = {
    sourceAccount = 1dd08b98505f691537926c5f09e9e851c63c91cf97feed0f04eba5d82e5095df,
    fee = 1000,
    seqNum = 13060995547138,
    timeBounds = NULL,
    memo = {
      type = MEMO_NONE
    },
    operations = [
      { sourceAccount = NULL,
        body = {
          type = CREATE_OFFER,
          createOfferOp = {
            takerGets = {
              type = CURRENCY_TYPE_ALPHANUM,
              alphaNum = {
                currencyCode = 55534400,
                issuer = e8cd7564985c8cd9e3334aa329e86ae953dda3d0adfca30f64b45ac881072b8d
              }
            },
            takerPays = {
              type = CURRENCY_TYPE_NATIVE
            },
            amount = 100,
            price = {
              n = 1,
              d = 1
            },
            offerID = 0
          }
        } }
    ]
  },
  signatures = [
    { hint = 1dd08b98,
      signature = e41ed0a004e4ff0a1ec41f93cf6dbadf9e67d5c2f82e7b5904c4772662085c83dd3fcde2cbacc0fa8313e6b0af71cae1c96560a876c9eecafbf6788738095a0e }
  ] }
 [LedgerManagerImpl.cpp:623]
2015-05-18T00:47:40.908 29a443 [] [Tx] ERROR Result: { feeCharged = 0,
  result = {
    code = txINTERNAL_ERROR
  } }
 [LedgerManagerImpl.cpp:625]

**Comment by MonsieurNicolas** [comment]
fixed
