### ISSUE TITLE
Deal with when LRU pushes out things that SCP still needs

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-core#509]

**Comment by gmarceau** [comment]
In the original ItemFetcher I wrote, this was handled by holding a pointer to the `Tracker` instance for as long as SCP may still need an item. 

I gather you did not like that solution and you have a different one in mind for this ticket. What did you not like about it, alternatively what do you like to see for the new version? 

As Nicholas mentioned, the new version bleeds scp responsibilities into overlay/, and bleed overlay responsibilities into PendingEnvelopes. It also reintroduces the duplication of the code that manages the lru cache. It also undoes the cache sharing between scp and overlay, which means the work that has gone into closing Issue #441 needs to be redone. I don't see how it is an improvement.

**Comment by jedmccaleb** [comment]
the SCP implementation has changed a lot since this issue @MonsieurNicolas is this actually still an issue?
