### ISSUE TITLE
Using a modern build tools like cmake

### ISSUE THREAD

**Issue by HongxuChen** [stellar/stellar-core#537]
Is there any plan to use a *modern* build tool to do the setup, such as CMake or SCons? Personally I prefer CMake since it might also benefit VS compilation.

**Comment by MonsieurNicolas** [comment]
Thanks for the feedback. We went back and forth on this one quite a bit.
We decided to use autotools as it's the most portable one.

We do not have any fancy build rules, so it's probably a wash.

I could see moving to one of these if compiling on Windows becomes a pain (historically, project files on Windows change with every version of Visual Studio) and the community has strong feelings about this.

**Comment by jedmccaleb** [comment]
Thanks closing for now
