### ISSUE TITLE
Automated full network testing

### ISSUE THREAD

**Issue by bekkibolthouse** [stellar/stellar-core#565]
Automated full network testing

Types of tests:
~~ - [ ] Fixed set of txs so we can ensure duplicate results with past implementations~~
^^not doing, stricken from scope

Results:
 - [ ] any core files created [in progress]
 - [x] collect sufficient metrics on each run.

**Comment by matschaffer** [comment]
@graydon I have https://github.com/stellar/puppet/issues/328 filed to capture cores & threaddumps from pipeline runs. Is this something that you actually have in progress?

It also occurred to me that we could pretty easily have atlas export all metrics as a json blob. That way we'd at least have all the raw data if we wanted to graph something after the fact.

**Comment by matschaffer** [comment]
Closing in favor of #643
