### ISSUE TITLE
TxSetFrame::trimInvalid and checkValid need to be refactored

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#582]
they share a lot of code

**Comment by evanlimanto** [comment]
I believe this issue can be closed now?

**Comment by MonsieurNicolas** [comment]
yes it can be. github will auto close issues if you use "resolves #N" instead of "Addresses #N" like you did in the PR. See https://help.github.com/articles/closing-issues-using-keywords/ for a list of keywords

**Comment by evanlimanto** [comment]
got it, thanks.
