### ISSUE TITLE
Make all acceptance tests pass

### ISSUE THREAD

**Issue by bekkibolthouse** [stellar/stellar-core#597]
Suite of acceptance tests are not all passing. Figure out what is going wrong, fix, so that all tests pass.

**Comment by graydon** [comment]
I am presently working on this.

**Comment by graydon** [comment]
(still going; this is extremely tedious)

**Comment by graydon** [comment]
As of stellar/stellar-core#688 (d27719b) all acceptance tests are passing. Sorry this took so long.
