### ISSUE TITLE
Benchmark current performance

### ISSUE THREAD

**Issue by bekkibolthouse** [stellar/stellar-core#598]
Run the performance tests on reference hardware and benchmark against previous runs. Establish baseline performance.

**Comment by graydon** [comment]
We're measuring network performance with the "autoload" mechanism. We run it in a 3-node testnet config as part of acceptance testing. It scales up randomly generated transaction load until a ledger is taking 250ms to close, which we consider "moderately loaded".

Most recent run (baseline) value for `ledger.transaction.apply` metric has `mean_rate` of 11.0261. I think that's as reasonable a value to use as any. We can improve this significantly; the machines are not especially busy during this load, they just have a little too much per-transaction latency.

Anyway for the sake of this bug I think we've got a baseline number to try to improve, I'm going to close it.
