### ISSUE TITLE
overlay: we connect multiple times to the same peer

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#606]
It looks like we allow connecting via different routes to the same peers.

I am not sure if this is a bad thing or not. Fixing it may require better trust in the connections. Right now we don't have any challenge so anybody can recycle peerIDs from the network.

{
         "id" : "gsdbsJKV6uNaLz7VPDRKzb8ZR5ao26L3eT1kioMu32Yg2mBtsgF",
         "ip" : "10.181.62.19",
         "olver" : 1,
         "port" : 39133,
         "ver" : "77fa464"
      },
      {
         "id" : "gsdbsJKV6uNaLz7VPDRKzb8ZR5ao26L3eT1kioMu32Yg2mBtsgF",
         "ip" : "54.227.13.198",
         "olver" : 1,
         "port" : 39133,
         "ver" : "77fa464"
      },
      {
         "id" : "gsQfnr7mWcFqpFddmp9J6cMxEqk8C3BwqQdmD42bmYPTcPLHmNR",
         "ip" : "54.161.230.185",
         "olver" : 1,
         "port" : 39133,
         "ver" : "77fa464"
      },
      {
         "id" : "gsQfnr7mWcFqpFddmp9J6cMxEqk8C3BwqQdmD42bmYPTcPLHmNR",
         "ip" : "10.155.19.184",
         "olver" : 1,
         "port" : 39133,
         "ver" : "77fa464"
      }

**Comment by MonsieurNicolas** [comment]
I can think of a couple reasons for this happening: multiple adapters bound (like above, private addresses are fine and should actually be preferred when routing between internal nodes) or some specific use of load balancers (inbound address is VIP from the LB, outbound is a DIP)

**Comment by MonsieurNicolas** [comment]
Note that the solution should also work when we have nodes with IPV4 and IPV6 addresses

**Comment by jedmccaleb** [comment]
Yeah it can naturally happen since one peer can have multiple IP:ports but we should drop peers when we realize we are already connected to them.
