### ISSUE TITLE
Link to original sources in lib/readme.md

### ISSUE THREAD

**Issue by stanford-scs** [stellar/stellar-core#628]
`lib/readme.md` says that the directory contains third-party code, but doesn't say exactly where the code comes from.  It should include links back to the home pages of all the projects from which stellar incorporates code, so that people can go there for documentation or to pull changes from the remote project.

**Comment by graydon** [comment]
This information is provided in COPYING, the paths of which need updating after your reorganization.

**Comment by MonsieurNicolas** [comment]
I think this was fixed by https://github.com/stellar/stellar-core/commit/43422d709511c855f64243d1f430ff4c7b3397b0
