### ISSUE TITLE
Command-line complete catchup

### ISSUE THREAD

**Issue by graydon** [stellar/stellar-core#643]
Two part bug:
- [x] Add a special startup mode that does catchup-complete immediately, without consulting network peers or trying to sync with them, just download and replay the specified history, saving current state to the db and exiting when complete.
- [ ] Using this, generate and archive a fixed, high-volume (10-million-account +) tx log so that we can do repeated load tests of replay and applying txs to large db.

**Comment by graydon** [comment]
See also #516

**Comment by MonsieurNicolas** [comment]
what we do now is parallel catchup of the entire public history as part of our validation suite - so extracting a subset is not needed
