### ISSUE TITLE
quorum safety checks and config safety features

### ISSUE THREAD

**Issue by graydon** [stellar/stellar-core#665]
- [x] change the config variable THRESHOLD to THRESHOLD_PERCENT, make it default to `67` (over 2/3 majority).
  - [x] add a new config variable FAILURE_SAFETY that defaults to `1`
  - [x] add a new boolean config flag UNSAFE_QUORUM that defaults to `false`
  - [x] on process startup, perform the following:
    - [x] throw if top-level THRESHOLD_PERCENT is less than 67% and user has not set UNSAFE_QUORUM
    - [x] throw if FAILURE_SAFETY is less than 1 and user has not set UNSAFE_QUORUM
    - [x] calculate quorum thresholds from THRESHOLD_PERCENTs and VALIDATORs (less accident-prone when adding/removing keys, less arithmetic for user to do)
    - [x] throw if there are less than `1+3*FAILURE_SAFETY` elements in top-level VALIDATOR set

**Comment by jedmccaleb** [comment]
yeah seems right.
can we make "UNSAFE_QUORUM"    "ALLOW_UNSAFE_QUORUM" though

**Comment by stanford-scs** [comment]
looks good to me.
