### ISSUE TITLE
Cache invalidation is wrong

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#690]
@graydon : from a cursory review of https://github.com/stellar/stellar-core/commit/c7210a38cf7c66be29d37b188970e2ed6d213902

entries are cached when calling "loadAccount" and invalidated when somebody calls delete or update.

The problem is that a sequence such as (which itself can be inside other transactions):
 1. begin tx
 2. loadAccount
 3. updateAccount
 4. loadAccount
 5. rollback tx

will cause the cache to contain information from the rolledback transaction.

Maybe I am not reading the code right, but I think it's possible. I figured I'd open an issue in case I am right :)

**Comment by graydon** [comment]
Quite correct. Thinking about it more there's also ... something I need to look into wrt. isolation level SERIALIZABLE and the degree of freedom postgres has in reordering transactions on the same session. I'll take this and have at least a simple / pessimistic fix by EOD, hopefully something better.

Nice catch, thanks. I knew it wasn't going to be so easy, but my brain wasn't quite working right.
