### ISSUE TITLE
offers amount as integer ? price in double ?

### ISSUE THREAD

**Issue by FredericHeem** [stellar/stellar-core#715]
Is it intended that the type of the *amount* in the *offer* table is an *integer* ?
When a offer is created with the amount 1.1, it is stored and truncated to 1. 
Also, it is wildly known that  the use of the *double* type for financial data has to be avoided, it is used at the moment to display the order book.
Any thoughts on that subject would be greatly appreciated.

**Comment by MonsieurNicolas** [comment]
amounts in stellar core are 64 bit integers representing sub-units of whatever is being traded. For example, an amount for XLM is stored in stroops (where 1 stroop is 1/1000000th of an XLM).
It's up to the client to do the right arithmetic: clients should do fixed point math and not use floating point types (other than for input/output).

**Comment by FredericHeem** [comment]
How do clients know about the decimal place of a given user defined asset ?

**Comment by FredericHeem** [comment]
Why not adding a new type of operation to create a new asset with some parameters such as the asset code, the asset name, an url describing the asset, the decimal place for the orderbook, the decimal place to display on the user interface, etc ...
A new table called *asset* would be added to the db and accessible though horizon.
What your thoughts about this idea ?

**Comment by MonsieurNicolas** [comment]
The decimal point is always in the same place for all assets from the core's point of view, @jedmccaleb convinced us that it's simpler to handle, read on. The asset description should be on the issuer's web site and should explain what it is and in which denomination. We didn't think we needed to include this in the protocol and let app writers/issuers define a model that they see fit for communicating what they trade.
