### ISSUE TITLE
sqlite wal file takes too much space

### ISSUE THREAD

**Issue by codeck** [stellar/stellar-core#717]
the .db-wal file grows too much while replaying in "Catchup" state.
my measurement, .db-wal file cost 10KB+/ledger meanwhile .db file cost about 1KB/ledger.
so in current testnet (about 400k ledgers), a fresh node will need 4GB+ for WAL for a complete catchup.
It's not clear whether the WAL file size is bounded.

similar issues in other project:
https://github.com/couchbaselabs/TouchDB-iOS/issues/189
https://wiki.mozilla.org/Performance/Avoid_SQLite_In_Your_Next_Firefox_Feature#Storage_Footprint

my config file:
```
PEER_PORT= 39133
RUN_STANDALONE=false
LOG_FILE_PATH="log/stellar-core.log"
HTTP_PORT=39132
PUBLIC_HTTP_PORT=false
CATCHUP_COMPLETE=true
UNSAFE_QUORUM=true
FAILURE_SAFETY=0
TARGET_PEER_CONNECTIONS=20
MAX_PEER_CONNECTIONS=30
PREFERRED_PEERS=[
  "core-testnet1.stellar.org",
  "core-testnet2.stellar.org",
  "core-testnet3.stellar.org"
]
KNOWN_PEERS=[]
DATABASE="sqlite3:///stellar.db"
[QUORUM_SET]
VALIDATORS=[
"GDKXE2OZMJIPOSLNA6N6F2BVCI3O777I2OOC4BV7VOYUEHYX7RTRYA7Y",
"GCUCJTIYXSOXKBSNFGNFWW5MUQ54HKRPGJUTQFJ5RQXZXNOLNXYDHRAP",
"GC2V2EFSXN6SQTWVYA5EPJPBWWIMSD2XQNKUOHGEKB535AQE2I6IXV2Z"]

[HISTORY.local]
get="cp history/{0} {1}"
put="cp {0} history/{1}"
mkdir="mkdir -p history/{0}"
[HISTORY.core_testnet1]
get="curl -sf https://s3-eu-west-1.amazonaws.com/history.stellar.org/prd/core-testnet/core-testnet-001/{0} -o {1}"
[HISTORY.core_testnet2]
get="curl -sf https://s3-eu-west-1.amazonaws.com/history.stellar.org/prd/core-testnet/core-testnet-002/{0} -o {1}"
[HISTORY.core_testnet3]
get="curl -sf https://s3-eu-west-1.amazonaws.com/history.stellar.org/prd/core-testnet/core-testnet-003/{0} -o {1}"
```

**Comment by codeck** [comment]
a simple workaround is just restart stellar-core when WAL file is too large since WAL file will shrink when database connection get closed.

**Comment by MonsieurNicolas** [comment]
Thanks for the detailed report. I am not too worried about the way the WAL file grows, it works as designed by the sqlite devs; I am pretty sure other databases have similar internal limitations. We do need to fix this though as it taxes disks way too much (and is unbounded with time).

I think that the primary issue is that we're running the full history import as one transaction. Instead we should do batches. This is similar to https://github.com/stellar/stellar-core/issues/432

**Comment by MonsieurNicolas** [comment]
I opened https://github.com/stellar/stellar-core/issues/718 to track the secondary issue of using 10 kB/ledger

**Comment by codeck** [comment]
donovan suggest 
```sql
PRAGMA journal_size_limit=0;
```
after open the sqlite db or just change macro
```c
#define SQLITE_DEFAULT_JOURNAL_SIZE_LIMIT -1" 
```
in https://github.com/stellar/stellar-core/blob/master/lib/sqlite/sqlite3.c

**Comment by MonsieurNicolas** [comment]
This will probably hide the issue: we should not be doing large transactions in the first place. Or I am missing something on how WAL works?

-----Original Message-----

**Comment by donovanhide** [comment]
I'm seeing this issue where the WAL file shows unbounded growth:
```
# ls -lh stellar.db*
-rw-r--r-- 1 root root  17M Oct  1 16:34 stellar.db
-rw-r--r-- 1 root root  18M Oct 11 13:04 stellar.db-shm
-rw-r--r-- 1 root root 2.3G Oct 11 13:04 stellar.db-wal
```
Looking at the file descriptors, seems like connection pooling is being used. Not sure if that is related.

```
# lsof stellar.db*
COMMAND    PID USER   FD   TYPE DEVICE   SIZE/OFF  NODE NAME
stellar-c 6137 root  mem-r  REG  253,1   18120704 49775 stellar.db-shm
stellar-c 6137 root   10ur  REG  253,1   17030144 49760 stellar.db
stellar-c 6137 root   11u   REG  253,1 2370212376 49774 stellar.db-wal
stellar-c 6137 root   12ur  REG  253,1   18120704 49775 stellar.db-shm
stellar-c 6137 root   24ur  REG  253,1   17030144 49760 stellar.db
stellar-c 6137 root   25ur  REG  253,1   17030144 49760 stellar.db
stellar-c 6137 root   29u   REG  253,1 2370212376 49774 stellar.db-wal
```
How do I enable logging of issued SQL commands to look at the actual transactions?

**Comment by MonsieurNicolas** [comment]
From what I saw locally: after applying 400 000 entries during catch up, the WAL file grew to close to 1 GB (and the main db file was untouched) even after catch up completed. When the app exited, the WAL file got deleted and the db file got updated to less than 80MB. This seems to indicate that something is interfering with the WAL file truncation.

As far as SQL logging, SOCI doesn't seem to have any way to trace SQL statements but for 99% of the use case for this, we can just enable logging in postgresql (look for `log_statement = 'all'`).
I understand that for debugging this particular issue, this is not that useful but it's such a corner case that I suspect we'll just add a bunch of temporary instrumentation while debugging this.

**Comment by MonsieurNicolas** [comment]
@donovanhide from looking at the link you provided, the only expected case of a WAL file growing given what we're doing seems to be a case of "checkpoint starvation" - but I don't see where we're starting long lived read transactions, so this is indeed quite puzzling. The only place where we're creating a separate session is in `StateSnapshot::writeHistoryBlocks()`

**Comment by graydon** [comment]
Yeah, something funny is going on with the connection pooling / WAL starvation I think. It might have to do with the way we hold persistent statement handles in the DB. I've seen SQLite consider those as a kind of resource-in-use before, they might count as a read transaction for the sake of WAL starvation. I'll keep digging.

At least part of the problem is we're not doing bucket-apply inside a transaction _at all_, so each entry gets its own implicit sqlite begin/end. When I batch them into larger txs (say 4096 or 65536 entries per tx) it goes about 5x faster and the WAL uses 20x less disk space. Goodness knows why; this hardly fits with the SQLite docs. I'll continue trying to get this straightened out. Sorry.

**Comment by graydon** [comment]
Update: changing the journal_size_limit pragma doesn't do anything. This is consistent with WAL starvation: it's never managing to checkpoint the WAL anyways. Flushing the prepared statement handles fixes it, though.

Fix incoming.

**Comment by donovanhide** [comment]
Sorry, these emails got mis-filtered in gmail... 

A bit of random googling turned up this link:

http://stackoverflow.com/questions/12416988/sqlite-db-with-wal-locked-when-preparing-a-select-statmement-why

Which suggests the possible use of `reset_if_needed()` instead of flushing the prepared statement cache, which might be a bit more wasteful:

https://github.com/stellar/stellar-core/blob/8d76947a20b66cf5744df9de46a68ad3abf758af/lib/soci/src/backends/sqlite3/statement.cpp#L76-L86

**Comment by MonsieurNicolas** [comment]
you are probably right - the problem is that `reset_if_needed` doesn't seem to be accessible outside of the sqlite backend in soci.
That said, I imagine that the overhead of preparing statements once per ledger close is probably fine. We'll find out as we look into bottlenecks

**Comment by donovanhide** [comment]
Looks like it never get exposed at the statement level...

This patch seems to explain the situation:
https://github.com/mloskot/soci/commit/543c7dbb6483660a5050b22e35666be8560fc386
