### ISSUE TITLE
proposal: meta data change tracking

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#719]
This would resolve https://github.com/stellar/stellar-core/issues/711 https://github.com/stellar/stellar-core/issues/712

Right now it's difficult in some cases for dependent services (like Horizon) that try to do more in depth analysis of changes to properly reconstruct what a given transaction really did for some operations.

For example, the "SetOptionsOp" operation may change arbitrary fields in the AccountEntry and while the operation has enough information to see for example which "Signer" were updated, the only way to know if the update is an update or an add is to compare signers to the previous version (before the operation) of the AccountEntry.

The problem is that "previous version" is hard to reconstruct if not running from genesis.

A naive implementation would be to include the previous version of a ledger entry in the meta data for each operation which is quite wasteful as for a given chain of transactions tx1...txn that modifies a ledger entry each tx_i result is the tx_i+1 previous version.

Instead, core can be changed to emit a new "LEDGER_ENTRY_STATE" meta before a ledger entry is modified (or deleted), that contains the state of the unmodified ledger entries if the ledger entry existed from a bucket imported from history. This way a consumer just needs to replay what is in "txhistory" in order to gain full knowledge of state transitions in the ledger.

In order to know if the extra information needs to be emitted, core just needs to keep track of which entries where present in the ledger after applying buckets. One way to do this would be to just add a flag for each ledger entries in the database (but not persisted anywhere else), but instead we can leverage https://github.com/stellar/stellar-core/issues/713 that has roughly the same DB cost while making it possible to walk history for a given ledger entry (and only load data where the entry was modified).

Work required for this change:
 * modify the code to backup objects about to be modified/deleted inside LedgerDelta, properly handling nested LedgerDelta changes (in case of rollback of inner change)
 * emit "LEDGER_ENTRY_STATE" when generating meta data with the old value of the entries before the standard CREATED/UPDATED/REMOVED that modifies them
 * add a "last modified" ledger sequence number to ledger entries
 * add an "imported ledger sequence" set after applying buckets to tell the system which ledger entries would trigger the "no op" tx (if an entry has a ledger seq smaller than the import one, the no op tx meta will be emitted)

**Comment by codeck** [comment]
from my experience of years of protocol analyzing, indexes for analyzing is very variable so that architect should separate dependency of them out of core protocol as much as possible. 

separation between history and ledger is one of attracting designs of stellar-core than rippled. this proposal is a backward step.

if horizon want provide more, it should do more like a processor instead a thin-tier delegate.

conclusion: buckets should keep only essential indexes/snapshots for rapid ledger processing. nothing more.

**Comment by MonsieurNicolas** [comment]
Totally agree. Maybe a clarification in case this was not clear: The only protocol change here is the addition of the version to the ledger entries, the meta stuff is not part of the protocol (unlike the tx result) and is just a way for the implementation of stellar core to talk to other parts of the system (in the same way the fact that we use SQL is not part of the protocol). We could be using json or whatever there, we use xdr just for convenience.

Nicolas

-----Original Message-----
