### ISSUE TITLE
Do we need to make DESIRED_BASE_RESERVE a config?

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#744]
right now it's hard-coded in the code.

Adding it for purpose other than generating a new genesis ledger also requires implementing https://github.com/stellar/stellar-core/issues/613

**Comment by jedmccaleb** [comment]
I think the idea is that we would do it sometime later after the network is live.

**Comment by MonsieurNicolas** [comment]
this was done in #1407
