### ISSUE TITLE
VC++ warning in xdrpp

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#748]
The line
`t = detail::to_int8<T>(autocheck::generator<int>{}(0x10000));`

causes the following warning
`lib\xdrpp\xdrpp/autocheck.h(77): warning C4244: 'argument': conversion from 'int' to 'uint8_t', possible loss of data (compiling source file ..\..\src\ledger\LedgerTests.cpp)`

The code that implements `detail::to_int8` doesn't seem to actually do what it's supposed to do as it's taking an 8 bit parameter.

**Comment by MonsieurNicolas** [comment]
To silence all that, I did
```
-    t = detail::to_int8<T>(autocheck::generator<int>{}(0x10000));
+    t = detail::to_int8<T>(autocheck::generator<int>{}(0x10000) & 0xFF);
```
but I am not sure it's correct wrt standard.

**Comment by graydon** [comment]
Consult with @stanford-scs on this, he's been over it a zillion times.

**Comment by stanford-scs** [comment]
Hmm... the code was already correct.  Since we are already sacrificing performance to shut up the compiler, I guess we might as well silence the warning.  But the & makes (admittedly plausible) assumptions that aren't guaranteed by the language spec.  Better would be a `static_cast<uint8_t>(autocheck::generator<int>{}(...))`.  Can you check if an explicit cast shuts up the compiler?

**Comment by stanford-scs** [comment]
Okay, please try

    git fetch git@github.com:/xdrpp/xdrpp msvc_placating_cast

**Comment by MonsieurNicolas** [comment]
I think the problem with the straight cast is that the behavior is not defined (and VC++ will crash debug builds because of that for any value outside of -128..127) and the generator generates data well outside those bounds.

I think the correct way is something like int32 -> uint32 -> mask to 0..255 -> cast to uint8 --> use "to_int8" to remap to int8 or uint8
Alternatively, change the generator to generate an int within the -128..127 range to avoid having to mask.

**Comment by MonsieurNicolas** [comment]
this is not the case in the current version of xdrpp
