### ISSUE TITLE
droped to "state" : "Joining SCP" after ISP changes my ip address

### ISSUE THREAD

**Issue by sacarlson** [stellar/stellar-core#749]
looks like this new stellar-core version has the same problem with "state" : "Joining SCP" after my ip address changes.
I guess stellar-core is meant for only static address users?
as far as I know this is consistent as my IP address changes every 24 hours and I have to restart every day.
In this last failure it was working fine with my ip at 124.122.43.53:11625 but now my ip is 124.122.224.61 so it's dropped me to Joining SCP that will never self correct (ran over 10 hours without fixing itself before) .  I can normally just restart the stellar-core to get it going again but the other day that also didn't work unless I wait 10 hours or so and restart then it works again (not sure related).  So the work around  for me would be to setup a script to check state and restart stellar-core  when needed or just depend on horizon as the point to transact. 

I'm running commit: 62b505004ef8c9db4cdfc7d9fc42ac1ea34b98a1
stellar-core log: https://drive.google.com/open?id=0B4pSHwxHXW9SV3hYUUtFRDJXUUU

**Comment by MonsieurNicolas** [comment]
I am not sure what the code does when IPs change, it should just work.
A "hot swap" of IP addresses can confuse the OS you are running too.
I think Graydon was going to take a look at the overall overlay.

**Comment by sacarlson** [comment]
it seems I can repeat this problem or a problem like it  by forcing my IP address to change by using my VPN service to move from my local thailand IP address to an IP address in Hong Kong, that seems to now make it get stuck in catchup mode.  this is with running testnet on the present stellar-core build 59a2dea...  again the work around of a soft reset fixes it.

**Comment by MonsieurNicolas** [comment]
To clarify your setup, is the configuration
 1. **your machine running stellar-core (WAN)** ---> ISP ----> internet
or
 2. **your machine running stellar-core (LAN)** ---> router (WAN) ---> ISP ---> internet

When you say that the ISP changes your address, does it invalidate the IP of the machine running stellar-core (1) or the one of some router in between (2) ?

I imagine that it's (1) but wanted to confirm.
Maybe we're not binding to the interfaces properly? Can you run the command
`netstat -panee` before and after an IP change and give the output that you get for stellar-core and Skype? (there might be multiple entries). Feel free to mask out portions of IP addresses (as long as we can tell which one is which between before/after).

**Comment by sacarlson** [comment]
no it's your number 2 with lan > router>wan > isp > internet.  a standard home system I would think for most. I'll attach a netstat -panee and also attached route -n so you get the full picture. https://drive.google.com/file/d/0B4pSHwxHXW9SZldWS1hFV3VIQzg/view?usp=sharing

**Comment by sacarlson** [comment]
I noted another event today that was different, were my vpn was active when I had stellar-core connected. at that time my ISP changed my wan dynamic  IP address that makes my openvpn go into failure and disconects from wan and not to recover without manual intervention.  but when I disconected openvpn to recover my wan connection,  stellar-core recovered without reset.  so maybe time is also  involved as my vpn had failed for maybe 5 minutes before I corrected it.  so this just shows that stellar-core can change ip address without total failure in some cases.  I don't know if this was just luck as it only happend one time that I have seen so far.

**Comment by MonsieurNicolas** [comment]
closing: there was a bug fixed a long time ago that was causing certain things to be cached the wrong way, maybe this resolved that issue? We've never heard of such problems for a while now.
Let's reopen this if anybody runs into this again
