### ISSUE TITLE
Change of price in manageOffer tx is ignored

### ISSUE THREAD

**Issue by buhrmi** [stellar/stellar-core#750]
Easily to repro on testnet.

It's not possible to change the price of an offer via manageOffer tx.

For example, check out this transaction ID: f244e51612d573e5802f3034a81219e5aa7fa94672ce692d55d3f161346bb29c
The price should have been changed to "2" but it remained at "5". Also, for some reason, the Amount is being set to "0.0000024" even tho I'm selling a self-issued asset, so there should be no top limit on how much i can sell...

Selling: Self-Issued Asset
Buying: Foreign Asset

**Comment by MonsieurNicolas** [comment]
Thanks.
Indeed the code is very wrong. Of course we don't have a test for changing the price either. Glad we're finding this now.
