### ISSUE TITLE
Removing signers does not work

### ISSUE THREAD

**Issue by nullstyle** [stellar/stellar-core#755]
See:  https://github.com/stellar/ruby-stellar-base/issues/16

In addition, you can see a stellar-core database dump that illustrates this bug here: https://github.com/stellar/horizon-importer/blob/master/spec/fixtures/scenarios/set_options-core.sql

The last transaction in txhistory, which does successfully complete, removes the signer `GC23QF2HUE52AMXUFUH3AYJAXXGXXV2VHXYYR6EYXETPKDXZSAW67XO4`, but as you can see from the `signers` table, it persists.

**Comment by MonsieurNicolas** [comment]
funny that I rewrote this code yesterday as I could not make sense of it. I was going to add new tests, so this should be fixed shortly

**Comment by MonsieurNicolas** [comment]
Turns out it's removing the last signer that was broken - the issue I found earlier is https://github.com/stellar/stellar-core/issues/761
