### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [stellar/stellar-core#769]
Would you like to add the configuration script "[AX_PTHREAD](http://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads?")" to [your build specification](https://github.com/stellar/stellar-core/blob/0761d0729f8b9d4974ee58ab98decac66884ad6b/configure.ac#L45 "Configuration checks")?

**Comment by MonsieurNicolas** [comment]
Yes please do. Submit a PR: I didn't know autoconf could take care of it.

-----Original Message-----

**Comment by elfring** [comment]
Would you like to pass any extra commands to the parameters "ACTION-IF-FOUND" and "ACTION-IF-NOT-FOUND" of the macro "AX_PTHREAD"?

**Comment by graydon** [comment]
Hm, I'm not sure about this; we use C++11 threads but that should be subsumed under the testing we do for C++11 in general.

**Comment by MonsieurNicolas** [comment]
Reading about this, yes we're using std::thread with C++ 11; so this option is probably not relevant. I am closing the issue.
