### ISSUE TITLE
Quick restart

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-core#790]
some type of restart that:

-waits till immediately after ledger close
-sets forcescp
-shutsdown the application
-starts back up

**Comment by graydon** [comment]
Why not just exit and restart? How often will one change this?

**Comment by jedmccaleb** [comment]
Actually we might not want to wait for a ledger to close before doing the quick restart. You could be in a situation where the network is stalled because too many nodes have failed. You will need to restart inorder to remove some of the failed guys from your quorum so you can't wait for a close to do that.

**Comment by MonsieurNicolas** [comment]
You may want to check with dm but I'm pretty sure you cannot restart in an SCP round without changing validator key (or we'd have to have a reliable way to recover all messages ever produced by a node which I think is not possible). With the same keys, the only safe thing to do is wait for the round to close.

**Comment by MonsieurNicolas** [comment]
I think that the way I'd like to implement this is by simply adding a command `waitforledger` that by default just waits for the next ledger to close (with a default timeout of let's say 20 seconds), that way an upgrade script would just do something like
 1. stellar-cmd waitforledger
 2. restart stellar-core

In the general case, there is no need to do force-scp as the validator will just miss one ledger close which is probably acceptable from the network point of view; The alternative is to run an extra `force-scp` between the stop and start, but I am not sure it's worth it.

**Comment by jedmccaleb** [comment]
we realized we can just always start with the node thinking it is in sync and it will fix this issue.
