### ISSUE TITLE
postgresql backend should be explicitly enabled or disabled

### ISSUE THREAD

**Issue by graydon** [stellar/stellar-core#80]
Currently configure enables or disables the postgresql backend based on sniffing for libpq. This is too subtle and confuses users both ways: when they want it sometimes they don't get it, when they don't want it sometimes they get it and then tests fail when it tries to connect to a local postgres. Make it explicit.

**Comment by raymens** [comment]
isn't this already in the configure using `./configure --disable-postgres`? (saw usage of it on Slack)

**Comment by graydon** [comment]
This exists already in configure. Closing.
