### ISSUE TITLE
 A guide for reading from history

### ISSUE THREAD

**Issue by nullstyle** [stellar/stellar-core#812]
It'd be great if we had an introductory article that introduced developers to how they can interact with a history archive.  This document would serve as a primer for anyone interested in writing software that inspects a history archive (rather than writing to it).  It should contain advice that could guide someone to code up applications that leverage the history stores such as:

- Producing a ledger snapshot as of a certain ledger sequence
- Producing a list of changes between one point in time and another
- Producing a history of changes for a single ledger entry (e.g. show me all the different states a given account has occupied)- Others?

## Things to cover

- Archive directory structure and file archetypes (e.g. this directory has JSON files that contain XYZ)
- General recommendations for reading from history
- For any XDR files, include file layout information and what top-level struct is used.
- Using HTTP to access public history archives?

Ideally, after reading this document, a reader who is running a local history archive (i.e. they have a local stellar-core that is publishing history to a local directory) could write a simple script using one of the client libraries to decode a portion of the history archive or iterate through the list of ledger headers.

**Comment by jedmccaleb** [comment]
Does it make sense to expand this to include those things: https://github.com/stellar/stellar-core/blob/master/docs/history.md

**Comment by nullstyle** [comment]
That was where I initially went to see if I could figure things out myself, so it makes sense to me.
