### ISSUE TITLE
errors in the config file need to be more explicit

### ISSUE THREAD

**Issue by graydon** [stellar/stellar-core#82]
When something goes wrong in a config file error, just dumping out a std::runtime_error is not really good enough. Should at minimum write out which config item was being processed, ideally more context than that too if any is available.

**Comment by matschaffer** [comment]
Guessing this is related so will mention here that CRLF terminated config files cause some "interesting" error messages:

```
❯ ./bin/stellar-core --conf ~/Downloads/stellar-config_cfg.txt
---did you forget a '#'? at line 1 [main.cpp:350]TAL Failed to parse '/Users/mat/Downloads/stellar-config_cfg.txt' :Unidentified trailing character
```

**Comment by MonsieurNicolas** [comment]
I think this was fixed a while back, the current output seems easy enough to understand and diagnose
```
./stellar-core --conf badconfig.cfg
[default FATAL] Got an exception: invalid LOG_FILE_PATH [main.cpp:648]
```

**Comment by matschaffer** [comment]
:heart:
