### ISSUE TITLE
Display mapping between hashes and quorum sets in /scp endpoint (and dump)

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#829]
Without quorum sets, it's quite complicated to analyze potential problems.

**Comment by jedmccaleb** [comment]
I was thinking we would allow people to give the nodes in their quorums common names in the .cfg. These common names could then be displayed in the logs. This will make telling what is going on way easier.

**Comment by MonsieurNicolas** [comment]
reopened - this was not fixed: right now /scp doesn't give any information on quorum sets
