### ISSUE TITLE
stellar-core executable is not updated when dependent library archive changes for default make target

### ISSUE THREAD

**Issue by HongxuChen** [stellar/stellar-core#832]
For example, when I modified some piece of code inside `lib/soci`, simply running `make` will generate a new `lib/libsoci.a`, but `stellar-core` is not updated accordingly.  
The autoreconf is `autoreconf (GNU Autoconf) 2.69`. And I was using a out-of-source build.

Practically it won't cause many problems since library code is not supposed to be changed.

**Comment by vogel** [comment]
Fixed in #1115
