### ISSUE TITLE
Stuck after full stellar-core reset with Applying buckets for level 7 at ledger 52031

### ISSUE THREAD

**Issue by sacarlson** [stellar/stellar-core#839]
I had my normal problem with failure after my IP changed so I just did a normaly soft reset that normaly fixes it but this time failed. so I attempted full database reset 3 times with each time it just gets stuck at the log line Applying buckets for level 7 at ledger 52031.   I'm now running stellar-core commit 28bcca5b669e17fe59f1fea9b596cd5ff399a4e6.  the reset of the startup scripts config files and log files can be seen at https://drive.google.com/folderview?id=0B4pSHwxHXW9Sejczc3RTX3dxUnM&usp=sharing

maybe not related but the first failure before full reset the stellar-core locked up my computer using 99.9% cpu and 88% or more of my 8gb mem,  this also happened two times with soft resets before I attempted full database reset.  I didn't collect any logs on that failure sorry.

**Comment by graydon** [comment]
I can reproduce this to some extent ... it doesn't actually get _stuck_ at that bucket, it just takes quite a while. That's because level 7 curr bucket has over 200,000 entries in it and it applies them synchronously. It should probably give more feedback on that, but on my machine here it does eventually complete that bucket-apply and catch up. What happens if you give it ... a while?

**Comment by graydon** [comment]
(In other words, I _think_ this is a manifestation of #432, possibly triggered by recent load-testing on the testnet?)

**Comment by MonsieurNicolas** [comment]
Also, @sacarlson when you say "88% or more of my 8gb mem" was that memory directly used by the process or overall OS memory (which includes things like disk caches)?

**Comment by sacarlson** [comment]
![screenshot-terminal-1](https://cloud.githubusercontent.com/assets/734826/10418252/1e0a6a7c-7080-11e5-99a6-5ad30ae70f4a.png)  this is what I saw at one failure this is not at it's worst as when it used up all mem and cpu I had no more control the the computer

**Comment by graydon** [comment]
Woah, it should _definitely_ never be using 4gb of memory. Something's off there. I'll dig in further, thanks.

**Comment by sacarlson** [comment]
I think this was in the shutdown phase and I'm using sqlite that might be part of it?  when I ctl-c to exit it seems it was stuck there also.  even kill seems to fails unless I do a killall -9 stellar-core. even after it stops running it leaves something in ps -A what's it called orphaned process?

**Comment by graydon** [comment]
I believe the change in PR #850 will fix this: it both greatly speeds up normal bucket-apply and makes the WAL file autocheckpoint as it's supposed to. This means the WAL file should remain 1.5mb or so and the  DB should grow incrementally while it's having buckets applied to it. Let me know if you're still seeing the problem with that change!

**Comment by graydon** [comment]
@sacarlson Is this fixed to your satisfaction?

**Comment by MonsieurNicolas** [comment]
@sacarlson : reopen issue if it still happens

**Comment by sacarlson** [comment]
yes this changes seems to have fix this for me thanks and good work.  not sure it's related but I also note that my ISP forced  ip changes no longer lock me out of the stellar network and can manually change IP address with vpn and still reconect without reset.

**Comment by MonsieurNicolas** [comment]
Good to hear it could be that the overlay changes I made help with recovering from an out of sync situation.

-----Original Message-----
