### ISSUE TITLE
when ll is set to fatal or none error messages still are shown

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-core#842]

**Comment by MonsieurNicolas** [comment]
Do we care? I mean why would anybody want to run a node and not know if it's working right?

**Comment by jedmccaleb** [comment]
Yeah it matters when you are trying to debug a certain thing but some other unrelated thing is spewing ERROR messages. for example, the bug where we reconnect over and over to ourselves causes an error message but I was trying to track something else and this made it more difficult.

**Comment by jedmccaleb** [comment]
Actually I think this is a case sensitivity issue. If you ll?level=fatal&partition=herder  it won't quite "Herder" but ll?level=fatal&partition=Herder will.  That should be fixed though.

**Comment by graydon** [comment]
This was fixed in #878
