### ISSUE TITLE
New install, Mac El Capitan, fatal error: 'libpq-fe.h' file not found

### ISSUE THREAD

**Issue by ChristopherA** [stellar/stellar-core#864]
When I follow instructions at https://github.com/stellar/stellar-core/blob/master/INSTALL.md the first command that fails is "make .". Subsequent make commands result in fatal error: 'libpq-fe.h' file not found

**Comment by jedmccaleb** [comment]
can you try `./configure --disable-postgres` and then `make`

**Comment by olivier-w** [comment]
@jedmccaleb Thanks worked for me!
