### ISSUE TITLE
forcescp does not work

### ISSUE THREAD

**Issue by codeck** [stellar/stellar-core#868]
the latest master, f105538e, run `stellar-core --forcescp` has no effect on table 'storestate'.
I think the bug is triggered by 2c30cd30 which made prepared statement of forcescp is not fresh but cached one. but the root cause was introduced by https://github.com/stellar/stellar-core/blob/f105538e/src/database/Database.h#L41-L62 .  clear_up(false) won't reset backend so consequential get_affected_rows() may return a cached value.

**Comment by MonsieurNicolas** [comment]
Yes you are correct on the cause. I ran into this yesterday too. I found a bug in upstream SOCI that I will get in shortly

**Comment by codeck** [comment]
i am not able to patch it keeping both performance and correctness. so waiting for your patch. upstream patch to make clear_up(false) works as expected is the best.
