### ISSUE TITLE
running tests uses a lot of RAM

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#886]
there seems to be some bug that causes huge RAM usage when simply running tests

On Linux, I saw memory usage spike up to 10GB of virtual memory

**Comment by MonsieurNicolas** [comment]
Turns out that it's because we create threads using the number coming out of
`std::thread::hardware_concurrency()`.

I am not sure how many worker threads we really need, but I suspect that it's way less than what we're currently using.

we should probably take the max of std::thread::hardware_concurrency() and something like number of levels ?

**Comment by graydon** [comment]
This will consume a lot of virtual space, but not a lot of resident. I don't think the former is a problem, but if the latter happens it'd be worth tracking. Generally, programs with dozens or even hundreds of threads are not a resource-consumption problem on linux.
