### ISSUE TITLE
Unparseable validators self identifier stellar-config.cfg

### ISSUE THREAD

**Issue by raymens** [stellar/stellar-core#887]
Stellar-core has trouble parsing `VALIDATORS=["$self"]` in the file https://github.com/stellar/stellar-core/blob/master/docs/stellar-core_standalone.cfg .

```
<startup> [default FATAL] Got an exception: unknown key in config [main.cpp:443]
```

**Comment by MonsieurNicolas** [comment]
which version are you trying this on? (head commit is fine)

**Comment by ptarasov** [comment]
Version: v0.2.2-33-ga16dddc. 
This issue happens not only with self identifier but for all from set of "NODE_NAMES"

**Comment by jedmccaleb** [comment]
ptarasov: can you paste your NODE_NAMES  and VALIDATORS=?

**Comment by ptarasov** [comment]
In fact they are the same as in example config for the validators. These ones(https://github.com/stellar/docs/blob/master/other/stellar-core-validator-example.cfg)

**Comment by raymens** [comment]
I'm on v0.2.3-2-gae1aa82 on Xubuntu. It does seem to work on Windows though (also head). I've had another weird thing happen on my Xubuntu VM that got fixed by itself, so it might just be me doing something wrong in Linux in my case...

**Comment by MonsieurNicolas** [comment]
found the issue: cpptoml doesn't iterate in config order but in some hash order. I'll get a fix out in the next version.

To work around this, don't use the aliased names
