### ISSUE TITLE
Erroneous `tx_BAD_SEQ` errors returned for valid transactions when submitted to non-validating node

### ISSUE THREAD

**Issue by nullstyle** [stellar/stellar-core#890]
Powderfan, a user in the slack channel, triggered an error such that their account can no longer post transactions.  It seems, after conferring with @MonsieurNicolas that this is due to an issue with non-validating stellar-core nodes.

Some contextual information:
```
Account: GDDGZJZSUVWN76BNQG5MDE3X6NGAEOI2CTGCOKJSKYGISREXE7LLK47N
Envelope: AAAAAMZspzKlbN/4LYG6wZN380wCORoUzCcpMlYMiUSXJ9a1AAAAZAAGPkYAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAA33K5RRMepccHX+kyj0ls1z1411T6uXhAYF/l6puSl7wAAAAAFEP9AAAAAAAAAAABlyfWtQAAAEC76wZ9hCL5xM2oNiKsiRtIsxTwWJaL4BtFomGT+EbFLZsEA1OmoT6QRLcd8nbs3HKjrxVy5d37nSQ5O/59srkI
Account Sequence:  1757320228896768
Envelope Sequence:  1757320228896769
```

**Comment by nullstyle** [comment]
This error occurred when submitting to `core-live-001`, by way of https://horizon.stellar.org

**Comment by TbLtzk** [comment]
don't know if this is important: before getting to this state I submitted transactions without switchinig to the live network signing password (forgot `Network.usePublicNetwork()`)
