### ISSUE TITLE
info should report if there is a backlog in publishing history

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#895]
Right now there is no good way to know if a node is fully caught up to the network other than watching for `put` events in the logs.
In general, I don't know if there is a good way to assess of the health of the history archive that an instance publishes to

**Comment by MonsieurNicolas** [comment]
Oh the information is there but doesn't seem to be updated all the time.

```
      "extra" : "Catchup mode 'complete', applying ledger 407231/407231, queued checkpoints: 210",
```

even though I see in the logs
```
2015-10-30T22:36:27.751 GC2V2 [History INFO ] Publishing 179 queued checkpoints [395967-407359]
```

**Comment by graydon** [comment]
there should also be a line in the logs that exactly matches the extra-status string. the log line is emitted simultaneously with the extra-status string being set. can you recheck the log?

**Comment by graydon** [comment]
As far as I know this is reported as plainly as we can. Closing for now. Reopen with further details if you disagree.
