### ISSUE TITLE
support changing quorum set on the fly?

### ISSUE THREAD

**Issue by codeck** [stellar/stellar-core#896]
suppose we are running validators with 7 entries in quorum slice, and 2 are down. then any one more stop will halt the whole network. if we reduce to 5 entries by exclude those 2. there are still 1 failure_safety. 

this feature may increase possibility of unintentional network fork. any quorum set update will potentially cause network fork and this feature makes quorum set change easier.

**Comment by MonsieurNicolas** [comment]
How is this different from #876 ?
Maybe you have a question on how to configure thresholds and quorum sets?
