### ISSUE TITLE
publish issues after being down for a while

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#898]
on testnet (no traffic, 400k inactive users), one of the boxes was down for a while (a few days).

When it came back up, because it's in "catchup complete", it created a backlog of snapshots to upload (200+).

A few issues there:
 * publishing is very slow - the bucket folder was 68M (100 files or so) but it takes order of 30 minutes to upload to aws.
 * the backlog is processed in chronological order, which means that the machine doesn't really help other nodes to join the network as most of the pushes are just old
 * should we limit the number of snapshots queue and stop catching up? it seems that this can consume a large amount of disk space

**Comment by graydon** [comment]
This is tricky and might well require some redesign of the history publishing system. I'm going to have to chew on it a while and do some experiments.

**Comment by graydon** [comment]
The queue is held in the database now and processed one-at-a-time from there. I'm not sure what if anything to do about the other issues; the slow upload is just aws being slow, the chronological order is (imo) the right thing to do as far as keeping the archive in near-contiguous order. I'm going to close this for now, unless you disagree?
