### ISSUE TITLE
need command to broadcast your SCP state to everyone,  bump ballot and start SCP again

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-core#909]
last night it seemed like SCP stalled out. everyone was connected but the ledger didn't close for some reason. We should fix that issue obviously but I think a command like this would also be useful.

**Comment by MonsieurNicolas** [comment]
forcescp does force to start SCP - I do not think we need some other mechanism. SCP messages are rebroadcast every 2 seconds and bumping ballot is done automatically using timeouts (and there is a cap for the timeout at 30 minutes currently, so ballots will be bumped no matter what every 30 minutes)
