### ISSUE TITLE
better error code when self trusting

### ISSUE THREAD

**Issue by FredericHeem** [stellar/stellar-core#915]
Setting the trust to itself leads to the error `op_invalid_limit` 
Let's implement a more relevant error message.

**Comment by MonsieurNicolas** [comment]
yeah there is no explicit check if an issuer tries to update its own trust line. I agree the error code can be improved.
Problem is that this is a protocol break (would break history), so I'll tag it to consider it for a future protocol change.

**Comment by jedmccaleb** [comment]
#1020
