### ISSUE TITLE
overlay load manager: consider including other metrics than db load

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#920]
Some requests between peers only involve memory, CPU and/or bandwidth.

For example a peer can in a loop:
- ask for a non existent txset
- send the same txset
- send the same invalid transaction

we should prioritize by looking at
- if it's some form of amplification (like sending an invalid transaction, that doesn't require any CPU from the sender side, but requires some from the receiving side).
- if a bug could manifest itself like that (resend of anything for example, is a class of common bugs)

**Comment by marta-lokhova** [comment]
@MonsieurNicolas is this issue still relevant? Load manager was removed in https://github.com/stellar/stellar-core/pull/2794 (some of the things you mention are also now mitigated by flow control)

**Comment by MonsieurNicolas** [comment]
yeah this is irrelevant now (and we're working on a different strategy anyways to manage the peer list)
