### ISSUE TITLE
add automatic "maintenance" to stellar-core

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#923]
stellar-core has a `maintenance` endpoint that should be periodically called to clean up the database.

`maintenance` right now only performs historical pruning of data that was successfully uploaded to history and/or imported into dependent services such as Horizon.

At a minimum, we should call it on startup (probably add a config to control this).

Maybe consider adding an automatic schedule within core (less important).

This can only be implemented after all dependencies such as Horizon properly update their cursor.

**Comment by MonsieurNicolas** [comment]
This will be done in two steps:
 1. cleanup if stellar-core is NOT in catchup mode `complete`
 2. cleanup all the time

Reason for this is that Horizon does not work yet if stellar-core is not in `complete` mode and when it does it will support importing from partial history in stellar-core (potentially importing/leveraging from history archive instead).

**Comment by MonsieurNicolas** [comment]
This item now tracks step 2 above (awaiting changes in Horizon to properly update cursors)

**Comment by vogel** [comment]
Currently MAINTENANCE_ON_STARTUP is always set to true, and the example config wrongly states it as a configurable option. I'll remove comment from example config until this is made configurable.

**Comment by MonsieurNicolas** [comment]
Horizon is now properly using cursors.

As the second step was never done, nodes that are configured with "CATCHUP_COMPLETE" have accumulated millions of ledgers of historical data in their database, causing the current implementation of `maintenance` to hang for a long time.

I think we need to take a slightly different approach here.

We should
- [ ] change the `maintenance` endpoint to take an optional parameter that is the maximum number of ledgers that will be deleted from each tables (default to something small like 50000) 
- [ ] replace the `MAINTENANCE_ON_STARTUP` option with something like `AUTOMATIC_MAINTENANCE_PERIOD` with a default of 3600 seconds (every hour) - can be turned off with a value of 0. That will trigger the same code from the `maintenance` endpoint on a schedule (no-op during catchup - just to be on the safe side).

note: to allow for Horizon to register its cursor, we should not run this auto-maintenance on startup, but instead wait for `AUTOMATIC_MAINTENANCE_PERIOD + random(AUTOMATIC_MAINTENANCE_PERIOD)`

with those settings (delete 50000 every 1800 seconds, it will take about a week for the validators to delete old data for the public network as of today ~ 14M ledgers)
