### ISSUE TITLE
Warning overload on VS2015.1

### ISSUE THREAD

**Issue by raymens** [stellar/stellar-core#935]
I think Update 1 for VS2015 has introduced some additional warnings. Since I've installed the update the Output and Error List get's flooded with these kind of errors:
```
Warning	C4060	switch statement contains no 'case' or 'default' labels (compiling source file ..\..\src\ledger\LedgerDelta.cpp)	stellar-core	D:\Workspaces\stellar-core\Builds\VisualStudio2015\src\generated\xdr\Stellar-ledger-entries.h	2004
```
Maybe use something like `#pragma warning(disable: 4060)` on top of all the generated header files?

**Comment by MonsieurNicolas** [comment]
Didn't know there was "update 1", I am installing it. I suspect that they actually fixed a bunch of compiler bugs where they stopped emitting warnings in some cases (I just tried a few switch related warning samples on a basic console app on RTM and they don't work right)
