### ISSUE TITLE
Allow frozen account to send back to the issuer

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-core#945]

**Comment by MonsieurNicolas** [comment]
We can make this change next time we rev the ledger protocol.

We have tests explicitly testing that a frozen account cannot do anything with the frozen assets. It's not clear to me that one behavior is better than the other.
On one hand with this change it makes it impossible for an issuer to block an account from having a balance, but on the other I picked this behavior as it seemed safer and simpler from a compliance point of view: the authorize functionality is there to deal with some compliance scenarios and allowing to send back the funds may open some weird loophole (a user may expect something in return by sending it back and the fact that it's the issuer may be moot from a compliance standpoint). Do we fully understand the ramifications of this?

**Comment by raymens** [comment]
Is this related to the following text in the docs? Because that seems to state that the account may send it back. Shouldn't the docs be changed if this isn't true (at this moment)?

```
Revoking access

As a gateway, you can mark the issuing account AUTHORIZATION REVOCABLE. With this setting, the gateway can freeze credit held by another account. When credit is frozen for a particular account, that account can only send the credit back to the gateway--it can't transfer the credit to any other account. This setting allows the issuing account to revoke credit that it accidentally issued or that was obtained improperly.
```

**Comment by MonsieurNicolas** [comment]
closing this issue: https://github.com/stellar/stellar-protocol is where protocol discussions happen, it's unclear to me that we'd make changes on that front at this time
