### ISSUE TITLE
deleting a non existing order doesn't fail

### ISSUE THREAD

**Issue by FredericHeem** [stellar/stellar-core#948]
First of all, when deleting an order, the order id is not sufficient, one must also add the buying and selling asset which should't be necessary.
Then, transaction to cancel is a non existing order doesn't fail:
```
"txbody": "AAAAAOIMOp42Tuw389MPINEKAKeCXWzs7Nxlg7WX73gl1+sWAAAAZAAALdsAAAAWAAAAAAAAAAAAAAABAAAAAAAAAAMAAAABVk9JRAAAAAC67XdZiwFZhU/ZeN4TiQIi/AzRG1PA8q/ncy5dFUoVWgAAAAFWT0lEAAAAALTdVVVGmQVAGYxQtnKy9gi049P6q5Zwe24UPJ2RNqZ/AAAAAAAAAAAAAAABAAAAAQAAAAAF9eD/AAAAAAAAAAEl1+sWAAAAQMtG2cPLx4sanMCEwB9bx7eYXkbyhdDocOi+FGt2Qf67PGmP325Fv/GOPINt+sGrT+R2JVuY1S+zjRPSDmDUHAs="

"txresult":"0KQRx/6q84isg1rU9p5y916BQFJGOHlLHZWkH9fBAzMAAAAAAAAAZP////8AAAABAAAAAAAAAAP////1AAAAAA=="
```

**Comment by MonsieurNicolas** [comment]
Yes, we require the buying/selling assets with the offerID as a safeguard against modifying the wrong offers (think of it as a checksum).

As for the problem with results that you are seeing. Is this on your dev box? testnet? Which compiler did you use?

I tried to repro what you are seeing but it seems to work fine for me: I end up with an error `MANAGE_OFFER_NOT_FOUND`.

Can you try the branch https://github.com/MonsieurNicolas/stellar-core/tree/manageOfferBug and see if you can run a couple tests and report back:
 * `./stellar-core --test "create offer"`
 * `./stellar-core --test "standalone"`

**Comment by FredericHeem** [comment]
Sorry for the noise, I was wrong on one point, the *manageOfferNotFound* error is correctly returned. However deleting an order with the right id but with random buy/sell asset works, which is not following your spec. However, it's fine for my use case as I believe the order id should be sufficient to cancel the order as it simplifies client side code.
See https://github.com/stellar/stellar-core/blob/eed89649c2060b8e9dacffe2cec4e8b258b32416/src/transactions/ManageOfferOpFrame.cpp#L45

Current situation is fine. Let's close it. Thanks a lot for the support.
