### ISSUE TITLE
deleting an order with the right id but with random buy/sell asset works

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#949]
We should consider enforcing the same path than what we're doing when we try to update an offer and fail if selling/buying does not match.

note: some people seem to already pass garbage to selling/buying as managerOffer requires those to be set (so we would break them with this change).

**Comment by jedmccaleb** [comment]
idk. I would think orderID should be enough to cancel an order?

**Comment by MonsieurNicolas** [comment]
You mean you'd like to have a separate operation to delete offers?
Or you mean having garbage is fine? I thought that the reason you used manageOffer to delete things was to have a consistent behavior (something like lim managerOffer(amount)@amount->0 = manageOffer(0) )

**Comment by jedmccaleb** [comment]
No I don't want to make a new operation. It seems like allowing garbage is fine?

**Comment by jedmccaleb** [comment]
ok leaving this that you only have to know the id to delete an offer not the assets also
