### ISSUE TITLE
history test "too far behind / catchup restart" fails in master

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#954]
This test is failing intermittently but more often than not (Linux and Windows), so master is blocked at this point.

It triggers an error during catchup "Catchup already in progress".
https://github.com/stellar/stellar-core/blob/master/src/history/HistoryManagerImpl.cpp#L723

**Comment by graydon** [comment]
I believe I introduced this in 2d664dc and it shouldn't be a problem in the new code. I've run this test in a loop for quite a while and no longer see it. It was a simple failure-to-reset the pointer owning the catchup state machine, fixable in any case.

**Comment by graydon** [comment]
This behavior was fixed during the rewrite in #951
