### ISSUE TITLE
status during catchup is off

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#962]
It looks like the progress when downloading files is not right:
```
      "extra" : "Catching up: downloading ledger files 14/13 (107%)",
```

Also, it looks backwards: it starts at 107% and then goes to 0% . The wording should be reversed as typical progress is expressed as percent towards completion, not percent of work left.

**Comment by graydon** [comment]
This behavior was fixed during the rewrite in #951. See https://github.com/stellar/stellar-core/blob/master/src/history/HistoryWork.cpp#L32-L48
