### ISSUE TITLE
write a tool that performs checks on history archive

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#964]
Right now stellar-core says it publishes to archives but we don't know if it's true.

There are a few things we could do (all on arbitrary ledger range):
 * basic sanity check - walk ledger header history, verify that the various files are there (transaction information, buckets, etc), perform basic hashing (ie, ledger header is valid)
 * integrity check - perform checks on content of files, re-hash the bucket files
 * diff between archives - allows to compare a known good archive to another unknown one. This allows to take an archive that was built using catchup complete/full validation and see if another archive is consistent with it

Once we have checks, some automatic repairs may be implemented.

**Comment by jedmccaleb** [comment]
https://github.com/stellar/archivist
