### ISSUE TITLE
Allow adding hash(tx) to the list for signers

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-core#965]
I realized chatting with Graydon today that this may be the best way to unify transaction based with account based system.

The key realization I had was that the way you would use this is by increasing the thresholds in such a way that "regular" accounts would not be able to do much, but that some transactions have higher weight, so that you would have for example (in the case of an escrow account):
- one tx to merge the escrow account back into the initiator's account, time bound and requiring only one other signature (weight of tx = high threshold - weight of one regular accounts)
- one tx to merge the escrow account into a destination account with a weight such that it requires two other signatures (weight tx = high threshold - 2*weight of regular accounts)

Both tx would consume the same sequence number (so that they are mutually exclusive), also when a transaction gets consumed like this, it would automatically be removed from the list of signers (this would happen during the fee processing step, before performing the actual operations).

There might be a different way, maybe using some sort of tokens that can be matched by property; but the advantage of this one is that it's very simple to understand and not error proof.

This should be tested against the list of problems that we'd want to address in the next round of the protocol rev.

**Comment by vogel** [comment]
Merged into next-db-and-proto
