### ISSUE TITLE
catchup:  std::runtime_error: failed to open XDR file

### ISSUE THREAD

**Issue by FredericHeem** [stellar/stellar-core#992]
`stellar-core` has ended during the catchup state with the following exception:
```
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: failed to open XDR file: tmp-prod/catchup-complete-0020f713-fe0c7c3958a3acc9/ledger-0002907f.xdr
```

By the way, when `stellar-core` is restarted, it restarts the catchup phase from the beginning.

**Comment by graydon** [comment]
Sounds like a failed download or race against the filesystem. Does it reoccur?

**Comment by FredericHeem** [comment]
The issue didn't show up again, after a restart, my local stellar-core has completed the catch up phase and is now in sync state with the prod network.

**Comment by graydon** [comment]
Absent a reproduction on this, I'm going to close for now. Reopen if you can figure out a way to make this happen reliably.
